### ISSUE TITLE
bootstrapping fails if emacs isn't built with json support

### ISSUE THREAD

**Issue by maw** [progfolio/elpaca#1]
## What's wrong

I was using a build of emacs without json support.

The bootstrapping process failed with:

```
In end of data:
elpaca-menu-melpa.el:38:6: Warning: the function ‘json-parse-string’ is not known to be defined.
Compilation finished.
```

In my case, the solution was to say `apt install libjansson-dev`; rebuild emacs, including `--with-json` in `configure`'s arguments, etc.  This isn't exactly a fully generalizable solution :smile:.

I think the instructions in README.org need to be clear that this requires a build of emacs with json support.

## Directions to reproduce

Try to bootstrap elpaca per instructions in README.org using emacs built without `--with-json`.

### Version information

* Emacs version: 28.1, built without json support
* Operating system: Ubuntu 20.04

**Comment by progfolio** [comment]
Sorry about that. The MELPA menu should default to the elisp library json.el when native JSON parsing is not available now.
Testing is appreciated.
Than you for the report.
