### ISSUE TITLE
[Feature]: Clarify prerequisite on ability to create symlinks on Windows

### ISSUE THREAD

**Issue by lebensterben** [progfolio/elpaca#102]
### Feature Description

Currently on the [README.org](/progfolio/elpaca/blob/master/README.org) it says

> Windows users must be able to create symlinks.

Though there's another [feature request](https://github.com/progfolio/elpaca/issues/72) on dropping this requirement, I believe we'd better clarify this requirement for the time being.

AFAIK, to create symbolic link, you need one of the following:

- On Windows 10 with admin privilege.
- On Windows 10 after its Creator's Update, has enabled `Developer Mode` from `Settings > Update & Security > For Developers`.
- On Windows >= 11.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for the suggestion.
Do you think linking to a guide such as this would be helpful?:

https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

That (or a similar guide if you're aware of a better one) seems like it could cover the process in more detail without requiring much maintenance on my end.

**Comment by progfolio** [comment]
I've added  a link to the guide.
(There are some other bugs with the way footnotes are being rendered in the docs. I may have to switch to markdown for the generated README. I'll deal with that at another time.)
