### ISSUE TITLE
[Bug]: When a package's dependency is built-in, but is an incompatible version

### ISSUE THREAD

**Issue by tsilvap** [progfolio/elpaca#106]
### Elpaca Version

```
Elpaca de7cc07 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-28
git --version:  git version 2.40.0
```

### Operating System

Fedora Linux 37

### Description

I've noticed this bug with the 'eglot' package. After installing it with `(elpaca eglot)`, then opening a source code file (for example a Go file) and running `M-x eglot`, we get the error:
```
eglot--connect: Symbol’s function definition is void: project-name
```

I believe that is because 'eglot' depends on 'project', but 'project' is a built-in package on Emacs 28.2, so Elpaca considers it already installed. But on Emacs 28.2, the installed version of 'project' is 0.8.1, which doesn't have the `project-name` function yet.

### Expected behavior

The way `package.el`deals with this is the 'eglot' package currently requires 'project' 0.9.8, so `package.el` sees the built-in version of 'project' doesn't satisfy the min-version and proceeds to fetch the latest 'project' package from ELPA. I think we should have a similar check in Elpaca.

**Comment by progfolio** [comment]
`project` (and other built-in packages) is a member of `elpaca-ignored-dependencies`. 
This means it will be skipped when checking dependencies.
This is usually what you want, but in this case, you'll want to explicitly tell Elpaca that you want to download a newer version of project.el:

```emacs-lisp
(elpaca project)
(elpaca eglot)
```

I'm not convinced automatically detecting this case and installing a newer version of a built-in package is the right thing to do. Say, for example, that there is a breaking change in the latest version of the built-in package. Updating it fixes the issue with eglot, but breaks several other packages (perhaps built-in, perhaps third-party) which haven't changed to support the latest version of package.
I'm open to suggestions if anyone has any ideas how to best deal with this.

**Comment by progfolio** [comment]
I've merged in a feature which will check that dependency versions are met.
If they are not, the order is failed.
That should prevent errors like the one described in the original message.
