### ISSUE TITLE
[Bug]: `(elpaca elpaca-use-package)` not working

### ISSUE THREAD

**Issue by ryunix** [progfolio/elpaca#109]
### Elpaca Version

```
Elpaca 4e01967 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-04-13
git --version:  git version 2.39.2
```

### Operating System

Gentoo Linux

### Description

I noticed that `(elpaca elpaca-use-package)` doesn't work after c05eb50.  In parent commit (de7cc07) it works.
Could you please try this code?

```elisp
(elpaca-test
  :ref "c05eb50"
  :init
  (elpaca elpaca-use-package)
  (elpaca-wait)
  (cl-assert (elpaca-installed-p 'use-package)))
```

**Comment by progfolio** [comment]
Sorry about that. Thinko on my part. It should be fixed now on master.

```emacs-lisp
(elpaca-test
  :init
  (elpaca elpaca-use-package)
  (elpaca-wait)
  (cl-assert (elpaca-installed-p 'use-package)))
```

Thanks for catching this and the succinct reproduction case.

**Comment by ryunix** [comment]
Thank you for the update.  Now `(elpaca elpaca-use-package)` is working!
