### ISSUE TITLE
[Support]:  use-package-chords configuration

### ISSUE THREAD

**Issue by AlexGalchenko** [progfolio/elpaca#114]
### Feature Description

Currently, if you want to use use-package-chords extension, you will see an error ":chords keyword is not recognized". 

After small digging, I found out that elpaca-use-package contains this line:
https://github.com/progfolio/elpaca/blob/782377af846421ec6a298f4cc7aaa1dcbd28e437/extensions/elpaca-use-package.el#L30

and use-package-chord extension add ":chords" keyword. 
https://github.com/jwiegley/use-package/blob/77945e002f11440eae72d8730d3de218163d551e/use-package-chords.el#L50

It would be great to have use-package-chords support within elpaca. 

Thanks!

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
This should work if `elpaca-wait` is used properly. Please see the example in the demo init file:

https://github.com/progfolio/elpaca/blob/782377af846421ec6a298f4cc7aaa1dcbd28e437/doc/init.el#L49-L54

**Comment by AlexGalchenko** [comment]
Emacs version: 
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)

My config section with use-package-chords looks like this:

(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (setq elpaca-use-package-by-default t))

(elpaca-wait)

(use-package use-package-core
  :elpaca nil
  :custom
  (use-package-verbose nil)
  (use-package-compute-statistics nil)
  (use-package-always-defer t)
  (use-package-expand-minimally t)
  (use-package-enable-imenu-support t))

(use-package use-package-chords
  :config
  (key-chord-mode 1))

**Comment by progfolio** [comment]
```emacs-lisp
(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (setq elpaca-use-package-by-default t))

(elpaca-wait)

(use-package use-package-core
  :elpaca nil
  :custom
  (use-package-verbose nil)
  (use-package-compute-statistics nil)
  (use-package-always-defer t)
  (use-package-expand-minimally t)
  (use-package-enable-imenu-support t))

(use-package use-package-chords
  :config
  (key-chord-mode 1))

(elpaca-wait) ;;<- needed before following use-package declarations

**Comment by AlexGalchenko** [comment]
Nope, still the same:
`Error (use-package): Failed to parse package avy: use-package: Unrecognized keyword: :chords`

Even with additional elpaca-wait the value of the use-package-keywords is this:

`(:disabled :defines :functions :preface :if :when :unless :elpaca :no-require :catch :after :custom :custom-face :bind :bind* :bind-keymap :bind-keymap* :interpreter :mode :magic :magic-fallback :hook :commands :autoload :init :defer :demand :load :config :diminish :delight :pin :ensure :load-path :requires)`


There is no :chords keyword. If I understand correctly, the use-package-chords modify the use-package-keywords list. But in case of elpaca it doesn't work.

**Comment by progfolio** [comment]
You have `use-package-always-defer` set to `t`. Thus, use-package-chords is not loaded in time. Add `:demand t` to the `use-package-chords` declaration.

```emacs-lisp
(elpaca-test
  :dir "elpaca.test"
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)
  (use-package use-package
    :elpaca nil
    :custom
    (use-package-verbose nil)
    (use-package-compute-statistics nil)
    (use-package-always-defer t)
    (use-package-expand-minimally t)
    (use-package-enable-imenu-support t))
  (use-package use-package-chords
    :demand t ;;<- force loading of use-package-chords/key-chord-mode
    :config
    (key-chord-mode 1))
  (elpaca-wait) ;;<- needed before following use-package declarations
  (use-package aceey-chord-mode (which-jump-mode
    :chords (("jj" . ace-jump-char-mode)
             ("jk" . ace-jump-word-mode)
             ("jl" . ace-jump-line-mode))))
  ```

**Comment by AlexGalchenko** [comment]
It works with `:demand `t! Thanks!
