### ISSUE TITLE
[Bug]: Fatal : the destination path for magit already exists

### ISSUE THREAD

**Issue by mattiasdrp** [progfolio/elpaca#117]
### Elpaca Version

```
Elpaca 8295909 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 29.0.60 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2023-02-01
git --version:  git version 2.34.1

```

### Operating System

Ubuntu 22.04.2 LTS

### Description

I tried moving my whole config to elpaca and I had some double definitions that I managed to fix by moving package declarations up and down. Magit never appeared in these warnings but I have a fatal error with it I can't fix, it says that the destination path already exists.

Here's what seems important in the magit info page:

```
dependencies: 
  compat
  dash
  git-commit
  magit-section
  seq
  transient
  with-editor
dependents: 
  magit-todos
commit:  1137083
statuses:
  (failed cloning unblocked-mono-repo ref-checked-out blocked)
```

I added magit-section.el to the files that need to be checked out by elpaca and all the dependencies are declared above the magit package declaration but it keeps failing. (and magit-todos has a fatal error because magit is a failed dependency)

Any idea of what I'm doing wrong?

Thanks for the package, it works really well!

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.
It's hard to say what's going wrong with the info you've shared so far.
Please include:

- The output of `M-x elpaca-version`
- A copy of the log view which shows the error/failure you mentioned

To get a copy of the log-view, you can `M-x elpaca-log` and then type "c" in the buffer.
That will copy the current view to your system clipboard formatted for posting here.

**Comment by mattiasdrp** [comment]
> Sorry. Skipped over that on my phone by accident.

No worries :-)

Oh, so you mean that it's considered as a fatal error because the error could not be filtered out by your function since it was in french, right? So if I set my locale in english, git won't be able to clone magit because the repository already exists but it will not fail because the warning will have been filtered out, right?

**Comment by progfolio** [comment]
> > Sorry. Skipped over that on my phone by accident.
> 
> No worries :-)
> 
> Oh, so you mean that it's considered as a fatal error because the error could not be filtered out by your function since it was in french, right? So if I set my locale in english, git won't be able to clone magit because the repository already exists but it will not fail because the warning will have been filtered out, right?

Correct. That should work as a temporary workaround. Let me know if it doesn't. I'll look into fixing it in a locale independent way as well.

**Comment by mattiasdrp** [comment]
Coming back on this, the error reappeared but now my locale is in english. I managed to overcome it by rearranging dependencies and using `:elpaca nil` but I think there's been a recent change that messes up with recognizing this specific error

**Comment by progfolio** [comment]
`M-X elpaca-version`?

**Comment by mattiasdrp** [comment]
```
Elpaca cc8a94b HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2023-07-09
git --version:  git version 2.34.1
```

**Comment by mattiasdrp** [comment]
I often remove entirely my elpaca repo to make sure that my config still works from scratch, I did it this morning and this error appeared. If I can help in any way, let me know :-)

**Comment by progfolio** [comment]
Oh, so you're on the latest and still seeing it?

**Comment by mattiasdrp** [comment]
```
(defvar elpaca-installer-version 0.5)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

(use-package general :demand t)
(elpaca-wait)

(eval-and-compile
  (setq
   use-package-verbose t
   use-package-expand-minimally t
   use-package-compute-statistics t
   use-package-enable-imenu-support t))

(setq custom-file (expand-file-name "customs.el" user-emacs-directory))
(add-hook 'elpaca-after-init-hook (lambda () (load custom-file 'noerror)))

(elpaca bind-key)
;; (elpaca use-package)

;; (use-package use-package-ensure-system-package
;;   :config (message "`use-package-ensure-system-package' loaded"))

(use-package git-commit
  :defer t)

(use-package magit
  :defer t)
```

With this simple file, the error appears

**Comment by mattiasdrp** [comment]
> Oh, so you're on the latest and still seeing it?

Yep

**Comment by progfolio** [comment]
Looking into it now.

**Comment by mattiasdrp** [comment]
Testing right now...

And it works!
