### ISSUE TITLE
[Support]: $BUILDS Files missing

### ISSUE THREAD

**Issue by dragove** [progfolio/elpaca#118]
### Elpaca Version

Elpaca 8295909 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)

### Operating System

Arch Linux

### Description

After installing [lsp-bridge](https://github.com/manateelazycat/lsp-bridge) there is an error showed up:

Warning (emacs): Config Error lsp-bridge: (file-missing "Cannot open load file" "No such file or directory" "acm-frame")

My config content:

```elisp
(elpaca yasnippet
  (require 'yasnippet)
  (yas-global-mode 1))

(elpaca (lsp-bridge :host github
                      :repo "manateelazycat/lsp-bridge")
  (require 'lsp-bridge)
  (global-lsp-bridge-mode))
```

There is also an error when I'm trying to install [blink-search](https://github.com/manateelazycat/blink-search)

Warning (emacs): Config Error blink-search: (file-missing "Cannot open load file" "No such file or directory" "blink-search-elisp-symbol")

my config:

```elisp
(elpaca (blink-search :host github
                      :repo "manateelazycat/blink-search")
  (require 'blink-search))
```

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.
Please keep future reports focused to one issue at a time.
It makes it easier for others (including myself) to search for in the future.

lsp-bridge attempts to manage load-path for acm itself, via the acm-library-path variable:

https://github.com/manateelazycat/lsp-bridge/blob/master/lsp-bridge.el#L83-L87

The assumption here is that the file is being loaded from within the repository directory (not the case for Elpaca or straight.el). To work around this the `:files` keyword can be used. The following test installs cleanly for me on Emacs 30:

```emacs-lisp
(elpaca-test
  :init
  (elpaca yasnippet)
  (elpaca (lsp-bridge :host github :repo "manateelazycat/lsp-bridge" :files (:defaults "acm/*"))
    (require 'lsp-bridge)
    (global-lsp-bridge-mode)))
```

Another lsp-bridge issue is that the implicit dependency on yasnippet:

https://github.com/manateelazycat/lsp-bridge/search?q=package-requires&type=code

I removed that from my original test and the package failed to load.
The dependency declarations/management for this package should be reworked so the user doesn't have to manually manage them. I suggest opening a bug report with the maintainer of lsp-bridge to discuss the issue.

**Comment by progfolio** [comment]
blink-search uses a similar approach to lsp-bridge to manage `load-path`:

https://github.com/manateelazycat/blink-search/blob/f9d7e573ea9069dcfbf11cf869dbf6e598d7068a/blink-search.el#L89-L94

Again, it may be worth discussing this with the package author.

The :files recipe keyword can be used to include the "backend" directory necessary for the package to work in `$BUILDS/blink-search/`.
(see [recipes](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipes)).
For example:

```emacs-lisp
(elpaca-test
  :init
  (elpaca (blink-search :host github :repo "manateelazycat/blink-search" :files (:defaults "backend"))
    (require 'blink-search)))
```

**Comment by dragove** [comment]
Thanks, Things get working after adding :files and elpaca-rebuild.
