### ISSUE TITLE
[Bug]: `debbugs`'s default recipe is missing `Debbugs.wsdl`

### ISSUE THREAD

**Issue by jpoiret** [progfolio/elpaca#119]
### Elpaca Version

Elpaca 8295909 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)
git --version:  git version 2.39.2

### Operating System

GNU Guix commit `aecc6e70587f8412cbbb9b2c13141de4f534518e`

### Description

The debbugs recipe should include the file `Debbugs.wsdl` for debbugs to work. I don't know how straight did it but I think it just worked out of the box for me with it. The lack of information on the GNU Elpa might not be helping though.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.

I've updated the GNU ELPA mirror menu to provide the same default `:files` spec as straight.el.
That should cover most packages. For those which it does not, the `:files` recipe keyword can be used to override the default value (see [https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipes](recipes)).

You'll want to update the menu via  `M-x elpaca-update-menus` `elpaca-menu-gnu-elpa-mirror` .
Testing is appreciated.

**Comment by jpoiret** [comment]
> Thanks for taking the time to fill out a report.
> 
> I've updated the GNU ELPA mirror menu to provide the same default `:files` spec as straight.el. That should cover most packages. For those which it does not, the `:files` recipe keyword can be used to override the default value (see [recipes](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipes)).

Yes, that was what I was using since this morning :)

> You'll want to update the menu via `M-x elpaca-update-menus` `elpaca-menu-gnu-elpa-mirror` . Testing is appreciated.

Works like a charm, thanks for the quick fix!
