### ISSUE TITLE
Problem installing deps of kind-icon

### ISSUE THREAD

**Issue by ashton314** [progfolio/elpaca#12]
## What's wrong

I want to install the `kind-icon` package:

```emacs-lisp
(elpaca-use-package kind-icon)
```

But I get this error when I try to install it:

```
error in process sentinel: Wrong type argument: listp, svg-lib
```

I looked in [the source for kind-icon](https://github.com/jdtsmith/kind-icon/blob/main/kind-icon.el#L7) and it looks like the dependencies might be formatted in an unexpected way:

```emacs-lisp
;; Package-Requires: ((emacs "27.1") svg-lib)
```

I haven't been able to find the spec for the package-requires declaration and whether or not versionless deps are allowed. As it stands, elpaca chokes on this. I'd like to know if this is something elpaca needs to fix, or if it's something that kind-icon should fix.

## Directions to reproduce

Try installing kind-icon

### Version information

* Emacs version: 29
* Operating system: macOS

**Comment by progfolio** [comment]
Thanks for the bug report.
That is a valid (if rare) dependency declaration.
See the section on "Package-Requires":

 https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html
 
 I've pushed a fix which should be able to build such packages now.
 Testing is appreciated.

**Comment by ashton314** [comment]
Works great now. Thanks!
