### ISSUE TITLE
[Bug]: void function `elpaca--queue` after byte compiling init.el

### ISSUE THREAD

**Issue by Trisk3lion** [progfolio/elpaca#121]
### Elpaca Version

Elpaca 8295909 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 30.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)
 of 2023-04-27
git --version:  git version 2.39.2

### Operating System

Debian 12 (running under WSL2)

### Description

Hello! 

I just recently migrated a bit of my Emacs configuration from quelpa to elpaca. At the moment I'm still using `package.el` for everything from Melpa/Elpa but now I use Elpaca when I want something directly from a git repository.

As I have fairly large `init.el`, I like to byte-compile it but this doesn't seem to work with Elpaca.
The error message I get is: `Symbol's function definition is void: elpaca--queue`

The start of my `init.el` looks like this:
```
(defvar elpaca-installer-version 0.3)
(defvar elpaca--queues nil)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
			      :ref nil
			      :files (:defaults (:exclude "extensions"))
			      :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (condition-case-unless-debug err
	(if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		 ((zerop (call-process "git" nil buffer t "clone"
				       (plist-get order :repo) repo)))
		 ((zerop (call-process "git" nil buffer t "checkout"
				       (or (plist-get order :ref) "--"))))
		 (emacs (concat invocation-directory invocation-name))
		 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
				       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		 ((require 'elpaca))
		 ((elpaca-generate-autoloads "elpaca" repo)))
	    (kill-buffer buffer)
	  (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default nil)
  (setq-default use-package-always-defer nil ; Always defer load package to speed up startup
	        use-package-verbose nil ; Don't report loading details
	        use-package-expand-minimally t  ; make the expanded code as minimal as possible
	        use-package-enable-imenu-support t  ; Let imenu finds use-package definitions
	        use-package-always-ensure nil
	        use-package-hook-name-suffix "-hook"))

;; Block until current queue processed.
(elpaca-wait)
```
And after running `emacs --debug-init`, the error seems to be coming from the byte-compiled code of:
```
 (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default nil)
  (setq-default use-package-always-defer nil ; Always defer load package to speed up startup
	        use-package-verbose nil ; Don't report loading details
	        use-package-expand-minimally t  ; make the expanded code as minimal as possible
	        use-package-enable-imenu-support t  ; Let imenu finds use-package definitions
	        use-package-always-ensure nil
	        use-package-hook-name-suffix "-hook"))
```

This is the stacktrace from `emacs --debug-init`
```
Debugger entered--Lisp error: (void-function elpaca--queue)
  elpaca--queue((elpaca :repo "https://github.com/progfolio/elpaca.git" :ref nil :files (:defaults (:exclude "extensions")) :build (:not elpaca--activate-package)) nil)
  byte-code("\306\307\10\"\306\307\11\"\nA\2\33\310\311\312\4!\203\30\0\3\202\31\0\4\"\210\312\3!\204\256\0\313\3\314\"\210\3151\243\0\316\317!\211\205B\0\320..." [elpaca-repos-directory elpaca-builds-directory elpaca-order default-directory invocation-directory invocation-name expand-file-name "elpaca/" add-to-list load-path file-exists-p make-directory t (debug error) pop-to-buffer-same-window "*elpaca-bootstrap*" call-process "git" nil "clone" plist-get :repo 0 "checkout" :ref "--" "-Q" "-L" "." "--batch" "--eval" "(byte-recompile-directory \".\" 0 'force)" require elpaca elpaca-generate-autoloads "elpaca" kill-buffer error "%s" buffer-string warn delete-directory recursive elpaca-autoloads load "./elpaca-autoloads" add-hook after-init-hook elpaca-process-queues elpaca-get ...] 18)
  load("/home/dev/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x16096e2fe161eff3>) #f(compiled-function () #<bytecode -0x1f3c61addc0b62b5>) t)
  command-line()
  normal-top-level()
```

Now I know that byte-compiling your `init.el` is [not recommended](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html) but I would still like to ask if there is anything that could be tweaked to enable it?

Another not related thing I noticed when reading the documentation and making the switch to Elpaca is that there is reference to an `elpaca-use-package` macro in the [manual](https://github.com/progfolio/elpaca/blob/master/doc/manual.md) but I can't seem to find it in the code, maybe it was made obsolete?

Thanks for a great package!

**Comment by progfolio** [comment]
Thank you for the detailed report.

The error you're seeing is likely due to the elpaca library not being loaded
when the compiled code is called. The `elpaca` macro is autoloaded (and will normally load `elpaca.el`), but when the init file is compiled the expansion of the macro is being called.
`elpaca--queue` is called in the body of `elpaca`:

https://github.com/progfolio/elpaca/blob/2190b8de91cb01aa23822999da1f9389732a2654/elpaca.el#L1445-L1463

> Now I know that byte-compiling your init.el is not recommended but I would still like to ask if there is anything that could be tweaked to enable it?

You may be able to workaround this by adding `(eval-when-compile (require 'elpaca))` before processing any orders via the `elpaca` macro. It's not a use-case I plan on supporting, though. IME byte-compiling one's init file leads to more complexity/errors with little (if any) gain.

> Another not related thing I noticed when reading the documentation and making the switch to Elpaca is that there is reference to an elpaca-use-package macro in the manual but I can't seem to find it in the code, maybe it was made obsolete?


Thanks for catching that. That was a macro which pre-dated `elpaca-use-package.el`.
I've removed the reference.
