### ISSUE TITLE
[Bug]: Lexical scoping lost for symbols captured by elpaca macro

### ISSUE THREAD

**Issue by darkfeline** [progfolio/elpaca#123]
### Elpaca Version

```
"Elpaca d5a8415 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-02
git --version:  git version 2.40.1"
```

### Operating System

Arch Linux (not relevant)

### Description

A recent commit broke the following way to use elpaca:

```
(let ((fork '(:remotes (("fork" :repo "darkfeline/magit"
                         :protocol ssh)))))
  ;; These packages are deps pulled in by magit.
  ;; They use the same repo, so they need to be forked too.
  (elpaca `(magit-section ,@fork))
  (elpaca `(git-commit ,@fork))
  (elpaca `(magit ,@fork)))
```

`git bisect` gives me:

```
235f9dc9ffb39a253e88ab1a4ce063bbeda732f5 is the first bad commit
commit 235f9dc9ffb39a253e88ab1a4ce063bbeda732f5
Author: Nicholas Vollmer <iarchivedmywholelife@gmail.com>
Date:   Tue Apr 25 11:08:24 2023 -0400

    reuse queue when orders re-evaluated
    
    This will allow one to modify a declaration and interactively re-evaluate it.
    The changes will overwrite the queued E's struct.
    
    elpaca-q<: set type slot to init when evaluated within init file
    elpaca--queue: reuse q if E already queued
    elpaca: reuse queue when possible, immediately process eval-last-sexp
    elpaca--maybe-reset-queue: ensure queues with incomplete orders processed
    elpaca-process-queues: reset queues when necessary

 elpaca.el | 41 ++++++++++++++++++++++++++++++++---------
 1 file changed, 32 insertions(+), 9 deletions(-)
```

**Comment by progfolio** [comment]
> A recent commit broke the following way to use elpaca:

Could you be more specific here? What is happening? Please include any errors or relevant elpaca-log output.

**Comment by progfolio** [comment]
Had time to test this.
I see that your above configuration now fails because the lexical environment is lost when expanding the `elpaca` macro. I'll have to think more on how I want to handle this. In the mean time, there are several ways to work around this:

Storing the data in a global var should expand properly:

```emacs-lisp
(elpaca-test
  :dir "elpaca.global-var"
  :init
  (defvar +elpaca-magit-fork
    '(:remotes (("fork" :repo "darkfeline/magit" :protocol ssh))))
  (elpaca `(magit ,@+elpaca-magit-fork))
  (elpaca `(magit-section ,@+elpaca-magit-fork))
  (elpaca `(git-commit ,@+elpaca-magit-fork)))
```

However, this (and the example you gave) require you to track which packages need to be forked explicitly. `elpaca-recipe-functions` could be used to do this programmatically:

```emacs-lisp
(elpaca-test
  :dir "elpaca.recipe-function"
  :init
  (setq elpaca-recipe-functions
        (lambda (recipe)
          (when (equal (plist-get recipe :repo) "magit/magit")
            '(:remotes (("fork" :repo "darkfeline/magit" :protocol ssh))))))
  (elpaca magit)
  (elpaca magit-section)
  (elpaca git-commit))
```

**Comment by darkfeline** [comment]
Thanks for the quick response as always, and sorry for omitting more error info from my report although you figured it out.  The last example sounds like the right solution for my XY problem, although I wonder if `elpaca` has the same issue as `straight.el` that prompted me to add my original fix.  If I remember correctly, `straight.el` simply doesn't tolerate if I forked only `magit`'s repo, even though in theory the other deps like `magit-section` could come from a non-forked copy of the repo.

Anyway, the "dep recipe must also be forked" is a separate issue (assuming it is present in `elpaca`) from the lexical scoping issue.  While your workaround solves my issue, I suspect other users may run into this scoping issue for other use cases, so I'll leave you to "think more on how you want to handle this".

**Comment by progfolio** [comment]
>  If I remember correctly, straight.el simply doesn't tolerate if I forked only magit's repo, even though in theory the other deps like magit-section could come from a non-forked copy of the repo.

I'd have to check, to be honest. It's hard to keep both code bases in my head at once.
By default, if multiple packages are hosted in the same repository, Elpaca will try to only clone that repository once. The rationale for that is:

- Most users will not be editing the source files, so this minimizes disk/network usage.
- If the author of the packages felt they were related enough to keep in a single repository, then development is usually tightly coupled.

You could keep multiple copies of the repository, one for your fork and another copy from which the dependencies are built like so:

```emacs-lisp
(elpaca-test
  :dir "elpaca.magit"
  :init
  ;; This will be cloned to $REPOS/magit.
  (elpaca (magit :host github :repo "darkfeline/magit" 
                 :protocol ssh
                 :remotes ("fork" ; Rename origin to fork.
                           ("origin" :repo "magit/magit"))))
  ;; These will share $REPOS/magit.github.magit (repo-name.host.user).
  (elpaca (git-commit))
  (elpaca (magit-section)))
```

I'd have to make some adjustments to the way the (unadvertised for now) `:local-repo` recipe keyword is handled to make it so all three could have a separate copy, but it wouldn't take much of a change. Is that a feature you would be interested in?

**Comment by darkfeline** [comment]
I remember more of my original issue with `straight.el`.  The problem is that magit and its deps are configured to use the same repository directory, but the deps declare different remotes for that directory than magit, and the deps are pulled in first (thus the ordering of the elpaca orders (originally `straight` calls) in my snippet).  I don't recall if this caused problems directly or if it was this coupled with the freezing feature of `straight.el`.

In any case, I was happy to see that elpaca uses the `:remotes` option, unlike in `straight.el` which used a `:fork` option, which tells me that elpaca should be more flexible when handling remotes.

Regarding the separate copies feature, I do not need it currently although it may be useful to me in the unforeseeable future (thanks for asking).

The question is, does elpaca work correctly (for some definition of "correct") if a user tries to declare a fork of magit without also forking its deps?  Because IIUC elpaca will need to clone the repo for the deps first, so it would use the remotes from the unforked dep recipe.

**Comment by progfolio** [comment]
> Regarding the separate copies feature, I do not need it currently although it may be useful to me in the unforeseeable future (thanks for asking).

Ok. Good to hear. I don't think many people will need such a feature, so I'll wait till there is demand to implement it.

> The question is, does Elpaca work correctly (for some definition of "correct") if a user tries to declare a fork of magit without also forking its deps? 

I think the current policy for "mono-repo" dependencies will cover most use cases.
In my previous comment I showed how the forked package can have its own copy and the deps published in the same repo can live in another copy. If it does cause some sort of problem for you, let me know and we can reconsider what the best approach here is. 

Thanks again.

**Comment by progfolio** [comment]
I've fixed the macro so the lexical scope should be available in the expansion.
Testing is appreciated.

**Comment by darkfeline** [comment]
From cursory testing, the fix works.  Will update if I find otherwise (or any other bug).

**Comment by progfolio** [comment]
> From cursory testing, the fix works. Will update if I find otherwise (or any other bug).

https://github.com/progfolio/elpaca/issues/143

^ That's an odd corner case which cropped up due to the change,  but it shouldn't effect the examples you gave in this thread.
