### ISSUE TITLE
[Feature]: Use ssh as default protocol for github (for maintainers)

### ISSUE THREAD

**Issue by psionic-k** [progfolio/elpaca#124]
### Feature Description

A configuration option to use ssh for protocols where we have sufficient credentials would have the remote configured correctly to make changes on packages that we both use and maintain.

**possible bug** I also don't have a diagnosis on a behavior, but I had to fall back to using cli git to unshallow my copy.  The `elpaca-unshallow` command didn't succeed, but I didn't observe any feedback.  I'll see it again if there is indeed a bug, but I think that's what I saw.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.

> A configuration option to use ssh for protocols where we have sufficient credentials would have the remote configured correctly to make changes on packages that we both use and maintain.

This can be specified via the `:protocol` recipe keyword for those packages.

https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipes

You can also customize `elpaca-order-defaults`.
Did you have something else in mind?

> possible bug I also don't have a diagnosis on a behavior, but I had to fall back to using cli git to unshallow my copy. The elpaca-unshallow command didn't succeed, but I didn't observe any feedback. I'll see it again if there is indeed a bug, but I think that's what I saw.

Please keep issues focused to one topic at a time in the future.
It makes it easier to search for discussion around issues.
For that command in particular, I'm leaning toward removing it.
Magit has an unshallow command which works well.

**Comment by psionic-k** [comment]
elpaca-order-defaults  sounds like what I want, although I might want a dynamic solution, such as a function to transform all repos under my organization to the ssh protocol and a non-shallow clone.

**Comment by progfolio** [comment]
> although I might want a dynamic solution, such as a function to transform all repos under my organization to the ssh protocol and a non-shallow clone.

You can also customize `elpaca-recipe-functions`. For example (untested):


```emacs-lisp
(defun +elpaca-dev-recipe (recipe)
  "If RECIPE is part of my organization, set it up for development."
  (when-let ((repo (plist-get recipe :repo)) 
             ((string-prefix-p "my-org/" repo)))
    (list :protocol 'ssh :depth nil)))

(add-hook 'elpaca-recipe-functions #'+elpaca-dev-recipe)
```

Does that help?

**Comment by progfolio** [comment]
I'm assuming this should do the trick. Let me know if you run into any issues or have any questions about that approach.

**Comment by aaronjensen** [comment]
This is awesome. Thank you!
