### ISSUE TITLE
[Bug]: Installation on Windows 11 fails because emacs can't create the symlinks

### ISSUE THREAD

**Issue by domsch1988** [progfolio/elpaca#125]
### Elpaca Version

Unclear, since installation fails. Since it clones from git, i'd assume the latest.

### Operating System

Windows 11 22H2

### Description

Emacs Version 28.2
My init.el only contains the basic elpaca setup and nothing else.
Installation starts correctly, but fails with the error:
`elpaca--link-build-files: (file-error "Making symbolic link" "Operation not permitted"`

I confirmed through a non-Admin cmd prompt, that my user is allowed to create symlinks in the needed folders. On Windows 11 this should work without other settings. I enabled developer mode in Windows anyways, just to check, without success.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.
Are you able to create symlinks in Emacs directly with the `make-symbolic-link` function? I don't have a windows VM on hand at the moment to test,  but I'll spin one up tomorrow to investigate.

**Comment by domsch1988** [comment]
No, the function called directly through emacs also fails
![grafik](https://github.com/progfolio/elpaca/assets/1961154/6a8a1767-6b85-442f-b3b4-d446cd9c753d)

Same action through a non-Admin cmd prompt is allowed
![grafik](https://github.com/progfolio/elpaca/assets/1961154/afc39df9-7159-48ff-a82f-b8d8eb8d8ef9)

This is also after completely uninstalling emacs and freschly installing 28.2 through winget.

**Comment by domsch1988** [comment]
I tested this again on a second Machine.
Again, Windows 11, latest Updates installed.
I pulled emacs 30.0.50 fresh from alpha.gnu.org as a zip (not the installer version)
Deleted my entire .emacs.d folder and set up the bare init.el and early-init.el as per the Readme.
Same result as above.

**Comment by domsch1988** [comment]
I really don't try to spam this thread, but the situation is all over the place.
Yesterday, i was able to get this working without issues on my Windows 11 work Laptop with the Installer Version of emacs 30.0.50.
Today, on my Windows 11 PC at home, same Updates installed, the same 30.0.50 installer Version of emacs comes back with the permission error.

I tried setting the permission for my user through gpedit anyways, but that didn't help.
I also share the emacs configuration between both PC's through a git repository, so no differences in the coniguration.

**Comment by domsch1988** [comment]
I really don't try to spam this thread, but the situation is all over the place.
Yesterday, i was able to get this working without issues on my Windows 11 work Laptop with the Installer Version of emacs 30.0.50.
Today, on my Windows 11 PC at home, same Updates installed, the same 30.0.50 installer Version of emacs comes back with the permission error.

I tried setting the permission for my user through gpedit anyways, and that seems to have helped?
In gpedit.msc the path is 
```
 <computer configuration>
   <Windows settings>
     <security settings>
       <local policy>
         <user rights>
           <creating symbolic links>
```
There you can add your User. gpupdate doesn't seem to be enough. For me it started working after logging out and back in.

With that said, "officially" this shouldn't be necesarry under windows 11. And at my work machine it wasn't. It MIGHT be the case that our IT guy has set this setting through GPO, but i highly doubt that.

For me at least, this is now working on both my machines so i'll close this.

**Comment by progfolio** [comment]
Apologies for the delayed response (health issue of my own to resolve).  I haven't had time to spin up a VM,  but I'm glad you were able to get this working. This tilts me more in favor of #72. I'll look into implementing it when I have time.

**Comment by High-Flyer** [comment]
Very beginners with taming emacs here on windows, I think i found the solution.
I was also stuck on file-error "Making symbolic link" Operation not permitted
**Just delete elpaca folder start emacs as admin and problem will be solved.**
Just my 2 cents thank you community.
