### ISSUE TITLE
[Feature]: Allow :tag to target "Latest tagged release" 

### ISSUE THREAD

**Issue by nathanvy** [progfolio/elpaca#126]
### Feature Description

It would be handy to have a way, rather than individually specifying specific tags for each package, to just pull "the most recent tag" or "latest tagged release" when fetching package sources.

Unless I have misunderstood the docs this is not currently supported.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a feature request.

> It would be handy to have a way, rather than individually specifying specific tags for each package, to just pull "the most recent tag" or "latest tagged release" when fetching package sources.

This can be done now with a `:pre-build` step and the proper git commands.
Elpaca is also designed in a way that should make it fairly easy to extend the syntax of the recipe format. For example, here's a test which extends the `:tag` recipe keyword to accept a `:latest` value which should check out the latest tag:

```emacs-lisp
(elpaca-test
  :dir "elpaca.tags"
  :init
  (defun +elpaca-recipe-tag-latest (recipe)
    "Translate :tag RECIPE keyword's :latest option."
    ;; Only applies when a recipe has specified :tag :latest.
    (when-let ((tag (plist-get recipe :tag))
               ((eq tag :latest)))
      (list :depth nil ; Can't rely on a shallow clone to get the latest tag.
            :pre-build ; Grab the most recent tag and check it out.
            '(let* ((tag (elpaca-with-process
                             (elpaca-process-call "git" "describe" "--tag" "--abbrev=0" "--always")
                           (if success (string-trim stdout)
                             (error "Unable to find latest tag: %S" stderr)))))
               (elpaca-with-process (elpaca-process-call "git" "checkout" tag)
                 (if success (message "checked out tag: %s" tag)
                   (error "Unable to check out tag: %S" stderr))))
            ;; remove our custom value so it does not interfere with the usual value checks.
            :tag nil)))

  ;; `elpaca-recipe-functions' will translate any recipe matching the above criteria.
  (setq elpaca-recipe-functions '(+elpaca-recipe-tag-latest))

  ;; Use our new syntax below.
  (elpaca (ement :host github :repo "alphapapa/ement.el" :tag :latest)))
```

The above only works for cases where the tag is available through git.
It also assumes that tag is a "release" tag. It could be made more general, though.

Some package authors do not tag releases and maintain version changes solely in the package's metadata header. These kinds of version changes can be detected (via git blame), but it's a little trickier. The same principle would apply, though.

I'll have to think on whether or not I'd like to include those options by default for the `:tag` recipe keyword. Thanks for the suggestion.

**Comment by progfolio** [comment]
> I'll have to think on whether or not I'd like to include those options by default for the :tag recipe keyword. 

In the interest of keeping the core functionality simple, I'll leave this up to interested parties to implement as an extension.
