### ISSUE TITLE
Some recipes missing

### ISSUE THREAD

**Issue by kandread** [progfolio/elpaca#13]
## What's wrong

First off, thanks for this package! I've been migrating my setup to `elpaca` and not sure if I'm doing anything wrong, but I can't install some packages: `ol-notmuch` and `consult-notmuch` in particular. They do have MELPA recipes and I can see the files under `elpaca-directory/cache/melpa/recipes`, but I can't find them when I either try to install them or search in `elpaca-manager`. It seems that recipes that have a source other than `github` (e.g., `sourcehut`) are the problematic ones. Tried stepping through with `edebug` but didn't have any luck.

## Directions to reproduce
- Start emacs with `emacs -Q`
- Evaluate the `elpaca` bootstrap snippet
- Either try to install `consult-notmuch` or search for it in `elpaca-manager`

### Version information

* Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
* Operating system: Linux (NixOS)

**Comment by progfolio** [comment]
> First off, thanks for this package! 

Thank you for testing it out in the early stages.
MELPA recently added support for `sourcehut` and `codeberg` as values to the `:fetcher` recipe keyword.
I've updated things on Elpaca's side so those recipes should be supported now.

Try the following:

1. update Elpaca (via `M-x elpaca-update` or the UI)
2. restart Emacs.
3. update Elpaca's menu item cache (C-u M-x elpaca-update-menus)
4. M-x elpaca-manager

You should then see both packages when you search for `-notmuch`.

Let me know how that works for you. Thanks again.

**Comment by kandread** [comment]
Worked like a charm. Thank for fixing this so quickly!
