### ISSUE TITLE
[Support]:  Clj-Org-Analyzer recipe files

### ISSUE THREAD

**Issue by kchousos** [progfolio/elpaca#130]
### Elpaca Version

Elpaca ab5f715 HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 29.0.90 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-05-03
git --version:  git version 2.40.1

### Operating System

Fedora Linux 38

### Description

Using

``` elisp
(use-package org-analyzer
  :elpaca (:host github :repo "rksm/clj-org-analyzer"))
```

doesn't work. Instead it shows this error:

```
elpaca--clone-dependencies: (file-error \"Read error\" \"Is a directory\" \"/home/kchou/.config/emacs/elpaca/repos/clj-org-analyzer/org-analyzer-el\")
```

The `.el` file is not in the root dir. How can I configure elpaca to work around that?

**Comment by kchousos** [comment]
It unfortunately doesn't work. Since I saw that this package is actually available on melpa, I tried installing it from the elpaca ui, but to no avail.

**Comment by progfolio** [comment]
> It unfortunately doesn't work.
 
You'll have to be more specific for me to help.
Are you seeing any errors?
What does the full elpaca-log show?
You can access that with `M-x elpaca-log` then typing "s"  in the log buffer to alter the search query to `.*`.

**Comment by kchousos** [comment]
Update: The following recipe works.

``` elisp
(use-package org-analyzer
  :elpaca (:main "org-analyzer-el/org-analyzer.el"))
```

Thank you for your help and for this amazing package!
