### ISSUE TITLE
[Bug]: use-package geiser-chez cause an error

### ISSUE THREAD

**Issue by dragove** [progfolio/elpaca#131]
### Elpaca Version

Elpaca 028ba74 HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-05-20
git --version:  git version 2.40.1

### Operating System

Arch Linux with emacs git version compiled with pgtk and nateive-comp

### Description

After add below code to init.el, an error raised up

```emacs-lisp
(use-package geiser-chez)
```

The error is:
⛔ Warning (emacs): Error loading "geiser-chez" autoloads: (void-function geiser-implementation-extension)

I've also tested it with

```emacs-lisp
(elpaca-test :init (elpaca geiser-chez))
```

and got the same error.

I also tried

```emacs-lisp
(use-package geiser-chez :after (geiser))
```

But the error is still there

It is weird that although I met the error, I can still use geiser with chez in .scm file.

**Comment by progfolio** [comment]
Thanks for reporting this bug.
Cached autoloads were being processed in reverse order.
I've pushed a patch which should fix this on the latest version of Elpaca.
Please try `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs`.
The autoload for that package should work as expected after that.
Testing is appreciated.

**Comment by dragove** [comment]
Thanks for your work, everything runs normally after update elpaca to the latest version.
