### ISSUE TITLE
[Bug]: Unable to answer questions asked during package installation

### ISSUE THREAD

**Issue by deejayem** [progfolio/elpaca#134]
### Elpaca Version

Elpaca 798351f HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-apple-darwin22.4.0, Carbon Version 169 AppKit 2299.5)
git --version:  git version 2.40.1

### Operating System

MacOS Ventura 13.3 and NixOS 22.11

### Description

Using a very simple config (copied from your documentation), adding `(use-package multi-vterm)`, and then starting emacs, I see the following, but cannot find how to answer (if I try, I just get `y is undefined`). The question doesn't appear in the minibuffer as it would without using elpaca.

![image](https://github.com/progfolio/elpaca/assets/2564003/75c3b2db-6879-4ca9-a844-b47dd2259b20)

Is it possible to answer it, or is elpaca swallowing it, and making it impossible?

**Comment by progfolio** [comment]
Thanks for taking the time to file a bug report.

> Is it possible to answer it

Yes. The command `elpaca-ui-send-input` can be used on any of the lines in the log which correspond to the package. There was actually a bug there, but I've patched it on the latest version. You'll want to `M-x elpaca-update` `elpaca` followed by restarting Emacs.

I tried installing `multi-vterm`. The good news I was able to answer "y" to continue the install process. The bad news is, after answreing "y",  the byte-compilation "succeeds", but the ".elc" file is empty on Emacs (version 30). I tried the same from the command line (sans Elpaca) and got the same result:

```shell
$ cd $ELPACA_BUILDS/multi-vterm/
$ emacs -q -L ../builds/vterm --batch --eval "(byte-recompile-directory  \"./\" 0  'force)"
```

I'm not sure if that's an Emacs bug, multi-vterm bug, or something else.

My advice would be to ensure vterm is built prior to installing multi-vterm.
I use the following `:post-build` recipe step to build vterm's module in my config:

```emacs-lisp
(use-package vterm
  :elpaca (vterm :post-build
                 (progn
                   (setq vterm-always-compile-module t)
                   (require 'vterm)
                   ;;print compilation info for elpaca
                   (with-current-buffer (get-buffer-create vterm-install-buffer-name)
                     (goto-char (point-min))
                     (while (not (eobp))
                       (message "%S"
                                (buffer-substring (line-beginning-position)
                                                  (line-end-position)))
                       (forward-line)))
                   (when-let ((so (expand-file-name "./vterm-module.so"))
                              ((file-exists-p so)))
                     (make-symbolic-link
                      so (expand-file-name (file-name-nondirectory so)
                                           "../../builds/vterm")
                      'ok-if-already-exists)))))

;; then install multi-vterm
```

You should be able to adapt it to your needs.
Testing is appreciated and let me know how it goes.

**Comment by deejayem** [comment]
Thank you for looking into this. With `elpaca-ui-send-input` I can install `multi-vterm` fine. The elc file isn't empty for me.

**Comment by progfolio** [comment]
> Thank you for looking into this. With `elpaca-ui-send-input` I can install `multi-vterm` fine. The elc file isn't empty for me.

Glad it's working for you. That points to a possible bug in Emacs. The machinery responsible for generating autoloads was rewritten between the version you're using and what I'm using. I'll investigate more and see if I can report it upstream. Thanks.

**Comment by nickgarber** [comment]
@deejayem Would you be willing to share the snippet where you've implemented this for demonstration/didactic purposes?

**Comment by progfolio** [comment]
> @deejayem Would you be willing to share the snippet where you've implemented this for demonstration/didactic purposes?

There shouldn't be anything to implement. `elpaca-ui-send-input` is a command bound to `!` by default in elpaca-log-mode. You would put point over a log line for the package you want to answer the question for, press `!`, then type what you want to send in the minibuffer. If you try that and it doesn't work or you are still having trouble please open a new issue.

**Comment by deejayem** [comment]
> @deejayem Would you be willing to share the snippet where you've implemented this for demonstration/didactic purposes?

@nickgarber Here's what's in my config, nothing special, as @progfolio said: https://codeberg.org/djm/dotfiles/src/branch/master/.emacs.d/lisp/init-shell.el#L34

(`use-feature` is a macro that sets `:ensure` to nil, as I'm using the version installed by nix home-manager. Previously it was working with plain `use-package` though).

**Comment by nickgarber** [comment]
I realize now that I misunderstood some context from this request. Despite my misunderstanding, (vis-a-vis an interactive solution vs non-interactive solution), you responded kindly and helpfully - just wanted to say, thanks!
