### ISSUE TITLE
[Support]: Evaluation of duplicate use-package declarations

### ISSUE THREAD

**Issue by orthofrog** [progfolio/elpaca#135]
### Elpaca Version

"Elpaca 7469471 HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-02-14
git --version:  git version 2.40.1"

### Operating System

Arch Linux

### Description

I heavily use duplicate use-package declrations like this:
```
(use-package consult
  :elpaca t
  ...)
(use-package consult
  :elpaca t
  ...)
```

and after elpaca repo update i found that only last use-package form been evaluated for each package. I didn't remember when was last update, so i checkout few commit and found that 235f9dc9ffb39a253e88ab1a4ce063bbeda732f5 commit seem like reason (but it and next commit after don't work for me at all and spit out a wrong number of argument error). From 8295909a655d984fe2da850eec441a43b7f28164 problem can be reproduced.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.
This is by design. If you prefer to have multiple declarations for the same package, set `:elpaca nil` for all but the first and make sure those declarations expand to deferred (via with-eval-after-load) code.

**Comment by orthofrog** [comment]
got it, thanks
