### ISSUE TITLE
[Bug]: `lsp-mode` not found? (hint: I am not using `lsp-mode`..)

### ISSUE THREAD

**Issue by StrictlyMonad** [progfolio/elpaca#136]
### Elpaca Version

```
Elpaca 7469471 HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
git --version:  git version 2.40.1
```

### Operating System

- NixOS (`nixos-unstable`)

### Description

After migrating to elpaca, I am running into `lsp-mode` not found error when there is no mention of lsp-mode in my configuration. 

My Emacs setup depends on Eglot and somehow Elpaca is not able to pick my Eglot setup unless invoked manually.

NOTE: this issue was not been encountered during my `straight.el` usage nor `package.el`.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.

> I am running into lsp-mode not found error

Please toggle-debug-on-error and share the backtrace for the error.

**Comment by StrictlyMonad** [comment]
Nothing is returned when I `toggle-debug-on-error`.

Here is my current eglot configuration:
```Emacs-Lisp
(use-package eglot
  :elpaca nil
  :custom
  (eglot-extend-to-xref t)
  (eglot-autoshutdown t)
  (eglot-confirm-server-initiated-edits nil))
  (eglot-menu-string "LSP")
  (eglot-ignored-server-capabilities '(:hoverProvider)))
```

This is excluding lines similar to the following:
```Emacs-Lisp
  :hook (python-mode . eglot-ensure)
```

**Comment by progfolio** [comment]
> Nothing is returned when I toggle-debug-on-error.

Where/when are you seeing the following error?:

> I am running into lsp-mode not found error

**Comment by StrictlyMonad** [comment]
Whenever I enter a new `prog-mode` buffer. Example: 
- Entering first `.rs` file -> `lsp-mode` message
- Entering second `.rs` file -> also lsp-message
- ... repeat

**Comment by progfolio** [comment]
And if you `M-x toggle-debug-on-error` and then enter a new prog-mode buffer, you do not see a backtrace buffer?

**Comment by StrictlyMonad** [comment]
Guess I should've tested another language before I spoke to early. Apparently the issue was not with elpaca, but the other package managers that failed to detect `lsp-mode` being the default for `rustic-mode`. :eyes: 

Apologies for the inconvinience and appreciate the help! :blush:
