### ISSUE TITLE
[Bug]: Cannot use doct after installing doct

### ISSUE THREAD

**Issue by philipsd6** [progfolio/elpaca#139]
### Elpaca Version

    : Elpaca 3c6dc41 HEAD -> master, origin/master, origin/HEAD
    : installer:      0.4
    : emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
    :  of 2023-05-28
    : git --version:  git version 2.40.1

### Operating System

Ubuntu 22.04.2 LTS

### Description

Given that elpaca's is asynchronous, it's not clear to me how to handle this typical workflow I've used before:

```elisp
(elpaca-test
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package doct
    :commands (doct)) ;; this defers doct

  (use-package org-capture
    :elpaca nil ;; builtin feature
    :after doct ;; but this needs doct
    :bind (("C-c c" . org-capture))
    :config
    (setq org-capture-templates (doct '(("Example" :keys "e" :type entry :clock t))))))
```

The `doct` package is cloned and built, but <kbd>C-c</kbd> <kbd>c</kbd> does not get bound, nor is `org-capture-templates` set.

**Comment by philipsd6** [comment]
Never mind... I tested after removing the `:after doct` from the second `use-package` form, and it works fine. I just thought it made sense to create the dependency since I use the previous package in the second `:config` but I guess that's not necessary.

**Comment by progfolio** [comment]
> Never mind... I tested after removing the `:after doct` from the second `use-package` form, and it works fine. I just thought it made sense to create the dependency since I use the previous package in the second `:config` but I guess that's not necessary.

The `doct` function is autoloaded, so calling it in the org-capture configuration will load doct on-demand.
