### ISSUE TITLE
[Support]: Getting error saying "Unable to determine recipe URL"

### ISSUE THREAD

**Issue by jny0444** [progfolio/elpaca#140]
### Elpaca Version

Elpaca 3c6dc41 HEAD -> master, origin/master, origin/HEAD
installer:     0.4
emacs-version:   GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66))
 of 2023-06-04
git --version:   git version 2.41.0

### Operating System

Mac OS

### Description

I installed elpaca yesterday and decided to install straight.el as well and tried installing a package called frame but now its showing this
<img width="1440" alt="Screenshot 2023-06-05 at 3 47 33 PM" src="https://github.com/progfolio/elpaca/assets/122870185/93aef435-f6a6-45d4-a2a6-324b24f01d73">

**Comment by jny0444** [comment]
nvm I got it corrected
I entered
`:elpaca nil`
and its fixed now

**Comment by progfolio** [comment]
You'll want to do that for any package which is built-in to Emacs.
