### ISSUE TITLE
[Feature]: Allow for evaluating `use-package` forms after init

### ISSUE THREAD

**Issue by philipsd6** [progfolio/elpaca#141]
### Feature Description

I'm not sure if this is a feature request, or a documentation request, but I have a literate Emacs config.org file and I often add a new package to an org-babel src block and then during that session, execute it with <kbd>C-c</kbd> <kbd>C-c</kbd> to try it out in my current session. But when I do that with a typical block like this:

```elisp
#+begin_src emacs-lisp
(use-package org-bulletproof
  :elpaca (:host github :repo "pondersson/org-bulletproof" :files (:defaults (:exclude "*-test.el")))
  :config
  (global-org-bulletproof-mode +1))
#+end_src
```

What happens when I execute that block is the *elpaca-log* buffer shows up -- but its empty, and does nothing. Is there some way to make this DWIM? The `elpaca-try` function isn't helpful, because this package (like many others) is not in the list of things to try. 

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for the suggestion. Added to current master branch.
Testing is appreciated.

**Comment by philipsd6** [comment]
Works perfectly, and sheesh, if I'd know it was as simple as that, I would have made a PR. :) 

Thanks!

**Comment by progfolio** [comment]
> Works perfectly, and sheesh, if I'd known it was as simple as that, I would have made a PR. :)
> 
> Thanks!

You're welcome. Thanks for testing.
