### ISSUE TITLE
[Support]: Can I install packages from Emacswiki using elpaca?

### ISSUE THREAD

**Issue by emacs-elements** [progfolio/elpaca#144]
### Elpaca Version

Elpaca f2a2414 HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 29.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2023-06-05
git --version:  git version 2.34.1

### Operating System

Linux Mint

### Description

Can I create a recipe(s) to install packages from Emacswiki using Elpaca. There are a few I use consistently but they require manually having to download to update:

bookmark+-chg.el
bookmark+-doc.el
bookmark+-lit.el
bookmark+-key.el
bookmark+-1.el  
bookmark+-bmu.el
bookmark+-mac.el
bookmark+.el    
highlight.el    
showkey.el      
festival.el     
vline.el        
col-highlight.el
hl-line+.el     
crosshairs.el   
hide-comnt.el   
thing-cmds.el   
sortie.el       
grep+.el        
fit-frame.el    
frame-fns.el    
frame-cmds.el   
zoom-frm.el

They are generally stored here:

https://www.emacswiki.org/emacs/

**Comment by progfolio** [comment]
Hi.

Elpaca is designed around using git repositories to store packages.
If there are mirrors of any of those packages which are stored in git repositories, you could point a recipe directly to those and it will work.
You can also store the elisp in a local repository and point the `:repo` keyword at the local file path.
That will give you the benefit of being able to easily build/rebuild/activate the package.

In theory, a menu could be made which scrapes the wiki directly and sets up a local git repository for each package, but  it's not something I plan on adding directly to Elpaca.

**Comment by emacs-elements** [comment]
I appreciate your assistance. I am looking forward to making the most of Elpaca with your suggested methods.
