### ISSUE TITLE
[Feature]: AOT native-compilation step

### ISSUE THREAD

**Issue by sashimacs** [progfolio/elpaca#146]
### Feature Description

elpaca is great but compared to straight.el cannot easily do ahead-of-time native compilation of packages. This can be a pretty bad experience as after elpaca is "technically done" I typically get a lot of slowdowns and comp warning windows pop-up as native-comp eventually happens bit-by-bit and it can be very jarring, particularly as some packages I only use occasionally.

I understand this might be possible with a custom build step but I didn't have any luck with that when I tried it. Maybe this is just some documentation on how to achieve this but I think an opt-in feature would be really great.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
I've implemented a rough draft for this feature on the "feat/aot-native-comp" branch.
You can try it by evaluating the following test case in you \*scratch\* buffer:

```emacs-lisp
(elpaca-test
  :ref "feat/aot-native-comp"
  ;; Needs to be set before Elpaca is loaded.
  :early-init (setq elpaca-aot-native-compilation t)
  :init (elpaca doct))
```

I don't think it's quite ready to merge because of the differences in setting the target directory for the eln files between Emacs 28 and 29+. Because the native compilation takes place ina subprocess, we'll want to inherit native-comp-eln-load-path (only present in 29.1+).
That's important because, otherwise, the child process will generate the eln files to the default folder. If anyone is aware of how to do that before 29.1, I can implement it.
You can check out the

**Comment by sashimacs** [comment]
Thanks for taking the time to look into this! I couldn't get the `elpaca-test` statement working correctly but I tried a full fresh install (removing my eln-cache and entire elpaca dir) with:

```emacs-lisp
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref "feat/aot-native-comp"
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
```

and setting `elpaca-aot-native-compilation` `t` in my early init and it all worked perfectly. I understand the debate around paying the upfront AOT cost but for me the extra time up-front is worth getting rid of slow-downs after a clean install/updates.

**Comment by progfolio** [comment]
> Thanks for taking the time to look into this!

You're welcome.

> I couldn't get the elpaca-test statement working correctly

Interesting. Were you seeing errors or anything I may be able to look into?

> I tried a full fresh install (removing my eln-cache and entire elpaca dir)

You could probably get away with just doing:

1. Edit elpaca-order :ref to point where you want and save the init file.
2. M-x elpaca-delete elpaca
3. Restart Emacs

That would save most of the work of re-downloading ELPA recipes and installing everything else.

> setting elpaca-aot-native-compilation t in my early init

Doesn't necessarily need to be in the early-init.
I used that in the `elpaca-test` form becauase the `:init` happens after the installer/bootstrap snippet. So long the option is set before Elpaca is loaded it should work.

> I understand the debate around paying the upfront AOT cost but for me the extra time up-front is worth getting rid of slow-downs after a clean install/updates.

I'll keep the branch around in case anyone is interested in looking into how this would need to be done on Emacs 28. Once that's implemented I could merge this feature.

**Comment by progfolio** [comment]
No interest has been shown in completing this feature, so I'll consider this closed for now.
