### ISSUE TITLE
[Bug]: `(wrong-number-of-arguments #<subr button-buttonize> 4)`

### ISSUE THREAD

**Issue by ryunix** [progfolio/elpaca#148]
### Elpaca Version

Elpaca 1392caa HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-05-19
git --version:  git version 2.39.3

### Operating System

Gentoo Linux

### Description

I found a bug in 1392caa.

Getting an error on Emacs 28.

Calling `#'elpaca-ui--buttonize` with 4 arguments.

https://github.com/progfolio/elpaca/blob/1392caa3774293baa7379f2d817b76dda001812f/elpaca-ui.el#L114-L115

`#'buttonize` (used in Emacs 29) has 4th argument.

```emacs-lisp
(defun buttonize (string callback &optional data help-echo)
```

`#'button-buttonize` (used in Emacs 28) does not have 4th argument.

```emacs-lisp
(defun button-buttonize (string callback &optional data)
```

**Comment by progfolio** [comment]
Thanks for catching that. Should be fixed on latest master. `M-x elpaca-update elpaca` followed by restarting Emacs should do the trick. Testing is appreciated.

**Comment by ryunix** [comment]
Thank you for the update. No error after updated.

**Comment by progfolio** [comment]
Thanks for testing
