### ISSUE TITLE
Customizing "builds" directory

### ISSUE THREAD

**Issue by bestlem** [progfolio/elpaca#15]
I like to run different versions of emacs e.g. a stable 28.1 and a development branch on 29

As compiled .elc files are not necessarily compatible over versions you need different build directories for each version.
I can control the original bootstrap but elpaca-build-dir hard codes this.

straight.el has the variable straight-build-dir to control this.

**Comment by progfolio** [comment]
> I can control the original bootstrap but elpaca-build-dir hard codes this.

I've added the `elpaca-builds-directory` variable, which should allow you to conditionally change where files are built.

**Comment by progfolio** [comment]
I've moved your note about the log buffer to #16.
Feel free to open as many issues as necessary, but please keep them to a single topic.
It makes it easier to manage and search form them.

**Comment by bestlem** [comment]
That seems not to be sufficient.
I chnage the build directory to
```
(defvar elpaca-builds-directory (expand-file-name (concat "builds-" emacs-version) elpaca-directory))
```
Run with emacs 28.1 and get what is expected. ~//.emacs.d/elpaca/builds-28.1/elpaca from the last line.

I then run emacs 29.0 and it fails on the last line.
```
 Warning (initialization): An error occurred while loading ‘/Users/mark/.emacs.d/init.el’:

Symbol's function definition is void: elpaca```

load-path has in it ```"/Users/mark/.emacs.d/elpaca/repos/elpaca/" ``` which is
 an Unexpected error as elpaca.el IS in that directory - actual error is run-hooks: Symbol’s function definition is void: elpaca-process-queues (I now remember why I don't like async - errors don't get reported as a simple backtrace et al)

Now do the opposite and run emacs 29 to create the original setup then run an emacs 28.1 - this fails with 
```byte-code: Symbol’s function definition is void: defvar-1```
I suspect that emacs 29 byte code is not readable by emacs 28.

I think the bootstrap process has to look for the build directory or as straight doe forceably recompile the elpaca code.

**Comment by bestlem** [comment]
A possible fix is asking why do we need to compile the bootstrap elpaca? It only runs when you first start a emacs version - after that it picks up elpaca from the versioned build directories.

If we remove the byte-recompile line

and also add just after the bootstrap when-let 
```
(require 'elpaca)
```

I tried new elpaca bootstraps with bothe versions and the other version run afterwards and it seems to work - using the minimal init-file. You end up with the two build directory under elpaca and on the restart you get elpaca from the versioned build directory not the bootstrap.

**Comment by progfolio** [comment]
> I suspect that emacs 29 byte code is not readable by emacs 28.

That's likely correct.

Try this:

1. Delete each `$BUILDS/elpaca` and `$REPOS/elpaca` directory.
2. comment out the bootstrap snippet line which byte-compiles Elpaca during the initial repo bootstrap:

```emacs-lisp
;;        (byte-recompile-directory elpaca-repo 0 'force)
```
3. Relaunch Emacs. 

Elpaca's repos should be rebuilt in $REPOS/elpaca without being byte-compiled.
That should allow it to load in the absence of a version-specific $BUILD/elpaca folder for both versions.

Let me know how that works out.

> I think the bootstrap process has to look for the build directory or as straight does, forcibly recompile the elpaca code.

$BUILDS/elpaca is used if it exists. If not, $REPOS/elpaca is used. I'd like to avoid complicating the bootstrap too much so skipping the byte-compilation altogether in this situation is probably the simple solution.

**Comment by bestlem** [comment]
After understanding that elpaca-build is not really used my init-file looks like.
```
;; -*- lexical-binding:t;coding: utf-8 -*-
(declare-function elpaca-generate-autoloads "elpaca")
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name (concat "builds-" emacs-version) elpaca-directory))
(when-let ((elpaca-repo (expand-file-name "repos/elpaca/" elpaca-directory))
           (elpaca-url  "https://www.github.com/progfolio/elpaca.git")
           ((add-to-list 'load-path elpaca-repo))
           ((not (file-exists-p elpaca-repo)))
           (buffer (get-buffer-create "*elpaca-bootstrap*")))
  (condition-case-unless-debug err
      (progn
        (unless (zerop (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo))
          (error "%s" (list (with-current-buffer buffer (buffer-string)))))
        (require 'elpaca)
        (elpaca-generate-autoloads "elpaca" elpaca-repo)
        (kill-buffer buffer))
    ((error)
     (delete-directory elpaca-directory 'recursive)
     (with-current-buffer buffer
       (goto-char (point-max))
       (insert (format "\n%S" err))
       (display-buffer buffer)))))
(require 'elpaca)
(require 'elpaca-autoloads)
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca (elpaca :host github :repo "progfolio/elpaca"))

(elpaca use-package (require 'use-package)) ; install use-package

(elpaca-use-package dash
					:demand
					:config
					(global-dash-fontify-mode))

(elpaca-use-package f :demand)

```

**Comment by progfolio** [comment]
> I tried new elpaca bootstraps with both versions and the other version run afterwards and it seems to work - using the minimal init-file. You end up with the two build directory under elpaca and on the restart you get elpaca from the versioned build directory not the bootstrap.


lol. Looks as if you've already tried what I suggested as I was typing it up. Glad that fixes things for you.
Stick with that for now.
I have plans to improve the bootstrap snippet.
 I'll take this use-case into consideration.

> A possible fix is asking why do we need to compile the bootstrap elpaca? It only runs when you first start a emacs version - after that it picks up elpaca from the versioned build directories.

That is true. Do you see much of a difference in the initial install time when running Elpaca without byte-compiling it?
I imagine the bottleneck is  in network/subprocess activity, but I haven't tested this myself yet.
That's my only concern with just skipping it altogether.
I could probably add a variable and conditionally check whether the user plans on running multiple Emacs versions which could be set above the bootstrap snippet.
