### ISSUE TITLE
[Bug]: Failed to bootstrap via HTTP proxy on macOS

### ISSUE THREAD

**Issue by jessie-hu-95** [progfolio/elpaca#152]
### Elpaca Version

Elpaca 2e65018 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.5.0, Carbon Version 169 AppKit 2299.6)
 of 2023-06-11
git --version:  git version 2.39.2 (Apple Git-143)

### Operating System

macOS Ventura 13.4.1

### Description

I just paste the bootstrap code into my `config.org` file, load it by `init.el`, and add `(setq package-enable-at-startup nil)` to `early-init.el`.
After reopening the Emacs app, the *elpaca-log* buffer lists only one package, `elpaca`, whose status is "failed" and info is `No recipe: (error "Selecting deleted buffer")`.
I tried to reinstall the package by `r x` keys, but it still didn't work.

*Message* buffer output:
```
Loading /Users/jessie/.config/emacs/config.el (source)...
(New file)
  INFO     Scraping files for elpaca-autoloads.el... 
Generating autoloads for elpaca-info.el...done
Generating autoloads for elpaca-log.el...done
Generating autoloads for elpaca-manager.el...done
Generating autoloads for elpaca-menu-gnu-elpa-mirror.el...done
Generating autoloads for elpaca-menu-melpa.el...done
Generating autoloads for elpaca-menu-non-gnu-elpa.el...done
Generating autoloads for elpaca-menu-org.el...done
Generating autoloads for elpaca-process.el...done
Generating autoloads for elpaca-test.el...done
Generating autoloads for elpaca-ui.el...done
Generating autoloads for elpaca.el...done
  INFO     Scraping files for elpaca-autoloads.el...done
Wrote /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-autoloads.el [2 times]
Cloning into '/Users/jessie/.config/emacs/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /Users/jessie/.config/emacs/elpaca/repos/elpaca...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-info.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-log.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-menu-gnu-elpa-mirror.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-menu-non-gnu-elpa.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-process.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-test.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/elpaca.el...
Checking /Users/jessie/.config/emacs/elpaca/repos/elpaca/doc...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/doc/early-init.el...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/doc/init.el...
Checking /Users/jessie/.config/emacs/elpaca/repos/elpaca/extensions...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/extensions/elpaca-use-package.el...

In toplevel form:
extensions/elpaca-use-package.el:28:1: Error: Cannot open load file: No such file or directory, use-package
Checking /Users/jessie/.config/emacs/elpaca/repos/elpaca/images...
Checking /Users/jessie/.config/emacs/elpaca/repos/elpaca/test...
Compiling /Users/jessie/.config/emacs/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 1 failed, 3 skipped in 4 directories)

Downloading MELPA recipes...
Added to /Users/jessie/.config/emacs/elpaca/cache/melpa/.git/info/sparse-checkout
Downloading MELPA recipes...100%
Using a proxy for https...
Loading /Users/jessie/.config/emacs/config.el (source)...done
Loaded /Users/jessie/.config/emacs/config.el
```

**Comment by jessie-hu-95** [comment]
I also tried to git clone the repo manually or remove the line `:files (:defaults (:exclude "extensions"))` in the bootstrap code. Both didn't work.

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a bug report.

> I also tried to git clone the repo manually or remove the line :files (:defaults (:exclude "extensions")) in the bootstrap code. Both didn't work.

I wouldn't expect that to work.
Try the following:

1. Remove the elpaca-directory (should be at ~/.emacs.d/elpaca/ by default).
2. Ensure the unmodified installer script is in your init.el (undo any changes made to it).
3. Start emacs from the command line passing the `--debug-init` flag. You may need to invoke it a certain way on Mac. See: https://emacs.stackexchange.com/questions/53646/how-do-you-run-emacs-on-mac
4. This should cause Emacs to hit the debugger when an error is signaled. When that happens copy the entire contents of that buffer to this issue. You'll want to expand all the ellipses before copying (usually bound to ".").

**Comment by jessie-hu-95** [comment]
Hi. progfolio. Thank you for your timely response.

Here is the output of the `*Backtrace*` buffer:
```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  elpaca-menu-melpa--metadata()
  elpaca-menu-melpa--index()
  elpaca-menu-melpa(index)
  elpaca--menu-items(t)
  elpaca-menu-item(elpaca nil)
  elpaca-recipe((elpaca :repo "https://github.com/progfolio/elpaca.git" :ref nil :files (:defaults (:exclude "extensions")) :build (:not elpaca--activate-package)))
  elpaca<-create((elpaca :repo "https://github.com/progfolio/elpaca.git" :ref nil :files (:defaults (:exclude "extensions")) :build (:not elpaca--activate-package)))
  elpaca--queue((elpaca :repo "https://github.com/progfolio/elpaca.git" :ref nil :files (:defaults (:exclude "extensions")) :build (:not elpaca--activate-package)) (elpaca-q< init 0 0 incomplete (25758 20478 467611 0) nil nil nil))
  (progn (elpaca--queue order-0 q-2))
  (if order-0 (progn (elpaca--queue order-0 q-2)))
  (let* ((order-0 elpaca-order) (item-1 (elpaca--first order-0)) (q-2 (or (and after-init-time (elpaca--q (elpaca-get item-1))) (car elpaca--queues)))) (if order-0 (progn (elpaca--queue order-0 q-2))) (if after-init-time (progn (let* ((e (and t (elpaca-get item-1)))) (if e (progn (elpaca--maybe-log t) (elpaca--unprocess e) (let* ((c (nthcdr 4 e))) (setcar c (cons 'queued (car c))))) nil)) (if (member this-command '(eval-last-sexp eval-defun)) (progn (elpaca-process-queues))) (if (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c)) (progn (if elpaca--interactive-timer (progn (cancel-timer elpaca--interactive-timer))) (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues))))) nil)
  load-with-code-conversion("/Users/jessie/.config/emacs/init.el" "/Users/jessie/.config/emacs/init.el" t t)
  load("/Users/jessie/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x187effab668d2cb4>) #f(compiled-function () #<bytecode 0x4d12c0e0e45188b>) t)
  command-line()
  normal-top-level()
```

**Comment by progfolio** [comment]
Thanks. That helps narrow down the issue.
It looks like the buffer used when retrieving the MELPA package metadata JSON is immediately killed.
This could be due to a networking issue.
Try the following:

1. Check to see if you are able to access https://melpa.org/archive.json with your browser. That may reveal a general netowrking issue.
2. If you can access the URL, try evaluating the following in your \*scratch\* buffer:

```emacs-lisp
(if-let ((debug-on-error t)
         (b (url-retrieve-synchronously "https://melpa.org/archive.json"))
         ((buffer-live-p b)))
    (with-current-buffer b
      (message "%S" (buffer-substring-no-properties (point-min) (point-max))))
  (error "Could not retrieve MELPA package metadata"))
```

If a backtrace buffer appears due to an error being signaled, please copy the whole backtrace buffer here as before.
Also copy the output in the \*Messages\* buffer (it may be best to kill the before just before evaluating the code so there aren't other messages)
for any output from `url-retrieve-sychronously`. Successful output will look like this, but your output will likely differ:

<details><summary>\*Messages\*</summary>

```
Contacting host: melpa.org:443
"HTTP/1.1 200 OK
Server: nginx
Date: Fri, 30 Jun 2023 13:05:17 GMT
Content-Type: application/json
Content-Length: 2256916
Last-Modified: Fri, 30 Jun 2023 13:02:15 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: \"649ed257-227014\"
Strict-Transport-Security: max-age=15768000
Accept-Ranges: bytes

{\"0blayout\":{\"ver\":[20190703,527],\"deps\":null,\"desc\":\"Layout grouping with ease\"...
LONG JSON BODY OMITTED
```
</details>

**Comment by jessie-hu-95** [comment]
Hi, progfolio.

1. The browser gives me the contents of the `archive.json` file.
2. I get `"\"\""` from the prompt line, and the `*Messages*` buffer outputs:
```
Loading /opt/local/share/emacs/site-lisp/subdirs.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
Mark set
Using a proxy for https...
Contacting host: melpa.org:443
""
"\"\""
Making completion list...
```

I appreciate your responses and after looking into it, I found out it was my network causing the issue. I am in China, and I setup a http(s) proxy for connection to GitHub. GitHub is accessible from a terminal after exporting the two environment variables, `http_proxy` and `https_proxy`. By the way, I can also get `archive.json` by (`http` is a command provided by `httpie` package):
```
http https://melpa.org/archive.json
```

Could you possibly provide a solution for this? Thank you.

**Comment by jessie-hu-95** [comment]
I also tried to use the TUI version Emacs. Nothing changed.

**Comment by jessie-hu-95** [comment]
Sorry for wasting your time.

After some tweaks on network configuration, it works...
I have no clue what happens. Maybe my network have been changed by some network managers?

😢

**Comment by progfolio** [comment]
Glad to hear it's working for you.
