### ISSUE TITLE
[Bug]: Nov can't be installed because of "idiot http"

### ISSUE THREAD

**Issue by Safenein** [progfolio/elpaca#153]
### Elpaca Version

Elpaca 2e65018 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
 of 2023-06-28
git --version:  git version 2.41.0

### Operating System

6.3.8-arch1-1
Archlinux

### Description

I'm new to Elpaca, so I'm might not now how to use it properly for now. I'm currently using the use-package macro of elpaca as I'm more used to it

The snippet:
```emacs-lisp
(use-package nov)
```

What I expected: Nov get installed and now I can read epub.

What happened: Emacs randomly insults http protocol for being idiot. I'm translating the error message as my emacs is not in english: "the idiot protocol http doesn't support superficial capacity".

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a bug report.
 "dumb" protocol is what git calls a certain type of transfer protocol.
For now, Elpaca has some locale-dependent code which checks if that protocol is available for a repository and, if not, attempts to reclone. You should be able to work around errors of this type by adding `:depth nil` to the package recipe.

e.g.

```emacs-lisp
(use-package nov :elpaca (:depth nil))
```

Does that help?

**Comment by Safenein** [comment]
Works flawlessly. Thank you very much.
