### ISSUE TITLE
[Bug]: Elpaca upgrade doesn't work with new function `elpaca-log-defaults`

### ISSUE THREAD

**Issue by realcomplex** [progfolio/elpaca#155]
### Elpaca Version

Elpaca 084a7df HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
git --version:  git version 2.41.0

### Operating System

Fedora 38

### Description

Unfortunately not entirely trivial to replicate the issue since it involves a bug in an elpaca version upgrade path, but hopefully I can explain it well enough.

I just updated elpaca to the newest version (i.e. `elpaca-update` `elpaca`) and restarted emacs. This results in an error that the function `elpaca-log-defaults` is undefined. This function was recently introduced.

The issue is resolved by manually deleting `elpaca/repos/elpaca` and `elpaca/builds/elpaca` and restarting emacs in order to force elpaca to bootstrap itself from scratch. Maybe updating elpaca doesn't generate autoloads for newly defined functions correctly? Something else?

Hopefully this is a good enough description of the problem; if it's not helpful I could try to downgrade elpaca and update it again in order to reproduce the issue fully.

Thanks for the work on this package!

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.

> The issue is resolved by manually deleting `elpaca/repos/elpaca` and
> `elpaca/builds/elpaca` and restarting emacs in order to force elpaca to
> bootstrap itself from scratch. Maybe updating elpaca doesn't generate autoloads
> for newly defined functions correctly? Something else?

For situations like this, you may be able to get away with `M-x elpaca-delete` `elpaca` followed by `M-x restart-emacs`. That should install Elpaca without having to re-install all your other packages.
  
> Hopefully this is a good enough description of the problem; if it's not helpful
> I could try to downgrade elpaca and update it again in order to reproduce the
> issue fully.

The description is fine and your hunch about autoloads makes sense.
Perhaps they were stale somehow.
Unfortunately I'm unable to reproduce the issue on my end.
If you find a way to reproduce it, let me know and I'll look into it.

Feel free to experiment with `elpaca-test` so you don't have to mess with your normal configuration. Here's what I tried:

1. Evaluate the following test case in your \*scratch\* buffer.
   It will install Elpaca and magit in a clean, temporary test environment.

```emacs-lisp
(elpaca-test
  :dir "elpaca.update-bug"
  :interactive t
  :keep t
  :init
  (elpaca magit))
```

2. Using the test Emacs instance, `M-x elpaca-visit` `elpaca` after everything is installed.
3. In the dired buffer for Elpaca's repo `M-x magit-reset-hard` `HEAD~10`
   You can change the number from 10 to rollback N commits.
4. `M-x elpaca-rebuild` `elpaca`. You should now have an older version of Elpaca built.
5. `M-x restart-emacs`
6. Once the test Emacs restarts, `M-x elpaca-udpate` `elpaca`. This should pull in the N commits that were rolled back in the step 3 and rebuild Elpaca. I would also check the `elpaca-log` output to see if there are any errors at this point.
7. `M-x restart-emacs` to see if the `elpaca-log-defaults` is undefined error is signaled.
    You should be able to `M-x describe-function` `elpaca-log-defaults` if everything worked as intended.


> Thanks for the work on this package!

You're welcome and thanks for using/testing it.

**Comment by progfolio** [comment]
> Just for completeness: deleting `elpaca` only works if you delete `elpaca-use-package` before.
 
This depends on how `elpaca-delete` is called.
`elpaca-delete` should refuse to delete dependencies of a package.
`C-u elpaca-delete` should delete dependencies too.
`C-u C-u elpaca-delete` should do the same, but without prompting.
When a package is marked for deletion from the UI, the FORCE and DEPS args are non-nil.

> **Edit**: deleting elpaca and removing the eln-cache solved this issue for me. Thanks for your support!

Glad you've got it working. I'll look into it more. Updating Elpaca should not require either of those steps.

**Comment by StrictlyMonad** [comment]
Can confirm that executing `elpaca-delete` -> `elpaca-use-package` & `elpaca` resolves the issue.

**Comment by progfolio** [comment]
I'm looking into this as we speak. Did you happen to notice whether or not the $BUILDS/elpaca/ directory was present when you were seeing the error? The only way I've been able to reproduce this is by deleting the $BUILDS/elpaca/ directory.
That can leave the $REPOS/elpaca/ directory in a state where the .elc files generated during the installation script are stale.
That's a plausible explanation (and the solution would be to set load-prefer-newer to t when loading directly from the $REPOS/elpaca/ dir), but I'm not sure why the $BUILDS/elpaca/ would be missing.

**Comment by StrictlyMonad** [comment]
I honestly did not check if the directory was present or not but if I run into this issue again, I'll make sure to look there first!

**Comment by aaronjensen** [comment]
I ran into this as well after updating Emacs (a master build to a newer master build) and then running elpaca-update-all. Deleting elpaca-use-package and elpaca fixed it for me as well. Unfortunately, I didn't check the elpaca directory in $BUILDS before doing so.

**Comment by progfolio** [comment]
> I ran into this as well after updating Emacs (a master build to a newer master build) and then running elpaca-update-all. Deleting elpaca-use-package and elpaca fixed it for me as well. Unfortunately, I didn't check the elpaca directory in $BUILDS before doing so.

Thanks. I'm pretty sure that's the scenario where the issue occurs. I'll have to think of a way to fix it without complicating the installer script too much. If it does happen again and you think of it, check to see if that folder is there.

**Comment by darkfeline** [comment]
FWIW I see this issue too, with my submodule setup.  The autoloads aren't regenerating when elpaca repo is updated out of band, apparently.

**Comment by progfolio** [comment]
> The autoloads aren't regenerating when elpaca repo is updated out of band, apparently.

Thanks for the data point. You'll have to describe how  you're updating the elpaca repo. The way you've set it up may not be supported.

**Comment by darkfeline** [comment]
> You'll have to describe how you're updating the elpaca repo.

By git resetting the elpaca repo to an arbitrary commit (a pinned "latest" commit via git submodules, basically how a lock functionality might work).  This can happen at any point, usually when an existing Emacs session is running, via magit or git in a separate terminal.

> The way you've set it up may not be supported.

Undoubtedly, though I think this is the general problem that elpaca doesn't check/rebuild itself on startup, likely for performance reasons.

**Comment by progfolio** [comment]
> I think this is the general problem that elpaca doesn't check/rebuild itself on startup, likely for performance reasons.

I've tried quite a few variations on the installer script to try and reduce the probability of stale autoloads, but ultimately I don't think we can guarantee anything short of storing a hash on disk and comparing it at every startup.
That wouldn't be acceptable performance wise.

I think the best we can do here is document the best way to deal with stale autoloads manually.
