### ISSUE TITLE
[Feature]: lint elpaca macro BODY

### ISSUE THREAD

**Issue by elizagamedev** [progfolio/elpaca#158]
### Elpaca Version

```
Elpaca a216ca8 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
git --version:  git version 2.40.1
```

### Operating System

Linux, nixOS

### Description

To reproduce, just enable flymake in an elisp buffer on a recent-ish version of Emacs and write some nonsense forms in an `(elpaca ...)` macro call. The documentation isn't really clear when `elisp-flymake-byte-compile` was added so I'm not sure of the specific version.

The issue seems to be that the form isn't compiled at compile time, which makes sense, given that the package might not exist at compile time. The only way I think this could be fixed is if the `elpaca` macro detected that it's being evaluated in the context of `elisp-flymake-byte-compile` and the entire macro short-circuited into something like...

```
(require foo nil t)
(body...)
```

...which would introduce the misconception to the byte compiler that that package is now available past that `(elpaca ...)` call, but it's better than nothing.

I'm not sure if this is out of the scope of elpaca or not, or if it should be considered a bug report or a feature request. I feel like perhaps I'm a minority for using flymake with elisp instead of flycheck. I might also try fixing this myself, but I wanted to at least report a bug with my assumptions in case I'm not alone here.

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a bug report.

> The issue seems to be that the form isn't compiled at compile time, which makes
> sense, given that the package might not exist at compile time.

The BODY of the `elpaca` macro expansion was being stored as a quoted list. 
This prevents the byte-compiler from looking at it as anything more than data.
I've changed the strategy by which the forms are stored, which should resolve the issue.

>I feel like perhaps I'm a minority for using flymake with elisp instead of flycheck.

I use flymake, but I believe either tool would've run into the same issue.

You should be able to update Elpaca via `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs`. Testing is appreciated. Thank you.

**Comment by elizagamedev** [comment]
Thank you for the really quick fix! I only got to try it out just today, but it seems like it's working so far. There does seem to be a remaining issue with trying to access autoloads without an explicit, redundant require statement. For example,

```elisp
(require 'page-break-lines-autoloads nil t)
(elpaca page-break-lines
  (global-page-break-lines-mode 1))
```


I should also mention that I've been advising `elisp-flymake-byte-compile` so that it picks up my elpaca-installed packages. (Maybe not the safest advice?)
```elisp
(define-advice elisp-flymake-byte-compile
    (:around (orig-fun &rest args))
  (let ((elisp-flymake-byte-compile-load-path load-path))
    (apply orig-fun args)))
```

I tweaked the elpaca macro to insert that redundant `(require *-autoloads nil t)` if it was being evaluated during compile time. In order to fully satisfy the byte compiler, it had to be at the top of a `(progn)` outside of the `(let)`.

```elisp
(defmacro elpaca (order &rest body)
  "Queue ORDER for installation/activation, defer execution of BODY.
If ORDER is `nil`, defer BODY until orders have been processed."
  (declare (indent 1) (debug t))
  (let ((o (gensym "order-")) (item (gensym "item-")) (q (gensym "q-")))
    `(progn
       ,@(if (and order (bound-and-true-p byte-compile-current-file))
             `((require (quote ,(intern (concat (symbol-name (elpaca--first order))
                                                "-autoloads")))
                        nil t)))
       (let* ((,o ,@(if (memq (car-safe order) '(quote \`)) `(,order) `(',order)))
              (,item (elpaca--first ,o))
              (,q (or (and after-init-time (elpaca--q (elpaca-get ,item))) (car elpaca--queues))))
         ,@(when body
             `((if ,item
                   (setf (alist-get ,item (elpaca-q<-forms ,q)) (lambda () ,@body))
                 ;;@FIX: nil semantics not good for multiple deferred...
                 (push (cons ,item (lambda () ,@body)) (elpaca-q<-forms ,q)))))
         (when ,o (elpaca--queue ,o ,q))
         (when after-init-time
           (when-let ((e (elpaca-get ,item)))
             (elpaca--maybe-log)
             (elpaca--unprocess e)
             (push 'queued (elpaca<-statuses e)))
           (when (member this-command '(eval-last-sexp eval-defun)) (elpaca-process-queues))
           (when (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c))
             (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
             (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues)))
         nil))))
```

For the first time ever, flymake is giving me useful feedback for my init.el. :)

Patch below, though it modifies basically the entire function due to the changed indentation.

```diff
diff --git a/elpaca.el b/elpaca.el
index 28a5503..d3f88bb 100644
--- a/elpaca.el
+++ b/elpaca.el
@@ -1457,25 +1457,30 @@ When MESSAGE is non-nil, message the list of dependents."
 If ORDER is `nil`, defer BODY until orders have been processed."
   (declare (indent 1) (debug t))
   (let ((o (gensym "order-")) (item (gensym "item-")) (q (gensym "q-")))
-    `(let* ((,o ,@(if (memq (car-safe order) '(quote \`)) `(,order) `(',order)))
-            (,item (elpaca--first ,o))
-            (,q (or (and after-init-time (elpaca--q (elpaca-get ,item))) (car elpaca--queues))))
-       ,@(when body
-           `((if ,item
-                 (setf (alist-get ,item (elpaca-q<-forms ,q)) (lambda () ,@body))
-               ;;@FIX: nil semantics not good for multiple deferred...
-               (push (cons ,item (lambda () ,@body)) (elpaca-q<-forms ,q)))))
-       (when ,o (elpaca--queue ,o ,q))
-       (when after-init-time
-         (when-let ((e (elpaca-get ,item)))
-           (elpaca--maybe-log)
-           (elpaca--unprocess e)
-           (push 'queued (elpaca<-statuses e)))
-         (when (member this-command '(eval-last-sexp eval-defun)) (elpaca-process-queues))
-         (when (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c))
-           (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
-           (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues)))
-       nil)))
+    `(progn
+       ,@(if (and order (bound-and-true-p byte-compile-current-file))
+             `((require (quote ,(intern (concat (symbol-name (elpaca--first order))
+                                                "-autoloads")))
+                        nil t)))
+       (let* ((,o ,@(if (memq (car-safe order) '(quote \`)) `(,order) `(',order)))
+              (,item (elpaca--first ,o))
+              (,q (or (and after-init-time (elpaca--q (elpaca-get ,item))) (car elpaca--queues))))
+         ,@(when body
+             `((if ,item
+                   (setf (alist-get ,item (elpaca-q<-forms ,q)) (lambda () ,@body))
+                 ;;@FIX: nil semantics not good for multiple deferred...
+                 (push (cons ,item (lambda () ,@body)) (elpaca-q<-forms ,q)))))
+         (when ,o (elpaca--queue ,o ,q))
+         (when after-init-time
+           (when-let ((e (elpaca-get ,item)))
+             (elpaca--maybe-log)
+             (elpaca--unprocess e)
+             (push 'queued (elpaca<-statuses e)))
+           (when (member this-command '(eval-last-sexp eval-defun)) (elpaca-process-queues))
+           (when (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c))
+             (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
+             (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues)))
+         nil))))
 
 (defcustom elpaca-wait-interval 0.01 "Seconds between `elpaca-wait' status checks."
   :type 'number)
```

**Comment by elizagamedev** [comment]
Hmm, actually, it seems like that change introduces big issues, like breaking flymake diagnostics for obviously nonexistent functions. I'll keep messing around with it.

**Comment by progfolio** [comment]
> Thank you for the really quick fix! I only got to try it out just today, but it
> seems like it's working so far.

You're welcome. Thanks for testing.

> There does seem to be a remaining issue with
> trying to access autoloads without an explicit, redundant require statement. For
> example,
> 
> ```elisp
> (require 'page-break-lines-autoloads nil t)
> (elpaca page-break-lines
>   (global-page-break-lines-mode 1))
> ```

The byte compiler doesn't normally know about autoloads.
You'd either need to explicitly require the feature as in your example, or declare the symbols using `declare-function` or `defvar`. e.g.

``` emacs-lisp
(reuqire 'elpaca)

(elpaca page-break-lines
  (declare-function global-page-break-lines-mode "page-break-lines")
  (global-page-break-lines-mode 1))
```

> I tweaked the elpaca macro to insert that...

That is more in the realm of a configuration macro than the package manager itself. For example, use-package offers the `:defines` and `:functions` keywords for this purpose:

https://github.com/jwiegley/use-package#byte-compiling-your-emacs

I don't plan on adding anything to the `elpaca` macro in that regard. 

> I should also mention that I've been advising elisp-flymake-byte-compile so that it picks up my elpaca-installed packages. (Maybe not the safest advice?)

Rather than advice, you should be able to set `elisp-flymake-byte-compile-load-path`.
e.g.

``` emacs-lisp
(setq elisp-flymake-byte-compile-load-path
      (nthcdr 2 (directory-files elpaca-repos-directory 'full ".*")))
```

**Comment by progfolio** [comment]
I'll have to see if I can find another solution for this. Eager macro expansion can cause breakage when loading an init file with the fix I applied.

**Comment by progfolio** [comment]
@elizagamedev: I've got an alternate solution on the "feat/lint-init" branch. If you get a chance, try evaluating the following test case in your \*scratch\* buffer. It'll install that branch and a minimal init file in a temporary test environment. You should be able to enable flymake in the init file and see byte comp warnings.

```emacs-lisp
(elpaca-test
  :ref "feat/lint-init"
  :interactive t)
```

I still have some testing to do before I decide on whether or not this is an appropriate solution. I'll keep you posted.

**Comment by elizagamedev** [comment]
Okay, with that branch, I am getting some lints. For example, if I write

```elisp
(elpaca org
  fictional-variable)
```

Then I get lints for the variable. But if I write something like

```elisp
(elpaca org
  (defun foobar (BAR)
    "bad docstring")
  (fictional-function))
```

No lints.

I'm starting to think that maybe the only way to accomplish this is to short circuit it in the way that I described in the OP--if flymake/elisp byte compiler detected, just expand straight to BODY, otherwise, do normal elpaca stuff.

**Comment by progfolio** [comment]
Thanks for testing.

> But if I write something like...

That's interesting. For me checkdoc will miss reporting errors even if the form is wrapped ina  let form. e.g.

```emacs-lisp
(let ()
  (defun foobar (it)
    "bad docstring"
    it))
```

Does not report any warnings.
Looks like it has something to do with the indentation of the form, as:

```emacs-lisp
(let ()
(defun foobar (it) ;; <- removed indentation here
    "bad docstring"
    it))
```

Results in the expected complaints.
So that's, unfortuantely, not specific to Elpaca, and may be worth reporting as an emacs bug.


I've pushed another version of the patch which should allow for more linting.
Testing is appreciated.

> I'm starting to think that maybe the only way to accomplish this is to short circuit it in the way that I described in the OP

I'm not sure if that's a great solution, but let me know if you find a way that works well.

**Comment by progfolio** [comment]
Here's a wrapper macro which implements the changes on the WIP branch.

``` emacs-lisp
(require 'elpaca)

(defmacro elpaca-lint-body (order &rest body)
  "Like `elpaca', but byte-compiler can see ORDER's BODY."
  `(progn
     (eval-and-compile (with-eval-after-load 'elpaca-never ,@body))
     (setf (alist-get 'elpaca-never after-load-alist nil t) nil)
     (elpaca ,order ,@body)))

;; No warning
(elpaca example fictional)
;; Warning: free variable 'fictional'
(elpaca-lint-body example fictional)

;; No warning.
(elpaca example (defun foo (bar) (broken)))
;; Warning: the function 'broken' is not known to be dfined.
(elpaca-lint-body example (defun foo (bar) (broken)))
```

Since byte compiling one's init file is not common practice (and actively discouraged by Emacs maintainers), I think this is probably the best option for now.
It prevents most users from incurring the cost of those checks on every startup.
If you wanted to get checkdoc working with that, perhaps the body could be inserted into a temp buffer on which checkdoc could be run.

I'll consider this closed for now, but let me know if you make any progress on a more elegant solution and we can reconsider. Thanks.
