### ISSUE TITLE
[Support]: `Duplicate item queued: tree-sitter`

### ISSUE THREAD

**Issue by Icy-Thought** [progfolio/elpaca#159]
### Elpaca Version

```
Elpaca fbf28c5 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
git --version:  git version 2.41.0
```

### Operating System

```
NixOS 23.11.20230705.f292b49 (Tapir)
```

### Description

Oftentimes when installing a package which provides a use-package hook and later appending the `(elpaca-wait)` command to that configuration file would result in:  `⛔ Warning (emacs): Duplicate item queued: package-name`.

This time I ran into the "duplicate warning" issue in the code block provided below, where Emacs had complain about a duplicate entry of `tree-sitter`.

```emacs-lisp
(use-package flymake-collection
  :after flymake
  :hook (flymake-mode . flymake-collection-hook-setup))
(elpaca-wait)
``` 

###### Useful links:
- [Emacs configuration](https://github.com/Icy-Thought/emacs.d/blob/7eb2f25c6f9cb84265f53e891438d68d489d8851/irkalla/init.org)

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> Oftentimes when installing a package which provides a use-package hook and later
> appending the `(elpaca-wait)` command to that configuration file would result
> in: `⛔ Warning (emacs): Duplicate item queued: package-name`.

Elpaca normally queues all packages prior to processing any of them.
This ensures the version of the package the user explicitly requests is installed even if a package declared before it needs that package as a dependency. e.g. 
  
  
```emacs-lisp
(elpaca a) ;; requires b
(elpaca (b :branch "development")) ;; this version of "b" is installed
```

`elpaca-wait` processes all of the queued packages up to the point it is called.
Therefore, it can't know about packages which are queued after the point where it is called. 
e.g.

```emacs-lisp
(elpaca a) ;; requires b
(elpaca-wait) ;; "a" is installed, "b" is installed as a dependency.
(elpaca b) ;; Elpaca warns about duplicate item here, because "b" has already been installed.
```

There are two ways to avoid this.
You could move whichever packages require tree-sitter after the tree-sitter declaration.
You should be able to get a list of those packages under the "dependents" section of `M-x elpaca-info` `tree-sitter` (looking at your config, it's probably ts-fold).

A better solution is to move all the declarations which require `elpaca-wait` before other declarations. This way, the blocking is minimized and the benefit of the queue system is maximized.

Does that help?

**Comment by progfolio** [comment]
Glad that helps. Thanks.
