### ISSUE TITLE
Emacs 28 vs Emacs 29 Elpaca log differences on macOS

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#16]
## What's wrong

Elpaca log  has borders around the header and clears each line as it completes. 
GNU emacs 29 Keeps all the entries visible in a list and does not box the headers.

### Version information

* Emacs version: emacs 28.1
* Operating system: macOS

Originally reported by: @bestlem

**Comment by progfolio** [comment]
@bestlem: If you could provide screenshots, it would help me understand what you are describing.

**Comment by bestlem** [comment]
I don't know if this is emacs 28.1 or a Mituharu port issue 

Both these are after deleting all elpaca files  and using the first run - The only odd thing I do is putting the elpaca files out of ~/.emacs.d 
```
(defvar elpaca-directory (expand-file-name "elpaca/" "/Users/mark/.local/emacs"))
(defvar elpaca-builds-directory (expand-file-name
								 (concat "build-" emacs-version "/")
								 elpaca-directory))
```

Mituharu emacs 28.1 All the lines did appear but were deleted when they completed.
So I had one line flashing

![Screenshot 2022-09-02 at 09 58 58](https://user-images.githubusercontent.com/37385/188269116-0fdaa122-d119-4a66-b403-8f7be87e76f4.png)

GNU emacs 29.0
![Screenshot 2022-09-03 at 12 47 24](https://user-images.githubusercontent.com/37385/188269137-5ca62ade-c051-4fe8-a6e2-7e36be0594e9.png)

**Comment by progfolio** [comment]
Thank you for the detailed response.
The first screenshot where the "header" is highlighted is a quirk of tabulated-list-mode when the "faux-header" is used.
I've seen it happen occasionally, but reproducing it is inconsistent. I'll take a look, but this would likely need to be fixed upstream (in tabulated-list-mode itself). However, it should not cause any loss of functionality in the log buffer. Try searching for something in the log buffer, or killing it and running `M-x elpaca-log`. You may find that it goes away after the buffer has been updated.

In the second screen shot (GNU Emacs 29) the default search query, `.*` is being used instead of `#unique !#finished`.
This may be the result of a bug. Had you interacted with the log buffer at all during the install? e.g. searching for anything, typing "s" or "S" in the buffer, etc? That may cause the query to change. If not, are there any error messages in the `\*Messages*` buffer?
Does `emacs --debug-init` hit the debugger?

Thanks again for testing. I appreciate it.

**Comment by bestlem** [comment]
Sorry I messed up my version control - I don't have the exact startup for this.

I can't reproduce the emacs 29 issue anymore, it now works the same way as my emacs 28.

Note I did not have any interaction when I did have the difference.

**Comment by progfolio** [comment]
> Sorry I messed up my version control - I don't have the exact startup for this.

Not a problem. I appreciate the response.

> Note I did not have any interaction when I did have the difference.

Thank you. That's valuable information.

> I can't reproduce the emacs 29 issue anymore, it now works the same way as my emacs 28.

Emacs 29 is a moving target, so it's entirely possible something was broken on a specific commit.
Since it works as expected now, I'll close the issue. If you or anyone else is able to reproduce this in a consistent manner we can reopen and figure out what's happening.

Thanks again.
