### ISSUE TITLE
[Bug]: Unable to bind key-bindings using the `:general` keywords in use-package

### ISSUE THREAD

**Issue by Xanaxus** [progfolio/elpaca#164]
### Elpaca Version

Elpaca 4d8727d HEAD -> master, origin/master, origin/HEAD
installer:      0.5

### Operating System

emacs-version:  GNU Emacs 28.2 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
git --version:  git version 2.41.0

### Description

I have been trying to set up a key binding for the [restart-emaces](https://github.com/iqbalansari/restart-emacs) in the following manner
```
(use-package restart-emacs
	 :elpaca
	  (restart-emacs :host github :repo "iqbalansari/restart-emacs")
	 :config
	 (setq restart-emacs-restore-frame t)
       :bind
	((:map global-map
	("<SPC> r r"  . restart-emacs))
  ))
 ```
  And this is what I have placed in my general side config
  ```
  (use-package general
    :config
    (general-evil-setup)

    ;; set up 'SPC' as the global leader key
    (general-create-definer dr/leader-keys
      :states '(normal insert visual emacs)
      :keymaps 'override
      :prefix "SPC" ;; set leader
      :global-prefix "M-SPC") ;; access leader in insert mode

  ;; (dr/leader-keys "c r" 'restart-emacs)
     )
  ```
 after which I am getting the following as an error
 
`Error (use-package): Failed to parse package restart-emacs: use-package: Unrecognized keyword: :general Disable showing Disable logging`

**Comment by progfolio** [comment]
Please see the comment in the demo init file starting here: 

https://github.com/progfolio/elpaca/blob/6df96526138c02986fdfadff1b8906c999936042/doc/init.el#L50
