### ISSUE TITLE
Cannot install BBDB

### ISSUE THREAD

**Issue by jleechpe** [progfolio/elpaca#17]
Trying to install BBDB using

```
(elpaca-use-package bbdb)
```
results in it not being able to find `bbdb-site` when trying to require it.

The file exists as `bbdb-site.el.in` and is linked as such but the makefile build-process copies the two *.el.in files to *.el so that they can be processed properly.

I've tried renaming them using `:pre-build` but it doesn't seem to do anything.

**Comment by progfolio** [comment]
Please share the full recipe you tried to install with.

**Comment by progfolio** [comment]
The presence of an `.el.in` file probably means you have to run `make` during the `:pre-build` phase to generate a resultant `.el` file.

Take a look at the README in the package's repo:

https://git.savannah.nongnu.org/cgit/bbdb.git/tree/README

It requires a couple pre-build steps.
Encoding those in the recipe should give yous something like:

```emacs-lisp
(bbdb :pre-build (("./autogen.sh") ("./configure") ("make")))
```

**Comment by jleechpe** [comment]
Thanks you, that recipe did the trick.

For some reason I'd decided I needed to quote the list which was likely why I was getting no results at all from the pre-build step.

**Comment by jthaman** [comment]
Does this recipe still work? I cannot find the function `elpaca-use-package` in my installation. I'm trying to do 

```
(use-package bbdb
  :elpaca (bbdb :pre-build (("./autogen.sh") ("./configure") ("make"))))
```

but I get the same error as OP.

**Comment by progfolio** [comment]
> Does this recipe still work? I cannot find the function `elpaca-use-package` in my installation. I'm trying to do
> 
> ```
> (use-package bbdb
>   :elpaca (bbdb :pre-build (("./autogen.sh") ("./configure") ("make"))))
> ```
> 
> but I get the same error as OP.

The following test case works for me on Arch Linux with Emacs 30:

```emacs-lisp
(elpaca-test
  :init
  (elpaca elpaca-use-package (elpaca-use-package-mode))
  (elpaca-wait)
  (use-package bbdb
    :elpaca (:pre-build (("./autogen.sh") ("./configure") ("make")))
    (require 'bbdb-site)))
```

Try evaluating that in your \*scratch\* buffer.
It will start a new Emacs session and install everything in a clean test environment.
If there is an error when trying to require `bbdb-site` please copy the entire contents of the backtrace buffer here (You'll want to expand all ellipses in the buffer before copying, too. Usually bound to "." by default.). Please also provide:

- The output of `M-x elpaca-version`
- The contents of the \*Warnings\* buffer if present.
- A full copy of the `elpaca-log`. `M-x elpaca-log` `s` `RET` `c` should copy a formatted log to your system clipboard.

**Comment by jthaman** [comment]
Now it works. I found that your test script also works on my computer,
but the elpaca use-package incantation inside it still failed. I deleted
my elpaca and elpa folders to start fresh, and it all works fine now.

--
Dr. John Haman
Maryland, USA
