### ISSUE TITLE
[Support] Document necessity of rebuilding packages 

### ISSUE THREAD

**Issue by deadcombo** [progfolio/elpaca#172]
### Feature Description

Hello,

It was not clear to me that I should do `elpaca-rebuild`  after modifying the package declaration on my init.el. I looked at the readme, manual, wiki and some issues and found no mention of it. I managed to update my configuration only after learning the following on the Emacs Matrix room:

>  Good idea.
> 
>     Installed via the default recipe:
> 
> 1(use-package corfu :elpaca t)
> 
> Package installs cleanly.
> 
>     Edited the declaration to match the recipe user gave.
>     Evaluated the use-package declaration.
> 
> M-x elpaca-rebuild corfu links/builds everything properly.
> 
> Perhaps step 3 was skipped. Editing the recipe and restarting Emacs won't rebuild the package automatically. But, even then, M-x elpaca-delete corfu followed by a restart should've re-installed with the new recipe. Hard to say without seeing the state of the user's package store at the time of the error.

As we discussed, I will describe my steps:

1. Attempted to apply the :files argument on use-package
Pretty straightforward error but it had not been clear to me that :elpaca expands to the elpaca function, I didn't see it used like that in manual and  thought it only accepted positive or nil.
I saw :files in "Installing Packages", so I did (use-package corfu :files :host… :repo) 

Only when I saw [this issue](https://github.com/progfolio/elpaca/issues/160) did I realize :files is an argument for Elpaca, not use-package. Not very bright 🤷 

2. Figured out I can use :elpaca (:host… :repo… :files ()
In between some more mishaps with parens and such I found [this issue](https://github.com/progfolio/elpaca/issues/141) where I learned to use :elpaca in use-package 

:elpaca (:host github :repo "pondersson/org-bulletproof" :files (:defaults (:exclude "*-test.el")))

3. Now when I restarted I got elpaca's log and I saw the Corfu extensions being pulled but they still weren't available despite being called in use-package. It couldn't find them.
I went to elpaca/repos and elpaca/builds and they were there and the paths in corfu-info were correct as well.
This triggered much rereading, reorganizing of :config and :init, some use-package experiments and such and finally looking at the Emacs social sites I know of, where I found your message, ran `elpaca-rebuild` , restarted and suddenly the commands were available.

Outside of this, other packages were a breeze, well done. This is a great package manager.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thank you for the details. I will take them into consideration when writing the "use-package integration" section of the manual. I'll find a spot to mention how interactive evaluation of declarations is handled.

**Comment by progfolio** [comment]
I've added a section to the manual describing Elpaca's use-package integration and mentioned interactive evaluation of declarations in the section about the elpaca macro.
