### ISSUE TITLE
[Feature]: `elpaca-info-mode` should use `read-only-mode`

### ISSUE THREAD

**Issue by iwahbe** [progfolio/elpaca#176]
### Feature Description

It doesn't seem like `elpaca-info-mode` should allow manual editing of the `*elpaca-info*` buffer. Most keys are undefined, but `RET` is still bound to `newline` (when not on buttons). 

For example, hitting `RET` in the middle of `source: ` results in:
<img width="298" alt="Screenshot 2023-08-24 at 10 46 17 AM" src="https://github.com/progfolio/elpaca/assets/22222529/1f5ad9a7-1395-474d-97b3-9ad5da3b218e">

--- 

I'm not 100% sure if this should be a feature or a bug fix. It's not breaking anything, so I figured feature.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> I'm not 100% sure if this should be a feature or a bug fix. It's not breaking
> anything, so I figured feature.

Thanks for taking the time to report an issue. This is more of a bug report.
Please see the [troubleshooting](https://github.com/progfolio/elpaca/wiki/Troubleshooting) page of the wiki for future reports.


> It doesn't seem like `elpaca-info-mode` should allow manual editing of the
> `*elpaca-info*` buffer. Most keys are undefined, but `RET` is still bound to
> `newline` (when not on buttons).

`elpaca-info-mode` is derived from `special-mode` which sets the buffer to read-only.
The `newline` command should `barf-if-buffer-read-only` in this case.
I'm unable to reproduce the issue on my end with the following test case.
Please try running it on your end and share the results so we can rule out any configuration issues:

<details open><summary>Test Case</summary>
[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)
```emacs-lisp
(elpaca-test
  :early-init (setq elpaca-menu-functions nil)
  :init (with-current-buffer (elpaca-info 'elpaca)
          (newline)))
```
</details>

<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>d0a24fc HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.5</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-08-18</td>
<tr><td>git</td><td>git version 2.41.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs...
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.plaGKf/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.plaGKf/elpaca/repos/elpaca...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.plaGKf/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.plaGKf/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.plaGKf/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.plaGKf/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.plaGKf/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)


Error: buffer-read-only (#<buffer *elpaca-info*>)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0x1e3b377958517815>))
  debug-early-backtrace()
  debug-early(error (buffer-read-only #<buffer *elpaca-info*>))
  newline()
  (save-current-buffer (set-buffer (elpaca-info 'elpaca)) (newline))
  load-with-code-conversion("/tmp/elpaca.plaGKf/init.el" "/tmp/elpaca.plaGKf/init.el" nil t)
  command-line-1(("--eval" "(setq debug-on-error t after-init-time nil)" "--eval" "(setq user-emacs-directory \"/tmp/elpaca.plaGKf\")" "-l" "./early-init.el" "--eval" "(run-hooks 'before-init-hook)" "-l" "./init.el" "--eval" "(setq after-init-time (current-time))" "--eval" "(run-hooks 'after-init-hook)" "--eval" "(run-hooks 'emacs-startup-hook)" "--eval" "(message \"\n Test Env\n\")" "--eval" "(elpaca-version 'message)"))
  command-line()
  normal-top-level()
Buffer is read-only: #<buffer *elpaca-info*>
```
</details>

**Comment by iwahbe** [comment]
My bad on not checking troubleshooting, I'll do that in the future. Thanks for such a responsive response.

Running test case gives me:
Host env:

|Elpaca | d0a24fc HEAD -> master, origin/master, origin/HEAD |
|--|--|
|installer |      0.5 |
|emacs-version |  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66))|
 of 2023-06-20 |
|git --version |  git version 2.41.0|

Output:
I don't see the formatted results buffer as described in the wiki. I get this:

<img width="707" alt="Screenshot 2023-08-24 at 12 10 05 PM" src="https://github.com/progfolio/elpaca/assets/22222529/396f7c37-aeb7-41a8-8cc2-33e77a289fa8">

That said, closing the "packages" section has me in an `elpaca-info-mode` buffer, and that rejects "RET", so that indicates a problem with my config.

**Comment by progfolio** [comment]
> My bad on not checking troubleshooting, I'll do that in the future. Thanks for
> such a responsive response.

Thank you. 
  
> Running test case gives me: Host env:
> 
> |Elpaca | d0a24fc HEAD -> master, origin/master, origin/HEAD |
> |--|--|
> |installer | 0.5 |
> |emacs-version | GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66))| of 2023-06-20 |
> |git --version | git version 2.41.0|
  
> Output: I don't see the formatted results buffer as described in the wiki. I get
> this:
> 
> <img width="707" alt="Screenshot 2023-08-24 at 12 10 05 PM"
> src="https://github.com/progfolio/elpaca/assets/22222529/396f7c37-aeb7-41a8-8cc2-33e77a289fa8">
> 

Interesting. I'm not sure if that's a quirk of Emacs on Mac, or what went wrong.

> That said, closing the "packages" section has me in an `elpaca-info-mode`
> buffer, and that rejects "RET", so that indicates a problem with my config.

Sounds reasonable. Thanks for following up.
