### ISSUE TITLE
[Support]: Auto hiding of elpaca-log after reloading init.el (user-config)

### ISSUE THREAD

**Issue by Momijie** [progfolio/elpaca#179]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [X] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

((elpaca . "661796a HEAD -> master, origin/master, origin/HEAD") (isntaller . 0.5) (emacs . "GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)") (git . "git version 2.42.0"))

### Operating System

Arch Linux 6.4.12-arch1-1

### Description

I tried most of the commands recommended under Logging in the wiki, either I'm entering them incorrectly or they're not doing exactly the feature I'm looking for here. When I reload my init.el, *elpaca-log* buffer pops up and takes the full screen. I would rather have this buffer in the background and not have to see it unless I navigate to it. I don't want to hide any of the information being logged.

**Comment by progfolio** [comment]
How are you reloading the config file?

**Comment by Momijie** [comment]
`   "hr" '((lambda ()(interactive)
             (load-file "~/.config/emacs/init.el")
             (ignore (elpaca-process-queues))) 
            :wk "Reload emacs config")
` Through a general keybinding, like this.

**Comment by progfolio** [comment]
Thanks.
You should give define the command via `defun` so it has a name you can push to `elpaca-log-command-queries`.
See the following test case:

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

``` emacs-lisp
(elpaca-test
  :interactive t
  :early-init (setq elpaca-menu-functions '(elpaca-menu-extensions))
  :init
  ;;Do not copy anything above this line into your config
  (defun +reload-init ()
    (interactive)
    (load-file (locate-user-emacs-file "init.el"))
    (ignore (elpaca-process-queues)))

  (with-eval-after-load "elpaca-log"
    (setf (alist-get '+reload-init elpaca-log-command-queries) 'silent))

  (global-set-key (kbd "C-c l") '+reload-init))
```

That should prevent the buffer from showing at all, but the information will still be logged to it. Bear in mind, when you switch to the log buffer, you may have to edit the search query to see the latest info. e.g. if it is "#unique !finished" you'll want to search for ".*".

**Comment by Momijie** [comment]
Oh perfect, still a bit new to elisp but I got it to work. Thank you for spending the time.
