### ISSUE TITLE
Native compilation of packages

### ISSUE THREAD

**Issue by Riyyi** [progfolio/elpaca#18]
I've looked through the repo but I couldn't find any references to this, is this feature planned?
Or is this already possible with some additional elisp in my config?

**Comment by progfolio** [comment]
Elisp native compilation is designed so that libraries are automatically compiled in a separate process the first time a library is loaded. I haven't added an "ahead of time" native compilation build step because I don't think it's all that valuable to eagerly native compile all installed libraries. Interested parties could write a function to handle this and add it to the build steps, though.

**Comment by Riyyi** [comment]
Maybe there is something wrong with my config, because while using Elpaca I've never seen the *Compile-Log* buffer pop up and when I check loaded functions using helpful, they all state to not be natively compiled, until I manually call `native-compile-async`:

![2022-09-13-233916_maim](https://user-images.githubusercontent.com/1911807/190014254-8cde6529-3862-4edc-9194-4dc883ce9435.png)

Built-in stuff, for example the `native-compile-async` function itself does show up as natively compiled right away.
Is there a better way to verify if functions have loaded the native compilation?

**Comment by progfolio** [comment]
> Maybe there is something wrong with my config,

Hard to say without seeing it. Happy to look if you're willing to share it.

> I've never seen the *Compile-Log* buffer pop up 

I see messages about async native compilation in the `*Async-native-compile-log*` buffer on my end.

I would check the value of the `native-comp-deferred-compilation` variable.

**Comment by Riyyi** [comment]
It kind of fixed itself. At first I deleted the `eln-cache` directory to see if it was compiling at all and it only did a couple of `subr--trampoline` files but nothing else. Then I deleted `elpaca` directory to let it start fresh and now it works as expected.
This was with `native-comp-deferred-compilation` set to `t`.
