### ISSUE TITLE
[Support]: Suppress unused lexical variable warning

### ISSUE THREAD

**Issue by Nekosis** [progfolio/elpaca#182]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca d2faaad HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
git --version:  git version 2.42.0

### Operating System

[Meowix Linux](https://github.com/Meowix-Linux/Meowix-ISO) x86_64 (Arch Linux-based)

### Description

On a fresh deployment of Emacs with my custom configuration, this undesired warning appears in the Elpaca log:

```
vterm-toggle                   byte-compilation     vterm-toggle.el:229:56: Warning: Unused lexical variable `cur-port'              10.006751
```

I have tried to suppress it by using `:defines` in the use-package declaration for vterm-toggle, but to no avail:

```elisp
(use-package
 vterm-toggle
 :after vterm
 :defines cur-port ;; Attempt to suppress the warning
 :config
 (setq vterm-toggle-fullscreen-p nil)
 (setq vterm-toggle-scope 'project)
 (add-to-list
  'display-buffer-alist
  '((lambda (buffer-or-name _)
      (let ((buffer (get-buffer buffer-or-name)))
        (with-current-buffer buffer
          (or (equal major-mode 'vterm-mode)
              (string-prefix-p
               vterm-buffer-name (buffer-name buffer))))))
    (display-buffer-reuse-window display-buffer-at-bottom)
    (reusable-frames . visible)
    (window-height . 0.3))))
```

What can I do to correctly suppress the error on a fresh install of Emacs with my config? I intend to package my config with my own Linux distro eventually, so I wouldn't like this warning to be shown to the user on first launch.

Full config: https://gist.github.com/Nekosis/0305697b06592848607eb1c802816a79

Thank you in advance.

**Comment by progfolio** [comment]
> On a fresh deployment of Emacs with my custom configuration, this undesired
> warning appears in the Elpaca log:
> 
> ```
> vterm-toggle                   byte-compilation     vterm-toggle.el:229:56: Warning: Unused lexical variable `cur-port'              10.006751
> ```

The warning is being generated when the package is byte-compiled.
It's not a result of your configuration.
Byte compiling the package on my end produces the following warnings:

``` emacs-lisp
vterm-toggle.el:211:2: Warning: docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...') 185.809374
vterm-toggle.el:229:47: Warning: Unused lexical variable ‘cur-user’              185.810434
vterm-toggle.el:229:56: Warning: Unused lexical variable ‘cur-port’              185.819951
vterm-toggle.el:395:15: Warning: the function ‘project-roots’ is not known to be defined. 185.839441
```

These need to be fixed upstream and should be reported to the maintainers of vterm-toggle 

  
> I have tried to suppress it by using `:defines` in the use-package declaration
> for vterm-toggle, but to no avail:

You can remove the `:defines`, as it won't fix those warnings.

**Comment by Nekosis** [comment]
OK. Will report upstream
