### ISSUE TITLE
[Support]: Package update log

### ISSUE THREAD

**Issue by cvdub** [progfolio/elpaca#189]
### Feature Description

It would be cool if elpaca had a way to show which packages were actually changed/updated after running `elpaca-update-all`, including the new commit messages for each package that was updated.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
After updating, update the search filter to "#latest #update-log".

**Comment by cvdub** [comment]
Perfect! Thank you so much for the detailed response.
