### ISSUE TITLE
elpaca-update-all does not fetch changes

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#195]
As of 518e7b6 `elpaca-update-all`  takes an optional `FETCH` argument as its first argument. Without it, the command will only merge changes which are already on disk and rebuild packages.
In order to fetch changes *and* merge/rebuild, pass the FETCH argument.
This can be done in lisp programs like so:

``` emacs-lisp
(elpaca-update-all 'fetch)
```

or interactively by passing a prefix-argument, e.g. `C-u`, before invoking the command.

The motivation for this change is to separate fetching from "updating" packages.
For example, if you run `elpaca-fetch-all`, and review the changes in the update log, then `elpaca-update-all`, the old behavior would fetch *again* which could pull changes which had not been reviewed. The new behavior prevents this from happening.

**Comment by justinbarclay** [comment]
Hey, thanks for working on and continuing to update elpaca.

From a user's perspective, I am not sure I understand this change. When I use update-all, I expect the update operation to fetch the latest update from the remote server and apply it to my setup. So separating fetching from updating seems like it's no longer updating, and instead, it is applying/copying. As you explained, there are technical reasons for doing this, but I am wondering if these technical reasons are the common case among Elpaca users. Is my use case the weird one?

Would it be more ergonomic for most users to have `elpaca-update-all` behave the same but support the special `fetch and apply` process with `C-u M-x elpaca-update-all` (going from 'fetch to 'no-fetch). Or if my use case is the weird one (or you simply don't want to support fetch being the default), would you be willing to add a configuration variable that controls the default behaviour of `elpaca-update-all`?

**Comment by progfolio** [comment]
> Hey, thanks for working on and continuing to update elpaca.

You're welcome and thank you for using Elpaca.

> As you explained, there are technical reasons for doing this

The issue isn't purely technical. As you point out, the fetching logic could be easily inverted. However, I want to encourage people to actually look at what's changed instead of blindly fetching and updating everything. 

>  Is my use case the weird one?

In my experience, I see these common patterns:

- Users who update all packages obsessively. I consider this poor practice, because it's a waste of bandwidth/power most of the time, but I can't stop them from using `elpaca-update-all` whenever they want.
- The majority of users seem to `elpaca-update-all` without fetching first. I consider that poor practice because it's less secure and leads to wasted effort/time when their config breaks.
- The minority of users fetch all changes, review them and selectively pull the ones they wish to incorporate.

I wouldn't say any of the use cases are "weird", but the third is the safest and least wasteful.


> would you be willing to add a configuration variable that controls the default behaviour of elpaca-update-all

I think I'll pass on such an option. They tend to make debugging harder (every time the function is involved, the value of that option has to be considered), and so I want to avoid them where possible.

A few possible alternatives:

We could automatically detect when there are fetched commits on disk when an update is requested.
If there are, `elpaca-update-all` could skip the fetch. If not, the fetch is performed.
This could lead to scenarios where the user fetched some time ago, so `elpaca-update-all` wouldn't necessarily bring them up to the latest version available (another fetch would be necessary). That's a better situation than always fetching, but still not the best.

We could add a separate "merge-all" command which covers the current non-prefix-arg behavior of `elpaca-update-all`. I'd like to avoid this, if possible. Straight.el has such a command, but it feels superfluous and still doesn't cover the case that a user might be pull in unwanted changes after fetching everything by using "update-all" after "fetch-all".

I'm open to other ideas if anyone has any, too.

**Comment by deadcombo** [comment]
> However, I want to encourage people to actually look at what's changed instead of blindly fetching and updating everything.

A much more sensible step would be to document how to use elpaca to do this efficiently as it isn't covered in the manual at all.
I've spent the last 10 minutes fumbling with the manager figuring how to use the logs to see what's changed and I only managed to land in a git directory once by accident and I don't know how to do it again.
A quick diff check in `elpaca-info` or magit integration would expedite the review process significantly.

> Users who update all packages obsessively. I consider this poor practice, because it's a waste of bandwidth/power most of the time, but I can't stop them from using elpaca-update-all whenever they want

I don't see why you should make this decision for users. If I want a package to remain static, I'll pin it. I don't see why concern yourself with my bandwidth or GitHub's (and power usage from fetching?).  
I don't see how using a rolling release model for Emacs is "obsessive".  Is tracking Emacs HEAD obsessive?

> The minority of users fetch all changes, review them and selectively pull the ones they wish to incorporate.

Why would I? You're trying to save me time debugging my config but you expect me to review every package commit? If I find a behavior I'm not happy with I'll revert it, If I hadn't updated this package I'd not have found this issue. If I find a regression in a package I'll make a pull request or file an issue, participating in the open source model.

You recognized how the majority of users use your package. Are you breaking to enforce your opinion of how configuration should be managed?
A much more sensible alternative is to make a new function `elpaca-rebuild-all` which I think is the behavior you want if I understand correctly (which I doubt as I don't see the purpose of this. Should I fetch packages one by one, fetch changes, review them and then update? I have 130 packages and you've mentioned previously you've got 100+ as well).


> We could automatically detect when there are fetched commits on disk when an update is requested.
> If there are, elpaca-update-all could skip the fetch. If not, the fetch is performed.
Your consideration is efficiency - this seems less so than simply running fetch on all. This also increases debugging friction, which you're concerned with.


> The majority of users seem to elpaca-update-all without fetching first. I consider that poor practice because it's less secure and leads to wasted effort/time when their config breaks.
Why is it less secure?

**Comment by progfolio** [comment]
> A much more sensible step would be to document how to use elpaca to do this efficiently as it isn't covered in the manual at all.

Thanks for pointing out the documentation gap.
I'll add a section once the design settles.

> I've spent the last 10 minutes fumbling with the manager figuring how to use the logs to see what's changed and I only managed to land in a git directory once by accident and I don't know how to do it again.
> A quick diff check in elpaca-info or magit integration would expedite the review process significantly.

When you run elpaca-fetch-all, the default search query should be `#latest #update-log`.  The view should show a summary of the commits which were fetched. 
If magit is installed, the commit hash is also a button which should show the diff in magit for each commit. I have plans to add the same button sans magit, but have not merged it yet.

> I don't see why you should make this decision for users.

It's not "making user's decisions" so much as fixing a design bug.
Fetching changes and then re-fetching to update is no good because something may have changed in between the two actions.

I'm also not stopping anyone from:

- passing a prefix argument to the command
- writing a command which wraps the command to do what they want
  e.g.

  ```emacs-lisp
  (defun +elpaca-update-all ()
    (interactive)
    (elpaca-update 'fetch 'interactive))
  ```

- advising the command
- proposing an alternative solution

I do have to decide on a default behavior in order to implement things.

>  If I want a package to remain static, I'll pin it.

That's not why the change was made.

>  I don't see why concern yourself with my bandwidth or GitHub's (and power usage from fetching?).

I can't control what people do with the software I write, but I can discourage what I consider to be poor practice. I'm not too interested in debating whether or not wasting power (or encouraging others to) is good or bad here, though.

> I don't see how using a rolling release model for Emacs is "obsessive".

"Rolling release model" and "updating on a timer every 5 minutes, or every time I start the editor" are two different situations. The number of users who do that are few enough where I don't feel like it's worth debating.

> A more sensible alternative is to make a new function elpaca-rebuild-all

Rebuilding is not the same as pulling in changes, unfortunately.
I mentioned adding another command in my last command, and perhaps I will.
Still haven't decided.

> Should I fetch packages one by one, review them and then update? I have 130 packages and you've mentioned previously you've got 100+ as well).

It's up to you how you choose to update your packages.
I typically fetch all the changes and review them before merging them.
The process does not take long and I update about once a month unless I have reason to do it sooner. 

> Why is it less secure?

The same reason blindly clicking "install", or signing something without reading it, is less secure in most contexts.
One hasn't reviewed what they're isntalling.
Emacs is designed around an especially privleged and insecure model, too, so I discourage running elisp without vetting it first.

Thanks for your opinion.
Do you have any suggestions for alternatives I haven't covered above?

**Comment by deadcombo** [comment]
>  When you run elpaca-fetch-all, the default search query should be #latest #update-log. The view should show a summary of the commits which were fetched.
If magit is installed, the commit hash is also a button which should show the diff in magit for each commit. I have plans to add the same button sans magit, but have not merged it yet.

Cheers, I hadn't known of `elpaca-fetch` before this issue. That's very well done and is what I had in mind. After using it I understand your motivation.

> It's not "making the user's decision" so much as fixing a design bug.

You're right,  I misunderstood you.

>I typically fetch all the changes and review them before merging them.

That's wiser, again I'd missed the fetch command log.

> Do you have any suggestions for alternatives I haven't covered above?

Perhaps rename `elpaca-update` to `elpaca-merge` instead of making an new command.  Sticking to git terms makes the upgrading behavior more evident. Fetch changes then merge.
I had conflated update with pull so far.
No new command to maintain and documenting upgrading becomes easy, I.e.: "Use `elpaca-fetch` to fetch commits and review them in the `elpaca-log` buffer. Use `elpaca-merge` to pull the commits and rebuild the packages.”

At the moment `elpaca-fetch` documentation says it does not merge or rebuild and `elpaca-update` does not say it does, it says "Update ITEM's associated package” which is not as explicit and cohesive as "Merge and rebuild ITEM's associated package” for example.

Perhaps the manual would benefit from a small synthesis of how you use Elpaca (or intend Elpaca to be used) as the "Quick Start". 
The Quick Start table currently states `elpaca-update` is the way to update packages. It does not mention `elpaca-fetch`, neither does the rest of the manual.
The default query tags aren't included in the manual either and have no key bound to them. If I understand it, the only way to see #update-log is to know the tag by checking the `elpaca-log-search-tags` variable or to run `elpaca-fetch`.

The documentation aspect is somewhat off-topic but I believe it is crucial to address the perceived misuse of `elpaca-update`.
I would be happy to contribute to the manual if you'd like that.

**Comment by progfolio** [comment]
> Perhaps rename `elpaca-update` to `elpaca-merge` instead of making an new
> command. Sticking to git terms makes the upgrading behavior more evident.

I had thought of something similar, and was on the fence about it.
It will be more evident to people who are familiar with git and less so with people who are not.
However, I it still might be the best compromise.

I've cut a branch with those changes:

https://github.com/progfolio/elpaca/commit/4f80c434b5728be5a93c9c9b62217a778dcafec4


> I had conflated update with pull so far as the update log shows `Fetching remotes`.

The old elpaca-update behavior would be analogous to a `git pull`.
That behavior will still be possible by passing a prefix-arg to `elpaca-merge` once the above branch commit is merged.

> The documentation aspect is somewhat off-topic but I believe it is crucial to
> address the perceived misuse of `elpaca-update`.

I've updated the quick start and some docstrings on the above branch to reflect the changes. 

> I would be happy to contribute to the manual if you'd like that.

Let's hold off on that for now.
There are still design elements in flux and I would rather avoid wasted effort on writing docs which become obsolete (This change will make the introductory video I and others have made obsolete).
The more things stabilize, the more documentation we can add.

**Comment by dertuxmalwieder** [comment]
> Perhaps rename elpaca-update to elpaca-merge instead of making an new command. Sticking to git terms makes the upgrading behavior more evident. Fetch changes then merge.

Just a thought from the sideline: Not everyone knows (or uses) Git. What users want to do: *Update* their packages.

The change confused me at first.

**Comment by progfolio** [comment]
Cthulhux ***@***.***> writes:

> Just a thought from the sideline: Not everyone knows (or uses) 
> Git. What users want to do:
> Update their packages.
>
> The change confused me at first.

Thanks. Noted. The terminology can (and will) be covered more 
thoroughly in the documentation.
