### ISSUE TITLE
[Bug]: Deleted previous config, elpaca causing emacs to crash with white screen.

### ISSUE THREAD

**Issue by Momijie** [progfolio/elpaca#198]
### Elpaca Version

The most current

### Operating System

Arch Linux, 6.6.1-arch1-1

### Description

Was refactoring my emacs config, deleted the elpaca directory. When it reinstalled it froze my emacs, and when opening again after killing emacs, it's just a white screen, can't interact with anything. Deleted everything in configuration and just had the essentials for downloading elpaca and this event still occurred. Reinstalled emacs, updated arch, restarted, not sure why this is happening.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> Elpaca Version

> The most current

Please provide the info requested in the issue template. (`M-x elpaca-version`)

The title of your issue mentions Emacs crashing, but what your description sounds like Emacs is blocked until you unblock it. Is Emacs actually crashing (closing on its own)? 

> Deleted everything in configuration and just had the essentials for downloading elpaca and this event still occurred. 

Please share the init file you are using.

> Reinstalled emacs, updated arch, restarted

None of this should be necessary, and changing many variables at once makes it harder to solve an issue.
Let's take it one step at a time.

**Comment by Momijie** [comment]
Well this was silly, when I connected my laptop to a different wifi source it started to work again. Though I'm sure this will happen to me again at some point, is there a log file available or a procedure I can go through to trobuleshoot?

If still needed:
```Elpaca 039ae35 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
git --version:  git version 2.42.1```

```
(setq package-enable-at-startup nil)
```
```
(defvar elpaca-installer-version 0.6)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
```

**Comment by progfolio** [comment]
> Well this was silly, when I connected my laptop to a different wifi source it started to work again.

Internet access is needed to perform the initial install. So it was most likely a networking issue.

> Though I'm sure this will happen to me again at some point, is there a log file available or a procedure I can go through to trobuleshoot?

When you launch Emacs and an initial installation is performed, the \*elpaca-bootstrap\* buffer should be shown. This will show the details of Elpaca itself being cloned. If that finishes successfully, the log should be shown. `elpaca-wait` blocks when called. You should be able to quit out of that blocking loop with `C-g` (which should fail any outstanding orders) and inspect any logs with `elpaca-log` from there.

Glad you got it sorted.
