### ISSUE TITLE
[Support]: Elpaca Installer mismatch

### ISSUE THREAD

**Issue by Xanaxus** [progfolio/elpaca#200]
### Elpaca Version

Elpaca 039ae35 HEAD -> master, origin/master, origin/HEAD
installer:      0.5

### Operating System

emacs-version:  GNU Emacs 29.1 (build 2, x86_64-suse-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
git --version:  git version 2.42.1

### Description

Upon trying to reinstall my config from scratch with just the config files. I encountered this error. 
>  WARNING: Elpaca Installer mismatch

Which is similar to the #155 issue, so tried to revert to a previous commit (ec68493dab80766da984382bab03ce3dccb8fd77) but was unsuccessful as then the use-package elpaca was also affected [got the following error: 
> “unable to build the/find the elpaca-use-package”

I also tride the cache deleting advice menioned in the following comment: 

> Thanks for taking the time to fill out a bug report.
> 
> > The issue is resolved by manually deleting `elpaca/repos/elpaca` and
> > `elpaca/builds/elpaca` and restarting emacs in order to force elpaca to
> > bootstrap itself from scratch. Maybe updating elpaca doesn't generate autoloads
> > for newly defined functions correctly? Something else?
> 
> For situations like this, you may be able to get away with `M-x elpaca-delete` `elpaca` followed by `M-x restart-emacs`. That should install Elpaca without having to re-install all your other packages.
> 
> > Hopefully this is a good enough description of the problem; if it's not helpful
> > I could try to downgrade elpaca and update it again in order to reproduce the
> > issue fully.
> 

>     2. Using the test Emacs instance, `M-x elpaca-visit` `elpaca` after everything is installed.
> 
>     3. In the dired buffer for Elpaca's repo `M-x magit-reset-hard` `HEAD~10`
>        You can change the number from 10 to rollback N commits.
> 
>     4. `M-x elpaca-rebuild` `elpaca`. You should now have an older version of Elpaca built.
> 
>     5. `M-x restart-emacs` to ensure the older version is loaded.
> 
>     6. Once the test Emacs restarts, `M-x elpaca-udpate` `elpaca`. This should pull in the N commits that were rolled back in the step 3 and rebuild Elpaca. I would also check the `elpaca-log` output to see if there are any errors at this point.
> 
>     7. `M-x restart-emacs` to see if the `elpaca-log-defaults` is undefined error is signaled.
>        You should be able to `M-x describe-function` `elpaca-log-defaults` if everything worked as intended

**Comment by progfolio** [comment]
> Upon trying to reinstall my config from scratch with just the config files. I encountered this error.

 >   WARNING: Elpaca Installer mismatch
 
 This is a warning. Was there an error in addition to the warning?
 Does the [wiki explanation](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#installer-version-mismatch) help?

**Comment by sethen** [comment]
Same thing here

**Comment by progfolio** [comment]
> Same thing here

Please answer the above question, too.

**Comment by sethen** [comment]
> > Same thing here
> 
> Please answer the [above question](https://github.com/progfolio/elpaca/issues/200#issuecomment-1807190819), too.

No error next to the warning, just the warning

**Comment by progfolio** [comment]
Okay. The wiki explanation linked above should help.

**Comment by Xanaxus** [comment]
Yes, the wiki explanation works. Thanks for the support!!

**Comment by Xanaxus** [comment]
Yes, the wiki explanation works. Thanks for the support!!

**Comment by sethen** [comment]
@progfolio That worked for me -- but now the `elpaca-update-all` function is gone... Did that get deprecated or something?

**Comment by progfolio** [comment]
> @progfolio That worked for me -- but now the `elpaca-update-all` function is gone... Did that get deprecated or something?

Please see the pinned issue:

https://github.com/progfolio/elpaca/issues/195
