### ISSUE TITLE
[Support]: Installing Elpaca for Emacs portable installation

### ISSUE THREAD

**Issue by dbaerit** [progfolio/elpaca#202]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

most recent

### Operating System

windows 11

### Description

Cloning into 'g:/emacshome/.emacs.d/elpaca/repos/elpaca'...
fatal: detected dubious ownership in repository at 'G:/emacshome/.emacs.d/elpaca/repos/elpaca'
'G:/emacshome/.emacs.d/elpaca/repos/elpaca' is on a file system that does not record ownership
To add an exception for this directory, call:

	git config --global --add safe.directory G:/emacshome/.emacs.d/elpaca/repos/elpaca

I added an exception for this directory, but I'm still getting this error when Emacs opens and it never completes cloning. I am trying to configure a portable install for emacs so it's on a flash drive which means there is no file ownership and no security tab in folder properties to change or add file ownership.

Edit: I should probably add that I'm also using Emacs 29.1

**Comment by progfolio** [comment]
Sorry, I can't offer any support for this set up.
I don't use Windows and it sounds more like an OS/filesystem permissions error than anything to do with Elpaca.
