### ISSUE TITLE
[Bug]: Solution to file-error "Making symbolic link" Operation not permitted, Error creating symlink on Windows 10/11

### ISSUE THREAD

**Issue by High-Flyer** [progfolio/elpaca#204]
### Elpaca Version

29.1 / deferred

### Operating System

Windows 10 Version 22H2 (OS Build 19045.3516)

### Description

This is a solution am sorry if it wasnt needed here. Apologies in advance, genuinely trying to help.
Error: symlinks path from error message bug on the windows installation of elpaca: info: elpaca-link-build-files: (file-error "Making symbolic link" Operation not permitted "c:/Users/username/.emacs.d/elpaca/repos/elpaca/elpaca-test.el" "c:/Users/username/.emacs.d/elpaca/builds/elpaca/elpaca-test.el")
Solution: Just delete Elpaca folder, after adding elpaca recipe in init.el just start emacs as an admin and it will solve by itself dont need to add simplink manually or bypass symlinks.
I hope it helps its solution so plz mark it solved. Thank you very much for the efforts and the package.

**Comment by progfolio** [comment]
> Solution: Just delete Elpaca folder, after adding elpaca recipe in init.el just start emacs as an admin and it will solve by itself dont need to add simplink manually or bypass symlinks.
I hope it helps its solution so plz mark it solved. Thank you very much for the efforts and the package.

This would require running Emacs as Admin (which sounds like a bad idea to me) any time a package needs to be symlinked.
A better solution is to enable symlinks for the user.
Unfortunately, I don't use Windows myself, but other users have reported success via the linked tutorial in the README.

**Comment by High-Flyer** [comment]
Am sorry thats what i realised this morning. i slept last night thinking package manager is set and install packages this morning and getting that same error Making symbolic link" Operation not permitted "now x_x
Manually setting symlink sadly either saying folder doesnt exists or the cannot create the link for already existing file.
thankfully this worked me avoiding symlinks.
```
	  (require 'elpaca)
	  (elpaca-generate-autoloads "elpaca" repo)
	  (load "./elpaca-autoloads")))
      (add-hook 'after-init-hook #'elpaca-process-queues)
;; Uncomment for systems which cannot create symlinks:
	  (elpaca-no-symlink-mode) ;;adding this before the order thanks to a git user post
      (elpaca `(,@elpaca-order))
```
Thank you again. Good day o7
