### ISSUE TITLE
[Support]: combining `:repo` and `:files` keywords in recipe for a local repo

### ISSUE THREAD

**Issue by benthamite** [progfolio/elpaca#206]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca 3384d68 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4.1 (c) (Build 22F770820d))
 of 2023-08-27
git --version:  git version 2.42.0

### Operating System

macOS Ventura 13.5.1

### Description

In my dotfiles repo, I have a subdirectory with a bunch of Elisp files, each of which extends the functionality of a package or feature by providing a feature named `[package/feature]-extras`. I would like to handle these files like I do ordinary packages/features. In this example, I am trying to load the feature `faces-extras`:

``` emacs-lisp
(use-package faces-extras
  :elpaca (faces-extras
	   :repo "/Users/pablostafforini/dotfiles/"
	   :files ("emacs/extras/faces-extras.el"))
  :demand t)
```

However, this doesn't work: `"Error (use-package): Cannot load faces-extras"`.

`"/Users/pablostafforini/dotfiles/"` points to a git repository, and `"/Users/pablostafforini/dotfiles/emacs/extras/faces-extras.el"` points to the location of `faces-extras.el` in that repository.

What am I doing wrong?

**Comment by benthamite** [comment]
Update: although I haven't figured out how to make the above work, I solved the underlying problem using a different approach. So I'm closing this issue.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.
My hunch is that the package build is failing.
Try:

1. Delete the ` $ELPACA-REPOS-DIRECTORY/dotfiles/` and `$ELPACA-BUILDS-DIRECTORY/faces-extras/" directories with `M-x elpaca-delete faces-extras` or manually.
2. Restart Emacs so Elpaca tries to install `faces-extras` again.
3. Share the output of `(elpaca-log "faces-extras")` and `M-x elpaca-info faces-extras`.

I tried creating a simplified version of the setup you've described locally and am unable to reproduce the issue so far.
