### ISSUE TITLE
[Support]: Cannot install a package

### ISSUE THREAD

**Issue by sauvala** [progfolio/elpaca#21]
### Emacs Version

GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-10-29

### Operating System

OS: Arch Linux x86_64

### question

Hi, I'm trying to replace my current use-package + straight setup with elpaca. I started testing to replace package by package but it seems like I faced a problem trying to enable [`vertico`](https://github.com/minad/vertico). I added the bootstrap code and specified it to use to load elpaca and `(elpaca use-package (require 'use-package))`. In my configs I try to load `vertico`:

```elisp
(elpaca-use-package vertico
  :demand t
  :init
  (vertico-mode))
```

But `vertico` is not installed (I cannot activate `vertico-mode` manually with `M-x` because it is not found). What I might be doing wrong?

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
> But vertico is not installed 

I can't be sure of what's wrong without seeing the output of the `elpaca-log` command.
Please copy that info here.

That said, your use-package declaration looks funny to me.
The `:init` keyword is for forms which are to be run prior to the package being required.
The `:demand` keyword is not necessary in your case because you're not using any keywords which defer loading. A better declaration would be:

```emacs-lisp
(elpaca-use-package vertico :config (vertico-mode))
```

**Comment by sauvala** [comment]
Hi @progfolio and thanks for quick reply.

I checked the output of `elpaca-log` and there the `vertico` was marked as `queued`. There were a few other packages that I already "migrated" to use `elpaca-use-package` and their status was not in `queued` state (I think it was `installed` but I cannot say for sure what was the wording).

This got me wondering if I should just try to install vertico with elpaca and changed all the other references to use plain old `use-package` instead of `elpaca-use-package`. This seemed to fix the issue and when I opened Emacs again, elpaca installed and enabled vertico. I think there was some old `:straight` config left for some of the packages and they  caused problems getting things downloaded?

I tested this hypothesis and used `elpaca-use-package` with a package having the `:straight` keyword:

```elisp
(elpaca-use-package consult-tramp
    :straight (:host github :repo "Ladicle/consult-tramp"))
```

And here is the Elpaca log when that config is used with vertico:

```
 Package Status Info Time ▼ 
elpaca                         queued               Package queued                                                                   00.000388
use-package                    queued               Package queued                                                                   00.000575
consult-tramp                  queued               Package queued                                                                   00.013753
vertico                        queued               Package queued                                                                   00.021784
elpaca                         queueing-deps        Queueing Dependencies                                                            00.330290
elpaca                         queueing-deps        No external dependencies detected                                                00.330491
elpaca                         activation           Activating package                                                               00.330496
elpaca                         activation           Package build dir added to load-path                                             00.330504
elpaca                         activation           Caching autoloads                                                                00.330510
elpaca                         activation           Autoloads cached                                                                 00.330729
elpaca                         info                 No Info dir file found                                                           00.330737
elpaca                         finished             ✓ 0.330 secs                                                                     00.330748
use-package                    queueing-deps        Queueing Dependencies                                                            00.330752
bind-key                       queued               Package queued                                                                   00.330836
bind-key                       queueing-deps        Queueing Dependencies                                                            00.331151
bind-key                       queueing-deps        No external dependencies detected                                                00.332304
bind-key                       activation           Activating package                                                               00.332308
bind-key                       activation           Package build dir added to load-path                                             00.332315
bind-key                       activation           Caching autoloads                                                                00.332320
bind-key                       activation           Autoloads cached                                                                 00.332407
bind-key                       info                 No Info dir file found                                                           00.332414
use-package                    activation           Activating package                                                               00.332423
use-package                    activation           Package build dir added to load-path                                             00.332430
use-package                    activation           Caching autoloads                                                                00.332434
use-package                    activation           Autoloads cached                                                                 00.332622
use-package                    info                 Adding Info path                                                                 00.332629
use-package                    finished             ✓ 0.332 secs                                                                     00.332644
bind-key                       finished             ✓ 0.001 secs                                                                     00.332647
```

Sorry for the trouble, I should have limited my debugging first to use only vertico and do the migration package by package. It was a little confusing that a package loaded before vertico caused the problem of vertico not being loaded. Do you think elpaca could handle this so that it would tell me that `consult-tramp` has problems on it's declaration and would still proceed to load vertico?

And about the `:init` keyword: good point, I have just copied the example from vertico's github page without thinking about this. I tested using `:config` but it seemed vertico was not working correctly with that.

Best regards,
Janne

**Comment by progfolio** [comment]
```emacs-lisp
(elpaca-use-package consult-tramp
    :straight (:host github :repo "Ladicle/consult-tramp"))
```


You'll want to remove any references to the `:straight` use-package keyword as well.
The following is an example config which should install all three of those packages:

```emacs-lisp
;;bootstrap snippet omitted
(elpaca use-package)
(elpaca-use-package (consult-tramp :host github :repo "Ladicle/consult-tramp"))
(elpaca-use-package vertico)
```

> I tested using :config but it seemed vertico was not working correctly with that.

That seems odd to me (both that it wouldn't work and that it would require `:init`).
You'd have to open an issue at the vertico repository, though. I'm not too familiar with that package.

**Comment by sauvala** [comment]
> That seems odd to me (both that it wouldn't work and that it would require :init).
You'd have to open an issue at the vertico repository, though. I'm not too familiar with that package.

Yes, I'll open a issue to there and ask about this.

Thanks for the help once again. 👍🏻
