### ISSUE TITLE
[Support]: Selecting repo source for individual packages

### ISSUE THREAD

**Issue by edgar-vincent** [progfolio/elpaca#212]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca ad60abc HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
git --version:  git version 2.42.0

### Operating System

NixOS 23.11

### Description

Hi!

This is going to be a very silly question, which I'm sure is covered by the documentation, but I can't figure it out.

How do I select, for each package, the repository (MELPA, Org, ELPA, ELPA-devel) it should be installed from, when using `use-package`? 

For instance, I usually don't want to install packages from ELPA-devel, so I did this:
```elisp
(setopt elpaca-menu-functions '(elpaca-menu-extensions
                                elpaca-menu-org
                                elpaca-menu-melpafor
                                elpaca-menu-non-gnu-elpa
                                elpaca-menu-gnu-elpa
                                elpaca-menu-non-gnu-devel-elpa
                                elpaca-menu-gnu-devel-elpa))
```
Is this the right way to do it? And how would I specify which repository a specific package should come from?

Thank you very much, and please excuse me for my silly enquiry.

``

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> How do I select, for each package, the repository (MELPA, Org, ELPA, ELPA-devel) it should be installed from, when using use-package?

You should be able to specify a specific recipe menu via the [:inherit recipe keyword](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipe-keyword-inherit). e.g.

```emacs-lisp
(elpaca (example :inherit elpaca-menu-melpa))
```

That will allow you to control on a per-recipe basis which menu functions are used.
The global option is `elpaca-menu-functions`, which will be consulted in order when the `:inherit` recipe keyword is `t`.
e.g.

```emacs-lisp
;; Using fictitious menus for the sake of example:
(setq elpaca-menu-functions '(elpaca-menu-first elpaca-menu-second)) 

;; `elpaca-menu-first` is checked for a menu item matching `example`, then `elpaca-menu-second`.
(elpaca (example :inherit t))
```

Does that help?

**Comment by edgar-vincent** [comment]
That's very clear. It all makes sense now.

Thank you very much indeed.

**Comment by progfolio** [comment]
Glad to help. Thank you.
