### ISSUE TITLE
[Support]: Unable to install `protobuf-mode`

### ISSUE THREAD

**Issue by Yevgnen** [progfolio/elpaca#221]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca cd4bd2b HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-apple-darwin23.2.0, Carbon Version 170 AppKit 2487.3)
 of 2023-12-24
git --version:  git version 2.43.0

### Operating System

macOS 14.2.1 (23C71)

### Description

When install `protobuf-mode` in `elpaca-manager`, get below error.

```
protobuf-mode                  failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"protobuf-mode\"") 26.449291
```

Tried following the existed issue with 

```
(use-package protobuf-mode
  :elpaca (:host github :repo "protocolbuffers/protobuf" :files ("editors/protobuf-mode.el")))
```

but got the same error.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> ```
> protobuf-mode                  failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"protobuf-mode\"") 26.449291
> ```

This is due to protobuf-mode.el being located in the  the "editors" sub-directory of the protobuf repository. I've just improved the algorithm which finds a package's main file, so you should be able to update Elpaca and it will find it. See the following test case:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init (setq elpaca-menu-functions '(elpaca-menu-melpa))
  (elpaca protobuf-mode)
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>f752db6 HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-18</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.ucbmGZ/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.ucbmGZ/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...
elpaca-log: "#unique"
"
elpaca                         finished             ✓ 0.538 secs                                                                     07.639483
protobuf-mode                  finished             ✓ 2.389 secs                                                                     09.490409
"

 Test Env

Elpaca f752db6 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2023-12-18
git --version:  git version 2.43.0
```
</details>


In general, if you see this error, you can supply the [:main recipe keyword](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipe-keyword-main) to explicitly tell Elpaca where the main elisp file is located.
  
Does that help?

**Comment by Yevgnen** [comment]
Hi, thanks, that helps. But I get another error

```
auctex                         failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"auctex\"") 00.952247
```
 from my original working `init.el` without specifying the `:main` keyword.
```
(use-package tex
  :elpaca auctex)
```

(Just FYI,  I didn't see the related error before a recent  update of `elpaca`. There also another error related to package version I have not reported it yet: when I install `ace-pinyin` I get error telling me that required version (`0.1.0`) of `pinyinlib` is not found. But I did not have time to test it fully right now.)

**Comment by progfolio** [comment]
> Hi, thanks, that helps. But I get another error
>
> ```
> auctex                         failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"auctex\"") 00.952247
> ```
>
> from my original working `init.el` without specifying the `:main` keyword.
>
> ```
> (use-package tex
>   :elpaca auctex)
> ```

I don't see how that recipe could've worked properly before.
Auctex requires a `:pre-build` step to install correctly.
See [this comment](https://github.com/progfolio/elpaca/issues/191#issuecomment-1870453017) for a recipe which should install Auctex correctly.

> There also another error related to package version I have not reported it yet: when I install `ace-pinyin` I get error telling me that required version (`0.1.0`) of `pinyinlib` is not found. But I did not have time to test it fully right now.)

I've recently added dependency version checks to Elpaca.
[pinyinlib](https://raw.githubusercontent.com/cute-jumper/pinyinlib.el/master/pinyinlib.el) does not properly declare a version in the packages header, which is a bug the maintainer of that package should address.
I suggest opening a bug report with them requesting they do so.
As a workaround, you could use the [:version recipe keyword](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#version) to forge the version number.


If you have any follow up questions, please open separate issues for these.
Keeping each issue focused to a single topic makes searching/referencing them easier in the future.
Thanks.
