### ISSUE TITLE
[Support]: elpaca-fetch-all fails

### ISSUE THREAD

**Issue by dertuxmalwieder** [progfolio/elpaca#223]
### Elpaca Version

Elpaca a38621a HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin23.2.0, NS appkit-2487.30 Version 14.2.1 (Build 23C71))
 of 2023-12-28
git --version:  git version 2.43.0

### Operating System

macOS Sonoma

### Description

`elpaca-fetch-all` can't pull `org`:

```
org                            failed               elpaca--finalize: (excessive-lisp-nesting 1601) 
```

I wonder why.

**Comment by progfolio** [comment]
Please share your configuration for Org mode.

**Comment by dertuxmalwieder** [comment]
It's [here.](https://code.rosaelefanten.org/dotfiles/file?name=emacs/init-org.el&ci=tip)

**Comment by progfolio** [comment]
Thanks. Try removing the following lines:

```emacs-lisp
;; Load the org package *NOW* to avoid conflics.
(elpaca-process-queues)
```

You'll also want to enable lexical binding for that file. `M-x elisp-enable-lexical-binding` should do the trick. Once you've made those edits, try restarting Emacs, enable debug-on-error (`M-x toggle-debug-on-error`), and `M-x elpaca-fetch-all`. If you get a backtrace, please paste the whole backtrace here.

**Comment by dertuxmalwieder** [comment]
> Those lines don't actually do what your comment says.

Oops! :-)

I added them because they fixed a conflict with Emacs's own `org` (basically, a few packages that used `org` were confused about which version to use). It *seems* that this has been solved now - your fix (including the lexical binding) worked for me. Sometimes, PEBKAC still gets me... **thank you!**

**Comment by progfolio** [comment]
Glad to hear it's fixed. Thanks.
