### ISSUE TITLE
[Support]: Warning (emacs): Package.el loaded before Elpaca

### ISSUE THREAD

**Issue by IceAsteroid** [progfolio/elpaca#224]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca d5e9fd8 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 2, x86_64-unknown-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
 of 2023-08-03
git --version:  git version 2.43.0

### Operating System

Void Linux

### Description

Emacs complaints: ```Warning (emacs): Package.el loaded before Elpaca```

I accidentially installed a package with package.el, and when I restarted emacs, it complaints the above message.

I'm using "org-babel-tangle" in an org file to tangle configs to the init file.

Config of elpaca in init file:
```
  ;; elpaca.el setup
  ;;; Boostrap elpaca
  (defvar elpaca-installer-version 0.6)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
				:ref nil
				:files (:defaults "elpaca-test.el" (:exclude "extensions"))
				:build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
	 (build (expand-file-name "elpaca/" elpaca-builds-directory))
	 (order (cdr elpaca-order))
	 (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (< emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
	  (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		   ((zerop (call-process "git" nil buffer t "clone"
					 (plist-get order :repo) repo)))
		   ((zerop (call-process "git" nil buffer t "checkout"
					 (or (plist-get order :ref) "--"))))
		   (emacs (concat invocation-directory invocation-name))
		   ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
					 "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		   ((require 'elpaca))
		   ((elpaca-generate-autoloads "elpaca" repo)))
	      (progn (message "%s" (buffer-string)) (kill-buffer buffer))
	    (error "%s" (with-current-buffer buffer (buffer-string))))
	((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (load "./elpaca-autoloads")))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
  ;;;; elpace integration with use-package
  (elpaca elpaca-use-package
    ;; Enable :elpaca use-package keyword.
    (elpaca-use-package-mode)
    ;; Assume :elpaca t unless otherwise specified.
    (setq elpaca-use-package-by-default t))
  ;;;;;; Necessary to use the `:elpaca' use-package keyword at the top-level.
  (elpaca-wait)
  ;;;; Prevent package.el to load packages prior to their
  ;;;;-init-file loading at startup in favor of elpaca.el
  (setq package-enable-at-startup nil)
```

I've tried:
```
  (use-package package
    :defer t
    :after elpaca
  )
```
But still not luck.

**Comment by progfolio** [comment]
Thanks for taking the time to open a support ticket.

> I accidentally installed a package with package.el, and when I restarted emacs,
> it complaints the above message.

When package.el installs packages it creates a folder, usually `~/.emacs.d/elpa` which contains the packages it has downloaded.
Emacs will also call `package-activate-all` when that folder is present, unless `(setq package-enable-at-startup nil)` is in your early-init.el file as recommended in the [Installation instructions](https://github.com/progfolio/elpaca#installer).

I would double check to make sure the setting is in your early-init.el file.


> I've tried:
> ```
>   (use-package package
>     :defer t
>     :after elpaca
>   )
> ```
> But still not luck.

You'll want to remove this and any other references to package.el from your init file, too.

Let me know if that helps.

**Comment by IceAsteroid** [comment]
The problem is, I had set the variable in the init file, whether to put it at the top of the init file, or just it's shown like in the conf I posted. It didn't solve the problem at all.

I had to instead remove the elpa folder to solve this warning message. That's weird.

**Comment by IceAsteroid** [comment]
Thank you so much for the information. It appears that was me misunderstanding the instruction in the readme page

> 
> You'll also want to disable package.el in your early-init file[2](https://github.com/progfolio/elpaca#fn.2):
> 
> (setq package-enable-at-startup nil)

Where early-init file is actually a separate file along with init file :) I never knew this before
