### ISSUE TITLE
[Bug]: Dependency loading fails

### ISSUE THREAD

**Issue by cyberdyne-skynet** [progfolio/elpaca#225]
### Elpaca Version

Elpaca d5e9fd8 HEAD -> master, origin/master, origin/HEAD

### Operating System

Arch Linux

### Description

I'm getting this error when downloading packages:

![2023-12-29_08-20](https://github.com/progfolio/elpaca/assets/122663460/fdeaff4d-90a8-465a-84bd-c2a4e49e7a8e)

**Comment by progfolio** [comment]
The issue with pescient is fixed on the master branch.
You can delete the `elpaca-directory` (usually located at `~/.emacs.d/elpaca/`) and restart Emacs to reinstall.

For the issue with seq.el please see: https://github.com/progfolio/elpaca/issues/216#issuecomment-1868747372

**Comment by progfolio** [comment]
I'll consider this closed for now. If have any more questions, feel free to leave a comment and we can re-open. Thanks.
