### ISSUE TITLE
[Bug]: GitHub issue form template invalid, only allows for Feature Request 

### ISSUE THREAD

**Issue by montchr** [progfolio/elpaca#226]
### Feature Description

**First and foremost: this is not a feature request.** It was submitted as a Feature Request because of the bug I am reporting: the only issue type available for selection is a Feature Request.

Edit: I am leaving the template as-is, but I can edit this comment to update if that would be helpful.

Edit 2: Though I changed the title, because of the template, this issue is unfortunately laballed as an enchantment.

Looking at the template, I see the following error message from GitHub:

> There is a problem with this template
> 
> title must be of type String and cannot be empty.

Source: <https://github.com/progfolio/elpaca/blob/master/.github/ISSUE_TEMPLATE/support.yml>

I would open a PR but this seems like something I should leave to maintainers to decide.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for bringing that to my attention. Should be sorted now.

**Comment by montchr** [comment]
Thanks! Confirmed.
