### ISSUE TITLE
[Support]: "Unable to find main elisp file for "auctex".

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#227]
None of these solutions seem to work for me. Elpaca always ends up reporting `error "Unable to find main elisp file for \"auctex\"`.

_Originally posted by @emacsomancer in https://github.com/progfolio/elpaca/issues/191#issuecomment-1872675115_

Please share the output of `M-x elpaca-version`, the log for `(elpaca-log "auctex")` and the configuration you are using.
My hunch is that the pre-build step is failing (Make is used to generate the main elisp file). I would check the logs for any errors or warnings related to auctex.

**Comment by emacsomancer** [comment]
elpaca-version:

"Elpaca 13dc968 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)
git --version:  git version 2.41.0"

`(elpaca-log "auctex")` brings up the elpaca log buffer filtered to "auctex", but when I click on "auctex" it flashes an error and complains about not being able to find the main elisp file and displays no log. The entry says: `auctex                         failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"auctex\"") 06.058076`.

The full screen:
```
 Package Status Info Time ▼ 
auctex-latexmk                 failed               Failed dependencies: (auctex)                                                    05.983470
auctex                         pre-build            Running :pre-build commands                                                      447.849083
auctex                         pre-build            Warning (emacs): Unable to determine elpaca-core-date                            448.084243
auctex                         pre-build            Running command: ("./autogen.sh")                                                448.104738
auctex                         pre-build            $/home/slade/.guix-home/profile/bin/emacs -Q --batch --eval (with-temp-buffer (setq load-prefer-newer t) (let ((p (make-process :name "elpaca-process-poll-/home/slade/.emacs.d/elpaca/repos/auctex/autogen.sh" :buffer (current-buffer) :command '("/home/slade/.emacs.d/elpaca/repos/auctex/autogen.sh")))) (add-hook 'after-change-functions (lambda (beg end _) (when (process-live-p p) (message "%s" (string-trim (buffer-substring-no-properties beg end))))) nil t) (while (accept-process-output p)))) 448.194836
auctex                         pre-build            /home/slade/.emacs.d/elpaca/repos/auctex/autogen.sh: line 31: autoconf: command not found 448.194850
auctex                         pre-build            Error running autoconf in .                                                      448.194859
auctex                         pre-build            Running command: ("./configure" "--without-texmf-dir" "--with-packagelispdir=./" "--with-packagedatadir=./") 448.215375
auctex                         pre-build            Running command: ("make")                                                        448.299490
auctex                         pre-build            $/home/slade/.guix-home/profile/bin/emacs -Q --batch --eval (with-temp-buffer (setq load-prefer-newer t) (let ((p (make-process :name "elpaca-process-poll-make" :buffer (current-buffer) :command '("make")))) (add-hook 'after-change-functions (lambda (beg end _) (when (process-live-p p) (message "%s" (string-trim (buffer-substring-no-properties beg end))))) nil t) (while (accept-process-output p)))) 448.398101
auctex                         pre-build            make: *** No targets specified and no makefile found.  Stop.                     448.398114
auctex                         pre-build            :pre-build steps finished                                                        448.409921
auctex                         failed               elpaca--queue-dependencies: (error "Unable to find main elisp file for \"auctex\"") 448.423087
```


config:
```
(use-package auctex
  ;; :elpaca nil
  :elpaca  (auctex :pre-build (("./autogen.sh")
                               ("./configure"
                                "--without-texmf-dir"
                                "--with-packagelispdir=./"
                                "--with-packagedatadir=./")
                               ("make"))
                   :build (:not elpaca--compile-info) ;; Make will take care of this step
                   :files ("*.el" "doc/*.info*" "etc" "images" "latex" "style")
                   :version (lambda (_) (require 'tex-site) AUCTeX-version)))

(though I've tried other variants as well.)

```

**Comment by progfolio** [comment]
The `:pre-build` step is failing and so Make can't generate the auctex.el file.
Note these log lines:

```
auctex                         pre-build            /home/slade/.emacs.d/elpaca/repos/auctex/autogen.sh: line 31: autoconf: command not found 448.194850
auctex                         pre-build            Error running autoconf in . 
```

It looks like installing autoconf should help.

**Comment by emacsomancer** [comment]
Ah, yes, installing autoconf seems to have worked! (Now to work on resolving the other issues.)

**Comment by progfolio** [comment]
> Ah, yes, installing autoconf seems to have worked! (Now to work on resolving the other issues.)

Glad it's working.
Feel free to open another ticket for any other issues.
I did notice this in your log output as well:

> auctex                         pre-build            Warning (emacs): Unable to determine elpaca-core-date                            448.084243

Since you are on a development version of Emacs, you'll want to set that variable to the build-date of Emacs before elpaca.el is loaded (before the installer script is a good spot). See [this comment](https://github.com/progfolio/elpaca/issues/222#issuecomment-1872596777) .

**Comment by mestinso** [comment]
@progfolio I'm getting this particular issue on Windows. Any particular ideas/suggestions, or do I need to figure out how to get autoconf installed?

**Comment by progfolio** [comment]
> Any particular ideas/suggestions

Check the output of `M-x elpaca-log` and narrow it down to auctex.
Look for errors in the pre-build steps.

> do I need to figure out how to get autoconf installed?

If the recipe calls for it, yes.
I would check Auctex's website to see if they have Window's specific installation instructions, too.

**Comment by mestinso** [comment]
> Check the output of `M-x elpaca-log` and narrow it down to auctex. Look for errors in the pre-build steps.

Right, so this is how I found this thread. The error I receive is "Unable to find main elisp file for "auctex".

> https://www.gnu.org/software/auctex/manual/auctex/Prerequisites.html#Prerequisites

I think that page is referring to precompiled builds of emacs itself. Though this [other page](https://www.gnu.org/software/auctex/manual/auctex/Installation.html#Installation) claims it's as easy as
`(use-package tex :ensure auctex)` without elpaca or straight.

A few more FYIs that may or may not be helpful:
1) I migrated from straight and this is one of only two issues I faced. This was my recipe on straight which worked fine:
`(use-package tex :straight auctex)` 
2) I tried to see if package.el could install auctex no problem from elpa, and sure enough it seemed to download and install fine.

I don't know enough about what happens behind the scenes with these different package managers, but let me know if you have any other ideas or suggestions. For now, i've just had to disable/remove auctex for my windows machine.

**Comment by progfolio** [comment]
Sorry, I may have linked to the wrong page.

https://www.gnu.org/software/auctex/manual/auctex/Installation-under-MS-Windows.html#Installation-under-MS-Windows

That should be the correct page.
If you can build it following those instructions, then Elpaca should be able to build it as well. The recipe may need to be altered depending on your system setup.

**Comment by progfolio** [comment]
https://www.gnu.org/software/auctex/manual/auctex/Installation-under-MS-Windows.html#Installation-under-MS-Windows

Sorry, looks like I linked to the wrong page. That should have instructions for building Auctex from source on Windows. If you're able to get it working by following those steps, Elpaca should be able to build it, too. It may require altering the package recipe, though.

The reason those package.el instructions work with package.el is because the package isn't being built by the client. It's installing a pre-built tarball hosted on GNU's servers. Straight uses a mirror of that server and (if memory serves) a slightly different recipe.

**Comment by mestinso** [comment]
@progfolio Thanks. So, I started going down the path mentioned on the "Installation under MS Windows" page, however I don't have MSYS or Cygwin etc. installed, and don't feel like going down that route for this one single thing.

Instead, what I ended up doing was the following, which feels a bit hacky, but ultimately worked great and was the path of least resistance for me:
```
(defvar package-list '(auctex))
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

(eval-and-compile
  (defun auctex-load-path ()
    (car (file-expand-wildcards "~/.emacs.d/elpa/auctex-*"))))

(use-package tex :ensure nil
  :load-path (lambda () (auctex-load-path))
  :init (load "auctex.el" nil t t)
  ...
```
I assume there is no other built-in method for elpaca to utilize these prebuilt package.el tarball from GNU's servers, is there? Potential future feature?

**Comment by progfolio** [comment]
Matt Stinson ***@***.***> writes:

> @progfolio Thanks. So, I started going down the path mentioned 
> on the "Installation
> under MS Windows" page, however I don't have MSYS or Cygwin etc. 
> installed, and don't
> feel like going down that route for this one single thing.

Ah, that's likely why the build script is not able to run.
 
> Instead, what I ended up doing was the following, which feels a 
> bit hacky, but ultimately
> worked great and was the path of least resistance for me:
>
> (defvar package-list '(auctex))
> (dolist (package package-list)
>   (unless (package-installed-p package)
>     (package-install package)))
>
> (eval-and-compile
>   (defun auctex-load-path ()
>     (car (file-expand-wildcards "~/.emacs.d/elpa/auctex-*"))))
>
> (use-package tex :ensure nil
>   :load-path (lambda () (auctex-load-path))
>   :init (load "auctex.el" nil t t)
>   ...

So long as you're careful with using two package managers, you 
should be fine.
There is potential for them to conflict with one another.
For example, if the same package is activated by both managers, 
one will "win".
Elpaca should generate warnings in this situation, though.
 
> I assume there is no other built-in method for elpaca to utilize 
> these prebuilt package.el
> tarball from GNU's servers, is there? Potential future feature?

Currently there's no way to Elpaca to install from pre-built 
tarballs without implementing custom build steps.
There's definitely potential for adding functionality for this and 
other types of package management, though.
I'll keep it in mind. Glad you got something working for now.
