### ISSUE TITLE
[Support]: elpaca fails to install magit

### ISSUE THREAD

**Issue by jeromeag** [progfolio/elpaca#228]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 13dc968 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
 of 2023-08-30, modified by Debian

### Operating System

Debian GNU/Linux trixie/sid

### Description

[init.el](https://github.com/progfolio/elpaca/files/13804700/init.el.txt) and [early-init.el](https://github.com/progfolio/elpaca/files/13804701/early-init.el.txt) files filled as recommended in elpaca `README.md` files.
`(use-package magit)` at the end of `init.el`.

elpaca fails to install magit.

Here is the content of `*elpca-log*` buffer:

 Package Status Info Time ▼ 
magit                          failed               Failed dependencies: (git-commit transient)                                      16.581294
git-commit                     failed               Failed dependencies: (transient)                                                 16.589510
transient                      failed               Requires seq minimum version: 2.24                                               16.597706

Note: a workaround is to add `(use-package seq)`  just before  `(use-package magit)`.

**Comment by progfolio** [comment]
>  I have searched previous issues to see if my question is a duplicate.

What did you search for? Did you have a look at the pinned issues or 
[This section of the wiki](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#unmet-version-dependencies )?

This is a feature, not a bug. Please see the above resources for how to deal with it properly.
