### ISSUE TITLE
[Feature]: Add quick advice on inferring versions from git tags to wiki

### ISSUE THREAD

**Issue by realcomplex** [progfolio/elpaca#229]
### Feature Description

Hi. Thanks for the great package!

I, as some others (from what I see from recent Github issues) have been a little bitten by the dependency version checking you introduced recently. I get it: it's apparently a bit of a pain to even reliably determine an elisp package version!

Anyway, after some digging I finally managed to figure out how to make elpaca happy with the `hl-todo` package, which _only_ exposes its version through git tags (see also https://github.com/tarsius/hl-todo/issues/79). In particular, the following form seems to work well for me:

```
(use-package hl-todo
  :elpaca (:type git
           :host github
           :repo "tarsius/hl-todo"
           :version elpaca--latest-tag
           :depth nil)
  :config
  (global-hl-todo-mode t))
```

The `:version` and `:depth` items needed to be added this time in order to make things work.

Would it be an idea to add a line or two about this trick in the wiki for others stumbling across the same issue? I had to dig into elpaca source code to even think about using the `elpaca--latest-tag` function, and the fact that this required `:depth nil` is also non-trivial. Hopefully this will save some other some time.

Cheers!

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by realcomplex** [comment]
On another note, it does seem to me like it might be sensible for elpaca to try and infer a version number from a git tag in the `elpaca--declared-version` function if no metadata can be found. However I recognise that this probably isn't straight forward since it would mean having to clone github repos fully (not shallowly) to even get the tags in the first place. Seems like versions are just quite a pain to deal with generally.

**Comment by progfolio** [comment]
> Hi. Thanks for the great package!

Thanks for the kind words and taking the time to fill out a ticket.
  
> Anyway, after some digging I finally managed to figure out how to make elpaca
> happy with the `hl-todo` package, which _only_ exposes its version through git
> tags

Yes. It's unfortunate that the package author wishes only to expose the version info through that means.
  
> following form seems to work well for me:

You shouldn't need to specify that much information, as much of it will be inherited from the menu item for hl-todo and `elpaca-order-functions`.

> The `:version` and `:depth` items needed to be added this time in order to make
> things work.

`:version` should be unnecessary in this case.
`elpaca--check-version` will attempt to find the declared version in this order:

- In the package's -pkg.el file.
- In the package main elisp file's Version: header field
- The latest version git tag.

The reason it initially failed is because a shallow clone (`elpaca-order-defaults` defaults to `:depth 1`) is unable to find any matching version tags.
The root of a shallow clone is a "grafted" git commit, so it doesn't share the have the same commit hash it would in a full clone. Thus, git doesn't find any tags which contain the commit.

The following should be enough:

``` emacs-lisp
(use-package hl-todo :elpaca (:depth nil))
```

See the following test case:

<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init (elpaca magit-todos)
  (elpaca (hl-todo :depth nil))
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>ec4befa HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-18</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.s1I6N7/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.s1I6N7/elpaca/repos/elpaca...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.s1I6N7/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...
elpaca-log: "#unique"
"
elpaca                         finished             ✓ 0.608 secs                                                                     06.475211
s                              finished             ✓ 0.606 secs                                                                     06.898273
pcre2el                        finished             ✓ 0.826 secs                                                                     07.116193
async                          finished             ✓ 0.941 secs                                                                     07.231975
compat                         finished             ✓ 1.507 secs                                                                     07.745534
dash                           finished             ✓ 1.630 secs                                                                     07.934408
with-editor                    finished             ✓ 1.037 secs                                                                     08.014186
hl-todo                        finished             ✓ 2.246 secs                                                                     08.113882
f                              finished             ✓ 1.890 secs                                                                     08.181799
git-commit                     finished             ✓ 1.431 secs                                                                     08.398034
magit-section                  finished             ✓ 1.486 secs                                                                     08.464268
magit                          finished             ✓ 4.999 secs                                                                     11.298049
magit-todos                    finished             ✓ 5.854 secs                                                                     11.720745
"

 Test Env

Elpaca ec4befa HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2023-12-18
git --version:  git version 2.43.0
```
</details>

> Would it be an idea to add a line or two about this trick in the wiki for others
> stumbling across the same issue?

Thanks for the suggestion.
I've added a paragraph [here](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#unmet-version-dependencies).
Does that help?

**Comment by koen-vg** [comment]
Ah you are right of course, the `:version` part is indeed not needed; I just didn't understand the code and didn't try with only the `:depth` part. Your explanation makes a lot of sense. Thanks so much!

**Comment by progfolio** [comment]
You're welcome!

**Comment by realcomplex** [comment]
Thanks, this makes a lot of sense! I just didn't understand the code and didn't think to try with only the `:depth` part. (deleted previous comment from wrong account.)

**Comment by benthamite** [comment]
Hi, I'm experiencing a similar issue with two packages involving a mismatch between their git tags and their version metadata:

- [password-store-otp](https://github.com/volrath/password-store-otp.el)
- [bibtex-completion](https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el)

In my init file, `pass` and `org-roam-bibtex` fail to load because they require versions 0.1.5 and 2.0.0 of those packages, respectively. Unfortunately, the solution you provided above doesn't work, e.g. updating my init file to include

```emacs-lisp
(use-package password-store-otp
  :elpaca (:depth nil
  :demand t))
```
does not make the `pass` error disappear. I do see a full (as opposed to a shallow) clone of  the `password-store-otp` repo in `elpaca/repos/password-store-otp`, but this does not seem to make a difference.

**Comment by progfolio** [comment]
> - [password-store-otp](https://github.com/volrath/password-store-otp.el)

Looks like the main elisp file still declares 0.1.0, while the maintainer has been making releases solely through git tags. That's a bug with that package as far as I'm concerned.
I would try to get in touch with the maintainer, but it doesn't look like there's much maintenance going on. See:

https://github.com/volrath/password-store-otp.el/issues/12

You can provide a version via the [:version recipe keyword](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipe-keyword-version). e.g.

``` emacs-lisp
(elpaca (password-store-otp :version (lambda (_) "0.1.5")))  ;;allows shallow clone, but will have to be maintained by you.
```

The recipe in the test case below should also work, but relies on an undocumented `:version-regexp` recipe keyword which I may end up getting rid of.

<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init
  (elpaca (password-store-otp
           :depth nil
           ;; Necessary becuase the tags are of format X.Y.Z instead of vX.Y.Z
           :version-regexp ".*"
           ;;Note: this function will likely be renamed soon to `elpaca-latest-tag'.
           :version (lambda (e) (elpaca--latest-tag e))))
  (elpaca pass)
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>61c8b9b HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-18</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.dqxIqd/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.dqxIqd/elpaca/repos/elpaca...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.dqxIqd/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...
elpaca-log: "#unique"
"
elpaca                         finished             ✓ 0.527 secs                                                                     06.421648
s                              finished             ✓ 0.645 secs                                                                     06.841605
dash                           finished             ✓ 1.310 secs                                                                     07.943909
f                              finished             ✓ 1.844 secs                                                                     08.144533
compat                         finished             ✓ 1.148 secs                                                                     08.173329
with-editor                    finished             ✓ 1.694 secs                                                                     08.368699
password-store                 finished             ✓ 2.400 secs                                                                     08.600363
password-store-otp             finished             ✓ 2.918 secs                                                                     08.819115
pass                           finished             ✓ 3.174 secs                                                                     09.068851
"

 Test Env

Elpaca 61c8b9b HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2023-12-18
git --version:  git version 2.43.0
```
</details>

Either solution should work around the issue, but it would be nice if the package author could be convinced to bump the Version field in the main elisp file, too. That'd save everyone else a lot of work.

> - [bibtex-completion](https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el)
>

Same exact scenario here.
Package has an outdated Version field in the main elisp file.
The options I outlined above should work similarly here.

Does that help?

**Comment by benthamite** [comment]
> Does that help?

Yes, thank you!
