### ISSUE TITLE
[Support]: use-package's `:ensure nil` equivalent?

### ISSUE THREAD

**Issue by ragnese** [progfolio/elpaca#23]
### Emacs Version

28.something

### Operating System

macOS

### question

My old use-package config had customizations for several built-in Emacs modes, like org. But, org mode doesn't need to actually be downloaded/installed, so use-package has the :ensure nil option to avoid trying to install the package while still getting the convenient, consistent, configuration syntax with :config, :bind, etc.

Is there a way to do that with elpaca-use-package? Or should I just stick to using use-package directly for those modes? It doesn't matter for any technical reason, but it would be nice if all of my package configs used the same top form instead of some starting with `(elpaca-use-package ...)` and some starting with `(use-package ...)`.

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
I've added handling of the `:ensure` keyword to `elpaca-use-package`.
Using Org as an example:

```emacs-lisp
(elpaca-use-package org :ensure nil)
;; expands to
(elpaca nil
  (use-package org))
```

Elpaca should be able to update/rebuild itself.
You can do so via the `elpaca-update` command.

Testing is appreciated. Thank you.

**Comment by ragnese** [comment]
Thank you so much for the quick update!

It seems to be working just fine. Although, when I ran `elpaca-update-all` and restarted my Emacs instance, it was totally borked and couldn't even find any of the elpaca commands and variables. Deleting the whole elpaca directory and starting again fixed it. I assume this was something I did and probably not elpaca's fault. It's my first day with elpaca...

Anyway, thanks again. So far, switching from straight + use-package to elpaca with its elpaca-use-package helper has been completely trivial- especially with this change!

**Comment by progfolio** [comment]
> Thank you so much for the quick update!

You're welcome. Thank you for bringing that to my attention.

> when I ran elpaca-update-all and restarted my Emacs instance, it was totally borked and couldn't even find any of the elpaca commands and variables.

Hard to say without seeing what happened.
Elpaca does respect `emacs --debug-init`, which may help track down what went wrong if it occurs again.
Feel free to open an issue if it happens again.

> Deleting the whole elpaca directory and starting again fixed it.

If all else fails, that's a surefire way to reset the state of everything at the cost of downloading/building everything again.

> Anyway, thanks again. So far, switching from straight + use-package to elpaca with its elpaca-use-package helper has been completely trivial- especially with this change!

Glad to hear it. Thanks again for testing.
