### ISSUE TITLE
[Bug]: Elpaca throws a warning message about `seq` when trying to fix `magit` issue

### ISSUE THREAD

**Issue by elijah-u** [progfolio/elpaca#230]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec4befa HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 2, aarch64-apple-darwin23.1.0, NS appkit-2487.20 Version 14.1.2 (Build 23B2091))
 of 2023-12-11

### Operating System

MacOS Sonoma 14.2.1

### Description

There is an issue installing magit using elpaca because of recent changes to that package that now require an updated version of transient and seq. This was discussed in magit tickets like: https://github.com/magit/magit/issues/5011 , as in issue for straight (https://github.com/radian-software/straight.el/issues/964 and https://github.com/radian-software/straight.el/issues/1139) and in a ticket for elpaca that was just recently closed (#228 ). 

I get that elpaca is doing what it's supposed to do by default by blocking the install of transient because it lists seq >= 2.24 as a dependency, and it doesn't just upgrade seq because it is on the `elpaca-ignored-depencies` list.

I had attempted the solution suggested by @jeromeag in #228 ... adding `(use-package seq)` before finding that ticket, but unfortunately it causes the following warning (reproducible using the init.el and early-init.el they provided with that one line added) to be consistently thrown:

⛔ Warning (emacs): seq loaded before Elpaca activation

Would you mind suggesting solutions for using elpaca to upgrade seq that don't throw that error? With magit being a pretty popular package, it might be worth throwing an example of the 'best practices' for this in the readme.

Thanks.

**Comment by progfolio** [comment]
Please see this pinned issue:

https://github.com/progfolio/elpaca/issues/216

**Comment by elijah-u** [comment]
Missed it despite looking all around for it. Sorry to waste your time. Many thanks for the link and the wonderful package manager.

**Comment by progfolio** [comment]
> Missed it despite looking all around for it. Sorry to waste your time. Many thanks for the link and the wonderful package manager.

Not a problem. I hope to make things easier with regards to package versions in the future. Thanks for the kind words and using the package.
