### ISSUE TITLE
[Bug]: elpaca--check-version: (error "Invalid version syntax: ‘0.3.3-DEV’") when updating CIDER

### ISSUE THREAD

**Issue by deejayem** [progfolio/elpaca#231]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec4befa HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-apple-darwin23.1.0, Carbon Version 170 AppKit 2487.2)
git --version:  git version 2.42.0

### Operating System

I've seen this on Linux and MacOS, but right now:
`23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64 i386 Darwin`
(Emacs is from nixpkgs though).

### Description

When updating CIDER (https://github.com/clojure-emacs/cider), I get the following error: `elpaca--check-version: (error "Invalid version syntax: ‘0.3.3-DEV’")`, and it is marked as `failed` in `*elpaca-log*`

I think this version string should be considered valid.

**Comment by progfolio** [comment]
> When updating CIDER (https://github.com/clojure-emacs/cider), I get the
> following error: `elpaca--check-version: (error "Invalid version syntax:
> ‘0.3.3-DEV’")`

Looks like that's the declared version for cider's "sesman" dependency.
  
> I think this version string should be considered valid.

Agreed. Emacs uses `version-regexp-alist` to determine the numeric value of the non-numeric portion of a version string via `version-to-list`.
The default value is:

``` emacs-lisp
(("^[-._+ ]?snapshot$" . -4) ("^[-._+]$" . -4)
 ("^[-._+ ]?\\(cvs\\|git\\|bzr\\|svn\\|hg\\|darcs\\)$" . -4)
 ("^[-._+ ]?unknown$" . -4) ("^[-._+ ]?alpha$" . -3) ("^[-._+ ]?beta$" . -2)
 ("^[-._+ ]?\\(pre\\|rc\\)$" . -1))
```

I've augmented it to be more lenient when Elpaca is checking versions.
See the following test case:

<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init
  (setq elpaca-menu-functions '(elpaca-menu-non-gnu-devel-elpa elpaca-menu-gnu-devel-elpa))
  :init
  (elpaca cider)
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>e08996a HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-18</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.dcVyGu/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.dcVyGu/elpaca/repos/elpaca...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.dcVyGu/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
elpaca-log: "#unique"
"
elpaca       finished ✓ 0.618 secs 20.172673
sesman       finished ✓ 0.634 secs 21.012295
spinner      finished ✓ 0.898 secs 21.276923
parseclj     finished ✓ 0.580 secs 21.300089
queue        finished ✓ 1.019 secs 21.398229
parseedn     finished ✓ 1.127 secs 21.505438
clojure-mode finished ✓ 4.413 secs 24.797838
cider        finished ✓ 6.139 secs 25.693851
"

 Test Env

Elpaca e08996a HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2023-12-18
git --version:  git version 2.43.0
```
</details>

The change is live on the master branch. Testing is appreciated.

**Comment by deejayem** [comment]
Thank you for fixing this quickly. After updating elpaca, `elpaca-rebuild` `cider` is successful.

**Comment by progfolio** [comment]
Thanks for taking the time to submit a ticket and testing
