### ISSUE TITLE
[Bug/Support]:

### ISSUE THREAD

**Issue by psionic-k** [progfolio/elpaca#232]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec4befa HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)
git --version:  git version 2.40.1

### Operating System

Linux, NixOS 23.11

### Description

I think this is just FYI at this point because I lost my error logs.   I could not find similar issues before resolving my issue.

My installation got messed up after running update on Elpaca itself.  I believe I attempted to update elpaca-use-package.  On restart, the system was trash, acting like it couldn't find the recipe for elpaca-use-package.

To recover, I tried relying on the bootstrap behavior by deleting both `builds/elpaca-use-package` and `builds/elpaca`, but multiple commits back to June were not satisfied with this and only deleting `repos/elpaca` finally fixed the issues.

I couldn't reproduce this after it got resolved.  Updating `elpaca-use-package` alone seemed to be where things went wrong.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a ticket, but I won't be able to reproduce without more specific information.
If it happens again or you're able to come up with a reproduction recipe feel free to edit this issue and give me a ping.
Glad you got things working again.

**Comment by ispringle** [comment]
FWIW I'm having the same issue this morning. Loaded emacs up and it's not-quite-frozen on the elpaca-log buffer. Two packages have failed to update and the Info column states:
![Screenshot 2024-01-02 at 10 02 27 AM](https://github.com/progfolio/elpaca/assets/18722936/6a3977bc-51d7-45b4-ae81-ca6e6125652e)

I say that it's "not-quite-froze" because I can do a few limited things still while this error is present, but that seems to be limited to hovering with the mouse changing faces or popping up info in the status bar. I can't do anything else.

With `debug-init` I can interact with emacs and it works as expected, minus the error that I get:
```
Debugger entered--Lisp error: (error "Cannot determine URL from recipe: (:source nil :protocol https :inherit t :depth 1 :package \"keychain-environment\")")
  error("Cannot determine URL from recipe: %S" (:source nil :protocol https :inherit t :depth 1 :package "keychain-environment"))
  elpaca-repo-dir((:source nil :protocol https :inherit t :depth 1 :package "keychain-environment"))
  elpaca<-create(keychain-environment)
  elpaca--queue(keychain-environment (elpaca-q init 1 0 incomplete (26004 13324 426512 0) nil ((keychain-environment (keychain-refresh-environment))) nil))
  (progn (elpaca--queue order-3 q-5))
  (if order-3 (progn (elpaca--queue order-3 q-5)))
  (let* ((order-3 'keychain-environment) (id-4 (elpaca--first order-3)) (q-5 (or (and after-init-time (elpaca--q (elpaca-get id-4))) (car elpaca--queues)))) (if id-4 (let* ((cl-x q-5)) (let* ((c (nthcdr 7 cl-x)) (p (assq id-4 (car c)))) (progn (if p (setcdr p '...) (setcar c (cons ... ...))) '((keychain-refresh-environment))))) (let* ((x (cons id-4 '(...))) (cl-x q-5)) (let* ((c (nthcdr 7 cl-x))) (setcar c (cons x (car c)))))) (if order-3 (progn (elpaca--queue order-3 q-5))) (if after-init-time (progn (let* ((e (and t (elpaca-get id-4)))) (if e (progn (elpaca--maybe-log) (elpaca--unprocess e) (let* (...) (let* ... ...))) nil)) (if (member this-command '(eval-last-sexp eval-defun)) (progn (elpaca-process-queues))) (if (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c)) (progn (if elpaca--interactive-timer (progn (cancel-timer elpaca--interactive-timer))) (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues))))) nil)
  load-with-code-conversion("/Users/IPringle/.config/emacs/init.el" "/Users/IPringle/.config/emacs/init.el" t t)
  load("/Users/IPringle/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x24129ba920c443e>) #f(compiled-function () #<bytecode 0xa102718fd609629>) t)
  command-line()
  normal-top-level()
```

I was able to resolve this by updating my sources with `elpaca-update-menus` (I only updated melpa fwiw) and I then was able to restart and elpaca started updating packages and working as expected. I did then get a _warning_ that there was a version mismatch but following the instructions in the [wiki](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#installer-version-mismatch) resolved that.

**Comment by psionic-k** [comment]
> `error "Cannot determine URL from recipe:`

this reflects what I saw at different points.  I also observed updating the menus would fix this issue.  However, once I tried  updating Elpaca itself and restarted, almost no elpaca commands would work.

**Comment by progfolio** [comment]
@ispringle:

> Loaded emacs up and it's not-quite-frozen on the elpaca-log buffer. 
> I say that it's "not-quite-froze" because I can do a few limited things still
> while this error is present, but that seems to be limited to hovering with the
> mouse changing faces or popping up info in the status bar. I can't do anything
> else.

Perhaps the error was signaled during an `elpaca-wait` loop?
I've added a patch which should make that less likely to freeze things.
If you end up in that state again, you can try `C-g` to quit `elpaca-wait`.

> I was able to resolve this by updating my sources with `elpaca-update-menus` (I
> only updated melpa fwiw) and I then was able to restart and elpaca started
> updating packages and working as expected. I did then get a _warning_ that there
> was a version mismatch but following the instructions in the
> [wiki](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#installer-version-mismatch)
> resolved that.

It sounds to me like maybe both you and @psionic-k may have hit this when updating:

https://github.com/progfolio/elpaca/issues/188

I have a plan to add versioning to the cache scheme so Elpaca can detect when it changes (which should be rare) and discard outdated caches automatically.
That might help with this corner case, assuming that's what's happening.
