### ISSUE TITLE
[Bug/Support]:   Warning for early loaded transient

### ISSUE THREAD

**Issue by psionic-k** [progfolio/elpaca#234]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 61c8b9b HEAD, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1.90 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
git --version:  git version 2.42.0

### Operating System

NixOS 23.11 or 23.05
Linux 6.1.61 #1-NixOS SMP PREEMPT_DYNAMIC Thu Nov  2 08:35:33 UTC 2023 x86_64 GNU/Linux

### Description

In reply to: https://github.com/magit/magit/discussions/4997#discussioncomment-8009164

I added the `eval-after-load` to get a debugger and look around.  I could not determine the offending use-package statement from the trace, just a generic `load my-init.el` basically.

In the debugger context, transient is not `feature-p`, the `load-path` doesn't contain transient explicitly, and the `load-history` doesn't contain any evidence that transient is actually loaded.  :man_shrugging: 

I modified the `eval-after-load` to show if it was being loaded twice.  No.

Am I missing something about what I should expect?

**Comment by progfolio** [comment]
Please share the exact test case you're using so we're on the same page here.

**Comment by psionic-k** [comment]
I resolved the issue.  I had a local package that depended on transient but I had set `elpaca: nil` in the use-package expression because the package is in my load path.  

For future readers:
``` elisp
(use-package screencap
  :elpaca nil
  :after transient)
```

This is kind of an edge case, but could use-package still manage the dependencies in that case?

Using `(setq use-package-verbose t)` and `with-eval-after-load` I was able to see the package trigger the load just using messages.

The `with-eval-after-load` workflow did also confirm the situation.  Early I think I had nested the expression by accident, so that's why I couldn't see the loading on the stack.

**Comment by progfolio** [comment]
> This is kind of an edge case, but could use-package still manage the dependencies in that case?

Once `:elpaca nil` is added, you're no longer using Elpaca.
There's nothing I can do in that case other than signal the warning when a package is loaded before it's requested to be activated by Elpaca. So the warning did it's job in this case.

**Comment by psionic-k** [comment]
I suppose the more appropriate way to handle this is to use the local-path style, but it's a bit annoying and verbose when the package is already in the load path.

Should I write something for `elpaca-recipe-functions`?  I'm thinking to translate `:elpaca load` into the explicit load path form.

The package is under version control and in the load path already.

**Comment by progfolio** [comment]
> I suppose the more appropriate way to handle this is to use the local-path style, but it's a bit annoying and verbose when the package is already in the load path.

Can you show me an example of what you mean? I'm not sure I understand.

> Should I write something for elpaca-recipe-functions? I'm thinking to translate :elpaca load into the explicit load path form.

The `:elpaca` keyword is interpreted by the `elpaca-use-package` package. That's before `elpaca-recipe-functions` will have a chance to change the recipe. Once I see an example of what solution  you're aiming for I should be able to help or offer more insight.

**Comment by psionic-k** [comment]
My load path includes a directory called: `~/.emacs.d/var/scratch-pkgs/`

I add this very early in my configuration, just after bootstrapping Elpaca.

There are many of these "scratch" packages". One of the packages, for example, is mandelbrot.  The problem is what if Mandelbrot requires transient?  Right now, I need to do this:

```elisp
(use-package mandelbrot
  :elpaca nil
  :after transient)
```

Because these packages, a new dependency could show up on every restart.  If I try to remember to add new dependencies every time, I will make errors sometimes.  I would prefer to manage the dependencies with Elpaca.

Right now, I'm not even using Elpaca, just loading straight off the load path.  That much is actually fine, even though it's a bit annoying if I needed to write this every time:  `elpaca: (local :repo "~/.emacs.d/var/scratch-pkgs/")`.   

Loading from the load path is fine.  The packages change quickly, and I have autocompile and `load-prefer-newer t` etc.   The highest value would be to handle dependencies for me and to defer the load until those dependencies will be under Elpaca's control.

Some of the dependencies themselves could be local :worried:.

**Comment by progfolio** [comment]
> elpaca: (local :repo "~/.emacs.d/var/scratch-pkgs/")

That's not fine grained enough for Elpaca to know about each individual package and its dependencies.
You could add each package, though. e.g.
Assuming the packages are in their own repositories under scratch-pkgs:

```emacs-lisp
(elpaca (mandlebrot :repo "~/.emacs.d/var/scratch-pkgs/mandlebrot/"))
```

If they're individual files under `.../scratch-pkgs/`:

```emacs-lisp
(elpaca (mandlebrot :repo "path/to/scatch-pkgs/" 
                                     :local-repo "mandlebrot" 
                                     :main "path/to/mandlebrot.el" 
                                     :files ("path/to/mandlebrot.el"))
```

**Comment by psionic-k** [comment]
> Assuming the packages are in their own repositories under scratch-pkgs:  

I've decided to choose this route.

Is there I way I could tell elpaca about several repositories in one directory, like a kind of local package archive?

**Comment by progfolio** [comment]
> Is there I way I could tell elpaca about several repositories in one directory, like a kind of local package archive?

Please provide an example of what you're after and I can help.
