### ISSUE TITLE
[Bug]: Creation of subr--trampoline files in wrong location

### ISSUE THREAD

**Issue by Roger-Roger-debug** [progfolio/elpaca#238]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca ad60abc HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2024-01-01
git --version:  git version 2.41.0
```

### Operating System

Gentoo

### Description

Sorry if this isn't an elpaca issue.

I'm trying to keep my `.config/emacs` clean. To that end I have this snippet in my early-init
```
(startup-redirect-eln-cache emacs-cache-directory)
```
This works for the most part, except sometimes when I'm installing new packages with elpaca I'm getting eln-cache files under `.config/emacs`. For example, I get these after installing evil-numbers
```
eln-cache/
eln-cache/29.1-5d7b03ea/subr--trampoline-726561642d6b65792d73657175656e63652d766563746f72_read_key_sequence_vector_0.eln
eln-cache/29.1-5d7b03ea/subr--trampoline-726561642d6b65792d73657175656e6365_read_key_sequence_0.eln
eln-cache/29.1-5d7b03ea/subr--trampoline-73656c6563742d77696e646f77_select_window_0.eln
eln-cache/29.1-5d7b03ea/subr--trampoline-7365742d77696e646f772d627566666572_set_window_buffer_0.eln
eln-cache/29.1-5d7b03ea/subr--trampoline-7573652d676c6f62616c2d6d6170_use_global_map_0.eln
eln-cache/29.1-5d7b03ea/subr--trampoline-7573652d6c6f63616c2d6d6170_use_local_map_0.eln
```

These files are duplicate and also exist under `.cache/emacs`, where I'd expect them to be.

The same doesn't happen when installing packes with `package-install` and native compilation enabled.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a ticket.

> I'm trying to keep my `.config/emacs` clean. To that end I have this snippet in my early-init
> ```
> (startup-redirect-eln-cache emacs-cache-directory)
> ```
> This works for the most part, except sometimes when I'm installing new packages with elpaca I'm getting eln-cache files under `.config/emacs`. For example, I get these after installing evil-numbers
> ```
> eln-cache/
> eln-cache/29.1-5d7b03ea/subr--trampoline-726561642d6b65792d73657175656e63652d766563746f72_read_key_sequence_vector_0.eln
> eln-cache/29.1-5d7b03ea/subr--trampoline-726561642d6b65792d73657175656e6365_read_key_sequence_0.eln
> eln-cache/29.1-5d7b03ea/subr--trampoline-73656c6563742d77696e646f77_select_window_0.eln
> eln-cache/29.1-5d7b03ea/subr--trampoline-7365742d77696e646f772d627566666572_set_window_buffer_0.eln
> eln-cache/29.1-5d7b03ea/subr--trampoline-7573652d676c6f62616c2d6d6170_use_global_map_0.eln
> eln-cache/29.1-5d7b03ea/subr--trampoline-7573652d6c6f63616c2d6d6170_use_local_map_0.eln
> ```

Interesting. Those are all functions defined at the C level in Emacs (keyboard.c, window.c, keymap.c). And it doesn't look like evil-numbers calls any of them directly.
  
Try evaluating the following test case in your \*scratch\* buffer:

``` emacs-lisp
(elpaca-test
  :ref "fix/eln"
  :interactive t
  :early-init
  (startup-redirect-eln-cache (temporary-file-directory))
  (setq elpaca-menu-functions '(elpaca-menu-non-gnu-devel-elpa))
  :init
  (elpaca evil-numbers (require 'evil-numbers))
  (elpaca-wait))
```

In the test Emacs session, once everything has installed, is there an `eln-cache` in the test user-emacs-directory?

**Comment by Roger-Roger-debug** [comment]
With your snippet my emacs directory stays clean.

**Comment by progfolio** [comment]
> With your snippet my emacs directory stays clean.

Thanks for testing. That's a good sign.
Let's try that branch with your actual set-up now.
Try the following:

1. Edit the `elpaca-order` variable in your init file so `:ref` has the value `"fix/eln"`.
2. Save your init.el.
3. `M-x elpaca-delete evil-numbers` 
4. `M-x elpaca-delete elpaca-use-package` 
5. `M-x elpaca-delete elpaca` 
6. Delete the unwanted `eln-cache` directory under `~/.config/emacs/`
7. `M-x restart-emacs`

   Elpaca should install from the patched "fix/eln" branch.
   evil-numbers should be reinstalled.

8. `M-x load-library evil-numbers`

Is the unwanted `eln-cache` directory created in this case?

9. Please share the output of the help buffer generated by `M-x describe-function` `evil-numbers/dec-at-pt`.

**Comment by Roger-Roger-debug** [comment]
```
evil-numbers/dec-at-pt is an autoloaded interactive native-compiled
Lisp function in ‘evil-numbers.el’.

It is bound to C-x.

(evil-numbers/dec-at-pt AMOUNT BEG &optional END TYPE INCREMENTAL
PADDED)

Decrement the number at point or after point before ‘end-of-line’ by AMOUNT.

If a region is active, decrement all the numbers at a point by AMOUNT.
```

`eln-cache` didn't get created, my `.config/emacs` is still nice and clean. :)

**Comment by progfolio** [comment]
> ```
> evil-numbers/dec-at-pt is an autoloaded interactive native-compiled
> Lisp function in ‘evil-numbers.el’.
> 
> It is bound to C-x.
> 
> (evil-numbers/dec-at-pt AMOUNT BEG &optional END TYPE INCREMENTAL
> PADDED)
> 
> Decrement the number at point or after point before ‘end-of-line’ by AMOUNT.
> 
> If a region is active, decrement all the numbers at a point by AMOUNT.
> ```
> 
> `eln-cache` didn't get created, my `.config/emacs` is still nice and clean. :)

Looks good to me.
I've merged the patch to the "master" branch.
You'll want to:

1. Set the `elpaca-order`'s `:ref` back to `nil` in your init.el file.
2. Save your init file.
3. `M-x elpaca-delete elpaca-use-package`
4. `M-x elpaca-delete elpaca`
5. `M-x restart-emacs`

That should re-install the Elpaca from the master branch and you should be good to go.
Thanks again for testing.

**Comment by Roger-Roger-debug** [comment]
Everything works as expected, thank you!
