### ISSUE TITLE
[Support]:  Working with multiple local repositories

### ISSUE THREAD

**Issue by psionic-k** [progfolio/elpaca#239]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca a7c5333 HEAD -> master, personal/master
installer:      0.6
emacs-version:  GNU Emacs 29.1.90 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
git --version:  git version 2.42.0

### Operating System

Linux chincharillos 6.1.61 #1-NixOS SMP PREEMPT_DYNAMIC Thu Nov  2 08:35:33 UTC 2023 x86_64 GNU/Linux

### Description

I have multiple packages, one repository for each package, stored in:

```
foo/package-a/
foo/package-b/
foo/package-c/
```

These packages are constantly changing because I'm developing things and adding and removing dependencies.  I want to delegate the work to elpaca, resulting in a use-package expression like this working:

```elisp
(use-package package-c)
```

How can I declare foo as a directory full of package repos so that package-a, package-b, and package-c are all available and I don't need to explicitly state their local path or dependencies as I add and remove them?

**Comment by progfolio** [comment]
> I have multiple packages, one repository for each package, stored in:
> 
> ```
> foo/package-a/
> foo/package-b/
> foo/package-c/
> ```
> 
> These packages are constantly changing because I'm developing things and adding
> and removing dependencies. I want to delegate the work to elpaca, resulting in a
> use-package expression like this working:
> 
> ```elisp
> (use-package package-c)
> ```
> 
> How can I declare foo as a directory full of package repos so that package-a,
> package-b, and package-c are all available and I don't need to explicitly state
> their local path or dependencies as I add and remove them?


The most flexible would be to define a menu to provide recipes for the local repositories:

```emacs-lisp
(defvar +local-menu-dir "path/to/foo/")
(defun +local-menu (_)
  "Return menu items for repos under `+local-pkg-dir'."
  (cl-loop
   for dir in (directory-files +local-menu-dir nil "[^.]")
   for path = (file-name-as-directory (expand-file-name dir +local-pkg-dir))
   for pre-build = ;; Explained below.
   `(let ((default-directory ,path))
      (elpaca-with-process-call ("git" "config" "receive.denyCurrentBranch" "updateInstead")
        (or success (error "%s" stderr))))
   collect (cons (intern dir) (list :source "Local Dev"
                                    :description (format "Locally hosted @ %s" path)
                                    :recipe `(:repo ,path :pre-build ,pre-build)))))
```

Then you should be able to add the menu to `elpaca-menu-functions` and update the menu item cache:

```emacs-lisp
(add-to-list 'elpaca-menu-functions #'+local-menu)
(elpaca-update-menus '+local-menu)
```

After that, your recipes should be available:

```emacs-lisp
(use-package 'package-a)
```

Note the `:pre-build` step will alter the git config for the local repo so that you can push from the copy under `elpaca-repos-directory`.
With this workflow it would be best to constrain your one of the two copies.
In this case it probably makes sense to treat the local repository as if it were hosted remotely, and develop from the Elpaca copy, pushing to the original. That would save  you the step of pulling in updates from the original repo.
You could side step this requirement by locally hosting bare repositories for your projects (I've done this myself in the past) or hosting, but that's an exercise I'll leave to the reader.

Does that help?

**Comment by progfolio** [comment]
Here's an illustrative test case.
I have a "testing" repository located at "/tmp/local-pkgs/testing/".


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :ref local
  :init (defvar +local-menu-dir "/tmp/local-pkgs/")
  (defun +local-menu (_)
    "Return menu items for repos under `+local-pkg-dir'."
    (cl-loop for dir in (directory-files +local-menu-dir nil "[^.]") for path =
             (file-name-as-directory (expand-file-name dir +local-menu-dir))
             for
             pre-build
             =
             (` (let ((default-directory (, path)))
                  (elpaca-with-process-call ("git" "config" "receive.denyCurrentBranch"
                                             "updateInstead")
                    (or success (error "%s" stderr)))))
             collect
             (cons (intern dir) (list :source "Local Dev" :description (format
                                                                        "Locally hosted @ %s"
                                                                        path)
                                      :recipe
                                      (` (:package (, dir) :repo (, path) :pre-build
                                                   (,
                                                    pre-build)))))))
  (add-to-list 'elpaca-menu-functions #'+local-menu)
  (elpaca-update-menus '+local-menu)
  (elpaca 'testing)
  (elpaca-wait)
  (with-current-buffer (elpaca-info 'testing)
    (message "%S" (buffer-substring-no-properties (point-min) (point-max)))))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>5b42d5e HEAD -> master, origin/master, origin/HEAD, maybe/no-structs</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.39, cairo version 1.18.0) of 2024-01-04</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-process.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-menu-org.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-menu-melpa.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-menu-elpa.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-log.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-ui.el’ newer than byte-compiled file; using older file
Source file ‘/tmp/elpaca.c3oE2f/elpaca/builds/elpaca/elpaca-info.el’ newer than byte-compiled file; using older file
Indenting region... 
Indenting region...done
Indenting region... 
Indenting region...done
"testing
Locally hosted @ /tmp/local-pkgs/testing/

source: Local Dev
menu item recipe:
( :package \"testing\"
  :repo \"/tmp/local-pkgs/testing/\"
  :pre-build (let ((default-directory \"/tmp/local-pkgs/testing/\"))
	       (elpaca-with-process-call (\"git\" \"config\" \"receive.denyCurrentBranch\"
					  \"updateInstead\") (or success (error \"%s\" stderr))))
  :source \"Local Dev\")
full recipe:
( :package \"testing\"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :source \"Local Dev\"
  :pre-build (let ((default-directory \"/tmp/local-pkgs/testing/\"))
	       (elpaca-with-process-call (\"git\" \"config\" \"receive.denyCurrentBranch\"
					  \"updateInstead\") (or success (error \"%s\" stderr))))
  :repo \"/tmp/local-pkgs/testing/\")
dependencies: nil
dependents: nil
version:  
statuses:
  (finished activation info byte-compilation autoloads linking unblocked pre-build ref-checked-out cloning queued)
files:
  $REPOS/testing/testing.el → $BUILDS/testing/testing.el
log:
  [2024-01-10 12:38:44] Package queued
  [2024-01-10 12:38:44] Continued by: elpaca--process
  [2024-01-10 12:38:44] Cloning
  [2024-01-10 12:38:44] $git clone --depth 1 /tmp/local-pkgs/testing/ /tmp/elpaca.c3oE2f/elpaca/repos/testing/
  [2024-01-10 12:38:44] Cloning into '/tmp/elpaca.c3oE2f/elpaca/repos/testing'...
  [2024-01-10 12:38:44] warning: --depth is ignored in local clones; use file:// instead.
  [2024-01-10 12:38:44] done.
  [2024-01-10 12:38:44] Continued by: elpaca--clone-process-sentinel
  [2024-01-10 12:38:44] Continued by: elpaca--configure-remotes
  [2024-01-10 12:38:44] Continued by: elpaca--checkout-ref
  [2024-01-10 12:38:44] Running :pre-build commands
  [2024-01-10 12:38:44] $/usr/bin/emacs -Q -L ./ -L /tmp/elpaca.c3oE2f/elpaca/builds/elpaca/ --batch --eval (let ((load-prefer-newer t) (gc-cons-percentage 1.0)) (require 'elpaca) (normal-top-level-add-subdirs-to-load-path) (elpaca--run-build-commands '(let ((default-directory \"/tmp/local-pkgs/testing/\")) (elpaca-with-process-call (\"git\" \"config\" \"receive.denyCurrentBranch\" \"updateInstead\") (or success (error \"%s\" stderr))))))
  [2024-01-10 12:38:44] Running command: (let ((default-directory \"/tmp/local-pkgs/testing/\")) (elpaca-with-process-call (\"git\" \"config\" \"receive.denyCurrentBranch\" \"updateInstead\") (or success (error \"%s\" stderr))))
  [2024-01-10 12:38:44] Continued by: elpaca--dispatch-build-commands-process-sentinel
  [2024-01-10 12:38:44] :pre-build steps finished
  [2024-01-10 12:38:44] Continued by: elpaca--queue-dependencies
  [2024-01-10 12:38:44] No external dependencies
  [2024-01-10 12:38:44] Checking dependency versions
  [2024-01-10 12:38:44] Continued by: elpaca--check-version
  [2024-01-10 12:38:44] Linking build files
  [2024-01-10 12:38:44] Continued by: elpaca--link-build-files
  [2024-01-10 12:38:44] Build files linked
  [2024-01-10 12:38:44] Generating autoloads: /tmp/elpaca.c3oE2f/elpaca/builds/testing
  [2024-01-10 12:38:44] $/usr/bin/emacs -Q -L /tmp/elpaca.c3oE2f/elpaca/repos/elpaca/ -l /tmp/elpaca.c3oE2f/elpaca/repos/elpaca/elpaca.el --batch --eval (progn (setq gc-cons-percentage 1.0) (elpaca-generate-autoloads \"testing\" \"/tmp/elpaca.c3oE2f/elpaca/builds/testing\"))
  [2024-01-10 12:38:44]   INFO     Scraping files for loaddefs... 
  [2024-01-10 12:38:44]   INFO     Scraping files for loaddefs...done
  [2024-01-10 12:38:44] Continued by: #[128 \"\\302\\301\\303\\300\\\"\\\"\\207\" [(\"Autoloads Generated\" nil) elpaca--process-sentinel apply append] 6 \"

(fn &rest ARGS2)\"]
  [2024-01-10 12:38:44] Autoloads Generated
  [2024-01-10 12:38:44] Byte compiling
  [2024-01-10 12:38:44] $/usr/bin/emacs -Q --batch --eval (let ((gc-cons-percentage 1.0) (native-comp-eln-load-path '(\"/home/n/.emacs.d/eln-cache/\" \"/usr/lib/emacs/30.0.50/native-lisp/\"))) (dolist (dir '(\"/tmp/elpaca.c3oE2f/elpaca/builds/testing\")) (let ((default-directory dir)) (add-to-list 'load-path dir) (normal-top-level-add-subdirs-to-load-path))) (byte-recompile-directory \"/tmp/elpaca.c3oE2f/elpaca/builds/testing\" 0 'force))
  [2024-01-10 12:38:44] Checking /tmp/elpaca.c3oE2f/elpaca/builds/testing...
  [2024-01-10 12:38:44] Compiling /tmp/elpaca.c3oE2f/elpaca/builds/testing/testing.el...
  [2024-01-10 12:38:44] Done (Total of 1 file compiled)
  [2024-01-10 12:38:44] Continued by: #[128 \"\\302\\301\\303\\300\\\"\\\"\\207\" [(\"Byte compilation complete\" nil) elpaca--process-sentinel apply append] 6 \"

(fn &rest ARGS2)\"]
  [2024-01-10 12:38:44] Byte compilation complete
  [2024-01-10 12:38:44] Compiling Info files
  [2024-01-10 12:38:44] Continued by: elpaca--compile-info
  [2024-01-10 12:38:44] Info source files not found
  [2024-01-10 12:38:44] Continued by: elpaca--dispatch-build-commands
  [2024-01-10 12:38:44] Activating package
  [2024-01-10 12:38:44] Package build dir added to load-path
  [2024-01-10 12:38:44] Continued by: elpaca--activate-package
  [2024-01-10 12:38:44] ✓ 0.209 secs
"

 Test Env

Elpaca 5b42d5e HEAD -> master, origin/master, origin/HEAD, maybe/no-structs
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.39, cairo version 1.18.0)
 of 2024-01-04
git --version:  git version 2.43.0
```
</details>

**Comment by psionic-k** [comment]
> In this case it probably makes sense to treat the local repository as if it were hosted remotely, and develop from the Elpaca copy, pushing to the original. That would save you the step of pulling in updates from the original repo.
You could side step this requirement by locally hosting bare repositories for your projects (I've done this myself in the past), but that's an exercise I'll leave to the reader.

It is a dilemma for sure.  There is no way to protect people from forgetting everything:
* If they treat the elpaca repos as if they are a cache they blow away dirty trees.  
* If they treat the source repos like they automatically install, they get stale packages.  

I think it's just an unavoidable educational moment :sweat_smile:

I will close this after I can test it out more.  Looks sound.  The bit about pushing back to the local repo was helpful.  I hadn't run into that issue in a while.

**Comment by progfolio** [comment]
> It is a dilemma for sure. 

I don't think this will be a common use case, so it shouldn't be an issue for many people.

> I will close this after I can test it out more. Looks sound. 

I'm closing the issue, but feel free to post here if you run into a trouble with what I suggested.

> The bit about pushing back to the local repo was helpful. I hadn't run into that issue in a while.

Yes, it'd be better to use a bare repo, even if it's stored locally, but that's not Elpaca specific.

**Comment by psionic-k** [comment]
I want to try another approach, telling Elpaca to symlink the dirty repo into place.  While this is of course bad for purity and reproducibility, i don't think it can be beaten in terms of convenience and simplicity.

Can this be done without creating issues for Elpaca?

My concern for using local bare repos is that if you `elpaca-delete` accidentally, potentially you killed dirty changes with no backup.

**Comment by progfolio** [comment]
> Can this be done without creating issues for Elpaca?

Yes. It would involve creating custom build steps which do the symlinking and adjusting each recipe's `:build` accordingly. That's an exercise for the reader.

> My concern for using local bare repos is that if you `elpaca-delete` accidentally, potentially you killed dirty changes with no backup.

That concern has little to do with bare repos. The risk is there no matter what if the repos only exist locally.

**Comment by progfolio** [comment]
> I didn't symlinks working because Elpaca was confused about cloning a repo that didn't have any commits yet.

You would want to replace the elpaca--clone build step with a step that symlinks the directory for those recipes.

> and pushed to the remote on github 

If the packages are hosted on github, why not clone directly from there?

> forgot to rebuild before next Emacs restart.

There's a WIP branch for a file watcher which will record when package's have been changed:

https://github.com/progfolio/elpaca/compare/master...feat/watcher

It would need to be tied into the startup process, but it could be arranged so that packages are automatically rebuilt.

> I miss elpaca-update and will add this command back in for my personal use, to fetch , merge, and build in one command.

Pass a prefix arg to `elpaca-merge`.

**Comment by psionic-k** [comment]
> If the packages are hosted on github, why not clone directly from there?

The usual progression is local development and then github.  I'm creating a solution to bridge the gap and then result in the same workflow for private packages and public ones.

**Comment by psionic-k** [comment]
> You would want to replace the elpaca--clone build step

By adding a recipe key or by temporarily decorating the `elpaca--clone` function?

**Comment by progfolio** [comment]
> > You would want to replace the elpaca--clone build step
> 
> By adding a recipe key or by temporarily decorating the `elpaca--clone`
> function?

By defining a build step function.
It would take an elpaca struct as its sole argument.
e.g.

``` emacs-lisp
(defun my-build-step (e)
  "Do something with E."
  (let ((repo (elpaca<-repo-dir e)))
    ;;etc
    (if some-error (elpaca--fail e "Because of the error")
      (elpaca--continue-build e))))
```

Then you would replace the build steps it replaces via the recipe's :build keyword.
The syntax for that would is an area I plan on improving, but you can find examples in other issues like #216

I would go with whatever is the simplest solution.
