### ISSUE TITLE
[Support]: cannot find ./elpaca-autoloads on fresh install when elpaca directory synced between two machines

### ISSUE THREAD

**Issue by tokisuno** [progfolio/elpaca#244]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

installer 0.6

### Operating System

arch linux

### Description

I get the following error when opening Emacs on my desktop:

An error occurred while loading ~/.config/emacs/init.el

file is missing: cannot open load file, no such file or dir ./elpaca-autoloads

This is off of a fresh install of emacs loading my dots for the first time. It is symlinked to a shared dir between my desktop and laptop (through syncthing) so my dots are insync.

**Comment by tokisuno** [comment]
It just didn't save my description. Awesome. 

I get the following error when opening Emacs on my desktop:

An error occurred while loading ~/.config/emacs/init.el

file is missing: cannot open load file, no such file or dir ./elpaca-autoloads

This is off of a fresh install of emacs loading my dots for the first time. It is symlinked to a shared dir between my desktop and laptop (through syncthing) so my dots are insync.

**Comment by tokisuno** [comment]
edit: fixed formatting

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket. I'll need more information to help you.

> It is symlinked to a shared dir between my desktop and laptop (through syncthing) so my dots are insync.

I'm not sure what the "it" is here. What files specifically are synced?

Please also include directory listings of the files under `elpaca-repos-directory`/elpaca and `elpaca-builds-directory`/elpaca.

**Comment by tokisuno** [comment]
> If you have your dotfiles uploaded somewhere, a link to them would help as well.

I have my dots uploaded but without my emacs atm. I will push that rn. By it, I mean my ~/.config/emacs/ folder.

> Please also include directory listings of the files under elpaca-repos-directory/elpaca and elpaca-builds-directory/elpaca.

How would I go about doing this step?

**Comment by tokisuno** [comment]
https://github.com/tokisuno/.dotfiles/tree/main/.config/emacs here are my emacs dots

**Comment by progfolio** [comment]
Elpaca installs repositories and builds packages relative to it's base directory.
The directory should be set before the installer script is run.
For example, in your configuration the following variables are set before the installer:

```emacs-lisp
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
```

Note the `elpaca-directory` is defined relative to `user-emacs-directory`.
That's usually "~/.emacs.d/" or "~/.config/emacs.d/" depending on how you have it set up.

So I'm interested in the following output from a terminal on the machine where you're seeing the error (I'm assuming the first user-emacs-directory in the examples, adjust to fit your settings):

```shell
ls -lah ~/.emacs.d/elpaca/repos/elpaca
```

and

```shell
ls -lah ~/.emacs.d/elpaca/builds/elpaca
```

**Comment by tokisuno** [comment]
Oh I should have pointed this out earlier: I run emacs as "emacs --init-directory ~/.config/emacs" in order to force my .config dots, as I was running into problems with that previously. I don't have .emacs.d symlinked. 

Would that make a difference?

**Comment by progfolio** [comment]
> I think we found the culprit here.

Indeed. I don't think your setup will work due to the symlinks not being updated.
The "build" directory isn't really meant to be persisted, so you can exclude that from syncing and allow Elpaca to rebuild things on the target machine. Removing `elpaca-builds-directory` and restarting Emacs should get things building.

**Comment by tokisuno** [comment]
Since this syncs an entire dir from a symlink, I don't really know how I would go about doing this. 

My .dotfiles folder has a .config folder where all my symlinks live, which is how I sync everything. Would you have any suggestions?

**Comment by progfolio** [comment]
I wouldn't sync the elpaca directory. That should be rebuilt from your init.el file on each machine. I suppose you could sync the repos, but the build directories I would skip. The byte-compiled files aren't guaranteed across Emacs versions.

**Comment by progfolio** [comment]
If you still need help with this feel free to comment and we can reopen the issue.
Thanks.
