### ISSUE TITLE
[Bug/Support]:

### ISSUE THREAD

**Issue by Abdulsarhan** [progfolio/elpaca#246]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 13dc968 HEAD -> master, origin/master, origin/HEAD
installer: 0.6
emacs-version: GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.40, cairo version 1.18.0
git --version: git version 2.43.0

### Operating System

Arch Linux x86_64
Kernel: 6.7.1-arch1-1

### Description

When I start emacs, I get a warning that says "Warning (emacs): Unable to determine elpaca-core-date"
This didn't used to happen before, the only things that could have changed were my version of emacs since I update emacs regularly because I am on a rolling release distro and elpaca, because I update elpaca regularly as well.

**Comment by progfolio** [comment]
Should go away if you `M-x elpaca-update elpaca` followed by `M-x restart-emacs`. Let me know if that works.

**Comment by Abdulsarhan** [comment]
> Should go away if you `M-x elpaca-update elpaca` followed by `M-x restart-emacs`. Let me know if that works.

elpaca-update doesn't even show up when I hit M-x. The only thing that shows up is elpaca-update-menus.

**Comment by Abdulsarhan** [comment]
Okay, C-u M-x elpaca-merge elpaca doesn't show up as an option for me. BUT I did C-u M-x elpaca-merge-all and that fixed it. Thanks!
