### ISSUE TITLE
[Bug/Support]: Some dependencies not being updated or pulled in for magit/hyperdrive/transient

### ISSUE THREAD

**Issue by titanofold** [progfolio/elpaca#248]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca cd5d91f HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-11-14
git --version:  git version 2.41.0
```

### Operating System

Windows 11 WSL

### Description

A few months ago, trying to install hyperdirve complained about transient not being present, so I had to add `(use-package transient)` to satisfy that dependency. Now transient is complaining about `seq` not being recent enough.

I'm betting adding another `use-package` would work around this issue

```
Package                        Status               Info                                                                             Time v
transient                      failed               Requires seq minimum version: 2.24                                               00.116980
hyperdrive                     failed               Failed dependencies: (transient)                                                 00.121101
magit                          failed               Failed dependencies: (transient)                                                 00.131146
```

**Comment by progfolio** [comment]
seq.el is a builtin package. You can install the development version to satisfy the min requirement for transient. Please see: https://github.com/progfolio/elpaca/issues/216

**Comment by titanofold** [comment]
> seq.el is a builtin package. You can install the development version to satisfy the min requirement for transient. Please see: #216

Thanks! The solution given there did the trick.

**Comment by progfolio** [comment]
Glad you got it working. Thanks.
