### ISSUE TITLE
[Bug]: Cannot clone org 

### ISSUE THREAD

**Issue by jleechpe** [progfolio/elpaca#25]
### Emacs Version

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

### Operating System

Arch Linux

### Bug Description

Org fails to clone after change in ded0a70

The org recipe is a full url to git repository on savannah.  The change to expand-file-name if host is not set breaks this by prefixing the url with the current directory.

Reverting to d7d887a allows the clone to work again.

This likely also affects org-contrib since the recipe is a full url for the repo rather than host + repo.

**Comment by progfolio** [comment]
Sorry about that and thank you for the report.
Should be fixed via 05e1a1c.
You can update Elpaca via the `elpaca-update` command followed by restarting Emacs.
Testing is appreciated.

**Comment by jleechpe** [comment]
That fixed the `org` package.  Thanks.

Strangely I needed to delete the `build/elpaca` and `repos/elpaca` directories because `elpaca` and `elpaca-process-queues` were not defined (I didn't think to grab a screenshot) and have it rebuild elpaca while restarting

**Comment by progfolio** [comment]
> Strangely I needed to delete the build/elpaca and repos/elpaca directories because elpaca and elpaca-process-queues were not defined (I didn't think to grab a screenshot) and have it rebuild elpaca while restarting

Interesting. It's possible something went wrong when Elpaca was updating itself.
If it happens again feel free to open another issue.
Thanks again for reporting/testing.
