### ISSUE TITLE
[Feature]: Quickly update package and load its features?

### ISSUE THREAD

**Issue by benthamite** [progfolio/elpaca#250]
### Feature Description

I often find myself wanting to update to the latest version of a package and load all of its features. Currently, this involves executing the following steps:

1. `M-x elpaca-fetch RET <package>`
2. `M-x elpaca-merge RET <package>`
3.1. `M-x load-library RET <feature 1>`
3.2.  `M-x load-library RET <feature 2>`
3.n.  `M-x load-library RET <feature n>` (where `n` is the number of features provided by the package)

Alternatively, one can run steps (1) and (2) and then restart Emacs.

I wonder if support could be provided for a command that does (1–3) in one go, without the need to restart. I understand that you want users to review fetched changes before merging them, but in certain contexts the user doesn’t need to do this. For example, if it’s a package developed by the user or an internal “package” for the user’s organization. (Both of these examples apply to my own case.)

(Incidentally, the [Quick Start](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#quick-start) section of the manual is outdated: it lists the obsolete commands `elpaca-update` and `elpaca-update-all`.)

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> ### Feature Description
> 
> I often find myself wanting to update to the latest version of a package and
> load all of its features. Currently, this involves executing the following
> steps:
> 
> 1. `M-x elpaca-fetch RET <package>`
> 2. `M-x elpaca-merge RET <package>` 3.1. `M-x load-library RET <feature 1>` 3.2.
> `M-x load-library RET <feature 2>` 3.n. `M-x load-library RET <feature n>`
> (where `n` is the number of features provided by the package)
> 
> Alternatively, one can run steps (1) and (2) and then restart Emacs.
> 
> I wonder if support could be provided for a command that does (1–3) in one go,
> without the need to restart. I understand that you want users to review fetched
> changes before merging them, but in certain contexts the user doesn’t need to do
> this. For example, if it’s a package developed by the user or an internal
> “package” for the user’s organization. (Both of these examples apply to my own
> case.)
> 
> (Incidentally, the [Quick
> Start](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#quick-start)
> section of the manual is outdated: it lists the obsolete commands
> `elpaca-update` and `elpaca-update-all`.)

Thanks for taking the time to fill out a feature request.
I added the elpaca-pull and elpaca-pull-all (aliased to elpaca-update and elpaca-update-all) a few days ago in 6a0d6390051c2935557bd12a1334811ef575891a.
Updating should give you access to those commands.

As far as reloading libraries goes, I'm not sure I want to officially support that or not.
Reloading a package is tricky because there's no way to know what state should be persisted or discarded between loads. Simply calling `load` on all the files providing features may work for some simple packages (I'm pretty sure that's what package.el does), but it's not guaranteed.

Alphapapa has a function which forcefully reloads package features:

https://github.com/alphapapa/unpackaged.el?tab=readme-ov-file#reload-a-packages-features


Modifying it slightly could work for Elpaca:

``` emacs-lisp
(defun +elpaca-reload-package (package &optional allp)
  "Reload PACKAGE's features.
If ALLP is non-nil (interactively, with prefix), load all of its
features; otherwise only load ones that were already loaded.

This is useful to reload a package after upgrading it.  Since a
package may provide multiple features, to reload it properly
would require either restarting Emacs or manually unloading and
reloading each loaded feature.  This automates that process.

Note that this unloads all of the package's symbols before
reloading.  Any data stored in those symbols will be lost, so if
the package would normally save that data, e.g. when a mode is
deactivated or when Emacs exits, the user should do so before
using this command."
  (interactive
   (list (let ((elpaca-overriding-prompt "Reload package: "))
           (elpaca--read-queued))
         current-prefix-arg))
  ;; This finds features in the currently installed version of PACKAGE, so if
  ;; it provided other features in an older version, those are not unloaded.
  (when (yes-or-no-p (format "Unload all of %s's symbols and reload its features? " package))
    (let* ((package-name (symbol-name package))
           (package-dir (file-name-directory
                         (locate-file package-name load-path (get-load-suffixes))))
           (package-files (directory-files package-dir 'full (rx ".el" eos)))
           (package-features
            (cl-loop for file in package-files
                     when (with-temp-buffer
                            (insert-file-contents file)
                            (when (re-search-forward (rx bol "(provide" (1+ space)) nil t)
                              (goto-char (match-beginning 0))
                              (cadadr (read (current-buffer)))))
                     collect it)))
      (unless allp
        (setf package-features (seq-intersection package-features features)))
      (dolist (feature package-features)
        (ignore-errors
          ;; Ignore error in case it's not loaded.
          (unload-feature feature 'force)))
      (dolist (feature package-features)
        (require feature))
      (when package-features
        (message "Reloaded: %s" (mapconcat #'symbol-name package-features " "))))))
```

You could add something like that to your config and see how it works.
Does that help?

**Comment by progfolio** [comment]
> Great, thanks so much!

You're welcome.

> It might be useful to add this to the Wiki. Happy to do that.

Feel free to add a page for it.

**Comment by benthamite** [comment]
[Done](https://github.com/progfolio/elpaca/wiki/Reloading-a-package%E2%80%99s-features-after-updating-a-package).
