### ISSUE TITLE
[Bug/Support]: Warning elpaca-core-date and Elpaca log popups

### ISSUE THREAD

**Issue by ddoherty03** [progfolio/elpaca#252]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca f19f4db HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2024-01-25
git --version:  git version 2.34.1
```

### Operating System

```
LSB Version:	core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

### Description

I have recently started getting the following warning on every start-up:
```
Warning (elpaca): Emacs 29.2.50 assigned 29.2 elpaca-core-date.
```
I have not been able to find anything online about it, and it's a pretty recent issue. 

Also, and probably unrelated, on every startup, elpaca pops up two log windows but shows no failures and apparently all successes.  Is there a way to suppress these?

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> I have recently started getting the following warning on every start-up:
> ```
> Warning (elpaca): Emacs 29.2.50 assigned 29.2 elpaca-core-date.
> ```
> I have not been able to find anything online about it, and it's a pretty recent issue. 
  
29.2.50 is a development version of Emacs, so the release date can't automatically determined. The warning can be suppressed (there should be a button to the left of the warning which allows this), or `elpaca-core-date` can be manually set as described on the [wiki page for warnings and errors](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#unable-to-determine-elpaca-core-date).

> Also, and probably unrelated, on every startup, elpaca pops up two log windows
> but shows no failures and apparently all successes. Is there a way to suppress
> these?

Please open a separate ticket for this and include a link to your init files.
I'll be happy to look into it.

**Comment by progfolio** [comment]
Closing, as the core-date issue should be taken care of. If not feel free to ping this and I can look into it more. Thanks.

**Comment by montchr** [comment]
FYI @progfolio I'm seeing the core-date issue again (not OP, but still). I hadn't seen it in a while, but I noticed that my Nix-built Emacs is now reporting a version of 29.3:

```
Elpaca f554ad4 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 1, aarch64-unknown-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
git --version:  git version 2.44.0
```

Let me know if I should open a separate issue about this.

**Comment by progfolio** [comment]
chris montgomery ***@***.***> writes:

> FYI @progfolio I'm seeing the core-date issue again (not OP, but 
> still). I hadn't seen it in a
> while, but I noticed that my Nix-built Emacs is now reporting a 
> version of 29.3:
>
> Elpaca f554ad4 grafted, HEAD -> master, origin/master, 
> origin/HEAD
> installer:      0.7
> emacs-version:  GNU Emacs 29.3 (build 1, 
> aarch64-unknown-linux-gnu, GTK+ Version 3.24.41, cairo version 
> 1.18.0)
> git --version:  git version 2.44.0
>
> Let me know if I should open a separate issue about this.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

29.3 was released about 11 hours ago.
I've added a core date for it.
Warning should go away after `M-x elpaca-pull elpaca` followed by 
`M-x restart-emacs`.
Let me know if that works for you.
