### ISSUE TITLE
[Bug/Support]: Auctex Vertico cyclic-function-indirection error

### ISSUE THREAD

**Issue by jsperger** [progfolio/elpaca#254]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca f19f4db HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.2 (build 2, x86_64-suse-linux-gnu, GTK+ Version 3.24.39, cairo version 1.18.0)
git --version:  git version 2.43.0
```

### Operating System

OS: openSUSE Tumbleweed x86_64
Kernel: 6.7.2-1-default
WM: sway

### Description

Vertico completion fails when the auctex package is also installed. Asking for completions fails with a ` cyclic-function-indirection` error. I'm not positive this is an elpaca error, but I briefly tested this in vanilla emacs with the auctex package from Melpa + vertico, and I didn't get any errors. 

### Steps to Reproduce 
```
(elpaca-test
  :interactive t
  :init
  (elpaca elpaca-use-package (elpaca-use-package-mode))
  (elpaca-wait)

  (use-package auctex :defer t
    :elpaca (:pre-build (("./autogen.sh")
                    ("./configure"
                     "--without-texmf-dir"
                     "--with-packagelispdir=./"
                     "--with-packagedatadir=./")
                    ("make"))
        :build (:not elpaca--compile-info) ;; Make will take care of this step
        :files ("*.el" "doc/*.info*" "etc" "images" "latex" "style")
        :version (lambda (_) (require 'tex-site) AUCTeX-version)))
  (elpaca-wait)
  
  (use-package vertico
    :elpaca t)
)
```
In the interactive test hit `M-x` and then `tab` (would normally show vertico completions)

### Backtrace
```
Debugger entered--Lisp error: (cyclic-function-indirection ConTeXt-mode)
  commandp(ConTeXt-mode)
  #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>)(ConTeXt-mode)
  #f(compiled-function (sym) #<bytecode 0x43bbe7234e5d655>)(ConTeXt-mode)
  all-completions("" [## 0 pr-ps-file-preview timer-next-integral-multiple-of-time otama dashboard-ls 0 ivy-explorer backquote-listify sgml-mode find-sibling-rules :expires cpp-parse-edit url-cookie-p zmq font-lock-syntactically-fontified znc uniquify-rename-buffer kind-icon 0 files--splice-dirname-file raw-text-dos lisp-mode-map ert-run-tests-batch 0 viscii elpaca--repo-type search-emacs-glossary Regexp\ Isearch\ Marked\ Buffers... min-width-safe nexus elpaca-q-p--cmacro :mac byte-set-marker BibTeX-auto-store nswbuff 0 yank-undo-function sort-coding-systems-predicate 0 use-package-handler/:interpreter 0 0 slot-unbound :match byte-compile-arglist-signatures-congruent-p vc-mode-line-hook latexdiff c-name puny-encode-digit ...] #f(compiled-function (sym) #<bytecode 0x43bbe7234e5d655>))
  complete-with-action(t [## 0 pr-ps-file-preview timer-next-integral-multiple-of-time otama dashboard-ls 0 ivy-explorer backquote-listify sgml-mode find-sibling-rules :expires cpp-parse-edit url-cookie-p zmq font-lock-syntactically-fontified znc uniquify-rename-buffer kind-icon 0 files--splice-dirname-file raw-text-dos lisp-mode-map ert-run-tests-batch 0 viscii elpaca--repo-type search-emacs-glossary Regexp\ Isearch\ Marked\ Buffers... min-width-safe nexus elpaca-q-p--cmacro :mac byte-set-marker BibTeX-auto-store nswbuff 0 yank-undo-function sort-coding-systems-predicate 0 use-package-handler/:interpreter 0 0 slot-unbound :match byte-compile-arglist-signatures-congruent-p vc-mode-line-hook latexdiff c-name puny-encode-digit ...] "" #f(compiled-function (sym) #<bytecode 0x43bbe7234e5d655>))
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55>("" #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>) t)
  completion-pcm--all-completions("" (point) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>))
  completion-basic-all-completions("" #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>) 0)
  #f(compiled-function (style) #<bytecode -0x1394c290652fd6fc>)(basic)
  completion--some(#f(compiled-function (style) #<bytecode -0x1394c290652fd6fc>) (basic partial-completion emacs22))
  completion--nth-completion(2 "" #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>) 0 (metadata (affixation-function . read-extended-command--affixation) (category . command)))
  completion-all-completions("" #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>) 0 (metadata (affixation-function . read-extended-command--affixation) (category . command)))
  minibuffer-completion-help(5 5)
  completion--do-completion(5 5)
  completion--in-region-1(5 5)
  #f(compiled-function (start end collection predicate) #<bytecode -0x9590ba601d4e2b7>)(5 5 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>))
  apply(#f(compiled-function (start end collection predicate) #<bytecode -0x9590ba601d4e2b7>) (5 5 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>)))
  #f(compiled-function (funs global args) #<bytecode -0xf5229f58a47ce2>)(nil nil (5 5 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>)))
  completion--in-region(5 5 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>))
  completion-in-region(5 5 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>))
  minibuffer-complete()
  funcall-interactively(minibuffer-complete)
  command-execute(minibuffer-complete)
  completing-read-default("M-x " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> #f(compiled-function (sym) #<bytecode 0x129a4799b2db9d5d>) t nil extended-command-history nil nil)
  read-extended-command-1("M-x " nil)
  read-extended-command()
  byte-code("\302\30\11\303 \10)E\207" [execute-extended-command--last-typed current-prefix-arg nil read-extended-command] 3)
  command-execute(execute-extended-command)
```

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> Vertico completion fails when the auctex package is also installed. Asking for
> completions fails with a ` cyclic-function-indirection` error.

It looks like this type of error can happen when a symbol's function cell is being looked up:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Function-Indirection.html


> I'm not positive this is an elpaca error, but I briefly tested this in vanilla emacs with the
> auctex package from Melpa + vertico, and I didn't get any errors.

I would be surprised if it's an Elpaca bug, as Elpaca does not touch any function symbols or define any aliases in packages.
The only avenue I can think of is if there is something strange going on with the autoloads files that are generated.
However, these are generated by the same Emacs mechanisms package.el uses.
  
> ### Steps to Reproduce 
> [...]
> In the interactive test hit `M-x` and then `tab` (would normally show vertico completions)

I tried the steps you have listed above in addition to enabling one of either ConTeXt-mode or vertico-mode and then attempting tab completion.
I was unable to reproduce the error on both Emacs 30.0.50 and Emacs 29.2.
Are there any other steps I'm missing?

I would `M-x elpaca-log` and [search](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#searching) for something like "warn|err" to see if there are any warnings or errors.
Especially for Auctex, which has a more complicated pre-build than most packages.
If there are please share them here.

It would also be useful to see the autoloads file at `$ELPACA-DIR/builds/auctex/auctex-autoloads.el` (may be named something similar, but whatever *-autoloads.el files are there would be useful to see).

**Comment by jsperger** [comment]
Thanks for taking the time to check, I thought it was unlikely but was starting to go a little crazy and wasn't sure where else to ask. The problem went away after I removed emacs from my package manager (looked like there were two versions in there emacs and emacs-nox)  and rebuilt from source.

**Comment by progfolio** [comment]
Just an FYI, I came across a package.el user with a similar complaint today: https://www.reddit.com/r/emacs/comments/1amdcd0/how_do_i_figure_out_which_updated_package_breaks/kpkzwa0/

Probably an issue upstream with Auctex.

**Comment by progfolio** [comment]
Documenting here in case anyone else runs into this.
Apparently this is a known issue upstream:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-02/msg00748.html
