### ISSUE TITLE
[Support]: elpaca-use-package warnings about keyword converted to :ensure

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#255]
Elpaca's use-package integration will now convert the `:elpaca` and `:straight` recipe keywords to `:ensure`.
To prevent warnings about this, replace those keywords with `:ensure` in your configuration file.
Likewise, replace the  `elpaca-use-package-by-default` variable with  `use-package-always-ensure`.

**Comment by deejayem** [comment]
Changing `:elpaca` to `:ensure` in my config worked fine. However, if I remove `(setq elpaca-use-package-by-default t)`, I run into problems (I already had `(setq use-package-always-defer t)`).

Without `elpaca-use-package-by-default` set, it seems that at least some things aren't being loaded. E.g. the modeline package I use isn't loaded, and when I try to use perspective, I get `Cannot open load file: No such file or directory, perspective` (and similar errors for consult and a few other packages I tried to test).

So either it's some quirk of my config, or `elpaca-use-package-by-default` is still needed.

```
Elpaca b02f119 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-apple-darwin23.2.0, Carbon Version 170 AppKit 2487.3)
git --version:  git version 2.43.0
```

**Comment by IceAsteroid** [comment]
Any corresponding documentation for this? How can I disable elpaca in the use-package section of a package if it doesn't need to use elpaca to download it?

**Comment by progfolio** [comment]
> Any corresponding documentation for this?

There is a [use-package integration](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#use-package-integration) section in the manual.

> How can I disable elpaca in the use-package section of a package if it doesn't need to use elpaca to download it?

The last example in that section shows how to do that (by adding `:ensure nil`).

**Comment by IceAsteroid** [comment]
Thank you, I was too quick to ask the question, sorry, my post has just been edited for that.

**Comment by IceAsteroid** [comment]
Another considerably stupid question by me. Just before I could use ":elpaca nil" to not let elpaca take control to download & install a package like eglot, since the melpa build had always failed.

By disabling elpaca that way, the use-package would automatically select the package in gnu repo. It became not as a problem back then, so I didn't ask for that.

Now, I always want to set the ":ensure" keyword specifically for use-package, while also wanting to let elpaca use the gnu repo?

The documentation doesn't obviously talk about this, what I've already seen is about how to set up repo for github or gitlab, but not examples for gnu and nongnu repos.

**Comment by progfolio** [comment]
> By disabling elpaca that way, the use-package would automatically select the package in gnu repo.

If you're trying to use package.el and Elpaca at the same time, that's not something I plan on supporting.
That said there's nothing stopping one from disabling/enabling `elpaca-use-package-mode` as they see fit.

> Now, I want to set the ":ensure" keyword specifically for some packages' use-package sections, while also wanting to let elpaca use the gnu repo, to try to install packages that have this issue and see if it works.

Elpaca provides a menu for GNU/Non-GNU Elpa.
If you're having trouble installing a specific package, please open a separate issue (if it hasn't already been covered in a previous issue) for that package.

**Comment by o0nd7ots** [comment]
For the confused: please read the https://github.com/progfolio/elpaca/commit/7c6f306779234a8b2cfdde28175609fb4c42eaf8 commit message.
