### ISSUE TITLE
[Bug]: Package TAB completion is inconvenient when using default minibuffer completion

### ISSUE THREAD

**Issue by danielmartin** [progfolio/elpaca#257]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 325060c HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.2 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646))
 of 2024-01-18
git --version:  git version 2.42.0

### Operating System

macOS 14.2.1

### Description

When using the `elpaca-info` command (and possibly others) with the default minibuffer completion in Emacs, two things could be fixed or improved:

- You need to enter the complete name of the package, including its description. This is inconvenient. I suggest perhaps adding the package description as a completion annotation, so that it is excluded from TAB completion (search for `annotation-function` in the Elisp manual).
- If you enter an incomplete name, or a package that doesn't exist, Emacs errors with `funcall-interactively: Wrong number of arguments: (1 . 2), 0`.

**Comment by progfolio** [comment]
> - You need to enter the complete name of the package, including its description.
>   This is inconvenient. I suggest perhaps adding the package description as a
>   completion annotation, so that it is excluded from TAB completion (search for
>   `annotation-function` in the Elisp manual).
> - If you enter an incomplete name, or a package that doesn't exist, Emacs errors
>   with `funcall-interactively: Wrong number of arguments: (1 . 2), 0`.

Agreed on both points.
I've had a long standing TODO to fix these.
The descriptions are included via annotations now.
Completion only needs to be done on the package name and source.
Matches are also required, which should prevent the wrong number of arguments error.

Testing is appreciated (`M-x elpaca-update`, `M-x restart-emacs`, `M-x elpaca-info`).
Let me know if that works for you.

**Comment by danielmartin** [comment]
>
> Testing is appreciated (`M-x elpaca-update`, `M-x restart-emacs`, `M-x elpaca-info`).
> Let me know if that works for you.

Works very well, thank you!

**Comment by progfolio** [comment]
Glad to hear it. Thanks for testing.
