### ISSUE TITLE
[Support]: automatically rebuilding packages

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#26]
Is this the correct way to tell Elpaca to rebuild a package on every init?

```emacs-lisp 
(add-hook 'elpaca-after-init-hook (lambda () (elpaca-rebuild 'my-package t)))
```

_Originally posted by @suconakh in https://github.com/progfolio/elpaca/issues/22#issuecomment-1299769837_

**Comment by progfolio** [comment]
I would not recommend doing it that way.
`elpaca-after-init-hook` will run after the package has already been loaded. So you will end up with the older version of the package loaded despite the rebuild. It's also wasteful in that it will rebuild no matter whether the package has changed or not. Another approach is to add a [file](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) or [per-directory](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) variable which rebuilds the package when it is saved.

For example:

```emacs-lisp
(add-hook 'after-save-hook
          (defun my/rebuild (interactive) (elpaca-rebuild 'example))
          nil 'local)
```

**Comment by suconakh** [comment]
This will work for me, thanks!
