### ISSUE TITLE
[Bug/Support]: Dependency error when using magit

### ISSUE THREAD

**Issue by Doomwhite** [progfolio/elpaca#265]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

0.6

### Operating System

Windows 10(21.H2 19044.3086)

### Description

For some reason, when downloading the magit package, I get dependency errors, even when I don't even use dash in my config.
![image](https://github.com/progfolio/elpaca/assets/40442835/d8e4a8c1-6479-4c12-b138-80b03edfdbe2)
This is my magit related code:
```
(use-package magit
  :commands magit-status)

(use-package treemacs-magit
  :after (treemacs magit)
  :ensure t)
```
I've tried using :after dash, removing the ':commands' part, commenting the treemacs part. 
The only fix is removing magit from my config for it to work.
TBH, I'm not even sure this is an Elpaca issue, just trying to find the root cause.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.
Could you please share the output of `M-x elpaca-version`?

**Comment by Doomwhite** [comment]
![image](https://github.com/progfolio/elpaca/assets/40442835/309dbf32-ba81-4ec7-a479-6c8d929edc6f)

**Comment by progfolio** [comment]
It looks like git is not able to print the date for those dependencies correctly.
Try this:

1. Get the directory for dash's repository via `M-x elpaca-info` `dash`.
    It should be listed in the files section and something similar to `~/.emacs.d/elpaca/repos/dash`. It will likely be different since you're on Windows, though.
    
2. With a terminal, navigate to that directory.
3. In that directory run the following git command and share (as text please, no screenshots) the full output:

```shell
git log -n 1 --format=%cd --date=format:%Y%m%d.%s
```

**Comment by Doomwhite** [comment]
The first try resulted in this:
![image](https://github.com/progfolio/elpaca/assets/40442835/c41ff14b-de93-42e1-9239-3834f317033e)

The second one returned nothing:
```
PS C:\Users\DooMWhite> cd C:\Users\DooMWhite\.config\emacs\elpaca\repos\dash
PS C:\Users\DooMWhite\.config\emacs\elpaca\repos\dash> git log -n 1 --format=%cd --date=format:%Y%m%d.%s
PS C:\Users\DooMWhite\.config\emacs\elpaca\repos\dash> git log
commit 5df7605da5a080df769d4f260034fb0e5e86a7a4 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Basil L. Contovounesios <basil@contovou.net>
Date:   Fri Feb 16 13:43:48 2024 +0100

    Stricter defexamples checking

    * dev/dash-defs.el (dash--example-to-test): Expand docstring.
    (defexamples): Ensure each triple is well-formed.
    * dev/examples.el (-intersection): Fix badly parenthesized cases.
```

**Comment by progfolio** [comment]
Okay. Let's stick with the terminal.
Please share the output for the following commands:

```shell
git log -n 1 --format=%cd
```
```shell
git log -n 1 --format=%cd --date=format:%Y%m%d
```

We need to find a `--date=format:` value that will return YYMMDD on your version of git.

**Comment by Doomwhite** [comment]
```
PS C:\Users\DooMWhite\.config\emacs\elpaca\repos\dash> git log -n 1 --format=%cd
Fri Feb 16 14:34:46 2024 +0100
PS C:\Users\DooMWhite\.config\emacs\elpaca\repos\dash> git log -n 1 --format=%cd --date=format:%Y%m%d
20240216
```

**Comment by progfolio** [comment]
Thank you. I've altered the date checking function.
Please try to `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs`.
Let me know if everything installs cleanly or if you run into any issues.

**Comment by Doomwhite** [comment]
It worked! Thanks!

**Comment by progfolio** [comment]
> It worked! Thanks!

Glad to hear it.
Thank you for testing.
