### ISSUE TITLE
[Support]: Load specific file or enable mode after init file has been loaded

### ISSUE THREAD

**Issue by bmp** [progfolio/elpaca#266]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca https://github.com/progfolio/elpaca/commit/09a94cadafc5a26602af7955633e4fb6478189a7 HEAD -> master, origin/master, origin/HEAD
installer: 0.6
emacs-version: GNU Emacs 29.2 (build 2, x86_64-unknown-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
of 2024-01-20
git --version: git version 2.43.2

### Operating System

OS: Void x86_64
Kernel: 6.6.16_1

### Description

In straight.el and normal init, I used to enable certain modes either after installing certain packages or at the very end of the init file. Is there a way to do that with elpaca?

For example, with [dwim-shell-command](https://github.com/xenodium/dwim-shell-command?tab=readme-ov-file#my-toolbox), I'd like to use `(require 'dwim-shell-commands)` after `dwim-shell-command` has been loaded, or I'd like to enable `repeat-mode` after all the packages have been loaded.

Also, apologies for spamming the issue system for the last few days! Hopefully resolving this will mean my transition from straight.el is complete.

**Comment by phat-sumo** [comment]
Hey bmp, elpaca provides [`elpaca-after-init-hook`](https://github.com/progfolio/elpaca/wiki/after-init-hook%3F-emacs-startup-hook%3F) which executes after packages have finished loading.
