### ISSUE TITLE
[Bug/Support]: Error 'elpaca--check-version' when downloading the dependencies

### ISSUE THREAD

**Issue by Doomwhite** [progfolio/elpaca#273]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 3e91606 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.2 (build 2, x86_64-w64-mingw32)
 of 2024-01-18
git --version:  git version 2.44.0.windows.1

### Operating System

Windows 10(21.H2 19044.3086)

### Description

I'm getting this error:
![image](https://github.com/progfolio/elpaca/assets/40442835/df08fa37-ec47-4bc8-89e0-8d144150b463)

**Comment by progfolio** [comment]
> I'm getting this error:

Please share the text of the error here.
I cannot view images at this time.

**Comment by Doomwhite** [comment]
It failed in the git-commit dep, the message is:
`elpaca--check-version: (wrong-type-argument stringp nil)`

**Comment by progfolio** [comment]
transient.el is a built-in package as of Emacs 28.1.
Unfortunately, it has not been added to `package--builtin-versions`, which Elpaca uses to determine the built-in package version.

I've filed an upstream bug report here:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-03/msg00114.html

I've also added a workaround for the meantime.
However, the latest version of magit requires a newer version of transient.el than what ships with Emacs.
That leads to two options:

Either, install the latest version of transient as well:

```emacs-lisp
(elpaca transient)
```
Or install the stable release of magit:

```emacs-lisp
(elpaca (magit :tag "v3.3.0"))
```

Does that help?

**Comment by Doomwhite** [comment]
Hmm, I have some :after magit and treemacs, so they are locked, how do I deal with them?
![image](https://github.com/progfolio/elpaca/assets/40442835/930c1f91-b60b-43bd-b592-f337bb4fa467)

**Comment by progfolio** [comment]
I'm sorry, I can't see the images  you're sharing.
If it's an image of an Emacs buffer, you should be able to copy the text content of any buffer and share it as text.

**Comment by Doomwhite** [comment]
```
lsp-treemacs                   blocked              Blocked by: (treemacs)                                                           01.463036
treemacs-magit                 blocked              Blocked by: (treemacs)                                                           01.463055
treemacs-icons-dired           blocked              Blocked by: (treemacs)                                                           01.463061
treemacs-evil                  blocked              Blocked by: (treemacs)                                                           01.463065
treemacs                       blocked              Blocked by: (hydra)                                                              01.477592
dap-mode                       blocked              Blocked by: (lsp-treemacs)                                                       01.497275

```

**Comment by progfolio** [comment]
Thank you.
I see that treemacs is listed as blocked by hydra, but hydra is not in the list of packages.
What is the output for `M-x elpaca-info` `hydra`?

**Comment by Doomwhite** [comment]
```
hydra [MELPA|GNU-devel ELPA]
Make bindings that stick around.

source: MELPA
url: https://github.com/abo-abo/hydra
menu item recipe:
( :package "hydra"
  :repo "abo-abo/hydra"
  :fetcher github
  :files (:defaults (:exclude "lv.el"))
  :source "MELPA")
full recipe:
( :package "hydra"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :source "MELPA"
  :files (:defaults (:exclude "lv.el"))
  :fetcher github
  :repo "abo-abo/hydra")
dependencies: 
  cl-lib >= 0.5
  lv     >= 0
dependents: 
  dap-mode
  lsp-treemacs
  treemacs
  treemacs-evil
  treemacs-icons-dired
  treemacs-magit
installed version: 0.15.0 317e1de
statuses:
  (blocked)
files:
  $REPOS/hydra/hydra-examples.el ! $BUILDS/hydra/hydra-examples.el
  $REPOS/hydra/hydra-ox.el       ! $BUILDS/hydra/hydra-ox.el
  $REPOS/hydra/hydra.el          ! $BUILDS/hydra/hydra.el
log:
  [2024-03-03 20:16:05] Waiting on monorepo c:/Users/Cliente/.config/emacs/elpaca/repos/hydra/
```

**Comment by progfolio** [comment]
I was unable to reproduce the issue on my end with your config.
Please try a clean install by removing the `elpaca` directory and see if the issue persists.
If it does, please do the following:

1. In the \*scratch\* buffer evaluate: `(setq elpaca-verbosity 100)`
1. `M-x elpaca-log`
2.  Type "s" to change the search query.
3. Hit enter to accept an empty prompt.
    The search query should be ".*".
4. `M-x write-file` to save the log to a file.
5. Upload the log file here.

**Comment by Doomwhite** [comment]
This log is without using 
```
(elpaca transient)
(elpaca magit)
```
or
```
(elpaca (magit :tag "v3.3.0"))
```
[log-1.txt](https://github.com/progfolio/elpaca/files/14481750/log-1.txt)

This one is using
```
(elpaca transient)
(elpaca magit)
```
[log-2.txt](https://github.com/progfolio/elpaca/files/14482647/log-2.txt)

This one is using
```
(elpaca (magit :tag "v3.3.0"))
```
[log-3.txt](https://github.com/progfolio/elpaca/files/14482651/log-3.txt)

**Comment by Doomwhite** [comment]
> I was unable to reproduce the issue on my end with your config.
You mean you used my repository?

**Comment by progfolio** [comment]
Thanks for the log output.
Note that all three of them have failed orders with the similar errors:

> treemacs                       failed               elpaca--clone: (file-error "Creating pipe" "Too many open files")                16.533046

See the wiki entry for ["Too many open files"](https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#too-many-open-files) errors. 

> You mean you used my repository?

Correct. I had to change a few things which are not portable (e.g. fonts I don't have installed, some Windows specific functions). However, everything bootstrapped fine for me. I am on Linux and I have `elpaca-queue-limit` set to 30. Windows seems to have a stricter file handle limit, so you'll have to experiment to see what value works for you.
