### ISSUE TITLE
[Support]: Fetching forces ssh auth

### ISSUE THREAD

**Issue by karthink** [progfolio/elpaca#274]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 6bbc174 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
git --version:  git version 2.42.0
```

### Operating System

Linux

### Description

I'm trying to install this package:

```elisp
(use-package isayt
  :ensure (:host gitlab :repo "andreyorst/isayt"
           :protocol https))
```

But when Elpaca tries to clone it, I get an openssh authentication prompt for gitlab.  Any idea what I might be doing wrong?

**Comment by progfolio** [comment]
The repo is named "isayt.el" (with the file extension).
Gitlab probably thinks you're trying to access a private repostiroy for that user since there is no public URL for "isyat".
See the output of the following test case:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init (setq elpaca-menu-functions nil)
  :init (elpaca (isayt :host gitlab :repo "andreyorst/isayt.el" :protocol https))
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>c7aed15 HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>installer</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-02-28</td>
<tr><td>git</td><td>git version 2.44.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.ZaYCYV/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.ZaYCYV/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

elpaca-log: "#unique"
"
elpaca                         finished             ✓ 0.547 secs                                                                     00.587671
isayt                          finished             ✓ 0.832 secs                                                                     00.872644
"

 Test Env

Elpaca c7aed15 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
 of 2024-02-28
git --version:  git version 2.44.0
```
</details>

**Comment by karthink** [comment]
Ah, that was carelessness on my part.  Thanks for catching it, and for the explanation.

I really like `elpaca-test` -- will use that in the future.

**Comment by progfolio** [comment]
> Ah, that was carelessness on my part. Thanks for catching it, and for the explanation.

You're welcome. I've made the same mistake, myself at times.

> I really like `elpaca-test` -- will use that in the future.

Thanks. It's proven to be very useful for debugging and can be great for trying out isolated package sets by adding `:interactive t`.
