### ISSUE TITLE
[Support]: How to use use-package with packages installed by system package managers

### ISSUE THREAD

**Issue by mmalikn** [progfolio/elpaca#280]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca cd5d91f HEAD -> master, origin/master, origin/HEAD
installer: 0.6
emacs-version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, Motif Version 2.3.8) of 2024-02-28
git --version: git version 2.44.0

### Operating System

Gentoo Linux

### Description

I am trying to copy the configuration from [Daviwil](https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-Mail-01.org) to configure [Mu4e](https://github.com/djcb/mu/tree/release/1.10):
``` emacs-lisp
(use-package mu4e
  :ensure nil
  :load-path "/usr/share/emacs/site-lisp/mu4e/"
  ;; :defer 20 ; Wait until 20 seconds after startup
  :config

  ;; This is set to 't' to avoid mail syncing issues when using mbsync
  (setq mu4e-change-filenames-when-moving t)

  ;; Refresh mail using isync every 10 minutes
  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/Mail")
...
```

My package Manager (Portage) installed Mu4e together with Mu like other distros too.
Elpaca still gives me this error:

> Unable to determine repo dir: (error "Cannot determine URL from recipe: (:source nil :protocol https :inherit t :depth 1 :package \"mu4e\")")

I propably have to use use-package differently when using packages from local sources but I can`t find the documentation for that.

**Comment by progfolio** [comment]
> Elpaca cd5d91f HEAD -> master, origin/master, origin/HEAD installer: 0.6

> ``` emacs-lisp
> (use-package mu4e
>   :ensure nil

Support for use-package's `:ensure` keyword was added in 7c6f306.
The version you're running ignores the `:ensure` keyword altogether.
You could either change `:ensure nil` to `:elpaca nil` on the version of Elpaca you're currently running, or keep your declaration as is and update Elpaca via `M-x elpaca-update`.

Does that help?

**Comment by mmalikn** [comment]
when writing `M-x elpaca-up` I can only use elpaca-update-menus

Changing `:ensure nil` to `elpaca nil` fixxed it.
Thank you very much

**Comment by progfolio** [comment]
> when writing M-x elpaca-up I can only use elpaca-update-menus

Then the version you're using is also behind this commit https://github.com/progfolio/elpaca/commit/6a0d6390051c2935557bd12a1334811ef575891a, which adds the `elpaca-update` and `elpaca-update-all` commands.

I would consider updating when you have time.

> Changing :ensure nil to elpaca nil fixed it.
> Thank you very much

Glad to hear it. You're welcome.
