### ISSUE TITLE
[Bug/Support]: When pre building AUCTEX, hang at Running command: ("./autogen.sh")

### ISSUE THREAD

**Issue by zhenwu0728** [progfolio/elpaca#281]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 77e7a48 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin23.3.0, NS appkit-2487.40 Version 14.3.1 (Build 23D60))
 of 2024-03-13
git --version:  git version 2.44.0

### Operating System

Apple M3 Max
MacOS 14.3.1 (23D60)

### Description

I used the recipe in [wiki](https://github.com/progfolio/elpaca/wiki/auctex), but emacs hangs at `Running command: ("./autogen.sh")` forever.

And when I press `RET` on that line, I saw `Cannot open load file: No such file or directory, tex-site`

<img width="1507" alt="Screenshot 2024-03-17 at 00 51 12" src="https://github.com/progfolio/elpaca/assets/46291075/ab46ad4d-a8e4-491e-bd4c-ad7168c9d521">

**Comment by progfolio** [comment]
Please follow these steps to share the log output as text.
1. `M-x elpaca-log`.
2. In the log buffer type `s`. You should be prompted for a search query in the minibuffer.
3. Type `auctex |` for the query then press `RET`.
4. `M-x write-file` to save the log.
5. Upload that file here.

**Comment by zhenwu0728** [comment]
That's what I got
```
Package Status Info Time ▼ 
auctex                         pre-build            Running :pre-build commands                                                      00.095580
auctex                         pre-build            Elpaca menu item cache discarded due to version change.                          00.195205
auctex                         pre-build            Running command: ("./autogen.sh")                                                00.197816
```

**Comment by seblemaguer** [comment]
have you tried to go to the directory `$ELPACA_ROOT_DIR/builds/auctex` (replace ELPACA_ROOT_DIR by the elpaca directory) and run the command `./autogen.sh` in the terminal directly? You are likely to get more info then

**Comment by zhenwu0728** [comment]
Below is the output if I run `./autogen.sh` in `auctex` directory. And `./configuration` and `make` are successful.
```
echo @set VERSION 13.3 >version.texi
echo @set UPDATED 2024-03-17 >>version.texi
makeinfo preview-latex.texi
makeinfo auctex.texi
pdftex tex-ref.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Homebrew) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./tex-ref.tex [3 columns per page]
Underfull \vbox (badness 10000) detected at line 401

Underfull \vbox (badness 10000) detected at line 442
[1{/opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/fonts/map/pdftex/up
dmap/pdftex.map}] [2] )
(see the transcript file for additional information)</opt/homebrew/Cellar/texli
ve/20230313_3/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb></opt/
homebrew/Cellar/texlive/20230313_3/share/texmf-dist/fonts/type1/public/amsfonts
/cm/cmbx8.pfb></opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/fonts/t
ype1/public/amsfonts/cmextra/cmcsc8.pfb></opt/homebrew/Cellar/texlive/20230313_
3/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></opt/homebrew/Cel
lar/texlive/20230313_3/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr6.pfb
></opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr7.pfb></opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/f
onts/type1/public/amsfonts/cm/cmr8.pfb></opt/homebrew/Cellar/texlive/20230313_3
/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsl8.pfb></opt/homebrew/Cella
r/texlive/20230313_3/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy6.pfb>
</opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/fonts/type1/public/am
sfonts/cm/cmsy8.pfb></opt/homebrew/Cellar/texlive/20230313_3/share/texmf-dist/f
onts/type1/public/amsfonts/cm/cmti8.pfb></opt/homebrew/Cellar/texlive/20230313_
3/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmtt8.pfb>
Output written on tex-ref.pdf (2 pages, 153271 bytes).
Transcript written on tex-ref.log.
```

**Comment by progfolio** [comment]
It's difficult to say what's going on without the full log output.
What you shared above looks incomplete.
It would also be nice to see the full output of the all of the commands you ran from the shell.

**Comment by zhenwu0728** [comment]
> It's difficult to say what's going on without the full log output. 

That's the full log output.

>What you shared above looks incomplete. 

Yes, It's incomplete, because it get stuck...

>It would also be nice to see the full output of the all of the commands you ran from the shell.

If I run these pre-build commands in shell, and comment out these commands in my emacs config, everything works fine.

**Comment by zhenwu0728** [comment]
Problem solved by downgrading Emacs to 29, but don't know why...

**Comment by progfolio** [comment]
Okay. Let me know if the problem crops up again on a stable version of Emacs.
Thanks.
