### ISSUE TITLE
hl-todo reporting version 0

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#287]
I find that the installed version of _hl-todo_ does not report a version number that allows _consult-todo_ to install.

> "hl-todo installed version (0) lower than min required 3.1.2"

The MELPA version reported is "20240329.1503", whereas that reported by the MELPA-Stable version is "3.6.0".

So, I want to try the MELPA-Stable version of hl-todo.

How would I create a suitable recipe?

_Originally posted by @s-a-c in https://github.com/progfolio/elpaca/discussions/286_

**Comment by progfolio** [comment]
@s-a-c The reason hl-todo is reporting a version of 0 is because the package maintainer relies solely on git tags for versioning. It's not possible for Elpaca to correctly resolve the git tag with a shallow clone (the default). Everything should work if you alter the recipe to download a full clone of the repository:

```emacs-lisp
(elpaca (hl-todo :depth nil))

;; Or if you're using use-package integration:

(use-package hl-todo :elpaca (:depth nil))
```

> So, I want to try the MELPA-Stable version of hl-todo.

The above will get you the latest MELPA version.
If you wish to pin a package to a specific version you can use the :tag recipe keyword.
e.g.

```emacs-lisp
(elpaca (hl-todo :pin t :tag "v3.6.0"))
```

Does that help?

**Comment by Ziqi-Yang** [comment]
Hi there. I encountered the similar problem. I have [consult-todo](https://github.com/liuyinz/consult-todo) in my package list. And Elpaca reports an error when I'm installing it.
```
hl-todo installed version (0) lower than min required 3.1.2
```
Is there a workaround to solve it? Thanks!

**Comment by progfolio** [comment]
> Hi there. I encountered the similar problem. I have [consult-todo](https://github.com/liuyinz/consult-todo) in my package list. And Elpaca reports an error when I'm installing it.
> ```
> hl-todo installed version (0) lower than min required 3.1.2
> ```
> Is there a workaround to solve it? Thanks!


The same advice mentioned here would apply: https://github.com/progfolio/elpaca/issues/287#issuecomment-2037336126

If that does not work for you, please open a new issue and I'll look into it.
