### ISSUE TITLE
[Bug/Support]: Symbol's value as variable is void: elpaca--queues

### ISSUE THREAD

**Issue by mattiasdrp** [progfolio/elpaca#290]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 3c1699a HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2024-04-12
git --version:  git version 2.34.1

```

### Operating System

Ubuntu 22.04

### Description

When starting emacs with a fresh installation, after elpaca is installed, if I restart emacs I have the following error:

`Symbol's value as variable is void: elpaca--queues`

Starting with --debug-init gives the following trace:

```
Debugger entered--Lisp error: (void-variable elpaca--queues)
  byte-code("\306\307\10\"\306\307\11\"\nA\2\33\310\311\312\4!\203\30\0\3\202\31\0\4\"\210\312\3!\204\277\0\313\3\314\"\210\f\315W\2030\0\316\317!\210\3201..." [elpaca-repos-directory elpaca-builds-directory elpaca-order default-directory emacs-major-version invocation-directory expand-file-name "elpaca/" add-to-list load-path file-exists-p make-directory t 28 require subr-x (debug error) pop-to-buffer-same-window "*elpaca-bootstrap*" call-process "git" nil "clone" plist-get :repo 0 "checkout" :ref "--" "-Q" "-L" "." "--batch" "--eval" "(byte-recompile-directory \".\" 0 'force)" elpaca elpaca-generate-autoloads "elpaca" message "%s" buffer-string kill-buffer error warn delete-directory recursive elpaca-autoloads load "./elpaca-autoloads" add-hook ...] 18)
  load("/home/mattias/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x157d656c1247f6eb>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()
```

I'm usually able to fix the bugs I find but this one, I just don't get it :shrug

**Comment by mattiasdrp** [comment]
Oh, my bad, I don't know how but there was a init.elc that was executed instead of init.el, removing it removed the bug

**Comment by progfolio** [comment]
. I 
-------- Original message --------From: Mattias ***@***.***> Date: 4/12/24  5:04 AM  (GMT-05:00) To: progfolio/elpaca ***@***.***> Cc: Subscribed ***@***.***> Subject: [progfolio/elpaca] [Bug/Support]: Symbol's value as variable is void: elpaca--queues (Issue #290) 
Confirmation

 I have checked the documentation (README, Wiki, docstrings, etc)
 I am  checking these without reading them.
 I have searched previous issues to see if my question is a duplicate.

Elpaca Version
Elpaca 3c1699a HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2024-04-12
git --version:  git version 2.34.1


Operating System
Ubuntu 22.04
Description
When starting emacs with a fresh installation, after elpaca is installed, if I restart emacs I have the following error:
Symbol's value as variable is void: elpaca--queues
Starting with --debug-init gives the following trace:
Debugger entered--Lisp error: (void-variable elpaca--queues)
  byte-code("\306\307\10\"\306\307\11\"\nA\2\33\310\311\312\4!\203\30\0\3\202\31\0\4\"\210\312\3!\204\277\0\313\3\314\"\210\f\315W\2030\0\316\317!\210\3201..." [elpaca-repos-directory elpaca-builds-directory elpaca-order default-directory emacs-major-version invocation-directory expand-file-name "elpaca/" add-to-list load-path file-exists-p make-directory t 28 require subr-x (debug error) pop-to-buffer-same-window "*elpaca-bootstrap*" call-process "git" nil "clone" plist-get :repo 0 "checkout" :ref "--" "-Q" "-L" "." "--batch" "--eval" "(byte-recompile-directory \".\" 0 'force)" elpaca elpaca-generate-autoloads "elpaca" message "%s" buffer-string kill-buffer error warn delete-directory recursive elpaca-autoloads load "./elpaca-autoloads" add-hook ...] 18)
  load("/home/mattias/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x157d656c1247f6eb>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()

I'm usually able to fix the bugs I find but this one, I just don't get it :shrug

**Comment by progfolio** [comment]
> Oh, my bad, I don't know how but there was a init.elc that was executed instead
> of init.el, removing it removed the bug

Compiling one's init file is currently unsupported by Elpaca.
It's rarely useful to do so in general and recommended against by Emacs devs, so it's unlikely I'll go out of my way to support it for now.

**Comment by mattiasdrp** [comment]
> (Apologies for the pocket reply earlier, my phone has been on the fritz)

No worries :-)

> Compiling one's init file is currently unsupported by Elpaca.
> It's rarely useful to do so in general and recommended against by Emacs devs, so it's unlikely I'll go out of my way to support it for now.

I never used this feature that's why it took me some time to figure out what was happening. I don't even know how I did this.
