### ISSUE TITLE
[Feature]: A way to show new commits after a fetch

### ISSUE THREAD

**Issue by aikrahguzar** [progfolio/elpaca#292]
### Feature Description

Hi,
  Thanks a lot for the great package manager. It's interactivity is great. Is there a way to see what repos changed after a `elpaca-fetch-all`? After the command, I see a log buffer which gets populated with all the packages I have installed. Is there a way to see only those packages which had new commits during the fetch? And possibly a way to see new commits?

Thanks again!

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> Hi, Thanks a lot for the great package manager. It's interactivity is great.

Thanks for the kind words.

> Is there a way to see what repos changed after a `elpaca-fetch-all`? After the
> command, I see a log buffer which gets populated with all the packages I
> have installed. Is there a way to see only those packages which had new
> commits during the fetch? And possibly a way to see new commits?
  
The default search query for the `elpaca-fetch-all` command is `"#latest #update-log"`.
That query should show what you're looking for.
It normally adds a button to the commit hash  in the "Info" column which, when clicked, will display the diff in another window if you have magit installed.
I've just added a diff viewer that does not require magit.

Try `M-x elpaca-pull` `elpaca` followed by `M-x restart-emacs`.
Once you've updated, try running `M-x elpaca-fetch-all` again.
If you don't see something like below, let me know.

![image](https://github.com/progfolio/elpaca/assets/44036031/91eac68b-d94b-4f4a-ace3-12d42a85adf8)

**Comment by aikrahguzar** [comment]
> Try `M-x elpaca-pull` `elpaca` followed by `M-x restart-emacs`. Once you've updated, try running `M-x elpaca-fetch-all` again. If you don't see something like below, let me know.

Thanks a lot! I just updated `elpaca` and ran `elpaca-fetch-all` after it. It produced an empty log buffer which is to be expected since I ran it yesterday too. I think it will work as expected.

BTW another related thing but I can also open another bug for it: when I do `M-x elpaca-manager RET` followed by `elpaca-ui-search-installed`, the date column doesn't look quite right to me. If I click on the date header twice to sort by the newest I see this,

![elpaca](https://github.com/progfolio/elpaca/assets/88336724/1d874a83-64b2-417b-8251-83d94d7e9310)

Somehow all packages from GNU and NonGNU ELPA show up with the same date as last `elpaca-fetch-all` although they haven't actually been updated.

**Comment by progfolio** [comment]
> Thanks a lot! I just updated elpaca and ran elpaca-fetch-all after it. It produced an empty log buffer which is to be expected since I ran it yesterday too. I think it will work as expected.

That stands to reason. Feel free to comment here if you notice anything related to the original issue next time there are updates to fetch.

> BTW

Let's move discussion of that to #293
