### ISSUE TITLE
[Feature] GNU/NonGNU menu item dates

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#293]
> Try `M-x elpaca-pull` `elpaca` followed by `M-x restart-emacs`. Once you've updated, try running `M-x elpaca-fetch-all` again. If you don't see something like below, let me know.

[W]hen I `M-x elpaca-manager RET` followed by `elpaca-ui-search-installed`, the date column doesn't look quite right to me. If I click on the date header twice to sort by the newest I see this,

![elpaca](https://github.com/progfolio/elpaca/assets/88336724/1d874a83-64b2-417b-8251-83d94d7e9310)

Somehow all packages from GNU and NonGNU ELPA show up with the same date as last `elpaca-fetch-all` although they haven't actually been updated.

_Originally posted by @aikrahguzar in https://github.com/progfolio/elpaca/issues/292#issuecomment-2063230496_

**Comment by progfolio** [comment]
When a menu item does not include a `:date` key, the default fallback date is the current date.
The GNU/NonGNU Elpa menus scrape the respective web pages for package data.
Those web pages do not offer any date information at this time (and so no `:date` value for those menu items).
I've opened a feature request upstream:
 https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-04/msg01089.html

If we can get a "Date" column added to the websites, I'll add that info to the menu items.
Otherwise, it's too costly to request hundreds of pages and scrape those.

**Comment by aikrahguzar** [comment]
> When a menu item does not include a `:date` key, the default fallback date is the current date. The GNU/NonGNU Elpa menus scrape the respective web pages for package data. Those web pages do not offer any date information at this time (and so no `:date` value for those menu items). I've opened a feature request upstream: https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-04/msg01089.html
> 
> If we can get a "Date" column added to the websites, I'll add that info to the menu items. Otherwise, it's too costly to request hundreds of pages and scrape those.

I wonder if for installed packages it is better to get the date from repo i.e. the date of the commit that is checked out? It is arguably inconsistent because the date will change when a package is installed but I think is a more intuitive option for installed packages. And the inconsistency makes sense from the point of view that the information for installed packages should be accurate while for the recipes it should be best we can obtain without too much effort.

**Comment by progfolio** [comment]
> I wonder if for installed packages it is better to get the date from repo i.e.
> the date of the commit that is checked out? It is arguably inconsistent because
> the date will change when a package is installed but I think is a more intuitive
> option for installed packages. And the inconsistency makes sense from the point
> of view that the information for installed packages should be accurate while for
> the recipes it should be best we can obtain without too much effort.

I've pushed a change which should now compute the date according to the HEAD of the repository for installed packages. To test you'll want to:

1. `M-x elpaca-pull` `elpaca`
2. `M-x restart-emacs`
3. `M-x elpaca-manager`

In cases where that date can't be computed, there are fall-backs which are less accurate.
Let me know if that works for you.

**Comment by aikrahguzar** [comment]
Thanks a lot! It works very well.
