### ISSUE TITLE
Installing packages failed with error stating "elpaca--repo-uri: wrong type argument: stringp, nil" even when using default recipes.

### ISSUE THREAD

**Issue by ghost** [progfolio/elpaca#3]
good morning sir,

recently, trying to find a better package management alternative to straight.el, I stumbled across your reddit post about this package manager. so I redited my config for elpaca but I don't know why I am recieving the following error in messages buffer:

elpaca--repo-uri: wrong type argument: stringp, nil

I have not changed or added the default elpaca recipes.

By the way, I am using arch linux with emacs-nativecomp package installed using pacman and if i am missing any essential information to provide please guide me for it though :) .

Also here is my emacs config (init.el) to reproduce the problem:

https://termbin.com/x8wr

## What's wrong

Getting error stating **elpaca--repo-uri: wrong type argument: stringp, nil** even using default recipes.

## Directions to reproduce

Here is my emacs config (init.el) to reproduce the problem:

https://termbin.com/x8wr

### Version information

* Emacs package info

**Name :** emacs-nativecomp
**Installed from:** Installed using pacman.

* Emacs version:

GNU Emacs 28.1

* Operating system:

Arch linux

**Comment by progfolio** [comment]
Thanks for testing, Mustafa.
I plan on making it easier to report bugs with Elpaca in the future, but that's still a work in progress.
For now, can you add  `(setq toggle-debug-on-error t)` at the beginning of your init.el and share the backtrace results here?
That should lend some insight as to what's causing the error.

**Comment by progfolio** [comment]
I've pushed a change so that the `--debug-init` flag is preserved while Elpaca is processing the user's init.
You should now be able to launch `emacs --debug-init` to get the backtrace without adding the `setq` I mentioned above.
Testing appreciated.

**Comment by mustafa-dhuleb** [comment]
I am living in a timezone different then yours so I apologise for the late reply.

Here is what I get when I ran "emacs --debug-init" the very first time:

Debugger entered--Lisp error: (wrong-number-of-arguments autoload-rubric 4)
  (autoload-rubric output nil 'feature 'compile)
  (write-region (autoload-rubric output nil 'feature 'compile) nil output nil 'silent)
  (let* ((default-directory dir) (auto-name (format "%s-autoloads.el" package)) (output (expand-file-name auto-name dir)) (generated-autoload-file output) (autoload-timestamps nil) (backup-inhibited t) (version-control 'never) (find-file-hook nil) (write-file-functions nil) (left-margin 0)) (write-region (autoload-rubric output nil 'feature 'compile) nil output nil 'silent) (cond ((fboundp 'loaddefs-generate) (loaddefs-generate dir auto-name nil nil nil t)) ((fboundp 'make-directory-autoloads) (make-directory-autoloads dir output)) ((fboundp 'update-directory-autoloads) (with-no-warnings (update-directory-autoloads dir)))) (let* ((buf (and t (find-buffer-visiting output)))) (if buf (kill-buffer buf) nil)) auto-name)
  elpaca-generate-autoloads("elpaca" "/home/destruct/.emacs.d/elpaca/repos/elpaca/")
  (progn (if (= 0 (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo)) nil (error "%s" (list (save-current-buffer (set-buffer buffer) (buffer-string))))) (byte-recompile-directory elpaca-repo 0 'force) (require 'elpaca) (elpaca-generate-autoloads "elpaca" elpaca-repo) (kill-buffer buffer))
  (condition-case err (progn (if (= 0 (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo)) nil (error "%s" (list (save-current-buffer (set-buffer buffer) (buffer-string))))) (byte-recompile-directory elpaca-repo 0 'force) (require 'elpaca) (elpaca-generate-autoloads "elpaca" elpaca-repo) (kill-buffer buffer)) ((debug error) (delete-directory elpaca-directory 'recursive) (save-current-buffer (set-buffer buffer) (goto-char (point-max)) (insert (format "\n%S" err)) (display-buffer buffer))))
  (if buffer (condition-case err (progn (if (= 0 (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo)) nil (error "%s" (list (save-current-buffer (set-buffer buffer) (buffer-string))))) (byte-recompile-directory elpaca-repo 0 'force) (require 'elpaca) (elpaca-generate-autoloads "elpaca" elpaca-repo) (kill-buffer buffer)) ((debug error) (delete-directory elpaca-directory 'recursive) (save-current-buffer (set-buffer buffer) (goto-char (point-max)) (insert (format "\n%S" err)) (display-buffer buffer)))) nil)
  (let* ((elpaca-repo (and t (expand-file-name "repos/elpaca/" elpaca-directory))) (elpaca-build (and elpaca-repo (expand-file-name "builds/elpaca/" elpaca-directory))) (elpaca-target (and elpaca-build (if (file-exists-p elpaca-build) elpaca-build elpaca-repo))) (elpaca-url (and elpaca-target "https://www.github.com/progfolio/elpaca.git")) (s (and elpaca-url (add-to-list 'load-path elpaca-target))) (s (and s (not (file-exists-p elpaca-repo)))) (buffer (and s (get-buffer-create "*elpaca-bootstrap*")))) (if buffer (condition-case err (progn (if (= 0 (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo)) nil (error "%s" (list (save-current-buffer ... ...)))) (byte-recompile-directory elpaca-repo 0 'force) (require 'elpaca) (elpaca-generate-autoloads "elpaca" elpaca-repo) (kill-buffer buffer)) ((debug error) (delete-directory elpaca-directory 'recursive) (save-current-buffer (set-buffer buffer) (goto-char (point-max)) (insert (format "\n%S" err)) (display-buffer buffer)))) nil))
  load-with-code-conversion("/home/destruct/.emacs.d/init.el" "/home/destruct/.emacs.d/init.el" t t)
  load("/home/destruct/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x154d6b6220d60726>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
  command-line()
  normal-top-level()

And Here is what I get when I ran "emacs --debug-init" the second time:

Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "elpaca-autoloads")
  require(elpaca-autoloads)
  load-with-code-conversion("/home/destruct/.emacs.d/init.el" "/home/destruct/.emacs.d/init.el" t t)
  load("/home/destruct/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157ec99e0843eb26>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
  command-line()
  normal-top-level()

**Comment by progfolio** [comment]
I'm pretty sure this error occurs if the recipe cache is corrupt and a recipe does not end up with a proper "name".
The package name is used when determining the build/repo directory names. If that ends up nil, we can hit the error you hit or (even worse) end up with unrelated packages which all think they're vendored in the same  "nil" mono-repository.

I've added an error condition that should at least prevent the error you were seeing and will cause a queued package to fail.
I still have to track down how the menu item cache is being corrupted and think of a better way to handle that scenario.
Thanks again.

**Comment by progfolio** [comment]
Did you happen to run the repository Makefile at any point?
I just pushed a fix in which the test suite was corrupting the menu-item cache.
That would've lead to the same error you were seeing.

**Comment by progfolio** [comment]
Closing this for now, as I have not been able to reproduce the error for some time.
If you have any more info to add, feel free and we can reopen if necessary.
Thanks.
