### ISSUE TITLE
[Feature/Suggestion]: Use jit-lock to make search more responsive 

### ISSUE THREAD

**Issue by aikrahguzar** [progfolio/elpaca#301]
### Feature Description

This is more of an idea so you can close it without doing anything but here it goes:

I had removed `#uniqe` from `elpaca-manager-default-search-query` since with it `M-x elpaca-manager` seemd to take a noticeable amount of time. Then I set `elpaca-manager-default-search-query` to  ` "#installed"` since I am looking for something related to an installed package more often that I am searching for some unknown package. 

Today I noticed that if a package was available from more than one source, the second time it appears with `elpaca-ui-conflicting` face. This got me thinking that `jit-lock` can be used for a lazier implementation for `#unique` tag.

Basically, at the same time the face `elpaca-ui-conflicting` is applied, the jit lock function can also put an invisible property with value let's say the same symbol `elpaca-ui-conflicting`. Filtering out the conflicting results then just corresponds to adding `elpaca-ui-conflicting` to `buffer-invisibility-spec` using `add-to-invisibility-spec`. This will filter out the duplicates as needed instead of doing it at the beginning. One problem with this idea is that it will be harder to get an accurate number of total search results and that might be confusing.

I don't know if this is worth doing but I thought I will share the idea.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by aikrahguzar** [comment]
> I've pushed a patch to master which should be about 10-15x faster according to my (admittedly simple) benchmarking:
> 
> ```
> 27   8%            + elpaca-ui--tag-unique
> ```
> 
> Let me know if you notice an improvement after an `M-x elpaca-pull` and `M-x restart-emacs`. Thanks.

Thanks a lot! `elpaca-manager` is much faster now.



> Using the invisibility spec is a neat idea. I think it could be used for a more general tabulated-list-mode feature that was proposed (but seems to have stalled) involving hiding/showing columns:
> 
> https://yhetil.org/emacs-bugs/87bkrtzkgm.fsf_-_@gnus.org/T/#u
> 
> I may suggest that idea there to bump that thread and see what the status is.

Invisibility spec does seem like the natural idea for hiding columns. I will experiment with this at some point (hopefully soon) and then report on that bug but please feel free to suggest the idea there in the meanwhile.

**Comment by progfolio** [comment]
aikrahguzar ***@***.***> writes: 
 
> Thanks a lot! elpaca-manager is much faster now.

> Invisibility spec does seem like the natural idea for hiding 
> columns. I will experiment with this at some point (hopefully 
> soon) and then report on that bug but please feel free to 
> suggest the idea there in the meanwhile. 
 

Glad to hear it! Thank you!
