### ISSUE TITLE
[Support]: Org loaded before Elpaca activation

### ISSUE THREAD

**Issue by teesh3rt** [progfolio/elpaca#308]
### Confirmation

- [ ] I have checked the documentation (README, Wiki, docstrings, etc)
- [x] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

installer: 0.7
emacs: 29.3

### Operating System

windows

### Description

for some reason when i try to install org manually it complains about it loading before elpaca
obviously it loads before elpaca because org is included in emacs
how can i fix this?

**Comment by progfolio** [comment]
>  obviously it loads before elpaca because org is included in emacs

Having a package installed and loaded are two different things.
Please see:

https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#feature-loaded-early

Let me know if that helps.

**Comment by teesh3rt** [comment]
thanks!
