### ISSUE TITLE
[Support]: (elpaca nil) does not work as shown in the tutorial

### ISSUE THREAD

**Issue by teesh3rt** [progfolio/elpaca#309]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

elpaca bc685f5
installer 0.7
emacs 29.3

### Operating System

windows

### Description

in the video tutorial, it shows that using (elpaca nil) lets you run things with elpaca without installing any package. however, when i try to use this, it throws `Wrong type argument: (or symbolp consp), nil`

**Comment by progfolio** [comment]
The video tutorial is outdated. Please refer to the manual and wiki here for the most recent information.

**Comment by teesh3rt** [comment]
then how can i do the same thing as in the tutorial in the current version?

**Comment by progfolio** [comment]
> then how can i do the same thing as in the tutorial in the current version?

Please see the following commit message:

https://github.com/progfolio/elpaca/commit/24a178eaec9e54de2adb541be8b0ab829849a26b

**Comment by teesh3rt** [comment]
ok, but how can i run things sequentially now without installing anything?

**Comment by teesh3rt** [comment]
nevermind, i read the commit message a bit further and found out
