### ISSUE TITLE
[Support] eros-eval-last-sexp, eros-eval-defun do not process elpaca queues

### ISSUE THREAD

**Issue by Gleek** [progfolio/elpaca#312]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 1458996 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 2, aarch64-apple-darwin23.4.0, NS appkit-2487.50 Version 14.4.1 (Build 23E224))
 of 2024-04-27
git --version:  git version 2.43.0

```

### Operating System

macOS Sonoma

### Description

This is a follow up from https://github.com/progfolio/elpaca/issues/120
Using [eros](https://github.com/xiongtx/eros) to run `eros-eval-last-sexp` and friends doesn't work immediately and requires a manual run of `(elpaca-process-queues)`

I've used the following config with `emacs -Q` to reproduce this:

```elisp
(setq use-package-always-ensure t)
(setq use-package-always-defer t)
(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))

(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))



(use-package eros
  :hook (emacs-lisp-mode . eros-mode)
  :config
  (setq test-var "test"))

```

Steps to reproduce:
1. emacs -Q
2. M-x eval-buffer test.el
3. M-x revert-buffer yes
4. C-h v test-var (we'll get "test" as the value)
5. change the line to some other value `(setq test-var "test123")`
6. `eros-eval-defun` or go to end of use-package declaration and run `eros-eval-last-sexp`
7. C-h v test-var (we'll still get "test" should have got "test123")

This is the elpaca-info for eros
```
eros
Evaluation Result OverlayS for Emacs Lisp

source: MELPA
url: https://github.com/xiongtx/eros
menu item recipe:
( :package "eros"
  :fetcher github
  :repo "xiongtx/eros"
  :files ("*.el" "*.el.in" "dir" "*.info"
          "*.texi" "*.texinfo" "doc/dir"
          "doc/*.info" "doc/*.texi"
          "doc/*.texinfo" "lisp/*.el" (:exclude
                                       ".dir-locals.el" "test.el" "tests.el"
                                       "*-test.el" "*-tests.el" "LICENSE"
                                       "README*" "*-pkg.el")))
full recipe:
( :package "eros"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :files (:defaults)
  :repo "xiongtx/eros"
  :fetcher github)
dependencies:
?
dependents: ?
```

**Comment by Gleek** [comment]
This should work, thanks. But do you think elpaca should be generic enough to handle these cases? 
I am specifically pointing to this portion of the code:
```elisp
(cond ((plist-get (elpaca<-recipe e) :wait) (elpaca-wait))
      (after-init-time
       (when (member this-command '(eval-last-sexp eval-defun)) (elpaca-process-queues))
       (when (member this-command '(eval-region eval-buffer org-ctrl-c-ctrl-c))
         (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
         (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues))))
```
Here, why do we create exceptions for the commands `eval-region eval-buffer org-ctrl-c-ctrl-c`? Wouldn't something like 

```elisp
(cond ((plist-get (elpaca<-recipe e) :wait) (elpaca-wait))
      (after-init-time
       (if (member this-command '(eval-last-sexp eval-defun))
           (elpaca-process-queues)
         (progn
           (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
           (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues)))))
```

also work with "all" commands that eval any code. Be it, `eval-expression` or running in `eshell` or `ielm` or using packages like eros. Sure, it won't be as fast as just doing `eval-last-sexp` but it would still work nonetheless.

If creating this exception for these commands important for some reason then maybe asking people to to override `this-command` is the way to go. But otherwise, it seems slightly hacky as this could potentially break other things that might want a distinction in both the commands.

**Comment by Gleek** [comment]
> as this could potentially break other things that might want a distinction in both the commands.

Ah! I just noticed that you adviced elpaca and not eros, as I assumed earlier for some reason. So this shouldn't break.

Please feel free to close, if you feel this is the only way to go about it and removing a whitelist of command is not possible.

**Comment by progfolio** [comment]
> I am specifically pointing to this portion of the code:
> Here, why do we create exceptions for the
> commands `eval-region eval-buffer org-ctrl-c-ctrl-c`? Wouldn't something like
> 
> ```elisp
> (cond ((plist-get (elpaca<-recipe e) :wait) (elpaca-wait))
>       (after-init-time
>        (if (member this-command '(eval-last-sexp eval-defun))
>            (elpaca-process-queues)
>          (progn
>            (when elpaca--interactive-timer (cancel-timer elpaca--interactive-timer))
>            (run-at-time elpaca-interactive-interval nil #'elpaca-process-queues)))))
> ```
> 
> also work with "all" commands that eval any code. Be it, `eval-expression` or
> running in `eshell` or `ielm` or using packages like eros. Sure, it won't be as
> fast as just doing `eval-last-sexp` but it would still work nonetheless.

The problem with that proposal is that it will introduce that delay any time queues are processed after init. That includes every startup. That's not an acceptable cost.
However, the idea itself isn't bad. We'll assume that macro expansion during a command means the user wants the queues immediately processed. If/when I get a bug report about that not being the case, I'll add an option to prevent immediate processing.
  
> Ah! I just noticed that you adviced elpaca and not eros, as I assumed earlier
> for some reason. So this shouldn't break.
> 
> Please feel free to close, if you feel this is the only way to go about it and
> removing a whitelist of command is not possible.

I've made it so the queues are processed if `real-this-command` is bound during expansion.
This should cover all commands.
You should be good on the master branch without the advice now.
Testing is appreciated:

1. `M-x elpaca-update` `elpaca`
2. `M-x restart-emacs`
3. Eval declarations with eros-mode enabled. Queue should be processed.

**Comment by progfolio** [comment]
I'll consider this closed, but feel free to let me know if you run into any issues. Thanks again.

**Comment by Gleek** [comment]
Hey @progfolio, 
Thanks for the update. I could not get the time yesterday to look at it.

Strangely,  I was not able to update elpaca for within elpaca and it's skipping it as a pinned package. This is the log that I get

```
  [2024-06-06 11:00:17] Continued by: elpaca--process
  [2024-06-06 11:00:17] Continued by: elpaca--announce-pin
  [2024-06-06 11:00:17] Skipping pinned package
  [2024-06-06 11:00:17] ✓ 0.011 secs
```
I haven't changed the recipe to mark it pinned anywhere and checking the full info also shows the same.
```
elpaca
Not available in menu functions

source: Init file
full recipe:
( :package "elpaca"
  ;; Inherited from declaration.
  :build (:not elpaca--activate-package)
  :files (:defaults "elpaca-test.el"
                    (:exclude "extensions"))
  :ref nil
  :repo "https://github.com/progfolio/elpaca.git"
  :depth 1
  ;; Inherited from elpaca-order-functions.
  :inherit t
  :protocol https)
dependencies:
  emacs >= 27.1
dependents: 
  elpaca-use-package
installed version: 0.0.2 8d9cbe5
statuses:
  (finished pinned queued)
files:
  $REPOS/elpaca/elpaca-test.el       → $BUILDS/elpaca/elpaca-test.el
  $REPOS/elpaca/doc/elpaca.texi      → $BUILDS/elpaca/elpaca.texi
  $REPOS/elpaca/elpaca-autoloads.el  → $BUILDS/elpaca/elpaca-autoloads.el
  $REPOS/elpaca/elpaca-info.el       → $BUILDS/elpaca/elpaca-info.el
  $REPOS/elpaca/elpaca-log.el        → $BUILDS/elpaca/elpaca-log.el
  $REPOS/elpaca/elpaca-manager.el    → $BUILDS/elpaca/elpaca-manager.el
  $REPOS/elpaca/elpaca-menu-elpa.el  → $BUILDS/elpaca/elpaca-menu-elpa.el
  $REPOS/elpaca/elpaca-menu-melpa.el → $BUILDS/elpaca/elpaca-menu-melpa.el
  $REPOS/elpaca/elpaca-menu-org.el   → $BUILDS/elpaca/elpaca-menu-org.el
  $REPOS/elpaca/elpaca-process.el    → $BUILDS/elpaca/elpaca-process.el
  $REPOS/elpaca/elpaca-ui.el         → $BUILDS/elpaca/elpaca-ui.el
  $REPOS/elpaca/elpaca.el            → $BUILDS/elpaca/elpaca.el
```

The last commit that it got stuck on is: 1458996bf02cb990b56b44fe210d836b280c84f1.
I did not go through the change in detail but it seems related. Let me know if you want to me to create another issue for this.


Anyway, I pulled elpaca manually and it seems to work fine.
