### ISSUE TITLE
[Bug]: fails to install packages which depend on ignored dependencies

### ISSUE THREAD

**Issue by elizagamedev** [progfolio/elpaca#313]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca bc685f5 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
git --version:  git version 2.42.0

### Operating System

Linux

### Description

The culprit appears to be cb84c5b0e90386f738001751e79c13a2f1a36162. `(elpaca--continue-build e)` returns a process object which is then passed to `(version-list-<)`, signalling an error of `(wrong-type-argument listp ...)`. Changing the form to `(progn (elpaca--continue-build e) nil)` seems to fix the error, but I don't know if this is correct.

**Comment by elizagamedev** [comment]
Spoke too soon; looks like `(cl-return (elpaca--continue-build e))` is probably the right approach.

**Comment by progfolio** [comment]
Thanks for the bug report.
Do you have a package in particular that this is reproducible with?
It will help with testing a solution.

**Comment by progfolio** [comment]
Should be taken care of after an `M-x elpaca-update` `elpaca` followed by an `M-x restart-emacs`. Testing appreciated. Thanks again.

**Comment by progfolio** [comment]
I'll consider this closed for now.
If you run into any issues after updating, let me know.
Thanks!

(P.S. Oneshot looks pretty cool. Added to my list of games to play)
