### ISSUE TITLE
[Support]: How to enforce the use of the (m)elpa package over the builtin

### ISSUE THREAD

**Issue by seblemaguer** [progfolio/elpaca#315]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 43ec2d8 HEAD -> master, origin/master, origin/HEAD
installer:      0.7

### Operating System

linux (kubuntu 22.04.4), GNU Emacs 29.3.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2024-04-15

### Description

Hello,

and apologies for what is likely going to be a stupid question, but after installing `jsonrpc` using the following command:

```elisp
(use-package jsonrpc
   :ensure (:tag "1.0.25"))
```
it seems I am still using the builtin version. 

To test this, I simply run `apropos` and pick up the function `jsonrpc-error`. The file pointed out in the help part still refers to builtin file (emacs/share/emacs/29.3.50/lisp/jsonrpc.el.gz).

Is there a way to enforce the use of the elpa version?

Thanks a lot

**Comment by progfolio** [comment]
Please share the output of `M-x elpaca-info` `jsonrpc` and the configuration you are using.
Are there any warnings in the \*Warnings\* buffer when you start Emacs?

**Comment by progfolio** [comment]
> Warning (emacs): jsonrpc loaded before Elpaca activation

There is your issue. You need to ensure jsonrpc is not loaded prior to Elpaca activating/loading it.
Please see: https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#feature-loaded-early

Does that help?

**Comment by seblemaguer** [comment]
yes, it did thanks a lot (I wrote ":demand t" instead of ":defer t" :facepalm: for dape).

**Comment by progfolio** [comment]
> yes, it did thanks a lot (I wrote ":demand t" instead of ":defer t" 🤦 for dape).

Thanks for getting back to me. Glad it worked out!
