### ISSUE TITLE
[Bug]: incorrect load-history library paths when autoloads cached

### ISSUE THREAD

**Issue by mekeor** [progfolio/elpaca#319]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 68ca012 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.16.0)
git --version:  git version 2.41.0
```

### Operating System

GNU Guix System Linux

### Description

1. Save this as `~/example.el`. (Note that `0x0` is an arbitrary, exemplary package. You can replace it with any other.)

```elisp
;; -*- lexical-binding: t; -*-

;;;; Bootstrap

(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;;;; Install and load a package

(elpaca (0x0))
(elpaca-process-queues)
(require '0x0)

;;;; Echo location

(require 'find-func)
(message (cdr (find-function-library '0x0-dwim)))
```

2. Start Emacs with only this file loaded: `emacs -Q -l example.el`
3. In this Emacs instance, type `C-h e` and you will see the `/home/user/.emacs.d/elpaca/builds/0x0/0x0.elc` message. -- Great! Emacs has correctly located the `0x0-dwim` function!
4. Now type `M-: (message (cdr (find-function-library '0x0-dwim))) RET`. Emacs will echo `/home/user/example.el`, i.e. it will fail at determining the location of the function from the external package. (If you put the example-code into `~/.emacs.d/init.el`, Emacs will echo `~/.emacs.d/init.el` here.) (Alternatively, you can also type `C-h f 0x0-dwim RET` and you'll get a `*Help*` buffer mentioning the wrong location.)

**Comment by progfolio** [comment]
Thanks for the bug report.

> ;;;; Install and load a package
> 
> (elpaca (0x0))
> (elpaca-process-queues)

`elpaca-process-queues` does not block.
So everything after this point will be executed too soon.

> (require '0x0)
> 
> ;;;; Echo location
> 
> (require 'find-func)
> (message (cdr (find-function-library '0x0-dwim)))
> ```

I see your point, though, and am able to reproduce with a slightly modified test.
I've pushed a patch which should address the issue.
Please try:

1. `M-x elpaca-update` `elpaca`
2. `M-x restart-emacs`

And let me know if the issue is taken care of for you.
Thanks.

**Comment by progfolio** [comment]
> Thank you very much! The fix works for me. Thanks for Elpaca in general too.

Thank you for testing!
