### ISSUE TITLE
[Bug/Support]: use-package :ensure keyword does not work as expected

### ISSUE THREAD

**Issue by ZharMeny** [progfolio/elpaca#323]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 8bb0fc8 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
git --version:  git version 2.44.1

### Operating System

Linux (NixOS Unstable)

### Description

Under normal circumstances (namely, vanilla `use-package` macro), `:ensure` keyword implies `t` unless otherwise specified.  Here's an example:
```Emacs lisp
(use-package embark-consult
  :ensure) ; t is implicit
```
If, however, `elpaca-use-package-mode` is on, the `:ensure` keyword does not imply `t` and you have to manually specify it, which is quite unexpected.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.

> Under normal circumstances (namely, vanilla `use-package` macro), `:ensure` keyword implies `t` unless otherwise specified.  Here's an example:
> ```Emacs lisp
> (use-package embark-consult
>   :ensure) ; t is implicit
> ```

I'm surprised that works and doesn't signal an error.
I've patched Elpaca's use-package support to be compatible.
Should work on your end after `M-x elpaca-update` `elpaca-use-package` followed by `M-x restart-emacs`. Testing appreciated.

**Comment by ZharMeny** [comment]
It works, thanks.

**Comment by progfolio** [comment]
Thank you for testing.
