### ISSUE TITLE
[Support]: GNU ELPA BBDB recipe points to NonGNU BBDB URL

### ISSUE THREAD

**Issue by jtamagnan** [progfolio/elpaca#327]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca b8ed514 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
git --version:  git version 2.45.1

### Operating System

Linux

### Description

# Background

For some cursed reason the version of BBDB on elpa and nongnu elpa differ. The version on GNU Elpa contains a `bbdb-site.el` file where as the non-GNU version contains a `bbdb-site.el.in` file. Since elpaca doesn't seem to support this `bbdb-site.el.in` version I'd like to use the GNU Elpa version.

It also seems like an issue that these two packages have diverged so badly that they contain different files. The non-gnu version is missing https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=commitdiff;h=7cc844f3c52823d6ce02b884afb2d493d52e5eda and instead has https://git.savannah.nongnu.org/cgit/bbdb.git/commit/lisp?id=260513509d0047f5a6eed7b6242c329cd97a4f43

# Problem

When trying to use the GNU version of this package it seems like the non-gnus version is actually installed.
```
(elpaca-test
  :dir "elpaca.bbdb"
  :early-init
  (setq elpaca-menu-functions '(elpaca-menu-gnu-devel-elpa))
  :init
  (pp "Enqueuing...")
  (elpaca bbdb)
  (pp "Waiting...")
  (elpaca-wait)
  (pp (shell-command-to-string (concat "cd " elpaca-repos-directory "/bbdb && git remote get-url --push origin"))))
```

The critical output is:
```
...
"https://git.savannah.nongnu.org/git/bbdb.git\n"
```

**Comment by progfolio** [comment]
> ...
> "https://git.savannah.nongnu.org/git/bbdb.git\n"
> ```

The package specs for GNU ELPA are hosted here:

https://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/elpa-packages

Note the :url for bbdb's recipe points to the nongnu.org host.
You can alter the recipe by specifying the URL of choice.
e.g.

``` emacs-lisp
(elpaca (example :url "https://someotherhost.org/"))
```

Does that help?

**Comment by jtamagnan** [comment]
Oh holy smokes, that make so much sense. I think I was led astray by the elpa website pointing to the gnu version of the code instead of the nongnu version that it was actually using - https://elpa.gnu.org/packages/bbdb.html. If anything this seems like a bug on the Elpa website
