### ISSUE TITLE
[Bug/Support]: Origin of packages installed

### ISSUE THREAD

**Issue by bmp** [progfolio/elpaca#328]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca b8ed514 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 31.0.50 (build 5, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
 of 2024-07-03
git --version:  git version 2.45.2

### Operating System

OS: Fedora Linux 40 (KDE Plasma) x86_64
Kernel: Linux 6.9.7-200.fc40.x86_64

### Description

I checked the wiki and the issues, but maybe my search terms were wrong. But here is a very short description of what I have noticed. I'm not sure if it is a bug or if it is my configuration, so I haven't edited the title.

I use packages from the respective repositories, MELPA and ELPA. However, in the elpaca manager buffer, many show up as MELPA/ELPA even though I am setting them up as from the source repositories, I have attached screenshots below for two packages which I am fetching from the repostories, there are more such examples in my setup. Is it because of some configuration that I have or is this expected behaviour? Though the full recipe is correct, shouldn't the source also be based on the full recipe rather than menu item recipe?

1. Wallabag:
   Showing source as init file:
   ![Screenshot_20240703_184814](https://github.com/progfolio/elpaca/assets/1095177/80ac947e-0598-4983-848e-10881e146836)
   The recipe being used:
   ![Screenshot_20240703_184828](https://github.com/progfolio/elpaca/assets/1095177/ace701b1-5686-43b7-bd6e-513b2ed23c73)

2. Mastadon:
   Showing the source as MELPA:
   ![Screenshot_20240703_185127](https://github.com/progfolio/elpaca/assets/1095177/a54af248-9423-48e2-9d33-875cda886dc1)
   The recipe being used:
   ![Screenshot_20240703_185138](https://github.com/progfolio/elpaca/assets/1095177/b5e763b9-1e3a-493f-b53d-89f29739e359)

**Comment by progfolio** [comment]
> 1. Wallabag: Showing source as init file:

A Wallabag menu item does not exist in any of the pre-configured ELPAs, so the source is set to "Init File" for convenience's sake.

> 2. Mastadon: Showing the source as MELPA:

Altering the recipe in your init file does not change the menu item's source.
To give a real world analogue, ordering a burger from McDonald's with extra pickles doesn't make the recipe "homemade".

The `elpaca-info` view shows the original menu-item recipe.
It also shows the computed recipe (the result of any configuration/modifications plus the inherited properties from that particular menu item) that would be used with that source.

In the manager view you can use the `#installed #unique` search tags to show packages which are installed and which sources they are pulling any recipe inheritance from. 
Is there something in particular you'd hope to gain from seeing the source be "Init File" (which is implied by virtue of them being installed) for those packages?
If I have a clearer picture of what you're trying to achieve, I may be able to suggest a custom search tag which shows what you'd like.

**Comment by progfolio** [comment]
> The analogue does make it clear, thank you!

You're welcome.

> 2. I was hoping to quickly filter these packages that are fetched from such
>    sources, and then be able to see the changes made to these packages at source
>    before I merge them.
> 
> Does this make sense?

Yes. I understand what you're aiming for now.
I would recommend using a custom search tag in this case.
Search tags are implemented as functions which take a list of tabulated-list-entries and optionally return a similar list.
In this case the heavy lifting is already done by Elpaca's #update-log search tag.
We just want to filter those results so only packages for which you've declared a `:branch`. 


The following function should do that:


``` emacs-lisp
(defun +elpaca-branched-entries (entries)
  "Return #update-log entries for packages with a :branch declared."
  (cl-loop for entry in entries
           for id = (ignore-errors (caar entry))
           for e = (and id (elpaca-get id))
           when (and e (plist-get (elpaca<-order e) :branch))
           collect entry))
```


Then you can customize `elpaca-log-search-tags` to alias to a tag name of your choosing.
For example, the following customization will result in a tag `#branched` in elpaca-log-mode views:

``` emacs-lisp
(with-eval-after-load "elpaca-log"
  (add-to-list 'elpaca-log-search-tags (cons 'branched #'+elpaca-branched-entries)))
```

You can then run `elpaca-fetch-all`, which should default to search query of `#latest #update-log`. `C-u` `s` will then allow you to edit the current Elpaca UI search query.
adding `#branched` to the end should filter the list to your desired entries.
You can live preview them with `elpaca-log-update-mode` and use all the usual features of the log view.

Does that help?

**Comment by progfolio** [comment]
I'll consider this issue closed for now. Feel free to comment if you have any more questions. Thanks.
