### ISSUE TITLE
[Bug]: point in *elpaca-log* buffer does not reflect new logs

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [progfolio/elpaca#33]
### Emacs Version

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)

### Operating System

Guix System 371aa5777a3805a3886f3feea5f1960fe3fe4219 x86_64 

### Bug Description

When the elpaca log buffer is displayed and actions are being logged into it, point stays at the beginning of the buffer.

In my experiences with logs which are actively updated, the point automatically goes to the bottom so that the user can see what's happening. Otherwise, the user has to keep scrolling down. This is what I think should be the default.

A specific example, I called `elpaca-rebuild` on `elpaca` to test a new commit and then the log buffer came up but I was confused momentarily and didn't know what was happening because I didn't see any change--there actually was change happening, but at the bottom of the buffer. My view was at the top of the buffer.

**Comment by progfolio** [comment]
Thanks for the report.


This a known issue, and I agree it could be improved.

 Emacs `tabulated-list-mode` has a way to print entries while remembering the user's position in the buffer. I believe when I wrote the log system I ran into performance issues using that method. I'll take another look at it to see if there's a way to retain the point without hitting the performance issue.

**Comment by progfolio** [comment]
I've pushed a change so that the log buffer will move point to the end of the buffer as log entries are printed.
