### ISSUE TITLE
[Bug/Support]: How do I update this dependency seperately using Elpaca?

### ISSUE THREAD

**Issue by TriAttack238** [progfolio/elpaca#331]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 2, x86_64-w64-mingw32)
 of 2024-03-24
git --version:  git version 2.45.2.windows.1

### Operating System

Windows 11

### Description

I'm trying to install Magit using Elpaca and the `elpaca` macro in my init file, and I've come across an interesting problem:

![image](https://github.com/progfolio/elpaca/assets/101959987/38844822-eefd-4b73-b820-2898393b573d)

When this package was initially installed, the update for git-commit was blocked by the installation of magit, and vice versa. This led to this situation:

![Screenshot 2024-07-10 231722](https://github.com/progfolio/elpaca/assets/101959987/c90776d1-9423-4ba3-b0c6-083ab187ef64)

I can use `elpaca-update` to first update git-commit and then properly install magit, but this does not last when I end the session and start a new one. What exactly is the permanent solution in this situation?

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a ticket.


> I'm trying to install Magit using Elpaca and the `elpaca` macro in my init file,
> and I've come across an interesting problem:
> 
> ![image](https://github.com/progfolio/elpaca/assets/101959987/38844822-eefd-4b73-b820-2898393b573d)

This means you need to either install a newer version of transient.el than is shipped with your Emacs version, or pin magit to an older verison that will work with the built-in version of transient.el.
e.g.

``` emacs-lisp
;; Install the latest transient.el
(elpaca transient)
(elpaca magit)
```

OR:

``` emacs-lisp
;; Install a specific version of magit.
(elpaca (magit :depth nil :tag "v3.0.1"))
```
  
> When this package was initially installed, the update for git-commit was blocked
> by the installation of magit, and vice versa.

This type of deadlock is a bug, but I've not been able to reproduce it.
Interestingly, another user reported such a deadlock on Windows 11:

https://github.com/progfolio/elpaca/issues/302

Please share your config and I'll take a look.

**Comment by TriAttack238** [comment]
Ah, so it looks like I missed that another dependency was the problem. Before I change anything, here is my entire `init.el`. But because I'm just starting out, it's pretty small:

```
;;Welcome to my Emacs config!

;;Use-Package Macro
;; This is only needed once, near the top of the file
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  (add-to-list 'load-path "<path where use-package is installed>")
  (require 'use-package))



;; knowledge if from https://systemcrafters.net/emacs-from-scratch/basics-of-emacs-configuration/

(setq inhibit-startup-message t
      visible-bell t) ;Control whether the startup screen happens



(global-display-line-numbers-mode 1)

;;TODO: get a better theme

(load-theme 'modus-vivendi t)

(hl-line-mode 1)

(blink-cursor-mode 1)

(setq history-length 25)

(savehist-mode 1)

(save-place-mode 1)

(setq custom-file (locate-user-emacs-file "custom-vars.el"))
(load custom-file 'noerror 'nomessage)

(global-auto-revert-mode 1)

(setq global-auto-revert-non-file-buffers t)

;;Installed through Msys2
;;pacman -S mingw64/mingw-w64-x86_64-aspell
;;pacman -S mingw64/mingw-w64-x86_64-aspell-en

(setq ispell-program-name "aspell")

(setq ispell-dictionary "english")

(context-menu-mode t)

(dolist (hook '(text-mode-hook ))
  (add-hook hook #'flyspell-mode))


;;Bootstrap for Elpaca, a package manager

(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Uncomment for systems which cannot create symlinks:
(elpaca-no-symlink-mode)

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))


;; Install Magit, the git porcelain
(use-package magit :ensure t :demand t)

```

> Install the latest transient.el

Wait, so the `elpaca` macro by default updates packages to the latest version? I suspected as such, but I don't remember it being explicitly stated in the documentation.

Ok, I just tried your advice by adding this code right before installing magit:

`(use-package transient :ensure t)`

This seems to have resolved issues for git-commit, but this error has appeared:

`Cannot determine Magit’s version (error "c:/Users/Sean Vo/AppData/Roaming/.emacs.d/elpaca/builds/magit/magit.el" repo static elpa dirname hash)`

**Comment by progfolio** [comment]
> ;;Welcome to my Emacs config!
> 
> ;;Use-Package Macro
> ;; This is only needed once, near the top of the file
> (eval-when-compile
>   ;; Following line is not needed if use-package.el is in ~/.emacs.d
>   (add-to-list 'load-path "<path where use-package is installed>")
>   (require 'use-package))

That part is unnecessary.
Installing `elpaca-use-package` ensures use-package is installed and activated if necessary.


> Wait, so the `elpaca` macro by default updates packages to the latest version?

It doesn't update anything.
It queues packages for installation (getting all the files on disk and built) and activation (adding the proper entries in `load-path`, loading autoloads).
It uses the package's source repository to do so.
Unless you specify a version you'd like to install in the package recipe, you get the latest version of the source repository by default.

> But this error has appeared:
> 
> `Cannot determine Magit’s version (error "c:/Users/Sean
> Vo/AppData/Roaming/.emacs.d/elpaca/builds/magit/magit.el" repo static elpa
> dirname hash)`

That's an error generated by the `magit-version` command (not Elpaca).
I've opened a PR to remedy that:

https://github.com/magit/magit/pull/5171

**Comment by TriAttack238** [comment]
> That part is unecessary 

Ah, must have read the documentation wrong.

>  It queues packages for installation (getting all the files on disk and built) and activation (adding the proper entries to the load-path, loading autoload).

So that means that it always matches the version of the repository it's drawing from, keeping packages up to date?

**Comment by progfolio** [comment]
> > It queues packages for installation (getting all the files on disk and built) and activation (adding the proper entries to the load-path, loading autoload).
> 
> So that means that it always matches the version of the repository it's drawing from, keeping packages up to date?

No. Once the package is installed, you will still need to update it when you want to. That is what the `elpaca-update`, `elpaca-fetch`, and `elpaca-merge` commands are for.

It just means that the *initial* installation will be from the current version of the repository if the recipe does not specify another version.

**Comment by TriAttack238** [comment]
I think I'm starting to get it. *Installing* using commands only installs for the current session, but _updating_ is something that persists between sessions. Also, as a beginner, how do I view a package update after I fetch it?

**Comment by TriAttack238** [comment]
Ok, everything is working as expected, but I thought at I might as well note this for future reference. When I trued to move the config I've been talking about (which is on my laptop) to my Windows 11 PC, everything seems to be the same except for these messages in `Async-native-compile-log`:

```
c:/Users/seank/.emacs.d/elpaca/builds/dash/dash.el: Error: Internal native compiler error failed to compile
c:/Users/seank/.emacs.d/elpaca/builds/magit/magit-transient.el: Error: Internal native compiler error failed to compile
```

As I just said things seem to be working fine, but that first error might mean that there's something wrong with compilation.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 2, x86_64-w64-mingw32)
 of 2024-03-24
git --version:  git version 2.45.2.windows.1

### Operating System

Windows 11

**Comment by progfolio** [comment]
> Installing using commands only installs for the current session, but updating is something that persists between sessions. 

Installing entails:

- downloading the repository to local disk
- byte-compiling elisp
- generating autoloads
- other build steps (generating Info manuals if present, etc)

That is skipped if a build folder for the package exists. 

Every time you queue a package (via use-package with elpaca integration or the `elpaca` macro itself) it is *activated*.
That's Emac's terminology for having the files be reachable via `load-path` and autoloads read so the package's entry point commands are available without an explicitly `require`.
This happens on each time Emacs is started.

When you update a package, you are changing the state of the source repository.
Then everything is rebuilt.
The next time you restart Emacs, that version of the package will be activated.


> how do I view a package update after I fetch it?

By default the `elpaca-log` command will show a query of `#latest #update-log` when `elpaca-fetch` is run. If there are any changes, they will be reported in the log. The commit hash will be a button which can be used to see the diff of each commit. If you wish to pull the changes in you can use `elpaca-merge` or the equivalent UI mode commands. There is also `elpaca-log-update-mode` which can be used to automatically show the diff associated with the current log entry in the elpaca-log when it is showing an update-log.


> Internal native compiler error failed to compile

That is an Emacs error that you should look into separately.
Elpaca does not handle native compilation.


>  ■  Warning (comp): magit-files.el:503:20: Warning: `sort' called with 1 argument, but requires 2

Looks like a possible bug with magit.
I would ask on that package's issue tracker.

**Comment by TriAttack238** [comment]
Thanks for the help, I'll go do that.
