### ISSUE TITLE
[Bug/Support]: Re-using /elpaca of running Emacs for temporary Emacs instances

### ISSUE THREAD

**Issue by psionic-k** [progfolio/elpaca#332]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca f19f4db HEAD -> idk, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
 of 2024-01-19
git --version:  git version 2.44.1

### Operating System

Linux 6.9.7

### Description

I'm developing dynamic libraries.  The workflow has issues though.  Emacs must be completely reloaded, so I have to spawn temporary Emacs instances.

My existing solution was just to give my current `load-path` variable to the new Emacs and then just load the freshly built dynamic module.

I can't recall clearly, but I'm sure you demonstrated how to do a test with specific version of an Elisp package using `elpaca-test`.  Maybe it was for using alternative versions of transient.  Maybe it was my imagination.

In any case, I feel like I'm duplicating work that Elpaca is already really good at.  I want to build the Elisp package, run the custom routine to build the dynamic library, and then start Emacs with the freshly built Elisp package and dynamic library loaded.

In the case that I'm developing out of the /elpaca directory, I suppose I can combine  `elpaca-rebuild` with some code from `elpaca-test`?  What parts of Elpaca should I employ?

**Comment by progfolio** [comment]
It sounds like you are aware of all the commands/macros that Elpaca has to offer that might help (`elpaca-rebuild`, `elpaca-test`). What have you tried so far? Do you have a specific question regarding either?

**Comment by progfolio** [comment]
I'll consider this closed for now. Feel free to comment if you have any specific questions. Thanks.
