### ISSUE TITLE
[Bug/Support]: Native Compilation Error, but only when using elpaca-use-package

### ISSUE THREAD

**Issue by TriAttack238** [progfolio/elpaca#333]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.3 (build 2, x86_64-w64-mingw32)
 of 2024-03-24
git --version:  git version 2.45.2.windows.1

### Operating System

Windows 11

### Description

I was trying to figure out why the internal compilation for magit seemed to not be working, and it seems be related to the use of `use-package` through `elpaca-use-package`. For example, if a certain section of my init.el file looks like this:

```
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))


;;Update Transient to make sure git-commit works
;; (use-package transient :ensure t)
(elpaca transient)

;; Install Magit, the git porcelain
;;(use-package magit :ensure t :demand t)
(elpaca magit)

```
Everything works as expected and there are no warnings or errors. But if I substitute this with `use-package`:

```
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))


;;Update Transient to make sure git-commit works
(use-package transient :ensure t)
;;(elpaca transient)

;; Install Magit, the git porcelain
(use-package magit :ensure t :demand t)
;;(elpaca magit)

```

Then the following warnings appear:

```
■  Warning (comp): c:/Users/seank/.emacs.d/elpaca/builds/elpaca/elpaca-log.el: Error: Internal native compiler error failed to compile
 ■  Warning (comp): c:/Users/seank/.emacs.d/elpaca/builds/magit/magit-base.el: Error: Internal native compiler error failed to compile
 ■  Warning (comp): c:/Users/seank/.emacs.d/elpaca/builds/magit-section/magit-section.el: Error: Internal native compiler error failed to compile
 ■  Warning (comp): c:/Users/seank/.emacs.d/elpaca/builds/magit/magit.el: Error: Internal native compiler error failed to compile
```

Could this be an issue with `use-package` or `elpaca-use-package`?

**Comment by progfolio** [comment]
I mentioned those errors in your other issue:

https://github.com/progfolio/elpaca/issues/331#issuecomment-2224265355

Elpaca does not perform native compilation. I think you should try and see if you can reproduce the issue with use-package without Elpaca. I would also search the emacs bug and devel mailing list archives to see if that error has been reported before.

**Comment by progfolio** [comment]
I'll consider this closed for now. Feel free to comment if you have any more information or a reproduction case that points to Elpaca. Thank you.
