### ISSUE TITLE
[Support]: Should we use no-byte-compile for all init?

### ISSUE THREAD

**Issue by meedstrom** [progfolio/elpaca#334]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
 of 2024-06-30, modified by Debian
git --version:  git version 2.45.2

### Operating System

Debian sid

### Description

This is just a request for clarification. The example init.el sets `no-byte-compile`, which makes sense for initting Elpaca itself, but what's not clear to me is if I should do it for the rest of init too.

I don't know how an elpaca form is quoted and expanded, so I wanted to check. Let's say I have a config.el which contains nothing but a lot of use-package forms, and I'm using `elpaca-use-package-mode` of course.  Do you expect compiling that into config.elc / config.eln to make a difference?

**Comment by progfolio** [comment]
From the Emacs manual:

https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html

> Byte-compiling your init file is not recommended (see [Byte Compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html#Byte-Compilation) in the Emacs Lisp Reference Manual). It generally does not speed up startup very much, and often leads to problems when you forget to recompile the file. A better solution is to use the Emacs server to reduce the number of times you have to start Emacs (see [Using Emacs as a Server](https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html)). If your init file defines many functions, consider moving them to a separate (byte-compiled) file that you load in your init file.

There was a point where I experimented with a byte-compiled init file, and I experienced all the issues mentioned above. Wasn't worth it. I don't plan on supporting byte-compiled init files at the moment.

**Comment by meedstrom** [comment]
Thanks! I also had issues when I experimented in the past, so I know the danger.  Perhaps just compiling the big file of defuns is a good balance.
