### ISSUE TITLE
[Support] use-package: Unrecognized keyword: :pretty-hydra

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#336]
Great, thanks very much for the help!

I upgraded to Emacs 29.4 and problem goes away!

However if you don't mind, I encountered another issue. 
I want to use elpaca and write something like this (borrowed from https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-ui.el#L118C1-L127C43 )

```
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :init
  (setq doom-modeline-icon centaur-icon
        doom-modeline-minor-modes t)
  :bind (:map doom-modeline-mode-map
         ("C-<f6>" . doom-modeline-hydra/body))
  :pretty-hydra
  ((:title (pretty-hydra-title "Mode Line" 'sucicon "nf-custom-emacs" :face 'nerd-icons-purple)
    :color amaranth :quit-key ("q" "C-g"))
```

but I got error:

```
⛔ Error (use-package): Failed to parse package doom-modeline: use-package: Unrecognized keyword: :pretty-hydra
```

I tried to `(require 'pretty-hydra)` but it says can't find it even though I can see elpaca already cloned and build it and `load-path` has its directory in it.

_Originally posted by @emacsbliss in https://github.com/progfolio/elpaca/issues/335#issuecomment-2251762677_

**Comment by progfolio** [comment]
pretty-hydra needs to be activated prior to using it.
Add `:wait t` to pretty-hydra's recipe.
This is explained in several places, e.g. the demo init.el file:

https://github.com/progfolio/elpaca/blob/ec0e5438c00fedb7371fadf70003e494ee9bc91e/doc/init.el#L54-L58

**Comment by emacsbliss** [comment]
Great, it works! Thanks a lot!

**Comment by progfolio** [comment]
> Great, it works! Thanks a lot!

Glad it worked. Thanks.
