### ISSUE TITLE
[Support]: Update package upstream remote

### ISSUE THREAD

**Issue by emacsomancer** [progfolio/elpaca#337]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)
 of 2024-07-23
git --version:  git version 2.45.2

### Operating System

Linux

### Description

How to update repos themselves? (E.g., have elpaca redownload the repo sources.) I noticed for my own package, when I migrated git hosts, that elpaca was still looking at the old host location, and I couldn't figure out how to fix this other than completely deleting ~/.emacs.d/elpaca and having elpaca start from scratch. (And I saw a notice today that AUCTeX is shifting to ELPA-only, and so was thinking about this.)

**Comment by progfolio** [comment]
> How to update repos themselves? (E.g., have elpaca redownload the repo sources.)

Do you mean changing the upstream remotes?

> I noticed for my own package, when I migrated git hosts, that elpaca was still
> looking at the old host location, and I couldn't figure out how to fix this
> other than completely deleting ~/.emacs.d/elpaca and having elpaca start from
> scratch.

Either of the following should work:

- Manually change the upstream remote via git or magit
- `M-x elpaca-delete` the package (it will be reinstalled on restart).

Deleting the entire Elpaca package store is almost never necessary.

Does that help?

**Comment by emacsomancer** [comment]
Thanks!

Yes, that seems to work - using `elpaca-delete`.
