### ISSUE TITLE
[Bug/Support]: how to install package from local file

### ISSUE THREAD

**Issue by emacsbliss** [progfolio/elpaca#339]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ec0e543 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 2, aarch64-apple-darwin23.3.0, NS appkit-2487.40 Version 14.3.1 (Build 23D60))
 of 2024-07-25
git --version:  git version 2.45.2

### Operating System

MacOS 14.3.1 (23D60)

### Description

with `straight.el` I can do something like this:

```
(use-package my-snippets
  :straight
    (:local-repo "~/.dotfiles/emacs/lisp"
     :files ("my-snippets.el")))
```

here the `lisp` directory is not a standalone repo, rather it's in the same repo as my other emacs config file.

I tried something like this but does not work:

```
(use-package my-snippets
  :ensure (:repo  "~/.dotfiles/emacs/lisp"
     :files ("my-snippets.el")))
```

I'm getting error:

```
my-snippets                 failed                 fatal: repository '/Users/emacsbliss/.dotfiles/emacs/lisp' does not exist
```

I guess elpaca assume that path is a git repo? How could I achieve the same thing with `elpaca`?

**Comment by progfolio** [comment]
> I guess elpaca assume that path is a git repo? How could I achieve the same
> thing with `elpaca`?

Point `:repo` to the repo's path and use `:files` to select files relative to that.
e.g.

``` emacs-lisp
(elpaca (example :repo "~/.dotfiles/" :files ("emacs/lisp/*.el")))
```

**Comment by emacsbliss** [comment]
awesome, that works!! Thanks a lot for helping out!!
