### ISSUE TITLE
[Bug/Support]: 

### ISSUE THREAD

**Issue by Lenbok** [progfolio/elpaca#342]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 1458996 HEAD -> master, origin/master, origin/HEAD

### Operating System

Linux mint

### Description

I have magit/forge etc installed through elpaca. ghub seems to be dependency of these. I tried to do an update, and elpaca complains:

```
elpaca--dependencies: Dependency detection error: "ghub-pkg.el" (file-missing "Opening input file" "No such file or directory" "/home/len/.emacs.d/elpaca/repos/ghub/ghub-pkg.el")
```

When I look in the repo elpaca has checked out for ghub, I see there is a recent commit that removes `ghub-pkg.el`. 

What is the corrective action here? I tried `elpaca-delete` and it gave the same error.

**Comment by Lenbok** [comment]
I nuked my `.emacs/elpaca` folder, and when rebuilding it encountered errors in a few packages with complaints about magit version (0) being lower than min version required. I then updated my magit recipe to `:ensure (magit :depth nil)`, deleted the checked out magit repo, and restarted. elpaca was then able to build everything OK.

It seems magit plays fast and loose with whatever packaging requirements elpaca expects.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> ### Elpaca Version
> 
> Elpaca 1458996 HEAD -> master, origin/master, origin/HEAD

You're running a slightly out of date version of Elpaca.
Please try updating Elpaca first:

1. `M-x elpaca-update` `elpaca`
2. `M-x restart-emacs`


> ### Description
> 
> I have magit/forge etc installed through elpaca. ghub seems to be dependency of
> these. I tried to do an update, and elpaca complains:
> 
> ```
> elpaca--dependencies: Dependency detection error: "ghub-pkg.el" (file-missing "Opening input file" "No such file or directory" "/home/len/.emacs.d/elpaca/repos/ghub/ghub-pkg.el")
> ```

What specific commands did you run to update?
  
> When I look in the repo elpaca has checked out for ghub, I see there is a recent
> commit that removes `ghub-pkg.el`.

Could you point me to that commit?
  
> What is the corrective action here? I tried `elpaca-delete` and it gave the same
> error.

What specific command did you try? `elpaca-delete` `ghub`?

**Comment by progfolio** [comment]
> I nuked my `.emacs/elpaca` folder

Please see  https://github.com/progfolio/elpaca/wiki/Troubleshooting#dont-delete-everything

> a few packages with complaints about magit version (0) being lower than min
> version required.

It looks like the MELPA recipe for magit has recently been altered to point to a "melpa" branch:
https://github.com/melpa/melpa/blob/51b0a905d5748d4d4f2e807435e56c6c2a312edb/recipes/magit#L4

The tip of that branch includes a magit-pkg.el file with a version of "0":
https://github.com/magit/magit/commit/622c6c37e0d615dc63e33e430ea20251778e9a61

I consider that a bug on magit's end. If they're going to the trouble of publishing the pkg.el files, they should include the correct information. Elpaca is flexible enough to work around that. See the following test case:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init (setq elpaca-menu-functions '(elpaca-menu-melpa))
  :init
  ;; Use the main branch instead of MELPA
  (elpaca (magit :host github :repo "magit/magit" :branch "main" :wait t))
  (princ (elpaca-info 'magit)))
```


</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>edc0dc2 HEAD -> master, origin/master, origin/HEAD, refactor/menu-cache</td>
<tr><td>installer</td><td>0.7</td>
<tr><td>emacs</td><td>GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0) of 2024-08-12</td>
<tr><td>git</td><td>git version 2.46.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping 16 files for loaddefs... 
  INFO     Scraping 16 files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.HmAIpD/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.HmAIpD/elpaca/repos/elpaca...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/doc/init.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/doc/installer.el...
Checking /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/test/elpaca-test.el...
Compiling /tmp/elpaca.HmAIpD/elpaca/repos/elpaca/test/elpaca-tests.el...
Done (Total of 12 files compiled, 4 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
magit
A Git porcelain inside Emacs.

source: MELPA
url: https://github.com/magit/magit
[OMITTED INFO]
installed version: 4.0.0 cd959c7
```
</details>

Alternatively the [:main recipe keyword](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#main) could be used to point to the file containing the correct version information (lisp/magit.el in this case).
