### ISSUE TITLE
[Bug/Support]: forge installed version (0) lower than min required 0.3 

### ISSUE THREAD

**Issue by domsch1988** [progfolio/elpaca#344]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca edc0dc2 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.60 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
 of 2024-07-30
git --version:  git version 2.39.2

### Operating System

Debian Stable

### Description

On trying to setup my existing configuration on a new Laptop, elpaca fails to install some packages:
```
 Package Status Info Time ▼ 
embark-vc                      failed               forge installed version (0) lower than min required 0.3                          56.827632
treemacs-magit                 failed               magit installed version (0) lower than min required 2.90.0                       66.561451
org                            activation           Autoloads cached                                                                 120.235017
org-roam                       unblocked            Checking dependency versions                                                     120.235089
consult-org-roam               failed               Failed dependencies: (org-roam)                                                  120.329158
```
Magit and forge both are installed fine. I can use magit as always. I also tried adding forge in a use-package statement, but that didn't change the issue. I tried a completely clean clone of my config without any caches, without success.

If needed, the configuration can be found here: https://gitlab.com/domsch1988/minemacs

**Comment by progfolio** [comment]
Please see the pinned issue: https://github.com/progfolio/elpaca/issues/343

Let me know if that helps.

**Comment by progfolio** [comment]
I'm assuming you've got this figured out, so I'll consider this closed. Feel free to comment if you still need support and I can reopen the issue. Thanks.
