### ISSUE TITLE
[Feature]: make elpaca-manager more discoverable

### ISSUE THREAD

**Issue by meedstrom** [progfolio/elpaca#346]
### Feature Description

This week in "Users are stupid":

Some people use M-x autocompletion to browse commands. When I try `M-x elpaca-ui-browse-package` it fails with "No package at point", so I figured you have to be in elpaca-ui for it to work,  but it took me months to find the `M-x elpaca-manager` command.  I was not really trying very hard, but still, it could be something to think about. :-)  

Maybe elpaca-manager can just be called elpaca-ui?  IDK, but at least the "No package at point" message could be more informative when you're in the wrong buffer, telling you to do M-x elpaca-manager.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> ### Feature Description
> Some people use M-x autocompletion to browse commands. When I try `M-x elpaca-ui-browse-package` it fails with "No package at point", so I figured you have to be in elpaca-ui for it to work

Correct. There are a number of commands that are only intended to work in the ui mode.
Emacs 28 introduced a way to filter inform `M-x` that some commands are only relevant in certain modes.
The situation can be improved once support for Emacs 27.1 is dropped.

> but it took me months to find the `M-x elpaca-manager` command.  I was not really trying very hard, but still, it could be something to think about. :-)  

I'm not sure what I can do other than autoloading the command and mentioning it in the manual.
It is mentioned on the first line of the "Quick Start" section's table for "Finding Packages".

> Maybe elpaca-manager can just be called elpaca-ui?

`elpaca-manager` is more for searching for packages.
It's flexible enough to operate on installed packages as well,
but the "UI" is also associated with the log.
I'm not opposed to finding an alias, but `elpaca-ui` is too generic.

**Comment by meedstrom** [comment]
Sounds fair.  Then I only suggest amending "No package at point" to something like "Not in elpaca-manager nor elpaca-log buffer".  Up to you. You can close this.

**Comment by progfolio** [comment]
> Sounds fair. Then I only suggest amending "No package at point" to something
> like "Not in elpaca-manager nor elpaca-log buffer".

Thanks for the suggestion.
I've made it so the error is "Not in elpaca-ui-mode buffer" when such commands are invoked outside the intended buffer, and "No package at point" when invoked at the wrong point within such a buffer.
