### ISSUE TITLE
[Bug]: Search prompt "Search (empty to clear)" wrongly implies an empty candidate will do unfiltered search

### ISSUE THREAD

**Issue by meedstrom** [progfolio/elpaca#347]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
 of 2024-06-30, modified by Debian
git --version:  git version 2.45.2
```

### Operating System

Debian sid

### Description

I tried to list all packages, including installed packages.  I saw the top bar saying "matching #unique !#installed", so I thought to myself, okay, let's remove that filter.  M-x elpaca filter... no match... M-x elpaca match... no match... hmm.. Ok, elpaca search!  And it says empty to clear, jackpot! Press RET with an empty string.   Hmm, that's odd, it didn't clear the filter.

Just an user story... 

I've since found the `g i` command, and I know if I want to see both installed and uninstalled I can type just "#unique", so I'm good. I'm still not sure how to show a totally unfiltered list, but I guess it's not important.  Anyway, the prompt "Search (empty to clear)" would maybe be more precise if it said something like "(empty for default filter)" instead.

**Comment by progfolio** [comment]
>Press RET with an empty string. Hmm, that's odd, it didn't clear the filter.

In that case the default query, as determined by elpaca-ui-default-query, is used.
I've amended the wording of the prompt to reflect that.
  
> I'm still not sure how to show a totally unfiltered list

The search works with regular expressions. `.*` should match everything.

Does that help?

**Comment by meedstrom** [comment]
Yep! Thanks!
