### ISSUE TITLE
[Support]: tab-bar, scroll-bar modes re-enabled during init

### ISSUE THREAD

**Issue by jsyjr** [progfolio/elpaca#348]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 7b5e269 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin23.6.0, NS appkit-2487.70 Version 14.6.1 (Build 23G93))
 of 2024-08-28
git --version:  git version 2.39.3 (Apple Git-146)

### Operating System

MacOS Sierra

### Description

In early-init.el I configure emacs for no menu-bar, no tool-bar, no tab-bar and no scroll bars.
Running elpaca leaves tab-bars and vertical scroll bars  re-enabled.
I have hacked around the issue by including in my elpaca-after-init-hook function these forms:

            (tab-bar-mode -1)
            (scroll-bar-mode -1)

(I have not searched the documentation, but I did search the elpaca source code for obvious mentions of tab-bar or scroll-bar.)

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

Do you see the issue if you evaluate the following test?

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :interactive t
  :early-init
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tab-bar-mode -1))
```

Do you have a link to the configuration which displays the issue?

>  I did search the elpaca source code for obvious mentions of tab-bar or scroll-bar

Elpaca does not enable or disable any of the mentioned modes.

**Comment by progfolio** [comment]
I'm unable to reproduce the issue on my end.
I'll consider this closed for now.
Feel free to comment if you are able to reproduce the issue with the test case above or a minimal reproduction case and I can open the issue and look into it more.
