### ISSUE TITLE
[Feature]: Provide a function entry in addition to the elpaca macro one.

### ISSUE THREAD

**Issue by daanturo** [progfolio/elpaca#35]
### Feature Description

Currently `elpaca` is a macro, which makes it cumbersome to write wrappers around that.

Maybe define a function named `elpaca*` (like `evil-define-key` and `evil-define-key*`)?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Hi. Thanks for the suggestion.

Could you give me some examples of wrappers you had in mind?

**Comment by daanturo** [comment]
Thank you for your consideration.

Currently I have only one of such:

```emacs-lisp

(defun my-pkg-args->elpaca-recipe (pkg url &optional branch rev)
  `(,pkg
    ,@(and branch `(:branch ,branch))
    ,@(and rev `(:ref ,rev :pin t))
    ,@(and url `(:url ,url))))

;; the wrapper
(cl-defun my-pkg-ensure (pkg &optional url &key branch rev
                             now globs)
  (my-elpaca-add (my-pkg-args->elpaca-recipe pkg url branch rev) now))

(defun my-elpaca-add (recipe &optional now)
  (eval `(elpaca ,recipe) t) ;; <- macro usage here
  (when now (elpaca-process-queues)))

```

The `eval` form could be simpler/more robust: `(elpaca* recipe)`.

**Comment by progfolio** [comment]
The Elpaca macro is designed to handle backquoted lists as orders.
The following should be simpler and work similar to what you have above:

```emacs-lisp
(cl-defun +my-pkg-ensure (pkg &optional url &key branch rev now)
  (elpaca `(,pkg
            ,@(and branch `(:branch ,branch))
            ,@(and rev `(:ref ,rev :pin t))
            ,@(and url `(:url ,url))))
  (when now (elpaca-process-queues)))
```

> more robust

Could you elaborate on this point? I'm don't see how providing a function would be any more robust.

**Comment by daanturo** [comment]
> Could you elaborate on this point? I'm don't see how providing a function would be any more robust.

That's about byte-compilation, a macro need `require`ing its provided library.

**Comment by progfolio** [comment]
I can't say I find that a convincing reason to expand Elpaca's API at the moment.
I've added it as a requested feature to my notes, though.
Closing for now, but we can re-evaluate down the road.
