### ISSUE TITLE
[Bug/Support]: Local branch deleted

### ISSUE THREAD

**Issue by meedstrom** [progfolio/elpaca#351]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca c6395a6 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
 of 2024-06-30, modified by Debian
git --version:  git version 2.45.2

### Operating System

Debian sid

### Description

Hi, first, thanks for Elpaca, it is very cool!

I am not sure if I am doing it wrong, but I like to develop my package directly in the elpaca/repos/package/ directory.

The directory was originally created by this initfile expression

```elisp
(use-package org-node
  :ensure (:fetcher github :repo "meedstrom/org-node"
                    :files (:defaults (:exclude "org-node-fakeroam.el"))
                    :branch "main"))
```

Now, I decided to remove `:branch "main"` because that is the default branch anyway.  Should make no difference, right?

Cue a restart and... well, the "main" branch is gone, and only the "melpa" branch is there.    I had some unfinished work in my local "main" branch, I'm guessing I can't get it back, but hopefully someone else does not have to go through that.

Context: my Melpa recipe does specify `:branch "melpa"`, but I did not think that my use-package expression with a custom `:ensure` would inherit anything from Melpa's recipe.

Also it would be nice if local branches were never erased, I think.  No matter how the use-package expression changes over time.

Another detail for completeness, I had also run `git fetch --unshallow` and then added `:depth nil` to the expression, not sure if that matters. I think it was the same restart.

**Comment by progfolio** [comment]
> Hi, first, thanks for Elpaca, it is very cool!

Thank you for the kind words. I'm glad you're finding Elpaca useful.

> I am not sure if I am doing it wrong, but I like to develop my package directly
> in the elpaca/repos/package/ directory.
> 
> The directory was originally created by this initfile expression
> 
> ```elisp
> (use-package org-node
>   :ensure (:fetcher github :repo "meedstrom/org-node"
>                     :files (:defaults (:exclude "org-node-fakeroam.el"))
>                     :branch "main"))
> ```
> 
> Now, I decided to remove `:branch "main"` because that is the default branch
> anyway. Should make no difference, right?

> Cue a restart and... well, the "main" branch is gone, and only the "melpa"
> branch is there. I had some unfinished work in my local "main" branch, I'm
> guessing I can't get it back, but hopefully someone else does not have to go
> through that.

The repository will not be touched unless the repo has been deleted and needs to be recloned.
  
> Context: my Melpa recipe does specify `:branch "melpa"`, but I did not think
> that my use-package expression with a custom `:ensure` would inherit anything
> from Melpa's recipe.

`elpaca-order-defaults` has `:inherit t` in it.
You can override that on a per recipe basis by adding `:inherit nil`, or changing the value of that variable to do so globally.
  
> Also it would be nice if local branches were never erased, I think. No matter
> how the use-package expression changes over time.

They should not be. I was not able to reproduce the issue on my end.
Perhaps I am missing some steps you took?

See if you can reproduce the issue using an interactive test session:

``` emacs-lisp
(elpaca-test
  :interactive t
  :init
  (elpaca elpaca-use-package (elpaca-use-package-mode))
  (use-package org-node
    :ensure (:fetcher github :repo "meedstrom/org-node"
                      :files (:defaults (:exclude "org-node-fakeroam.el"))
                      :branch "main")))
```

Let me know what steps you take if you can and I will look into it.

**Comment by meedstrom** [comment]
I can not reproduce it either, sorry to say. Even elpaca-rebuild or elpaca-update keeps the branch on "main".  When would it switch to the inherited `:branch` setting, if ever?

**Comment by progfolio** [comment]
> I can not reproduce it either, sorry to say. Even elpaca-rebuild or elpaca-update keeps the branch on "main". When would it switch to the inherited `:branch` setting, if ever?

Currently the branch is only considered during the initial clone.
That's by design so one can switch branches freely while developing a package.

> Feel free to close the issue. I can make a new one another day if it recurs.

Sounds good. Let me know if you find a way to reproduce the issue.
