### ISSUE TITLE
[Support]: Multiple packages in emacs/elpa respository

### ISSUE THREAD

**Issue by telenieko** [progfolio/elpaca#355]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca df557d6 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)
git --version:  git version 2.46.0

### Operating System

Fedora Silverblue 40, Emacs installed via home-manager (nix)

### Description

There are several recipes that rely on different branches of the same repository. See the screenshots below of `elpaca-info` for `peg` and `queue`.

It does not seem possible to install both packages with `elpaca` as it appears to do one single clone of the repository (under `repos/elpa` in this case) which prevents it from having two different branches checked out at the same time.

Other than having two different clones of the repository, one for each package, I don't see how else to fix that?

![image](https://github.com/user-attachments/assets/faa7de68-b968-44ae-8b27-c57250e0f2b8)

![image](https://github.com/user-attachments/assets/f20759cf-6695-4145-96d3-91bcabfb76c4)

**Comment by progfolio** [comment]
> It does not seem possible to install both packages with `elpaca` as it appears
> to do one single clone of the repository (under `repos/elpa` in this case) which
> prevents it from having two different branches checked out at the same time.
> 
> Other than having two different clones of the repository, one for each package,
> I don't see how else to fix that?

Elpaca will clone the repository for each package. See the output of the following test case, which successfully installs peg and queue:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init
  (elpaca peg)
  (elpaca queue)
  (elpaca-wait)
  (princ (elpaca-log "#unique")))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>ac6f563 HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>installer</td><td>0.7</td>
<tr><td>emacs</td><td>GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2) of 2024-09-12</td>
<tr><td>git</td><td>git version 2.46.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping 16 files for loaddefs... 
  INFO     Scraping 16 files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.yMvbv2/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.yMvbv2/elpaca/repos/elpaca...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/doc/init.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/doc/installer.el...
Checking /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/test/elpaca-test.el...
Compiling /tmp/elpaca.yMvbv2/elpaca/repos/elpaca/test/elpaca-tests.el...
Done (Total of 12 files compiled, 4 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...

queue                          finished             ✓ 0.826 secs                                                                     04.723433
elpaca                         finished             ✓ 0.842 secs                                                                     04.739375
peg                            finished             ✓ 1.015 secs                                                                     04.913057
```
</details>

This costs more disk space.
Possible optimizations have been discussed, but not implemented (e.g. sparse cloning these repositories).

**Comment by telenieko** [comment]
Thank you for the tips. I can reproduce the test run as instructed and in effect, the temporary directory has `peg` and `queue` inside `repos/`.

For some reason my Emacs is not doing that, it is doing `repos/elpa` with `peg` and then `queue` cannot be installed:

    (Debugger entered--Lisp error: (error "Unable to find main elisp file for \"queue\""

I am trying to pinpoint where the issue is (why my Emacs checkout peg as elpa).

**Comment by progfolio** [comment]
I see now in your screenshots (side note: https://github.com/progfolio/elpaca/wiki/Troubleshooting#prefer-text-over-screenshots)  that you still have recipes which refer to the `:local-repo` recipe keyword, which has been removed.  Try:

1. `M-x elpaca-update-menus` to pull the new recipes for those packages. 
2. `M-x elpaca-delete` both peg and queue.
3. `M-x restart-emacs`

The packages should then be installed correctly.

**Comment by telenieko** [comment]
That fixed it! Thank you.

Noted the comment about screenshots!

**Comment by progfolio** [comment]
> That fixed it! Thank you.

Glad it worked out. Thank you.

**Comment by pcn** [comment]
Thank you for this clear answer. I was stuck with queue not installing properly. Is there a way to use elpaca-update-menus to update all recipes in cases like this, since I needed to update 7 manually when just elpa by itself didn't address whatever the source of the failure was.

**Comment by progfolio** [comment]
> Thank you for this clear answer.

You're welcome.

> Is there a way to use elpaca-update-menus to update all recipes in cases like
> this, since I needed to update 7 manually when just elpa by itself didn't
> address whatever the source of the failure was.

See the docstring of `elpaca-update-menus`:

``` emacs-lisp
(elpaca-update-menus &rest MENUS)

Update all menus in MENUS or ‘elpaca-menu-functions’.
When called interactively with C-u update all menus.
```
