### ISSUE TITLE
[Feature]: document how to start elpaca

### ISSUE THREAD

**Issue by jbulow** [progfolio/elpaca#357]
### Feature Description

It is not clear from the documentation how to start the "UI". When/where are the documented keybindings available?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by jbulow** [comment]
Where does the keys "g m" work? What is "UI" in this context?
Pressing "f x" in elpaca manager is documented as "fetching package updates". It is not clear how this should be used to update installed packages. It expects the cursor to be on a package. The package list defaults to all packages. 

Very hard to see what the normal workflow is for managing packages.

**Comment by progfolio** [comment]
There is an acoompanying video linked from the README.

**Comment by jbulow** [comment]
Yes, it does not answers this question or is it updated very recently?

**Comment by progfolio** [comment]
The video does answer the questions, though it is mildly out of date.
There's also a section on the UI in the [manual](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#ui).
What have you tried so far?
