### ISSUE TITLE
[Bug]: elpaca-build-steps destructively modified through delq

### ISSUE THREAD

**Issue by Alan-Chen99** [progfolio/elpaca#363]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 9d977fb grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu)
git --version:  git version 2.25.1

### Operating System

ubuntu

### Description

This `delq` here
https://github.com/progfolio/elpaca/blob/9d977fb9864e32b5dc7d93d2a6076b30fddf1795/elpaca.el#L542
potentially modifies `elpaca-build-steps` destructively, causing `elpaca--clone` to be permanently removed. 
This only manifests if one inserts something before `elpaca--clone` in `elpaca-build-steps`.
changing it to `remq` fixes the problem.

**Comment by progfolio** [comment]
> This `delq` here
> https://github.com/progfolio/elpaca/blob/9d977fb9864e32b5dc7d93d2a6076b30fddf1795/elpaca.el#L542
> potentially modifies `elpaca-build-steps` destructively

Good eye. Thank you. Fixed on master.
