### ISSUE TITLE
[Support]: Altering packages

### ISSUE THREAD

**Issue by jinzhongjia** [progfolio/elpaca#365]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 3f122fc grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 2, x86_64-w64-mingw32)
 of 2024-07-05
git --version:  git version 2.46.2.windows.1

### Operating System

windows 11 23H2

### Description

I am trying to debug a small bug in lsp-mode. Now I have made a little modification in the local clone, and I want to directly import the local package. How should I set it up?
https://github.com/progfolio/elpaca/issues/339
I found this issue, but according to the description, I set it like this

```lisp
(use-package lsp-mode
  :ensure '(lsp-mode :repo "C:\\Users\\jinzh\\code\\lsp-mode")
  :commands (lsp lsp-deferred)
  :hook (prog-mode . lsp-deferred))
```
But it is still the imported github package
Are there any other settings I should make?

**Comment by progfolio** [comment]
> - [X] I am checking these without reading them.

Please take care when filling out the issue form.

> I am trying to debug a small bug in lsp-mode. Now I have made a little
> modification in the local clone, and I want to directly import the local
> package. How should I set it up?

If you modified the files for lsp-mode under `$ELPACA-DIRECTORY/repos/lsp-mode/`, you'll want to invoke `M-x elpaca-rebuild` `lsp-mode` to recompile the files. They will be reloaded after restarting Emacs. There's no need to store a separate, local copy of the repository.

Does that help?

**Comment by jinzhongjia** [comment]
Can it be achieved without building?
It is a little inconvenient to build and change the code in the elpaca directory.

**Comment by progfolio** [comment]
> Can it be achieved without building?

You can interactively evaluate forms you've changed via the typical evaluation commands (e.g. `eval-last-sexp`, `eval-defun`, `eval-buffer`...). Try `M-x apropos-command` and searching for `^eval`. That will immediately load your changes in the current Emacs image. That will work regardless of what package manager is being used.

> It is a little inconvenient to build and change the code in the elpaca directory.

Far from it. I use the following workflow daily:

1. `M-x find-library` `name of package`
2. Alter the package.
3. `C-u elpaca-rebuild`  to rebuild the package associated with the current buffer.
4. Start a fresh Emacs image.
5. Test changes in the fresh image (can be automated with the `elpaca-test` macro as well).

This is a better workflow than interactively evaluating your changes on the fly because it ensures a clean test environment for the changes and prevents one from "breaking" (really, just putting the image in a funky state) the image of Emacs they're doing the work from.

What specifically do you find inconvenient about either of those workflows and how do you imagine they could be improved?

**Comment by jinzhongjia** [comment]
I was a neovim user in the past (I still use it now, of course) and its `lazy.nvim` allowed me to specify a directory for local plugins and it would directly try to load the plugin from that directory while producing no extra build artifacts
I think this solution is more convenient for developing a new plug-in locally or debugging other people's plugins.

Of course, the reason why I came up with these ideas may also be influenced by neovim’s philosophy of use.

**Comment by jam1015** [comment]
Thanks for posting this workflow @progfolio 


> 
>     3. `C-u elpaca-rebuild`  to rebuild the package associated with the current buffer.
> 


 Right now an advantage of [straight.el](https://github.com/radian-software/straight.el/tree/master) for me   is that you [don't have to do this rebuild-step](https://github.com/radian-software/straight.el/blob/master/README.md#using-straightel-to-develop-packages)  .  You can just edit the code in `[user emacs directory]/straight/repos/[repo name]` and the changes in the source code are immediately reflected when you restart emacs. 

I tried  using the `'kill-emacs-hook` to make elpaca rebuild the package I'm working on on emacs exit but couldn't make it work. 

This is just about saving the effort of one command, but it is more convenient and much easier to not have to remember to run `elpaca-rebuild` for each change.   

This could actually be hard to implement under the hood, I have not looked at the elpaca source code at all/how it implements async.  Maybe a keyword / something you can add to the `:ensure` recipe.  But that goes away from what seems to me an advantage of elpaca, that it doesn't add too much on top of `use-package` whereas `straight` adds the `:straight` option.

There is also the option of adding to load path or directly evaluating the package code I'm working on, but if I'm using a package manager it would be nice to not have to do that.

**Comment by progfolio** [comment]
> Thanks for posting this workflow @progfolio 
> 
> 
> > 
> >     3. `C-u elpaca-rebuild`  to rebuild the package associated with the current buffer.
> > 
> 
> 
>  Right now an advantage of [straight.el](https://github.com/radian-software/straight.el/tree/master) for me   is that you [don't have to do this rebuild-step](https://github.com/radian-software/straight.el/blob/master/README.md#using-straightel-to-develop-packages)  .  You can just edit the code in `[user emacs directory]/straight/repos/[repo name]` and the changes in the source code are immediately reflected when you restart emacs. 
> 
> I tried  using the `'kill-emacs-hook` to make elpaca rebuild the package I'm working on on emacs exit but couldn't make it work. 
> 
> This is just about saving the effort of one command, but it is more convenient and much easier to not have to remember to run `elpaca-rebuild` for each change.   
> 
> This could actually be hard to implement under the hood, I have not looked at the elpaca source code at all/how it implements async.  Maybe a keyword / something you can add to the `:ensure` recipe.  But that goes away from what seems to me an advantage of elpaca, that it doesn't add too much on top of `use-package` whereas `straight` adds the `:straight` option.
> 
> There is also the option of adding to load path or directly evaluating the package code I'm working on, but if I'm using a package manager it would be nice to not have to do that. 

See https://github.com/progfolio/elpaca/issues/368#issuecomment-2391501469

**Comment by jam1015** [comment]
Updated the wiki to reflect this: https://github.com/progfolio/elpaca/wiki/_Automatic-Rebuilding-on-Restart
