### ISSUE TITLE
[Support]: elpaca installing packages twice for spacemacs

### ISSUE THREAD

**Issue by emacs18** [progfolio/elpaca#366]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca a65fcc5 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
 of 2024-09-25
git --version:  git version 2.43.0

### Operating System

Ubuntu 24.04 as detailed below.

$ cat /proc/version
Linux version 6.8.0-45-generic (buildd@lcy02-amd64-115) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024
$ 

### Description

This is not a bug report. Rather I would like to ask why packages are being installed twice. Likely I'm doing something incorrectly.

[spacemacs](https://github.com/syl20bnr/) uses `package.el` to install packages by default.

I have been using [straight.el](https://github.com/radian-software/straight.el) with spacemacs for several years. My clone of spacemacs has [this branch](https://github.com/emacs18/spacemacs/tree/sm-straight) which has the changes I needed to make use of `straight.el` instead of `package.el`.

Today I tried to use `elpaca` (rather than `package.el` or `straight.el`) with spacemacs. It seems to be working somewhat, but it is installing packages twice; once with `package.el` and also with `elpaca` as detailed below. How can I prevent packages from being installed via `package.el`?

Following details how the packages are installed twice.

About 150 packages are installed via `package.el` as shown here.

     1  $ cd /home/me/.emacs.d
     2  
     3  $ ls elpa/30.0/develop | wc -l
     4  150
     5  
     6  $ ls elpa/30.0/develop | head -4
     7  ace-jump-helm-line-20160918.1836
     8  ace-link-20220901.1710
     9  ace-window-20220911.358
    10  aggressive-indent-20230112.1300
    11  
    12  $ ls -l elpa/30.0/develop/ace-link-20220901.1710/
    13  total 76
    14  -rw-rw-r-- 1 me me  3567 Oct  1 16:43 ace-link-autoloads.el
    15  -rw-r--r-- 1 me me 36477 Oct  1 16:43 ace-link.el
    16  -rw-rw-r-- 1 me me 30635 Oct  1 16:43 ace-link.elc
    17  -rw-r--r-- 1 me me   420 Oct  1 16:43 ace-link-pkg.el

About 300 packages are installed via elpaca as detailed below.

     1  $ ls elpaca/builds/ | wc -l
     2  310
     3  
     4  $ ls -l elpaca/builds/ace-link/
     5  total 40
     6  -rw-rw-r-- 1 me me  3440 Oct  1 16:43 ace-link-autoloads.el
     7  lrwxrwxrwx 1 me me    61 Oct  1 16:43 ace-link.el -> /home/me/.emacs.d/elpaca/repos/ace-link/ace-link.el
     8  -rw-rw-r-- 1 me me 30635 Oct  1 16:43 ace-link.elc
     9  
    10  $ ls -al elpaca/repos/ace-link/
    11  total 72
    12  drwxrwxr-x   4 me me  4096 Oct  1 16:43 .
    13  drwxrwxr-x 295 me me 12288 Oct  1 17:29 ..
    14  -rw-rw-r--   1 me me 36427 Oct  1 16:43 ace-link.el
    15  drwxrwxr-x   8 me me  4096 Oct  1 16:43 .git
    16  -rw-rw-r--   1 me me    13 Oct  1 16:43 .gitignore
    17  -rw-rw-r--   1 me me   166 Oct  1 16:43 Makefile
    18  -rw-rw-r--   1 me me  2033 Oct  1 16:43 README.md
    19  drwxrwxr-x   2 me me  4096 Oct  1 16:43 test

My `load-path`  has `elpaca` paths in it first then later followed by `package.el` paths.
       1 ("/home/me/.emacs.d/elpaca/builds/python"
       2  "/home/me/.emacs.d/elpaca/builds/lsp-java"
       3  "/home/me/.emacs.d/elpaca/builds/dap-mode"
       4  "/home/me/.emacs.d/elpaca/builds/lsp-treemacs"
    ...
     306  "/home/me/.emacs.d/elpaca/builds/pcre2el"
     307  "/home/me/.emacs.d/elpaca/builds/dotenv-mode"
     308  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-visual/local/zoom-frm/"
     309  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-modeline/local/vim-powerline/"
     310  "/home/me/.emacs.d/layers/+lang/sql/local/sqlfmt/"
     311  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-editing/local/spacemacs-whitespace-cleanup/"
     312  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin/"
     313  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-org/local/space-doc/"
     314  "/home/me/.emacs.d/layers/+lang/python/local/pylookup/"
     315  "/home/me/.emacs.d/layers/+completion/helm/local/helm-spacemacs-help/"
     316  "/home/me/.emacs.d/layers/+completion/helm/local/helm-spacemacs-faq/"
     317  "/home/me/.emacs.d/layers/+spacemacs/spacemacs-evil/local/evil-unimpaired/"
     318  "/home/me/.emacs.d/layers/+distributions/spacemacs-bootstrap/local/hybrid-mode/"
     319  "/home/me/.emacs.d/layers/+distributions/spacemacs-bootstrap/local/holy-mode/"
     320  "/home/me/.emacs.d/layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/"
     321  "/home/me/.emacs.d/elpa/30.0/site/ace-jump-helm-line-20160918.1836"
     322  "/home/me/.emacs.d/elpa/30.0/site/ace-link-20220901.1710"
    ...
     649  "/home/me/.emacs.d/elpa/30.0/site/lv-20200507.1518"
     650  "/home/me/.emacs.d/elpa/30.0/site/pcre2el-20240629.2322"
     651  "/home/me/.emacs.d/core/libs/forks/"
     652  "/home/me/.emacs.d/core/libs/spacemacs-theme/"
     653  "/home/me/.emacs.d/core/libs/" "/home/me/.emacs.d/core/"
     654  "/home/me/.emacs.d/elpaca/builds/elpaca-use-package"
     655  "/home/me/.emacs.d/elpaca/builds/elpaca/"
     656  "/home/me/opt/emacs/30.b-d63bff4d88f/share/emacs/30.0.91/site-lisp"
     657  "/home/me/opt/emacs/30.b-d63bff4d88f/share/emacs/site-lisp"
     658  "/home/me/opt/emacs/30.b-d63bff4d88f/share/emacs/30.0.91/lisp"
    ...
     681  "/home/me/opt/emacs/30.b-d63bff4d88f/share/emacs/30.0.91/lisp/calc"
     682  "/home/me/opt/emacs/30.b-d63bff4d88f/share/emacs/30.0.91/lisp/obsolete"
     683  "/home/me/org/me/dot-emacs/lisp")

**Comment by progfolio** [comment]
Sorry. I don't use Spacemacs, so I don't know its inner workings. I suggest opening a support ticket on that repo.

I can assure you that Elpaca is not installing packages twice, though.
It looks like the packages were installed once with package.el, and then again with Elpaca. Does package.el re-install them if you delete the `elpa` directory? If so, I suggest familiarizing yourself with how Spacemacs handles package installation and going from there.
