### ISSUE TITLE
[Bug/Support]: Possible memory leak?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [progfolio/elpaca#367]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Latest

### Operating System

Win11

### Description

I'm doing a fresh install of all my packages this morning and Elpaca seems to be hanging, my latest message is 'Downloading MELPA recipes... 100%'. Emacs is sitting at around 15-20% CPU usage and memory consumption is rising endlessly.

![image](https://github.com/user-attachments/assets/788367cc-7981-40c5-99c7-cd37fee9f7b0)

**Comment by progfolio** [comment]
Thank you for taking the time to fill out a support ticket.
Please provide the following additional info:

- a link to your init files
- amount of RAM installed on the system in question
- Are you utilizing a VPN or any other proxied networking settings?

**Comment by JordanAnthonyKing** [comment]
Unfortunately I'm going to close this as I couldn't reproduce, after the initial run elpaca would hang but cpu and ram usage would be 0/negligable.

Ultimately this was caused by some incorrect config setting my init and package directories to totally separate folders by mistake.
