### ISSUE TITLE
[Feature]: Display new packages in elpaca-manager

### ISSUE THREAD

**Issue by jumper047** [progfolio/elpaca#372]
### Feature Description

Package.el's list packages has nice feature - it displays newly added packages at the beginning of the list when executing `list-packages` command (I belive it calculates new packages list locally, as diff between all packages on last update and current one). Is it possible to add something like this in elpaca-manager?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Sorting by the "Date" column in the elpaca-manager UI should give something similar. It will also include packages which have been updated recently. Calculating a list of new packages can be achieved by writing a custom search tag. I have no plans to add such a feature by default, though.
