### ISSUE TITLE
[Support] custom elpaca-recipe-functions hook not working for ELPA recipes

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#376]
Just to follow up, the issue I was having was due to this:

```
(defun aj/elpaca-dev-recipe (recipe)
  "If RECIPE is part of my organization, set it up for development."
  (when-let* ((repo (plist-get recipe :repo))
              ((string-prefix-p "aaronjensen/" repo)))
    (list :protocol 'ssh :depth nil)))

(add-hook 'elpaca-recipe-functions #'aj/elpaca-dev-recipe)
```

This, for some reason, breaks elpa recipes now. I haven't sorted through why yet, so for now I'm leaving it disabled.

_Originally posted by @aaronjensen in https://github.com/progfolio/elpaca/issues/375#issuecomment-2450881273_

**Comment by progfolio** [comment]
Could you please share the output of `M-x elpaca-info` for one of the ELPA packages this stopped working for?

**Comment by aaronjensen** [comment]
Looks like it's my function:

```
Debugger entered--Lisp error: (wrong-type-argument listp "denote")
  string-prefix-p("aaronjensen/" ("https://github.com/protesilaos/denote" . "denote"))
  (and repo (string-prefix-p "aaronjensen/" repo))
```

**Comment by progfolio** [comment]
> Looks like it's my function:
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument listp "denote")
>   string-prefix-p("aaronjensen/" ("https://github.com/protesilaos/denote" . "denote"))
>   (and repo (string-prefix-p "aaronjensen/" repo))
> ```
> 

Yes. That's the root cause.

> Why is repo a cons?

That's the result of this change https://github.com/progfolio/elpaca/commit/df557d60bde407e398c336322977cdd29bcb8128.
It was made to simplify the recipe format (less keywords, the better).
Any functions handling the `:repo` keyword should be prepared to deal with a cons cell for a renamed repo or a string.
Does that make sense?

**Comment by aaronjensen** [comment]
Yes, that makes sense, thank you. I've updated it to this:

```el
(defun aj/elpaca-dev-recipe (recipe)
  "If RECIPE is part of my organization, set it up for development."
  (when-let* ((repo (plist-get recipe :repo))
              (repo (if (consp repo)
                        (car repo)
                      repo))
              ((string-prefix-p "aaronjensen/" repo)))
    (list :protocol 'ssh :depth nil)))
```

Seems to work fine. 

For what it's worth, I don't necessarily know that "less keywords, the better" is something that leads to a better design. I'd be more likely to err on the side of "less complexity, the better". This change has made a field that represented one thing now represent two things (or one). This means that my function which was previously unconcerned with the repo alias must now change to accommodate that, whereas before, I could ignore it entirely.

**Comment by progfolio** [comment]
> Seems to work fine.

Glad to hear it. `car-safe` is an alternative as well:

```emacs-lisp
(defun aj/elpaca-dev-recipe (recipe)
  "If RECIPE is part of my organization, set it up for development."
  (when-let* ((repo (plist-get recipe :repo))
              ((string-prefix-p "aaronjensen/" (or (car-safe repo) repo))))
    (list :protocol 'ssh :depth nil)))
```

> For what it's worth, I don't necessarily know that "less keywords, the better" is something that leads to a better design.
> I'd be more likely to err on the side of "less complexity, the better".

I agree that lessening complexity should be the goal in general.
That was one my initial motivations for this project.
In this case, the `:local-repo` keyword was seldom used and had to be accounted for all over the code base. Admittedly, the reduction in complexity is a tradeoff for a slightyly more complex keyword. I think in this case it was worth the trade.

I also have plans to remove `:pre-build` and `:post-build` down the road. These are special cases of `:build`. Id rather make it easier to conditionally alter a single list of `:build` steps.

Thank you for the input, though. I will keep it in mind and see if I can think of a better design for this case.

**Comment by aaronjensen** [comment]
> car-safe is an alternative as well:

Interesting, that one is new to me. Using it would be awkward though unless I'm missing something: `(repo (or (car-safe repo) repo))` I think I'd rather use the explicit conditional instead of relying on `or` for something like this. 

> In this case, the :local-repo keyword was seldom used...

Got it. I don't have full context on the scope of benefit of the change, so maybe it was a net improvement. It's possible that the data structure and the input macros could be divorced so that there's only one data structure format (i.e., it's always a cons cell) but the input format would convert it as appropriate.

> I also have plans to remove :pre-build and :post-build down the road...

Copy that. I use pre-build in one place for `tree-sitter-module`
