### ISSUE TITLE
[Support]: Help fixing an instance where local-repo was previously used.

### ISSUE THREAD

**Issue by dixius99** [progfolio/elpaca#379]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 5b5b319 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 2, aarch64-apple-darwin23.5.0, NS appkit-2487.60 Version 14.5 (Build 23F79))
 of 2024-07-01
git --version:  git version 2.39.5 (Apple Git-154)

### Operating System

macOS Sequoia 15.1

### Description

I know there must be an easy solution for this, but I can't figure it out. I have this in my init.el:

```
(use-package dracula-theme
  :ensure (:local-repo "dracula-theme")
  :config
  (load-theme 'dracula :no-confirm))
```

which used to install the Dracula theme into repos/dracula-theme. Now that `local-repo` is gone, I can't figure out how to change the above to continue installing Dracula into repos/dracula-theme, as it now installs into repos/emacs.

Could you show me how to do it now?

**Comment by progfolio** [comment]
The `:local-repo` recipe keyword has been supplanted by the [:repo](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipe-keyword-repo) recipe keyword. You should be able to locally rename the repository like so:

```emacs-lisp
(use-package dracula-theme
  :ensure (:repo ("dracula/emacs" . "dracula-theme")))
```

Does that help?

**Comment by dixius99** [comment]
100% helps!

I knew that I had to use :repo now instead of :local-repo, but I was messing up the way I was writing it (I was missing parentheses and maybe not the problem, but I spelled out the full path to the remote repo to point to the GitHub URL).

Thanks for your help!
