### ISSUE TITLE
[Feature]: Add a menu for built-in packages?

### ISSUE THREAD

**Issue by declantsien** [progfolio/elpaca#38]
### Feature Description

Add a menu for built-in packages? So other packages can depend on them(see error below),
and be listed when using `elpaca-manager`.

Built-in packages are indexed here `C-h v package--builtins`.

---
Recently, I `elpaca-try password-store`, and got the error below.

```
password-store                 failed               Failed dependencies: ("auth-source-pass")                                        19.267592
auth-source-pass               failed               elpaca--clone: (wrong-type-argument stringp nil)                              19.269149
```

I resolved it by `(add-to-list 'elpaca-ignored-dependencies 'auth-source-pass)`

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Hi. Thanks for the suggestion.

> I resolved it by (add-to-list 'elpaca-ignored-dependencies 'auth-source-pass)

I think this is the correct solution here. Elpaca currently requires Emacs version >= 27.1. The `auth-source-pass` package is included with the minimum supported version. I've added it to the "master" branch in 829ebd6.

In general, I don't think I will be adding a menu to Elpaca for built-in packages. Few packages declare specific built-in dependencies and most (correctly) declare a minimum Emacs version. Cases like this, where the package was developed and distributed separate from Emacs, and then was moved to core are relatively rare.

It may be worth asking the maintainer of password-store if they can change the Package-Requires metadata in light of `auth-source-pass` no longer being distributed externally. They'd have to remove the explicitly dependency on that and bump the min required Emacs version to when it was added to core. Looking at the Emacs repository, that looks like Emacs 26:

```shell
git tag --contains 0e066efe3b8 | head -n 1
emacs-26.0.90
```

**Comment by declantsien** [comment]
> most (correctly) declare a minimum Emacs version

Right, sounds reasonable. Thanks.

> It may be worth asking the maintainer of password-store if they can change the Package-Requires metadata in light of auth-source-pass no longer being distributed externally.


I may send a bug report to their mailing list later if I have time. I will paste back the link if I manage to do that.

Nice work BTW. Closing this issue for now.

**Comment by declantsien** [comment]
Finally, sent a bug report to password-store.el mailing list.
Paste the link here as a reference.
https://lists.zx2c4.com/pipermail/password-store/2022-December/004697.html

**Comment by calancha** [comment]
We have updated the metadata in the password-store package as suggested above.
- We have dropped the auth-source-pass external dependency.
- Now, the Emacs minor version required is Emacs 26.

Thank you for the report to the list!

**Comment by progfolio** [comment]
I was able to install the  latest version of the package via Elpaca.
@declantsien: `elpaca-update-menus` before `elpaca-try password-store` should do the trick.

**Comment by declantsien** [comment]
Yeah, it's working without setting `elpaca-ignored-dependencies`. We
probably also want to revert `829ebd6`.

Cheers

**Comment by progfolio** [comment]
@declantsien: Thanks for testing.

> We probably also want to revert `829ebd6`.

Not necessary. Thank you, though.
