### ISSUE TITLE
[Bug/Support]: Magit not cloning correct branch

### ISSUE THREAD

**Issue by zmward99** [progfolio/elpaca#381]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca d74d27f grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
 of 2024-11-04
git --version:  git version 2.43.0

### Operating System

Ubuntu 24.04.1

### Description

Trying to use my config on a new machine and everything seems to be working like normal except the installation of the magit package. For some reason magit will not clone from the main branch, only from the "legacy-stub". I've tried specifying the branch name as "main" like what is show in the documentation, but even that doesn't work. 

`(use-package magit
  :host github :repo "magit/magit" :branch "main")`

**Comment by progfolio** [comment]
> `(use-package magit :host github :repo "magit/magit" :branch "main")`

This is incorrect syntax for elpaca's use-package integration.
Try this instead:

``` emacs-lisp
(use-package magit :ensure (:branch "main"))
```

**Comment by zmward99** [comment]
That works now, thank you!
