### ISSUE TITLE
[Support]:

### ISSUE THREAD

**Issue by jsyjr** [progfolio/elpaca#382]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 7b5e269 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin23.6.0, NS appkit-2487.70 Version 14.6.1 (Build 23G93))
 of 2024-09-08
git --version:  git version 2.39.5 (Apple Git-154)

### Operating System

Mac OSX - Sequoia (15.0.1)

### Description

I would like to be able to audit the external packages introduced by my init.el.  In particular, I would like something akin to Manuel Uberti's [package report](https://manueluberti.eu/posts/2021-09-01-package-report/).

Manuel assumes that all package handling uses built-in package.el.  In my case, I use elpaca.  I think that the one function that needs to be reimplemented is mu--archive-packages:

```
(defun mu--archive-packages ()
  "Return a list of (archive . package) cons cells."
  (seq-reduce
   (lambda (res package)
     (let ((archive (package-desc-archive
                     (cadr (assq package package-archive-contents))))
           (pkg (symbol-name package)))
       (push (cons archive pkg) res)))
   (mapcar #'car package-alist)
   nil))
```

I am unfamiliar with elpaca's data structures.  Can you suggest an equivalent elpaca implementation?

**Comment by progfolio** [comment]
I've got good news for you. Elpaca already has this information available.
`M-x elpaca-manager` will open a manager view.
Then you can type `g i` to search for `#unique #installed` packages. You should see a count in the header-line which is the total number of packages you have installed. You can then filter that search query to narrow it down to each source for the packages. e.g. "#unique #installed ||| MELPA" to get a total count of packages installed from MELPA.

You can learn more about searching in the manual:

https://github.com/progfolio/elpaca/blob/master/doc/manual.md#searching

**Comment by jsyjr** [comment]
Thanks for the helpful reply.

I have tried your suggestion and am puzzled by the output.  *E.g.*:

Package                 Description
                                          Date                Source
tree-sitter-hl  Not available in menu functions
2024-05-12   Init file
eglot-booster   Not available in menu functions
2024-09-11   Init file
ws-butler       Unobtrusively remove trailing whitespace.
2020-11-17   MELPA
yaml            YAML parser for Elisp
2023-12-11   MELPA
hideshowvis     Fringe markers for regions foldable by hideshow.el
 2024-05-29   NonGNU-devel ELPA
filladapt       Adaptive fill
2022-12-21   GNU-devel ELPA


How should I interpret the Source column when all of my packages are
retrieved from their respective source repositories:

(use-package tree-sitter-hl
  :ensure (:host github :repo "emacs-tree-sitter/elisp-tree-sitter"


                 :files (:default "core/*.el" "lisp/*.el"))
  :after (treesit)
  )


(use-package eglot-booster
  :ensure (:host github :repo "jdtsmith/eglot-booster")
  :after (eglot)
  :config
  (eglot-booster-mode 1)
  )

(use-package ws-butler
  :ensure (:host github :repo "lewang/ws-butler")
  :defer 1
  :config
  (ws-butler-global-mode 1)
  )

(use-package yaml
  :ensure (:host github :repo "zkry/yaml.el")
  :defer t
  )

(use-package hideshowvis
  :ensure (:host github :repo "sheijk/hideshowvis")
  :after (hideshow)
  :hook (prog-mode . hideshowvis-minor-mode)
  :config
  (hideshowvis-symbols)
  )

(use-package filladapt
  :ensure (:host github :repo "emacsmirror/filladapt" :branch "master")
  :config
  (my/def-hook my/text-mode ()
    text-mode-hook
    "Configure auto-fill and filladapt."
    (setq fill-column 80)               ; becomes local
    (turn-on-auto-fill)
    (turn-on-filladapt-mode))
  )


/john

**Comment by progfolio** [comment]
> Thanks for the helpful reply.

You're welcome.
  
> How should I interpret the Source column when all of my packages are retrieved
> from their respective source repositories:

The "source" column refers to the source for the package recipe.
For example, the ws-butler and yaml package recipes were inherited from the MELPA menu function's recipes, whereas the eglot-booster and tree-sitter-hl recipes did not inherit from any menu function's recipes. Those two are fully specified in your init file.

Does that make sense?

**Comment by jsyjr** [comment]
Again, thanks for the detailed explanation.

A couple comments:

   - Given your explanation, the Source column seems prone
   to misinterpretation.  Only the easily missed 'Init file' entry really
   hints at its true significance. Might "Recipe" be more helpful?
   - The preceding makes me wonder about the precise significance of the
   Date column.  Does it refer to the recipe? the package source? date last
   checked?  ...
   - I had hoped to have some clue as to whence each package source was
   retrieved.  Clearly, elpaca knows this (to whit the manager's 'b'
   command).  Any thoughts?

/john

**Comment by progfolio** [comment]
>    - Given your explanation, the Source column seems prone to misinterpretation.
>    Only the easily missed 'Init file' entry really hints at its true
>    significance. Might "Recipe" be more helpful?

It's not confusing once one understands the recipe-based approach to package declaration. Feedback noted, though. Thank you.

>    - The preceding makes me wonder about the precise significance of the Date
>    column. Does it refer to the recipe? the package source? date last checked?
>    .. 

  The date column is scraped from the package metadata when an ELPA publishes that (e.g. MELPA) and falls back to the date of the latest commit when that is not available. 
  This gives an idea of how recently the package was modified and/or published.

>    - I had hoped to have some clue as to whence each package source was
>    retrieved. Clearly, elpaca knows this (to whit the manager's 'b' command).
>    Any thoughts?

Elpaca's search engine is flexible enough to customize the results.
Your feature request sounds like it could be covered by a custom search tag:
  
https://github.com/progfolio/elpaca/blob/master/doc/manual.md#search-tags

You can see some examples of search tag implementations in `elpaca-log.el`, e.g. `elpaca-log-updates`.
