### ISSUE TITLE
[Support]: get packages from github mirror

### ISSUE THREAD

**Issue by nanakura** [progfolio/elpaca#383]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Is there a configuration similar to straight.el as follows?
```elisp 
(advice-add 'straight-vc-git--encode-url :around #'noalias-set-github-mirror)
(defun noalias-set-github-mirror (oldfunc &rest args)
   (let ((url (apply oldfunc args)))
      (replace-regexp-in-string (rx (group "github.com"))
                                "githubfast.com" url nil nil 1)))
(setq straight-vc-git-default-protocol 'https)
```

### Operating System

win11

### Description

I don't want to get the package directly from github, but through some mirror

**Comment by progfolio** [comment]
> ### Confirmation
> 
> - [X] I have checked the documentation (README, Wiki, docstrings, etc)
> - [X] I am checking these without reading them.
> - [X] I have searched previous issues to see if my question is a duplicate.
> 
> ### Elpaca Version
> 
> Is there a configuration similar to straight.el as follows?
> ```elisp 
> (advice-add 'straight-vc-git--encode-url :around #'noalias-set-github-mirror)
> (defun noalias-set-github-mirror (oldfunc &rest args)
>    (let ((url (apply oldfunc args)))
>       (replace-regexp-in-string (rx (group "github.com"))
>                                 "githubfast.com" url nil nil 1)))
> (setq straight-vc-git-default-protocol 'https)
> ```
> 
> ### Operating System
> 
> win11
> 
> ### Description
> 
> I don't want to get the package directly from github, but through some mirror


No function advice necessary. Elpaca offers `elpaca-order-functions` and `elpaca-recipe-functions` for these sorts of customizations. For example, you could something like the following to `elpaca-recipe-functions`:


```emacs-lisp
(defun +elpaca-with-github-mirror (recipe)
  "Replace github with githubfast in package RECIPE."
  (let* ((repo (plist-get recipe :repo))
         (url (or (car-safe repo) repo)))
    (if-let (((string-match-p "github.com" url))
             (mirror (replace-regexp-in-string "github.com" "githubfast.com" url)))
        (list :repo (if (consp repo) (cons mirror (cdr repo)) mirror))
      (if-let ((fetcher (plist-get recipe :fetcher))
               ((eq fetcher 'github))
               (mirror (concat "https://www.githubfast.com/" url)))
          (list :fetcher nil
                :repo (if (consp repo) (cons mirror (cdr repo)) mirror))))))

(add-to-list 'elpaca-recipe-functions #'+elpaca-with-github-mirror)
```

> (setq straight-vc-git-default-protocol 'https)

This is already the default, but can be changed via `elpaca-order-defaults` if you like.
