### ISSUE TITLE
[Bug]: Unable to Update MELPA Menu

### ISSUE THREAD

**Issue by ScriptMang** [progfolio/elpaca#385]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 4ad20d9 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 29.4 (build 2, aarch64-apple-darwin24.0.0, NS appkit-2566.00 Version 15.0.1 (Build 24A348)) of 2024-10-25
git --version:  git version 2.47.0

### Operating System

MacOs Sequoia

### Description

I'm unable to update any menu functions.
I tried updating the melpa menu and it says its unable to pull
Melpa recipes.  This wasn't a problem a week ago for me.

**Comment by progfolio** [comment]
Please evaluate the following in your \*scratch\* buffer and share the output:

```emacs-lisp
(let ((default-directory (expand-file-name "./melpa/" elpaca-cache-directory)))
  (elpaca-with-process-call ("git" "pull")
    (princ (or stdout stderr))))
```

**Comment by ScriptMang** [comment]
it doesn't print any output in messages, but my linter says
 
- function  elpaca-with-process-call is not known to be defined.
- git is a malformed function

**Comment by ScriptMang** [comment]
After looking at my init.el I removed an old reference to elpaca-use-package mode and replaced it with the new one

`(elpaca-wait)
(elpaca (use-package :host github repo: "jwiegley/use-package"))`

To 

`(elpaca elpaca-use-package)
(elpaca-use-package-mode))`


Now when loading emacs I get the error loading alist 
before elpaca

**Comment by ScriptMang** [comment]
Managed to fix let-alist loading before emacs by 
adding the property :after (elpaca) to my let-alist package 
declaration. However that didn't fix the melpa not pulling.

**Comment by ScriptMang** [comment]
weirdly enough, the function elpaca-pull-all works.
It updates all my pkg archive sources, fetches them and merges them. However,  calling elpaca-update-menus doesn't update
the recipe list for any source. Calling elpaca-update-all doesn't 
rebuild the packages properly either.

**Comment by progfolio** [comment]
Too many separate issues going on at once here.
Please share your config files and I will take a look when I have time.

**Comment by ScriptMang** [comment]
For configuration I used a mix of an system crafter's 
"crafted emacs" modules I personally edited, init.el  
and early-init.el.  Not sure what other config  files are 
needed but added custom.el, and customs.el. 
I also added a copy of my elpaca folder thats 
contains only elpaca details.


The crafted-emacs modules I edited and used 
`"~/crafted-emacs/modules/crafted-init-config.el"`
`"~/crafted-emacs/modules/crafted-completion-config.el"`



Please let me know if there is any other config files I'm missing.
[scriptmang's_configs.gz](https://github.com/user-attachments/files/17770662/scriptmang.s_configs.gz)

**Comment by ScriptMang** [comment]
[scriptmang's_configs.gz](https://github.com/user-attachments/files/17770687/scriptmang.s_configs.gz)

**Comment by progfolio** [comment]
The gzip archive decompresses to a binary on my end.
Why not upload them to your github account in a repository?

**Comment by ScriptMang** [comment]
I didn’t know you’d have trouble opening it.Will do, when I get the chance.On Nov 15, 2024, at 9:33 PM, Nicholas Vollmer ***@***.***> wrote:﻿
The gzip archive decompresses to a binary on my end.
Why not upload them to your github account in a repository?

**Comment by ScriptMang** [comment]
https://github.com/ScriptMang/emacs-config

It's my first time posting my config,
please let me know what I should I fix or remove.

Thanks

**Comment by isaacraja** [comment]
I've a similiar issue with MELPA.  whenever i do elpaca-update-menus for MELPA, I get this error.
```
Downloading MELPA...
Unable to pull MELPA recipes.
```
But I can do a manual `git pull` and the below code works too. 

```
(let ((default-directory (expand-file-name "./melpa/" elpaca-cache-directory)))
  (elpaca-with-process-call ("git" "pull")
    (princ (or stdout stderr))))
```
in scratch buffer, I get 
```
"Updating d2b2189e..dba758aa
Fast-forward
 html/index.html             | 1 +
 recipes/{edts-mode => edts} | 5 ++---
 recipes/system-packages     | 1 -
 3 files changed, 3 insertions(+), 4 deletions(-)
 rename recipes/{edts-mode => edts} (94%)
 delete mode 100644 recipes/system-packages
"
```

**Comment by progfolio** [comment]
> https://github.com/ScriptMang/emacs-config
> 
> It's my first time posting my config, please let me know what I should I fix or
> remove.
> 
> Thanks

I took a look.
You still have references to `after-init-hook` which need to be udpated to `elpaca-after-init-hook`. There's also gratuitous use of Elpaca's `:wait t`, and use-package's `:demand t` which shouldn't be necessary. Both will slow down your Emacs start up time as well as initial install time.

I've fixed the issue with the MELPA menu (I introduced a bug with some recent refactoring).
If you and @isaacraja could test and confirm everything works I would appreciate it:

1. `M-x elpaca-update` `elpaca`
2. `M-x restart-emacs`
3. `M-x elpaca-update-menus` `elpaca-menu-melpa`

Thank you both.

**Comment by ScriptMang** [comment]
I can say after this fix the melpa menu funct is working again.
However, can you check the other update menu functions besides melpa.
When I choose gnu-elpa its says its downloading, but it doesn't  reach 100%.
All other menu functs do the same thing.

**Comment by isaacraja** [comment]
Melpa menu works for me again. Like @ScriptMang said above - other menus doesn't reach 100%

**Comment by progfolio** [comment]
I assume for both of you Emacs is not hanging, correct?
If so, it's just a matter of printing the message in all cases. The menus are being updated.
I'll take care of that after work.

**Comment by ScriptMang** [comment]
For me at least, gnu elpa hangs for a few seconds, then go back to normal.

**Comment by progfolio** [comment]
All menus should print 100% message properly now. Thank you both for testing.

**Comment by progfolio** [comment]
> For me at least, gnu elpa hangs for more than a few seconds.

That's expected and dependent on your internet speed and GNU's server's response time. Menu updates are not asynchronous.
