### ISSUE TITLE
[Bug/Support]: Init installer version does not match /home/user/.config/emacs/elpaca/builds/elpaca/doc/installer.el.

### ISSUE THREAD

**Issue by domsch1988** [progfolio/elpaca#386]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 4ad20d9 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
 of 2024-07-22, modified by Debian
git --version:  git version 2.39.5

### Operating System

Debian 12.8

### Description

I just cloned my config fresh and this error Comes up. Otherwise, Emacs seems to be running fine, though elpaca did have issues installing ef-themes through use-package. Might not be related though.
My config can be found here: https://gitlab.com/domsch1988/vimacs

**Comment by progfolio** [comment]
Please see: https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#installer-version-mismatch
