### ISSUE TITLE
[Support]: No file or directory elpaca/cache/melpa/recipes on Windows 11

### ISSUE THREAD

**Issue by andanao** [progfolio/elpaca#387]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 4ad20d9 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 30.0.92 (build 2, x86_64-w64-mingw32)
 of 2024-10-30
git --version:  git version 2.47.0.windows.1

I have symlinks disabled with this set below my elpaca bootstrap code:
```
(when (member system-type '(windows-nt ms-dos))
  (elpaca-no-symlink-mode))
```

Same thing happens on Emacs 29

### Operating System

Windows 11

The computer is a corporate device, git has been set to use local IT provided issuer certificates, outside of Elpaca git works as you would normally expect except SSH cloning does not work.

### Description

```
Debugger entered--Lisp error: (file-missing "Opening directory" "No such file or directory" "c:/Users/adanaos/git/emacs-new/elpaca/cache/melpa/recipes/")
  directory-files("./recipes/" full "\\(?:\\`[^.]\\)")
  elpaca-menu-melpa--index(elpaca)
  elpaca-menu-melpa(index elpaca)
  elpaca-info--menus(elpaca)
  elpaca--info(elpaca nil)
  elpaca-info(elpaca nil t)
  elpaca-ui-info()
  funcall-interactively(elpaca-ui-info)
  command-execute(elpaca-ui-info)
```

Under the elpaca directory
```
ls /elpaca/cash/melpa/
```
returns nothing

Manually creating the directory seems to have resolved the issue.

**Comment by progfolio** [comment]
> The computer is a corporate device, git has been set to use local IT provided
> issuer certificates, outside of Elpaca git works as you would normally expect
> except SSH cloning does not work.
> 
> ### Description
> 
> ```
> Debugger entered--Lisp error: (file-missing "Opening directory" "No such file or directory" "c:/Users/adanaos/git/emacs-new/elpaca/cache/melpa/recipes/")
>   directory-files("./recipes/" full "\\(?:\\`[^.]\\)")
>   elpaca-menu-melpa--index(elpaca)
>   elpaca-menu-melpa(index elpaca)
>   elpaca-info--menus(elpaca)
>   elpaca--info(elpaca nil)
>   elpaca-info(elpaca nil t)
>   elpaca-ui-info()
>   funcall-interactively(elpaca-ui-info)
>   command-execute(elpaca-ui-info)
> ```

Elpaca uses the `make-directory` to create directories.
Most likely a permissions issue on your machine considering it's a corporate device.
Are you able to create directories via elisp with `make-directory` under your user's .emacs.d?
  
> Under the elpaca directory
> ```
> ls /elpaca/cash/melpa/
> ```
> returns nothing
  
  `$EMACS-DIR/elpaca/cache` vs cash, but if make-directory failed, I wouldn't expect the correct path to list anything either.
> 
> Manually creating the directory seems to have resolved the issue.

That makes sense if the issue was permissions related.
Did you create the directory via Emacs, or by other means (e.g. Window's File Explorer or Powershell)?

**Comment by andanao** [comment]
> Elpaca uses the `make-directory` to create directories.
> Most likely a permissions issue on your machine considering it's a corporate device.
> Are you able to create directories via elisp with `make-directory` under your user's .emacs.d?

`make-directory` works fine both under `.emacs.d/` and under the test directory that I've been using.

I created the directory in mingw64 with mkdir

**Comment by progfolio** [comment]
Interesting. I'm unable to reproduce the issue on my Windows 11 machine, so I'm not sure what it could be. I'll consider this closed for now since you've got things working. Thank you.
