### ISSUE TITLE
[Feature]: Merging autoloads?

### ISSUE THREAD

**Issue by aaronjensen** [progfolio/elpaca#388]
### Feature Description

Hi, do you have any plans for a `package-quickstart` equivalent and/or have you tested whether or not it offers much performance benefit on a modern machine?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> ### Feature Description
> 
> Hi, do you have any plans for a `package-quickstart` equivalent and/or have you
> tested whether or not it offers much performance benefit on a modern machine?
> 
> ### Confirmation
> 
> - [X] The feature I'm proposing does not already exist in Elpaca

Thanks for the suggestion.

Currently, if `elpaca-cache-autoloads` is non-nil (the default), all of a package's autoloads are read into memory and an entire queue's worth are evaluated at once. This is all done utilizing a single buffer, too.

At one point I experimented with concatenating autoloads during package building, but I have not done rigorous enough testing to say whether or not it's worth it. Another similar optimization would be adding the minimum set of directories to `load-path`, which would optimize elisp library look up time. Both ideas can be accomplished by writing custom build steps, but I haven't done so. As a feature, I think it's fairly low priority right now.

If you're interested and need help writing the custom build steps, I can give advice.

**Comment by aaronjensen** [comment]
> Another similar optimization would be adding the minimum set of directories to load-path, which would optimize elisp library look up time

What would the minimum set entail? I'm not sure I understand this one.

As for the custom build step, are you imagining that after building each package it would append its autoloads to a single file? Or is there a post-build-of-everything step that could be used to more or less enumerate all packages and concatenate their autoloads?

**Comment by progfolio** [comment]
> > Another similar optimization would be adding the minimum set of directories to
> > load-path, which would optimize elisp library look up time
> 
> What would the minimum set entail? I'm not sure I understand this one.

Any libraries which can operate with a set of uniquely named files can co-exist in the same directory on `load-path`. e.g. `elisp/a.el`, `elisp/-b.el`. The only case you'd need more directories is when libraries depend on files which are not uniquely named. I haven't experimented enough with this to see whether it's worth the effort.

  
> As for the custom build step, are you imagining that after building each package
> it would append its autoloads to a single file?

Correct.

**Comment by aaronjensen** [comment]
>> As for the custom build step, are you imagining that after building each package
>> it would append its autoloads to a single file?
> Correct.

Hmm, it would need to be rebuilt from scratch any time the packages changed (i.e., one was added or removed). That's probably more complexity than I can take on, but maybe I can experiment with whether or not the performance difference is notable on modern machines.

**Comment by progfolio** [comment]
> Hmm, it would need to be rebuilt from scratch any time the packages changed
> (i.e., one was added or removed). That's probably more complexity than I can
> take on, but maybe I can experiment with whether or not the performance
> difference is notable on modern machines.

It shouldn't be too complex.
I took a crack at a prototype this afternoon.
You can experiment with it using the `elpaca-test` macro.
Try evaling this test case to bootstrap the environment:

``` emacs-lisp
(elpaca-test
  :ref "quickstart"
  :interactive t
  :init
  ;; You can declare more packages here if you like...
  (elpaca (doct :host github :repo doct)))
```

Once the test environment is bootstrapped, write out an autoloads file via `M-x elpaca-write-autoloads`.
Then add the following in the `init.el` file prior to the Elpaca installer, replacing the path with whatever you used above in the `elpaca-write-autoloads` command:

``` emacs-lisp
(setq elpaca-cache-autoloads "/path/to/autoloads.el")
```

When you `M-x restart-emacs` that file should be used instead of the usual caching method. 
The code will still need some polish, but in terms of refreshing the autoloads, one could add something like the following to `kill-emacs-hook`:

``` emacs-lisp
(add-to-hook 'kill-emacs-hook (apply-partially #'elpaca-write-autoloads elpaca-cache-autoloads))
```

That should keep the autoloads in sync for each session.

**Comment by aaronjensen** [comment]
Nice, thanks.

For me, it saves about 12ms on average on elpaca init time (variance was somewhat high, but the cached version was consistently faster).

My average time is a bit over 400ms on an M4 Max (so my absolute deltas are going to be relatively small because the machine is so fast). 

That's with my actual config, which has 140 or so packages.

I can't say that's amazing, and not sure it's worth the additional complexity for me personally, but it may be more impactful for others.

**Comment by progfolio** [comment]
> Nice, thanks.
> 
> For me, it saves about 12ms on average on elpaca init time (variance was
> somewhat high, but the cached version was consistently faster).
> 
> My average time is a bit over 400ms on an M4 Max (so my absolute deltas are
> going to be relatively small because the machine is so fast).
> 
> That's with my actual config, which has 140 or so packages.
> 
> I can't say that's amazing, and not sure it's worth the additional complexity
> for me personally, but it may be more impactful for others.

I observed similar results on my end.
Not something I think I'll incorporate into my config, but at least I have a rough implementation here if anyone is interested in the future. 

Thanks for testing. I'll consider this issue closed for now.

**Comment by aaronjensen** [comment]
Sounds good..Thank you.
