### ISSUE TITLE
[Support]: I need help reorganizing my emacs config  with elpaca

### ISSUE THREAD

**Issue by ScriptMang** [progfolio/elpaca#389]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 63da6a4 HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 29.4 (build 2, aarch64-apple-darwin24.0.0, NS appkit-2566.00 Version 15.0.1 (Build 24A348))
 of 2024-10-25
git --version:  git version 2.47.0

### Operating System

Macos Sequoia

### Description

> > https://github.com/ScriptMang/emacs-config
> > It's my first time posting my config, please let me know what I should I fix or
> > remove.
> > Thanks
> 
> I took a look. You still have references to `after-init-hook` which need to be udpated to `elpaca-after-init-hook`. There's also gratuitous use of Elpaca's `:wait t`, and use-package's `:demand t` which shouldn't be necessary. Both will slow down your Emacs start up time as well as initial install time.
> 
> I've fixed the issue with the MELPA menu (I introduced a bug with some recent refactoring). If you and @isaacraja could test and confirm everything works I would appreciate it:
> 
> 1. `M-x elpaca-update` `elpaca`
> 2. `M-x restart-emacs`
> 3. `M-x elpaca-update-menus` `elpaca-menu-melpa`
> 
> Thank you both.

Before you mentioned my issues with  my pkg installs using elpaca. 
Can you  go into detail.

**Comment by progfolio** [comment]
You shouldn't need to add `:wait t` except for a few special cases. Try removing all of those and see how that works.

**Comment by ScriptMang** [comment]
I managed to figure out.
My start time went down from 10s to 6 seconds.
Pkgs update quicker too. 
Thanks again for pointing it out.

https://github.com/ScriptMang/emacs-config

**Comment by progfolio** [comment]
> the section on async from this page helped alot https://github.com/progfolio/elpaca/wiki/Migrating-to-Elpaca. It should be at the home-page, to prevent beginners like me from using `:wait t` and `:demand t`.

I'm glad it was helpful. `:demand t` has nothing to do with Elpaca, that's a use-package setting. The wiki and manual are linked to from the README, which is intended to provide a brief overview.
