### ISSUE TITLE
[Bug/Support]: Can't use custom `elpaca-directory` (No such file or directory, ./elpaca-autoload)

### ISSUE THREAD

**Issue by azzamsa** [progfolio/elpaca#391]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 34b1d1b grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 30.0.92 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)
 of 2024-11-26
git --version:  git version 2.47.1
evil-line-move: Beginning of buffer
Elpaca 34b1d1b grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 30.0.92 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)
 of 2024-11-26
git --version:  git version 2.47.1
```

### Operating System

```
OS: Fedora Linux 41 (Workstation Edition) x86_64
DE: GNOME 47.1
WM: Mutter (Wayland)
```

### Description

I use `(setq straight-base-dir camp-var-dir)` for Straight and it has no issue. But when doing the same for `elpaca-directory (expand-file-name "elpaca/" camp-var-dir)` , it didn't work.

I also tried `elpaca-directory (expand-file-name "var/elpaca/" user-emacs-directory)`, because `camp-var-dir` is just `(defvar camp-var-dir (expand-file-name "var/" user-emacs-directory))`. But it also doesn't work.

The error message is:

```
⛔ Warning (initialization): An error occurred while loading ‘/home/user/.config/emacs/init.el’:

File is missing: Cannot open load file, No such file or directory, ./elpaca-autoloads

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by progfolio** [comment]
> ### Description
> The error message is:
> 
> ```
> ⛔ Warning (initialization): An error occurred while loading ‘/home/user/.config/emacs/init.el’:
> 
> File is missing: Cannot open load file, No such file or directory, ./elpaca-autoloads
> 
> To ensure normal operation, you should investigate and remove the
> cause of the error in your initialization file.  Start Emacs with
> the ‘--debug-init’ option to view a complete error backtrace.
> ```

Please share the full backtrace when starting emacs with the `--debug-init` flag as well as the init file which throws the error.

**Comment by progfolio** [comment]
> Result of `emacs --debug-init`
> 

> ```lisp
> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "./elpaca-autoloads")
>   load("./elpaca-autoloads")
> ```

Does the issue persist if you try a clean install?

>   I changed
>   
>   ```diff
>   modified   core/camp-bootstrap.el
>   -(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
>   +(defvar elpaca-directory (expand-file-name "var/elpaca/" user-emacs-directory))
>   ```

That should do the trick, and I'm unable to reproduce the issue on my end with the following test case:


``` emacs-lisp
(elpaca-test
  :interactive t
  :early-init
  (setq elpaca-directory (expand-file-name "var/elpaca/" user-emacs-directory)))
```

**Comment by azzamsa** [comment]
Thanks, worked like a charm! 🍩 

Thanks for Elpaca.

```diff
 ;; -*- lexical-binding: t; -*-
 
 (defvar elpaca-installer-version 0.8)
-(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
+(defvar elpaca-directory (expand-file-name "elpaca/" camp-var-dir))
 (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
 (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
 (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
@@ -35,7 +35,7 @@
   (unless (require 'elpaca-autoloads nil t)
     (require 'elpaca)
     (elpaca-generate-autoloads "elpaca" repo)
-    (load "./elpaca-autoloads")))
+    (load (expand-file-name "./elpaca-autoloads" repo))))
 (add-hook 'after-init-hook #'elpaca-process-queues)
 (elpaca `(,@elpaca-order))
 ```
