### ISSUE TITLE
[Bug/Support]: Issues using elpaca-after-init-hook

### ISSUE THREAD

**Issue by JordanAnthonyKing** [progfolio/elpaca#392]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 34b1d1b HEAD -> master, origin/master, origin/HEAD
installer:      0.8
emacs-version:  GNU Emacs 31.0.50 (build 1, x86_64-w64-mingw32)
git --version:  git version 2.47.0.windows.2
```

### Operating System

Windows 11

### Description

I've been having issues with elpaca-after-init-hook. Several modes I try to enable with it don't work.
For example, these three modes don't activate:
```
(add-hook 'elpaca-after-init-hook 'recentf-mode)
(add-hook 'elpaca-after-init-hook 'savehist-mode)
(add-hook 'elpaca-after-init-hook 'save-place-mode)
```

Neither does this:
```
(use-package pulsar
  :ensure t
  :commands pulsar-global-mode
  :hook (elpaca-after-init . pulsar-global-mode))
```

But this does:
```
(use-package tab-bar-echo-area
  :ensure t
  :defer t
  :hook (elpaca-after-init . tab-bar-echo-area-mode))
```

Here's the value of the hook immediately after init:
```
(tab-bar-echo-area-mode global-ligature-mode global-corfu-mode marginalia-mode
                        vertico-mode evil-mode undo-fu-mode pulsar-global-mode
                        which-key-mode after-init-test save-place-mode
                        savehist-mode recentf-mode global-auto-revert-mode)
```

Looking  a bit closer, all of the modes after evil aren't active.
All I notice is that I have evil configured with `:ensure (:wait t)`. I have several other modes also hooking evil-mode.

Thanks.

**Comment by progfolio** [comment]
I see you've closed the issue. Get it sorted out?

**Comment by JordanAnthonyKing** [comment]
undo-fu-mode isn't a real mode :L
