### ISSUE TITLE
[Feature]: Warning to update installer snippet on pulling elpaca 

### ISSUE THREAD

**Issue by deadcombo** [progfolio/elpaca#394]
### Feature Description

Hi, I'd like a heads-up whenever I should update the installer snippet - previously I ran into `installer version mismatch` but it was not the case for 0.8, which I only noticed now.
I propose a warning to the *Warnings* buffer when a new installer is available.
Alternatively making the installer part of elpaca proper so the `git pull` takes care of it automatically.

Thank you.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> ### Feature Description
  
> I propose a warning to the *Warnings* buffer when a new installer is available.

That is the case. The check is performed each time Elpaca is loaded.
A warning will still be displayed if a mismatch is detected.
See the following test case, which prints a warning for the current installer (version 0.8).

``` emacs-lisp
(elpaca-test
  :interactive t
  :early-init
  (setq elpaca-installer-version 0.7))
```

> Alternatively making the installer part of elpaca proper so the `git pull` takes care of it automatically.

The installer is tracked in Elpaca's repo at [https://github.com/progfolio/elpaca/blob/master/doc/installer.el](./doc/installer.el).
When you pull in changes, the package is not automatically reloaded. It will be reloaded once Emacs is restarted, and the version check happens at that time.
If you'd like to reload the package when a pull is performed, you'll have to write a custom build step to do so.

**Comment by brhertz** [comment]
> The installer is tracked in Elpaca's repo at [https://github.com/progfolio/elpaca/blob/master/doc/installer.el](./doc/installer.el). 

Awesome, that's what I was about to ask. Whether it's possible to keep the installer code I run in tune with the repo by simply loading a file that's also part of the repo and kept in sync with the developing code base.

Directly copying such a chunk verbatim - which also includes a version number and some nontrivial logic - into your init file, as suggested in the README, seems a bit risky to me, in case one happens to perform a git pull after a longer while.

Thanks!
