### ISSUE TITLE
[Feature]: Support for Emacs < 27.1

### ISSUE THREAD

**Issue by eflanigan00** [progfolio/elpaca#396]
### Feature Description

I'm restricted to use Emacs 26. It would be great if elpaca could run on that. 

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a feature request. I don't plan on providing support for Emacs versions lower than 27.1 at this time.
