### ISSUE TITLE
[Support]: Guidance on updating all packages

### ISSUE THREAD

**Issue by ashton314** [progfolio/elpaca#41]
### Emacs Version

GNU Emacs 30.0.50 (build1, aarch64-apple-darwin21 ...) 2022-12-01

(Yes, running bleeding edge. Why not?)

### Operating System

macOS

### question

What is the "blessed way" to update all packages? I've been going into `elpaca-manager`, holding down `u` to mark all packages for update, hitting `x`, then waiting a while. Then I'll mark all packages with `r` and wait a little longer until they rebuild. Is there a better way?

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
`M-x elpaca-update-all` should work

**Comment by ashton314** [comment]
Well the name should have tipped me off. 🤦🏼‍♂️ Thanks!
