### ISSUE TITLE
[Feature]: move detailed information from README to someplace else

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [progfolio/elpaca#43]
### too much information in the readme

IMO although the readme does contain useful information I think that it goes too much in depth sometimes.  Not that this shouldn't be documented, but I think that parts of the README are definitely more focused for a developer or for someone wishing to customize/do something more involved or nuanced as opposed to someone just wishing to try a new package manager and install packages.

### sections I think should perhaps be moved to a developer readme. 

[inheritence-precedence](https://github.com/progfolio/elpaca#inheritance-precedence)
[menus](https://github.com/progfolio/elpaca#menus)
[orders](https://github.com/progfolio/elpaca#orders)
[queues](https://github.com/progfolio/elpaca#queues)

### what I think the readme should contain

Here I make the assumption that the README should be intended for users that are either not well versed in elisp  or just want to get going and switch to a new package manager. To that end, the most important points are the bootstrapping, installing packages and--since I know people are going to be confused by this--the how to make sure their init is loaded in the proper order. Right now this is mentioned in the FAQ, but I would even put this in the example config.

Maybe the recipe format could go into the developer's readme as well because `elpaca` provides a lot of recipes out of the box so maybe those details don't need to be there. I think quelpa also doesn't have exact recipe details in its readme.

* bootstrap snippet
* recipe format
* example config
* example installing packages (maybe can be bundled with example config)

Also I think `elpaca-try` should be mentioned or maybe aliased to `elpaca-install`. I get why it's named try over install. But I definitely had trouble identifying this function when I first tried `elpaca`.

I think this could bring a lot of new users. I know I was a bit intimidated and confused by some of the depth of the readme which I later realized I didn't need to understand at all for basic usage. I think also the readme doesn't do justice to how good of a package manager elpaca actually is. I remember thinking "ah ok, looks like its a bit better than straight" when I first read the readme when it's in actuality leagues ahead of any other known package manager. Maybe a gif of the `elpaca-log` when installing a package would be nice too.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks again for your input.
I agree with the general thrust of your points.

WIP branch where I'm rewriting the README, adding an Info manual, and will be adding some demo GIFS/link to a video tour of the package: https://github.com/progfolio/elpaca/tree/feat/doc

I'll likely finish up work on this later today.

**Comment by progfolio** [comment]
I've merged most of the changes described in my last comment.
I need to capture a better demo gif and record the video tour, but there is a placeholder to give an idea of what it will be like.

Elpaca now much shorter README, and an Info manual (also available in markdown so it can be browsed via github, etc) which contains what the README used to and then some.

I'm sure there are still some rough edges (I don't like the way the footnotes and internal links work when exporting to texinfo, so I'll have to look into possibly changing that), but it's a start.

**Comment by Luis-Henriquez-Perez** [comment]
> I need to capture a better demo gif and record the video tour, but there is a placeholder to give an idea of what it will be like.
> Elpaca now much shorter README, and an Info manual (also available in markdown so it can be browsed via github, etc) which contains what the README used to and then some.

I like the changes to the README very much. It is much more concise. And it contains only the information pertinent to the basics of getting it working.

I particularly like that you mention this: "Add any configuration which relies on after-init-hook, emacs-startup-hook, etc to elpaca-after-init-hook so it runs after Elpaca has activated all queued packages."

One thing I would consider adding--either in the example `init.el`, the bootstrap (debatable but I can see reasons why), or perhaps in the important section--is the trick where you move your config to `config.el` and load it in the `after-elpaca-init-hook`. Actually, maybe it would suffice just putting it in the info manual and linking to it in the README. 

The reason for adding this is to just to explicitly drive the point home. It the one "fool-proof" trick that I feel most users will opt for if they don't want to scour their config, separating what does and what doesn't depend on the startup process. It's arguably the simplest way to make your config work with elpaca out of the box.

**Comment by Luis-Henriquez-Perez** [comment]
On further consideration I suspect the init.el is the best place. Maybe a code snippet and a comment like the one below would be nice.

```elisp
;; Having moved main configuration to `config.el', make sure it's loaded only
;; after we're sure elpaca has installed and activated all the packages. 
(add-hook 'elpaca-after-init-hook
	  (lambda () (load (expand-file-name "config.el" user-emacs-directory))))
```

**Comment by progfolio** [comment]
`elpaca-wait` should simplify things here, but the non-blocking approach works, too.
I'm not sure if these belong in the repository demo files or another spot, like a wiki or something.
I'll think on it. Thanks again.
