### ISSUE TITLE
[Bug]: Code example in Queue section is wrong

### ISSUE THREAD

**Issue by kamoii** [progfolio/elpaca#44]
### Emacs Version

GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2022-12-25

### Operating System

Arch

### Bug Description

I think the example code in `Queue` section doesn't work.
My understanding is that (2) and (3) is executed before (1). Shouldn't (2) and (3) be the body of (1)? or maybe my understanding is wrong.
```
(elpaca-queue
              (elpaca (melpulls :host github :repo "progfolio/melpulls"))   ;; (1)
              (add-to-list 'elpaca-menu-functions #'melpulls)  ;; (2)
              (elpaca-update-menus #'melpulls))  ;; (3)
;; Implicitly queued into a new queue.
(elpaca menu-item-available-in-melpulls)
```

**Comment by progfolio** [comment]
Thank you. That example is indeed outdated. The forms should be part of the elpaca /BODY/. I'm in the middle of rewriting the README as well as writing an Info manual. I'll be sure to update the example in the upcoming version.
