### ISSUE TITLE
[Feature]: Install and manage a non elisp package

### ISSUE THREAD

**Issue by dinkonin** [progfolio/elpaca#46]
### Feature Description

Hello  I'm trying to install[ this tree-sitter language definitions bundle](https://github.com/casouri/tree-sitter-module/)  using elpaca like this:
```elisp
(elpaca-use-package (tree-sitter-module
             :type git :host github
             :repo "casouri/tree-sitter-module"
             :pre-build (("./batch.sh"))
             :files ("dist/*.so" "dist/*.dll" "dist/*.dylib"))
  :init
  (with-eval-after-load 'treesit
    (add-to-list 'treesit-extra-load-path
		 (concat elpaca-builds-directory "tree-sitter-module"))))
```
It builds it and symlinks the modules in the builds directory but elpaca signals this error.
`elpaca--queue-dependencies: (error "Unable to find main elisp file for tree-sitter-module)`

How can I instruct it not look for a main elisp file, I tried `:main nil` and   `:build (:not elpaca--queue-dependencies)`?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for the report.
`elpaca--queue-dependencies` was unconditionally added to the list of build steps when a package's build dir is on disk.
I had a note about possibly fixing it, but I didn't think I'd see a use case crop up so soon.
I've removed the restriction in the 6780771. This should allow you to add:

```emas-lisp
:build (:not elpaca--queue-dependencies)
```

to your recipe to skip that step.

You can update Elpaca via the `elpaca-update` command followed by restarting Emacs.
Testing is appreciated.

**Comment by progfolio** [comment]
I actually tested this out myself. 
It's probably easier to explicitly include build steps instead of excluding them. 
A glob after the directory name in the `:files` directive should copy everything over. 
The `:type` keyword is not currently recognized by Elpaca (it's a striaght recipe keyword),
but it currently won't harm anything by being there.
This recipe worked for me:

```emacs-lisp
(elpaca (tree-sitter-module
         :host github :repo "casouri/tree-sitter-module"
         :pre-build ("./batch.sh")
         :files ("dist/*")
         :build ( elpaca--clone elpaca--add-remotes
                  elpaca--fetch elpaca--checkout-ref
                  elpaca--run-pre-build-commands elpaca--link-build-files)))
```

**Comment by dinkonin** [comment]
Using this recipe builds and installs the modules without error but for some reason rebuilds them on every emacs startup.

**Comment by progfolio** [comment]
Ah, that's right. We'll still want to use `:not` to exclude build steps.
Try the following recipe:

```emacs-lisp
(elpaca (tree-sitter-module
         :host github :repo "casouri/tree-sitter-module"
         :pre-build ("./batch.sh")
         :files ("dist/*")
         :build (:not elpaca--clone-dependencies elpaca--queue-dependencies
                      elpaca--generate-autoloads-async elpaca--byte-compile
                      elpaca--compile-info elpaca--install-info
                      elpaca--add-info-path elpaca--activate-package)))
```

**Comment by dinkonin** [comment]
It's working now. Thank you!

**Comment by progfolio** [comment]
Thank you for testing.
