### ISSUE TITLE
[Support]: How to work with multiple remotes (forks, in particular)?

### ISSUE THREAD

**Issue by ktetzlaff** [progfolio/elpaca#50]
### Emacs Version

GNU Emacs 30.0.50
Development version 26b93ce7cc1d on kt_fix_sieve-manage_multibyte_handling branch; build date 2022-12-31.

### Operating System

Debian bookworm

### question

I'm currently using `straight.el` and just started to play around with `elpaca`. I really like it, thanks for working on this!

However, somehow I cannot convert the following:

```elisp
(use-package zenburn-theme
  :straight (:fork (:protocol ssh)) ;; :repo "ktetzlaff/zenburn-emacs"
  :init
  (load-theme 'zenburn t nil)
```

to an equivalent _elpaca_ recipe.

With _straight_, the form above creates a clone with remotes `origin` (from the original recipe) and `fork` (my fork). _straight_ then uses `fork/master` to install the package. However, _elpaca_ ends up using `origin/master` (which is _bbatsov/zenburn-emacs_ __not__ _ktetzlaff/zenburn-emacs_) for the package installation.

I first tried the following:

```elisp
(elpaca-use-package (zenburn-theme
                     :remotes (("fork"
                                :host github  ;; why is it necessary to specify the :host?
                                :protocol ssh ;; the :protocol keyword is missing in the documentation
                                :repo "ktetzlaff/zenburn-emacs")
                               "origin"))
  :init
  (load-theme 'zenburn t nil))
```

then:

```elisp
(elpaca-use-package (zenburn-theme
                     :remotes (("fork"
                                :host github
                                :repo "ktetzlaff/zenburn-emacs"
                                :protocol ssh)
                               ("origin"
                                :host github ;; why is it necessary to repeat :host?
                                :repo "bbatsov/zenburn-emacs"
                                :protocol https)))
  (load-theme 'zenburn t nil))
```
But in both cases, the branch which gets used during the build/install phase, is `origin/master` (aka _bbatsov/zenburn-emacs_) not my fork.

I even tried:

```elisp
(elpaca-use-package (zenburn-theme
                     :remotes ("fork"
                               ("fork"
                                :host github
                                :repo "ktetzlaff/zenburn-emacs"
                                :protocol ssh)))
  :init
  (load-theme 'zenburn t nil))
```

Which, at first glance, looked to do the right thing:

```sh
git -C zenburn-emacs status
# On branch master
# Your branch is up to date with 'fork/master'.
```
So, there is now a branch `fork/master`, but now _forks' URLs_ points to _bbatsov/zenburn-emacs_ and not _ktetzlaff/zenburn-emacs_:

```sh
git -C zenburn-emacs remote -v
fork    https://github.com/bbatsov/zenburn-emacs.git (fetch)
fork    https://github.com/bbatsov/zenburn-emacs.git (push)
```

---

After that, some remarks regarding the _elpaca_ `:remotes` documentation:

> The first element is the default remote when installing the package. If it is a string, it names the default remote. The remaining elements are lists of the form: (NAME . PROPS)

From this, it is not clear to me, how to select the default remote. The first sentence seems to indicate that the order of remotes decides which remote should be the default. However, the second sentence then seems to state that the first element is only used as default if it is a string?

Anyway, since I always end up with `origin/master`: What needs to be done to get `fork/master`?

The documentation then goes on:

> NAME is a string used to name the remote. PROPS are recipe keyword/value pairs used to override values previously declared in the recipe.

Here, the _... used to override values previously declared in the recipe ..._ part doesn't seem to be working. E.g. even in the 2nd example, leaving out the `:host` in the `origin` remote results in an error (due to `:host nil`).

### Relevant information

```emacs-lisp
elpaca commit SHA: 008949ef8edf804e4833d5
```

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
Thanks for bringing this to my attention.

I've refactored this feature. It should work as expected now. I've also reworded the [documentation](https://github.com/progfolio/elpaca/blob/master/doc/manual.md#recipes) and added additional logging to, hopefully, make it clearer how to use. Testing is appreciated.

**Comment by ktetzlaff** [comment]
> Testing is appreciated.

Ok, here we go ...

With the following recipe:
```elisp
(elpaca
 (zenburn-theme :depth nil
                :remotes (("fork"
                           :repo "ktetzlaff/zenburn-emacs"
                           :protocol ssh))))
```
the inheritance is now working. And the result:
```sh
git -C zenburn-emacs remote -v
# fork    git@github.com:ktetzlaff/zenburn-emacs.git (fetch)
# fork    git@github.com:ktetzlaff/zenburn-emacs.git (push)
# origin  https://github.com/bbatsov/zenburn-emacs.git (fetch)
# origin  https://github.com/bbatsov/zenburn-emacs.git (push)

git -C zenburn-emacs branch -a
# * fork/master
#   master
#   remotes/fork/master
#   remotes/origin/HEAD -> origin/master
#   remotes/origin/master

git -C zenburn-emacs status
# On branch fork/master
# Your branch is up to date with 'remotes/fork/master'.
# ...
```
also looks just fine. Thanks!

Two minor issues:

1. The keyword `:remotes` is a bit misleading (at least to me). It really allows
   to specify additional remotes to the original remote from the recipe. So
   maybe something like `:extra-remotes` would be better?

2. I'm wondering why there are two checked out branches. I would have expected
   (or preferred) just a single `master` branch (named `master` checked out from
   remote `fork`.

   It's not a big issue, but would you consider to change the logic, clone with
   `--no-checkout` and then later - just once - checkout the default branch of
   the default remote?

---

What I also noticed: When starting Emacs the first time after adding a new
Elpaca git recipe, Emacs show the elpaca-log buffer. What I get is just a single
for the new package line which gets automatically updated as the
clone/fetch/checkout/build sequence proceeds.

To see the details I tried to expand the log by pressing `l` on the _package
line_. But that's somewhat difficult since point tends to jump to the _title line_
of the table. So you have to be pretty fast to move point to the _package line_
and press `l` before point jumps back up.

Is it possible to keep point on the last line of the buffer?

**Comment by ktetzlaff** [comment]
Ah - I forgot: The updated documentation is much clearer now. Thanks again!

However, it still doesn't mention the `:protocol` keyword. 😏

**Comment by progfolio** [comment]
> I'm wondering why there are two checked out branches. I would have expected
> (or preferred) just a single master branch (named master checked out from
> remote fork.
>
> It's not a big issue, but would you consider to change the logic, clone with
> --no-checkout and then later - just once - checkout the default branch of
> the default remote?

I've reworked the logic to give the shorter branch name to the checked out remote.
With the following recipe:

```emacs-lisp
(zenburn-theme :remotes ("fork" :host github :repo "progfolio/zenburn-emacs"))
```

My fork remote is checked out with head at it's master branch. 
The origin remote is still present, but has its master branch renmaed to origin/master.
I want to keep both remotes because the intended workflow here is for contributing patches
to other remotes.

If you want a single remote pointing at your personal fork of a repository, you can override the recipe without the `:remotes` keyword. e.g.

```emacs-lisp
(zenburn-theme :host github :repo "my/zenburn-emacs")
```

I also missed this in your example earlier:

> why is it necessary to specify the :host [in the :remote entry]?

It's not strictly necessary. If it isn't specified, it will be inherited from the top-level recipe's `:host`. However, I would recommend being more explicit in this case in case the upstream recipe changes hosts.

Does that help?

**Comment by ktetzlaff** [comment]
> I've reworked the logic to give the shorter branch name to the checked out remote. With the following recipe:
> 
> ```emacs-lisp
> (zenburn-theme :remotes ("fork" :host github :repo "progfolio/zenburn-emacs"))
> ```
> 
> My fork remote is checked out with head at its master branch. The origin remote is still present, but its master branch is renamed to origin/master.

Thanks, but I don't think this is a good idea. Because now the _local branch_ `origin/master` actually hides the _remote branch_. git even warns about that. E.g. `git log -10 origin/master` now produces a `warning: refname 'origin/master' is ambiguous.`

For a typical _fork workflow_ (like github _pull requests_ or gitlab _merge requests_) where people don't have write access to the original remote), that is not helping. Typically, to sync the fork with upstream (aka origin), people would either rebase or merge _fork_ with _origin_. E.g. `git rebase origin/master`. But that would now presumably merge from the _local_ `origin/master` branch (in fact it does that with my current git 2.39.0 - but considering the _ambiguous_ warning, this might not be the case with a different git version).

Anyway, to achieve the original goal of syncing fork with origin, either the _local_ `origin/master` branch would need to be updated first, or people would need to remember to use `remotes/origin/master` to actually get the intended result.

> I want to keep both remotes because the intended workflow here is for contributing patches to other remotes.

If that's a concern, maybe use a different branch naming scheme for local branches. E.g. replace the `/` with a `.`? Or don't create a local branch by default and add an option for people who actually need it (e.g. `:localname`).

> > why is it necessary to specify the :host [in the :remotes entry]?
> 
> It's not strictly necessary. If it isn't specified, it will be inherited from the top-level recipe's `:host`. However, I would recommend being more explicit in case the upstream recipe changes hosts.

Ok, yes - that sounds like good advice.

**Comment by progfolio** [comment]
Thanks for the input. I've reworked things to avoid shadowing remote names with branch names. A list of examples assuming the following order:

```emacs-lisp
(elpaca (zenburn-theme :remotes VALUE))
```

| :remotes VALUE                                                             | repo state                                                         |
|-------------------------------------------------------------------------- |------------------------------------------------------------------ |
| "origin" or ("origin")                                                     | origin->master                                                     |
| "renamed" or ("renamed")                                                   | renamed->master                                                    |
| ("fork" :host github :repo "progfolio/zenburn-emacs") or ((ditto&#x2026;)) | fork->master; origin remote has no local branch checked out        |
| (("origin" ("fork" :host github :repo "progfolio/zenburn-emacs")))         | origin->master; fork remote has no local branch checked out        |
| (("renamed" ("fork" :repo "progfolio/zenburn-emacs")))                     | renamed->master; fork remote (:host inherited) has no local branch |

Thoughts?

**Comment by ktetzlaff** [comment]
> ...
> Thoughts?

Looks good to me. Thanks!
