### ISSUE TITLE
[Feature]: Improve logging. E.g. (add option to) increase log verbosity/log external comands.

### ISSUE THREAD

**Issue by ktetzlaff** [progfolio/elpaca#51]
### Feature Description

While trying to figure out what was going on in recipes with multiple remotes (s. #50), I found the available logs lacking. E.g. with the following recipe:

```elisp
(elpaca-use-package (zenburn-theme
                     :remotes (("fork"
                                :host github
                                :repo "ktetzlaff/zenburn-emacs"
                                :protocol ssh)
                               ("origin"
                                :host github
                                :repo "bbatsov/zenburn-emacs"
                                :protocol https))))
```

the log contains:

```
...
zenburn-theme                  cloning              Adding Remotes                                                                   03.920017
zenburn-theme                  cloning              Fetching origin                                                                  04.024162
zenburn-theme                  cloning               * [new branch]      master     -> fork/master                                   08.925965
zenburn-theme                  cloning              Remotes fetched                                                                  08.926009
zenburn-theme                  ref-checked-out      remote's HEAD checked out                                                        08.926020
...
```

Which is missing a lot of relevant information and contains some inconsistencies. Like:

* _Adding Remotes_: Which remotes got added/fetched?
* _Fetching origin_: How? From where?
* After _Fetching origin_, the next message is about a new branch _fork/master_. Why? Where did _fork_ get fetched?
* _remote's HEAD checked out_: HEAD of which remote?

As a quick overview, the current logging is fine. But also quite useless when it really matters. ;-)

As a suggestion: It would help a lot if the external (git, build, install, ...) commands which are executed would be logged. Maybe after enabling verbose logging via a customizable variable.

---

Further down, it gets much more detailed:

```
zenburn-theme                  byte-compilation     Byte compiling                                                                   09.122967
zenburn-theme                  byte-compilation     Checking /home/kai/.emacs.d/minimal/elpaca/builds/zenburn-theme...               09.249076
zenburn-theme                  byte-compilation     Compiling /home/kai/.emacs.d/minimal/elpaca/builds/zenburn-theme/zenburn-theme-autoloads.el... 09.261003
zenburn-theme                  byte-compilation     Compiling /home/kai/.emacs.d/minimal/elpaca/builds/zenburn-theme/zenburn-theme.el... 09.261011
zenburn-theme                  byte-compilation     Done (Total of 0 files compiled, 2 skipped)                                      09.261019
zenburn-theme                  byte-compilation     Byte compilation complete                                                        09.261058
```

However, now some of the messages are too long to fit into the elpaca-ui table and get cut off. The log seems to claim that two files got byte compiled (`Compiling ...`). But, in the next line the log continues with: `Done (Total of 0 files compiled, 2 skipped)`. So actually nothing got compiled? Why? Maybe having the complete messages would clarify this (or maybe not, s.  [1]).

Is there a way to see the complete log lines?

[1] The zenburn theme sources are a bit peculiar. Byte-compiling the `.el` files actually does not produce any output. I.e. there are no `.elc` files.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for the feedback.

> Adding Remotes: Which remotes got added/fetched?

Agreed. The function which takes care of this needs to be refactored/renamed.
It's really configuring remotes (possibly renaming as well as adding).
The refactor will hopefully address #50 as well.

> As a quick overview, the current logging is fine. But also quite useless when it really matters.

Useless is a bit of an exaggeration, IMO. The log gives insight into each step in the process. This allows one to quickly tell what step of a the process the package is blocked or failed at when that happens. It also logs all output from `:pre/post-build` commands. I'm sure I can improve the logging, though.

>  It would help a lot if the external (git, build, install, ...) commands which are executed would be logged. Maybe after enabling verbose logging via a customizable variable.

I've added a user option, `elpaca-verbosity` (defaulting to 0).
Log events are now given a "verbosity" number.
The `elpaca-log` buffer will display all log events which are less than or equal to the user's `elpaca-verbosity` setting. This value can be temporarily changed in the log buffer by using the `#verbosity` search tag with an argument. e.g. `#(verbosity 1)` will display all the log events + the commands being issued. If you prefer to see them by default, `(setq elpaca-verbosity 1)` (or most-positive-fixnum if you want to ensure all  future events are shown) before the bootstrap snippet should work.

I've also added some logging to the default process filter functions (which most of Elpaca's funtions use when creating sub processes) that will log the command being issued with a verbosity of 1.

> However, now some of the messages are too long to fit into the elpaca-ui table and get cut off. 

> Is there a way to see the complete log lines?

This is how the built-in tabulated-list-mode works.
There should be a tool tip which will display the full text when mousing an abbreviated line.
The columns can also be widened/narrowed via the `tabulated-list-(widen/narrow)-current-column` commands. I also plan on adding a way to dump the log view to a buffer which is not in tabulated list mode, which should make logs easier to view and share. 

>  The log seems to claim that two files got byte compiled (Compiling ...). But, in the next line the log continues with: Done (Total of 0 files compiled, 2 skipped). So actually nothing got compiled? Why? 

That is the output of Emacs byte-compiler. 
It scans each file to see if it needs to be compiled.
In that package's particular case, it specifies a local variable which prevents byte compilation in both the autoloads and main file. e.g.

```emacs-lisp
;; Local Variables:
;; no-byte-compile: t
```

That is why both files are skipped and why the byte compiler can't know ahead of time whether or not it will be able to compile them.

As always, testing is appreciated. You should be able to update Elpaca via the `elpaca-update` command followed by `restart-emacs`. Thanks again.

**Comment by ktetzlaff** [comment]
> > As a quick overview, the current logging is fine. But also quite useless when it really matters.
> 
> Useless is a bit of an exaggeration, IMO.

Yes, I should have added a smiley. 😉
 
> > It would help a lot if the external (git, build, install, ...) commands which are executed would be logged. Maybe after enabling verbose logging via a customizable variable.
> 
> I've added a user option, `elpaca-verbosity` (defaulting to 0).
> ...
> If you prefer to see them by default, `(setq elpaca-verbosity 1)` (or most-positive-fixnum if you want to ensure all future events are shown) before the bootstrap snippet should work.

Thanks! I've added:

```elisp
(defvar elpaca-verbosity (if init-file-debug most-positive-fixnum 0))
```

at the top of the bootstrap snippet to enable verbose logging when emacs gets started with `--debug-init`.

> I've also added some logging to the default process filter functions (which most of Elpaca's funtions use when creating sub processes) that will log the command being issued with a verbosity of 1.

That really helps, great!

> > Is there a way to see the complete log lines?
> 
> There should be a tool tip which will display the full text when mousing over an abbreviated line.

Ah, yes - good to know.

> I also plan on adding a way to dump the log view to a buffer which is not in tabulated list mode, which should make logs easier to view and share.

Yes, please. 👍 With your `tabulated-list-widen-current-column` hint, I already kind of get that: move point to 3rd column, press `C-u 2000 M-x }`, `C-x h` (`mark-whole-buffer`), `M-w` (`kill-ring-save`) and yank the result into a new buffer.

> > So actually nothing got compiled? Why?
> 
> That is the output of Emacs byte-compiler. It scans each file to see if it needs to be compiled. In that package's particular case, it specifies a local variable which prevents byte compilation in both the autoloads and main file. e.g.
> 
> ```emacs-lisp
> ;; Local Variables:
> ;; no-byte-compile: t
> ```

Ah, yes - thanks (now that you mention it, I think I remember having seen that before). And after widening the log msg column, the complete log output from the byte compiler isn't really helping either (they could provide a hint that compiling was skipped due to the `no-byte-compile: t`).

> As always, testing is appreciated. You should be able to update Elpaca via the `elpaca-update` command followed by `restart-emacs`. Thanks again.

And a Big Thanks back to you for the fast response (and for working on elpaca)!

**Comment by progfolio** [comment]
> (they could provide a hint that compiling was skipped due to the no-byte-compile: t)

That may be worth reporting to Emacs developers if you think it would be better.
I don't know if it would be easy for them to implement or not, or if they have already considered it.

Glad the new feature is working for you, though.
I'll improve the logs as Elpaca develops.
