### ISSUE TITLE
Elpaca does not respect --debug-init

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#53]
[I] start an emacs instance with `--debug-init` enabled, but the backtrace isn't showing up. And emacs's is suggesting that I didn't use the debug flag.

_Originally posted by @Luis-Henriquez-Perez in https://github.com/progfolio/elpaca/issues/42#issuecomment-1377247681_

**Comment by Luis-Henriquez-Perez** [comment]
To provide more information: I used `(start-process "emacs" nil "emacs" "--debug-init")` to create the emacs instance.

This is the specific function I ran to open the emacs instance. I'm using archlinux so I am certan that the `gnu/linux` clause is what went through.

```
(defun oo/open-emacs-instance ()
  "Open a new emacs instance in debug-mode."
  (interactive)
  (pcase system-type
    ('darwin
     (start-process-shell-command "emacs" nil "open -n /Applications/Emacs.app --args --debug-init"))
    ('gnu/linux
     (start-process "emacs" nil "emacs" "--debug-init"))))
```

**Comment by progfolio** [comment]
Please provide your full init files and I will try to reproduce. Thanks.

**Comment by Luis-Henriquez-Perez** [comment]
Thit zip contains my `init.el`, my `recipe.org` file and my `config.el` file. The `config.el` file shouldn't be necessary I tested with the loading the `config.el` commented out. You will need to change the path `~/dotfiles/recipes.org` to what suits you.

```elisp
(defun oo-read-recipes ()
  "Return a list of recipes from recipe file."
  (with-temp-buffer
    (insert-file-contents "~/dotfiles/recipes.org")
    (goto-char (point-min))
    (let (orders)
      (while (re-search-forward "#\\+begin_src emacs-lisp\n\\(?1:.+\\)\n#\\+end_src" nil t)
	(push (cadr (car (read-from-string (match-string 1)))) orders))
      orders)))
```

[initfiles.zip](https://github.com/progfolio/elpaca/files/10384040/initfiles.zip)
