### ISSUE TITLE
[Support]: GNU ELPA menu not downloading to custom elpaca-directory

### ISSUE THREAD

**Issue by Cloudcolour** [progfolio/elpaca#54]
### Elpaca Version

Elpaca version: ac3fbc9 HEAD -> master, origin/master, origin/HEAD
GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-11

### Operating System

Arch Linux

### question

When I modify `elpaca-directory` to a custom path the bootstrapping process fails for GNU ELPA mirror. 

Here is what my bootstrap looks like, 
```lisp
(declare-function elpaca-generate-autoloads "elpaca")
(defvar elpaca-directory (expand-file-name "elpaca/" path-packages-dir))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :build (:not elpaca--activate-package)))
(when-let ((elpaca-repo (expand-file-name "repos/elpaca/" elpaca-directory))
           (elpaca-build (expand-file-name "elpaca/" elpaca-builds-directory))
           (elpaca-target (if (file-exists-p elpaca-build) elpaca-build elpaca-repo))
           (elpaca-url  "https://www.github.com/progfolio/elpaca.git")
           ((add-to-list 'load-path elpaca-target))
           ((not (file-exists-p elpaca-repo)))
           (buffer (get-buffer-create "*elpaca-bootstrap*")))
  (condition-case-unless-debug err
      (progn
        (unless (zerop (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo))
          (error "%s" (list (with-current-buffer buffer (buffer-string)))))
        (byte-recompile-directory elpaca-repo 0 'force)
        (require 'elpaca)
        (elpaca-generate-autoloads "elpaca" elpaca-repo)
        (kill-buffer buffer))
    ((error)
     (delete-directory elpaca-directory 'recursive)
     (with-current-buffer buffer
       (goto-char (point-max))
       (insert (format "\n%S" err))
       (display-buffer buffer)))))
(require 'elpaca-autoloads)
;; (add-hook 'after-init-hook #'elpaca-process-queues)
(autoload 'elpaca--queue "elpaca")      ; needed because of byte-compilation of this file
(elpaca `(,@elpaca-order))
```
Here is my definition for `path-packages-dir`
```lisp
(defconst path-packages-dir
  (expand-file-name (format "packages/%s.%s/"
                            emacs-major-version
                            emacs-minor-version)
                    path-local-dir)
  "Where packages are stored.")
```
It has worked with `straight.el` without problems, so I don't believe it's the path formulation that's problematic.

When I use the default 
```
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
```
the GNU ELPA recipes download and install successfully. It seems like `elpaca` isn't looking in the right place when I change the value. 

Below is the output I get when building emacs from the command line with Eldev.

### Relevant information

```emacs-lisp
Loading /home/myusr/.config/emacs/init.el (source)...
Checking /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-log.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-menu-gnu-elpa-mirror.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-menu-non-gnu-elpa.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-process.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-test.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/elpaca.el...
Checking /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/doc...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/doc/early-init.el...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/doc/init.el...
Checking /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/images...
Checking /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/test...
Compiling /home/myusr/.config/emacs/.local/packages/29.0/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 10 files compiled, 3 skipped in 3 directories)
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Downloading MELPA recipes...
MELPA recipes downloaded.
MELPA menu index cached
Downloading GNU ELPA recipes...
No such file or directory
Contacting host: elpa.gnu.org:443
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      init-autoloads.el
Downloading GNU ELPA recipes...
No such file or directory
Contacting host: elpa.gnu.org:443
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Contacting host: elpa.gnu.org:443
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Contacting host: elpa.gnu.org:443
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
Downloading GNU ELPA recipes...
No such file or directory
No incomplete queues to process
```

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
Thanks for the report.
Could you tell me what the value of the `elpaca-cache-directory` and `user-emacs-directory` are at the time of failure?

**Comment by Cloudcolour** [comment]
The value for `elpaca-cache-directory` is
```lisp
"/home/myusr/..cache/emacs/packages/29.0/elpaca/cache"
```
and value for `user-emacs-directory` is 
```lisp
"~/.config/emacs"
```

**Comment by progfolio** [comment]
And how about `elpaca-menu-gnu-elpa-mirror-cache-path`?

**Comment by Cloudcolour** [comment]
Value for `elpaca-menu-gnu-elpa-mirror-cache-path` is
```lisp
"/home/trismegistus/.cache/emacs/packages/29.0/elpaca/cache/gnu-elpa-mirror.eld"
```

**Comment by progfolio** [comment]
Thank you.

Could you try evaluating the following in your \*scratch\* buffer? It works similar to `straight-bug-report`. It will install Elpaca in clean environment and start an interactive Emacs session with a possible fix. You'll have to point the `:early-init` and `:init` keywords to your files.

```emacs-lisp
(elpaca-test
  :ref "fix/gnu-elpa-cache"
  :early-init (:file "path/to/early-init.el")
  :init (:file "path/to/init.el"))
```

**Comment by Cloudcolour** [comment]
Here is my value for `path-local-dir`, which `path-packages-dir` depends on. 
```lisp
(defconst path-local-dir
  (concat
   (file-name-as-directory
    (or (getenv "XDG_CACHE_HOME")
        (concat path-home-dir ".cache")))
   "emacs/")
```
I might change this to the `.local` subdir of the `emacs` directory, but again, this has worked as-is with straight so far.

**Comment by progfolio** [comment]
Alternatively, you can test just by editing the `elpaca-order` variable in the bootstrap snippet to point to the `:ref` to "fix/gnu-elpa-cache".
You'll want to delete the elpaca-directory, elpaca-builds-directory, elpaca-cache-directory, and elpaca-directory/repos too.

**Comment by Cloudcolour** [comment]
Unfortunately, I tried both methods and deleted all of the aforementioned directories but I'm not getting any new behavior.

**Comment by progfolio** [comment]
I've pushed some more changes to see if we can hit the debugger or get a more descriptive error.
Please try again ensuring that Emacs is launched with the `--debug-init` command line option.
If you do hit the backtrace buffer, please copy its expanded contents here, else the contents of the messages buffer will do.

**Comment by progfolio** [comment]
I would also check what `(executable-find "git")` returns.

**Comment by progfolio** [comment]
I tried cloning your "flux-emacs" repository to see if I could reproduce the error on my end. However, I'm told to run an eru script which produces its own error.

**Comment by Cloudcolour** [comment]
Ah, I am not using the Eru script anymore. But I am using `Eldev`: https://github.com/doublep/eldev. 

I just now copy and pasted your bootstrap code on the off-chance there was some strange error that had creeped into mine, and it seems that GNU ELPA is downloading correctly. 

Unfortunately, I'm running into some strange issue with `use-package`. The `elpaca-log` command shows that the status of use-package is `cloning-deps", but it's stuck at that point. And this is causing issues elsewhere. 

But the original issue must have been tied to my bootstrap code.

**Comment by Cloudcolour** [comment]
I will spend more time dissecting what's going on with my setup. Thank you so much for your assistance, I really appreciate it.

**Comment by progfolio** [comment]
> But the original issue must have been tied to my bootstrap code.

I was able to get it the menus to download after installing eldev.
The issue you originally reported wasn't present. I hit some other error particular to config about a missing autoloads file which instructed me to run that eru script.

```sh
 $ ls /home/n/.config/flux-emacs/.local/packages/30.0/elpaca/cache/
gnu-elpa-mirror  gnu-elpa-mirror.eld  melpa  melpa.eld  menu-items.eld  non-gnu-elpa.eld
```
>  I'm running into some strange issue with use-package. The elpaca-log command shows that the status of use-package is `cloning-deps

There's a bug that has recently surfaced with repositories which contain more than one elisp package in them. I should have a fix for it soon.

However, your Emacs version may have use-package built in. You could simply require it instead of installing to work around the issue for now.
