### ISSUE TITLE
[Bug]: File named `orgguide.info` appears when rebuilding org package

### ISSUE THREAD

**Issue by leotaku** [progfolio/elpaca#59]
### Elpaca Version

elpaca-version: 2fc1b2f HEAD -> feat/elpaca-wait, origin/feat/elpaca-wait
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
git --version:  git version 2.39.0

### Operating System

NixOS Linux

### Bug Description

Whenever I rebuild or update the `org` package e.g. using `M-x elpaca-rebuild RET org RET`, a file named `orgguide.info` is created in the current directory of my Emacs process.

I would expect that such a file might be created during the build process of org, but it does not seem correct for it to be placed in the current directory.

**Comment by progfolio** [comment]
Thanks for the bug report.
Could you please provide a log by executing the following:

1. ` (setq elpaca-verbosity 1)`
2. `M-x elpaca-rebuild org`
3. `c` in the log buffer should copy the current view to the clipboard, which can be pasted here.

**Comment by progfolio** [comment]
The problem should be fixed on the latest version of Elpaca.
Try the following:

1. `M-x elpaca-delete org`
2. `M-x elpaca-delete elpaca`
3. Delete `~/.emacs.d/elpaca/cache/menu-items.eld`
4. Restart Emacs.

Emacs should install the latest version of Elpaca and Org.
The orgguide.info file should then be located in `~/.emacs.d/elpaca/builds/org/`.
Rebuilding Org should have the same effect.

**Comment by leotaku** [comment]
I agree, with the newest version the problem no longer appears for me. Thank you for the quick response and fix!

**Comment by progfolio** [comment]
Thanks for testing
