### ISSUE TITLE
[Support]: Extension not loading since elpaca-use-package deprecated

### ISSUE THREAD

**Issue by apancyborg** [progfolio/elpaca#60]
### Elpaca Version

elpaca-version: 45e724e HEAD -> master, origin/master, origin/HEAD
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2023-01-31

### Operating System

Linux x86_64

### question

This used to work but since elpaca-use-package is deprecated it throws an error:
 
```
(elpaca-use-package (vertico :files (:defaults "extensions/*"))
  :defer t
  :bind (:map vertico-map
              ("M-DEL" . vertico-directory-delete-word))
  :hook (rfn-eshadow-update-overlay . vertico-directory-tidy)
  :init (vertico-mode))
```

The error is the following:
 Failed to parse package (vertico :files (:defaults extensions/*)): Wrong type argument: symbolp, (vertico :files (:defaults "extensions/*"))

The elpaca nil method below also does not work:

```
(elpaca nil
  (use-package vertico-directory
    :after vertico
    :bind (:map vertico-map
                ("M-DEL" . vertico-directory-delete-word))
    :hook (rfn-eshadow-update-overlay . vertico-directory-tidy)))
```

Thanks a lot for your work on elpaca.

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by apancyborg** [comment]
This works perfectly. 
Thank you very much for taking the time to explain.

**Comment by ashton314** [comment]
I had this same issue, and this fix worked for me. (Though, I *did* have to run `elpaca-rebuild` to get the files to symlink.) This would make a nice addition to the README or manual. I'm happy to open a PR later when I get the chance if you'd like.

**Comment by progfolio** [comment]
I'd like to keep the docs succinct.
Adding a declaration which configures a built-in package to the demo init.el file with a brief comment should be clear enough. I'll add it to my Todo list.

**Comment by progfolio** [comment]
@ashton314 I've added such an example to the demo init.el. Thanks for the suggestion.
