### ISSUE TITLE
[Bug]: `savehist` install fails with `wrong-type-argument`

### ISSUE THREAD

**Issue by zetashift** [progfolio/elpaca#62]
### Elpaca Version

```sh
elpaca-version: cb819ec HEAD -> master, origin/master, origin/HEAD
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2202.70 Version 11.7.2 (Build 20G1020))
 of 2023-01-23
git --version:  git version 2.37.1 (Apple Git-137.1)
```

### Operating System

MacOS 13, ARM

### Bug Description

Hi! I'm kinda new to all this, I'm trying to setup `vertico` and `savehist`, but `savehist` fails to install:

Using the following code:
```elisp
;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :init
  (savehist-mode 1))
```

`savehist failed  elpaca--clone: (wrong-type-argument stringp nil)   00.188934`

**Comment by progfolio** [comment]
You'll want to add `:elpaca nil` to your use-package declaration for built-in packages so Elpaca does not attempt to install them.

**Comment by zetashift** [comment]
So this made the error go away:
```
;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :elpaca nil
  :init
  (savehist-mode 1))
  ```
  Thank you!

**Comment by progfolio** [comment]
Glad it was a simple fix. 
I've added a more descriptive error message for this type of failure.
Thank you for the report.
