### ISSUE TITLE
[Feature]: Throttling downloads 

### ISSUE THREAD

**Issue by dertuxmalwieder** [progfolio/elpaca#65]
### Feature Description

On Windows, I ran into a “too many open files” error too often - it seems that installing 20-or-so packages over Elpaca reaches the limit of what Windows provides. My workaround was to add *(elpaca-wait)* in random places, but that’s not an elegant solution.

Could we have a way to limit the number of parallel processes?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
The "feat/qlimit" branch contains preliminary work on such a feature.
Still buggy, but I plan on working it out.

**Comment by dertuxmalwieder** [comment]
Awesome. I will test it once it's in. :)

**Comment by progfolio** [comment]
I forgot to ask, how many packages are being installed?
Evaluating the following in the \*scratch* buffer should give the result:

```emacs-lisp
(length (elpaca--queued))
```

**Comment by dertuxmalwieder** [comment]
It's 67.

**Comment by progfolio** [comment]
I believe it has to do with how many file handles a process has open at once.

https://techcommunity.microsoft.com/t5/windows-blog-archive/pushing-the-limits-of-windows-handles/ba-p/723848

The above article shows some techniques for finding out how many files a process has open.
I will add a setting to mitigate the problem, but I'm curious what the limit is.

**Comment by dertuxmalwieder** [comment]
> I will add a setting to mitigate the problem, but I'm curious what the limit is.

[512](https://learn.microsoft.com/en-us/cpp/c-runtime-library/file-handling?redirectedfrom=MSDN&view=msvc-170), it seems.

**Comment by progfolio** [comment]
I've added a user option, `elpaca-queue-limit`, which I'm hoping will address this problem.
When set to an integer, it should block any orders which are explicitly queued (not dependencies which are queued as part of building an order) beyond that limit. The queue limit does not count packages which are already built, so it should not have a meaningful impact on startup times when everything is already built.
To test this branch:

1. Remove the extra `elpaca--wait` calls and set `elpaca-queue-limit` in your init file.
2. Edit  elpaca's recipe so the `:ref`  value is `"fix/proclimit"`. 
3. `M-x elpaca-delete`  `elpaca`
4. `M-x restart-emacs`

Testing is appreciated.
Thank you.

**Comment by dertuxmalwieder** [comment]
“Block” means “won’t happen any time”? Because that’d break my configuration. Or are they moved to separate queues?

**Comment by progfolio** [comment]
Sorry. I wasn't clear in my explanation. They're blocked until another processed order finishes and unblock them. It should limit the amount of orders being processed at once.

**Comment by dertuxmalwieder** [comment]
I’ll be on my Windows machine in an hour or so. I’ll report!

**Comment by dertuxmalwieder** [comment]
I report success :-) - tried with `(setq elpaca-queue-limit 25)` and a complete removal of the elpaca folder to trigger a complete rebuild. 15 was too much. 12 worked for me.

I got a handful of "queue limit exceeded" messages in the \*elpaca-log\*. (Maybe 12 is a sane default on `'windows-nt`?)

**Comment by progfolio** [comment]
> I report success :-) - tried with (setq elpaca-queue-limit 25) and a complete removal of the elpaca folder to trigger a complete rebuild. Even 15 was too much. 12 worked for me.

Glad it worked for you.

> I got a handful of "queue limit exceeded" messages in the *elpaca-log*

Those are expected. It's just letting you know why those orders have been blocked.

**Comment by dertuxmalwieder** [comment]
I thought so. I guessed it would make sense to report that your letting me know that the orders have been blocked is actually working as well... ;-)

**Comment by progfolio** [comment]
As far as a default value goes, I'll leave that to the user (defaulting to `nil`).
I haven't heard anyone else hitting the limit on Linux or Mac.

I'll merge this to master. Just remember to switch your elpaca recipe `:ref` back to `nil`.
