### ISSUE TITLE
[Feature]: Avoid eglot being installed as dependency when it's built-in

### ISSUE THREAD

**Issue by meliache** [progfolio/elpaca#66]
### Feature Description

I recently migrated from straight and I just noticed that my version of eglot is outdated compared to what's bundled in my recently compiled emacs30. I found that I'm using the package `eglot` (built-in) and `consult-eglot` (from github).

I use the use-package integration and for eglot I tried to set `:elpaca nil` to force it to use the emacs-built-in version. I then ran `elpaca-delete` on `consult-eglot` and `eglot` and restarted emacs but it re-installed eglot from github, despite the `:elpaca nil`, which I assume is because `consult-eglot` has it as a dependency.

Can I somehow force consult-eglot to not add the eglot package as a dependency and instead use the built-in one? Would be nice if that was more straight-forwards. In straight.el I think it was fine to just use `:straight (:type built-in)`.

I'll dig into the documentation and probably there's a way to deal with that, like providing a local path to my emacs installation for `:repo` and then a custom `:files` to the package. But I didn't do that in the first place, as I read somehwere to use `:elpaca nil`  for built-in packages and didn't expect the packages might be cloned anyway as dependencies.

I don't think this is a bug, more a discussion item but I wasn't sure where to ask questions. _Feature_ might be appropriate in case you might add features to better handle such cases, or maybe improve the documentation on built-in package mentioning how to work with dependencies for packages that are also available on github/elpa etc.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
The most straightforward way is to add the package to `elpaca-ignored-dependencies` before package orders are processed. I've added `eglot` by default for Emacs 29+.

Try `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs` and see if your eglot version is correct after the change.

**Comment by progfolio** [comment]
> I use the use-package integration and for eglot I tried to set :elpaca nil to force it to use the emacs-built-in version.

`:elpaca nil` means "disable elpaca-use-package-mode for this declaration".
So the declaration is not deferred and will not install the package, but as you saw, it doesn't prevent another package from installing it as a dependency.

I'll have to think more on whether or not to add a recipe keyword akin to straight's `:type`.
I agree it would be more convenient than pushing to `elpaca-ignored-dependencies`, but there may be some cases in which it won't work. e.g. The package is declared after a package which depends on it and `elpaca-wait` is called between the two. So for now, I recommend the simple solution of pushing to `elpaca-ignored-dependencies` before any queues are processed.

**Comment by meliache** [comment]
Awesome, thanks :pray: ! I was looking for exactly something like `elpaca-ignored-dependencies` but hadn't found it earlier. Eventually, maybe you could make it more discoverable by declaring it via `defcustom`?

> I'll have to think more on whether or not to add a recipe keyword akin to straight's :type.

From my side, this keyword is not needed anymore if there's another way to declare ignored dependencies. I'm all in favor of you trying to keep bloat out of elpaca and follow a more KISS-philosophy. I understand while you're not eager to introduce new keywords, as it's kind of an API, once you add it, you cannot remove the keyword anymore without breaking backwards-compatibility, while adding a new keyword is always possible.

**Comment by progfolio** [comment]
> Eventually, maybe you could make it more discoverable by declaring it via defcustom?

Done. Thanks for the suggestion.
