### ISSUE TITLE
[Bug]: elpaca-queue-limit is not used when updating all packages

### ISSUE THREAD

**Issue by dertuxmalwieder** [progfolio/elpaca#67]
### Elpaca Version

```
Elpaca 7ba93cd HEAD -> master, origin/master, origin/HEAD
installer:      0.1
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32)
git --version:  git version 2.39.2.windows.1
```

### Operating System

Windows 11

### Bug Description

`elpaca-update-all` does not (seem to) respect the queue limit, I run into "too many open files" a lot.

**Comment by progfolio** [comment]
Thanks for the report. I've moved the queue limit check into `elpaca--continue-build`. That should do the trick and be a more accurate way of respecting the limit. To test:

1. `M-x elpaca-delete` `elpaca`
2. Edit elpaca recipe to point `:ref` to `"fix/qlimit"`
3. `M-x restart-emacs`
4. Try `elpaca-fetch-all`, `elpaca-update-all`, etc.

Testing is appreciated. Thanks again.

**Comment by dertuxmalwieder** [comment]
LGTM!

**Comment by progfolio** [comment]
Thanks for testing. I've merged the fix into the master branch and removed the "fix/qlimit" branch.
