### ISSUE TITLE
[Bug]: Warning (emacs): Elpaca installer version mismatch

### ISSUE THREAD

**Issue by djgoku** [progfolio/elpaca#70]
### Elpaca Version

M-x elpaca-version:
```
elpaca-process-output: git exited with code 128: fatal: not a git repository (or any of the parent directories): .git
```

git information:
```
master origin/master c44122621630b8ee0f5a1da63540087ec3f31e9d
Author:     Nicholas Vollmer <iarchivedmywholelife@gmail.com>
AuthorDate: Wed Feb 22 11:21:54 2023 -0500
Commit:     Nicholas Vollmer <iarchivedmywholelife@gmail.com>
CommitDate: Wed Feb 22 11:21:54 2023 -0500
```

### Operating System

macOS Ventura 13.2.1

### Bug Description

Updated to the latest elpaca and restarted, and I get the above warning. But then when I check `elpaca-version` I am also getting a weird error.

**Comment by djgoku** [comment]
Fixed https://github.com/progfolio/elpaca/pull/71

**Comment by progfolio** [comment]
> Updated to the latest Elpaca and restarted, and I get the above warning.

That warning is signaled when the published installer has changed.
It's a signal for users to check the installer in their init file.
In this case it was the addition the elpaca-repos-directory variable.

Thanks for the bug report. It looks like I was too hasty when doing the search and replace for the new variable.
Should be fixed on the latest master branch.
`M-x elpaca-update` `elpaca` followed by restarting Emacs should do the trick.
Testing is appreciated.

**Comment by djgoku** [comment]
https://github.com/progfolio/elpaca/commit/cc27305c13eb9baf6192168039805c8d0da3f044

Fixes the `alpaca-version` issue, but not the `Elpaca installer version mismatch`.

**Comment by progfolio** [comment]
In order to get rid of "Elpaca installer version mismatch" warning,  copy the current installer to your init file:

https://github.com/progfolio/elpaca/blob/master/doc/manual.md#installer
