### ISSUE TITLE
[Bug]: New keyword in use-package doesn't work

### ISSUE THREAD

**Issue by krdzo** [progfolio/elpaca#76]
### Elpaca Version

Elpaca 4d7f763 HEAD -> master, origin/master, origin/HEAD
installer:      0.2
emacs-version:  GNU Emacs 29.0.60 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-02-15
git --version:  git version 2.39.2

### Operating System

Fedora 37

### Bug Description

Elpaca doesn't load right when using a use-package keyword that a newly installed package is defining.
An example will better explain this. I have the default elapaca installation script with the `elpaca-use-package` installed like it is in the readme:
```
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)
```

Beneath this I have:
```
(use-package blackout)

(use-package gcmh
  :blackout
  :config
  (gcmh-mode 1))
```
Then when I start Emacs it gives me the `Unrecognized keyword: :blackout` error.\
Everything works correctly if I add `(elpaca-wait)` funciton, like this:
```
(use-package blackout)
(elpaca-wait)

(use-package gcmh
  :blackout
  :config
  (gcmh-mode 1))
````

This is an example with `blackout` but it is the same error with every package that defines new use-package keywords such as `general` and the like. 

P.S. Don't know if this is a problem with elpaca or use-package but taught to report it here first

**Comment by progfolio** [comment]
> Everything works correctly if I add (elpaca-wait) funciton, like this:

That is the intended behavior. I may add an optional value for the `:elpaca` use-package keyword to make this more transparent. e.g.

```emacs-lisp
;;NOT IMPLEMENTED YET
(use-package blackout :elpaca wait)
(use-package example :blackout)
```

**Comment by krdzo** [comment]
Aha ok. I just recently updated to emacs 29 and thought to start using `use-package` and when I tried to port some packages this happened so it seemed like a bug but if it's intended behavior then I will work with that.
