### ISSUE TITLE
[Feature]: eagerly install when use-package declaration is evaluated using eval-last-sexp

### ISSUE THREAD

**Issue by p00f** [progfolio/elpaca#78]
### Feature Description

When I evaluate a use-package declaration using `C-x` `C-e` or `pp-eval-expression` / `pp-eval-defun` (via embark) I always want to immediately install the package. Instead I need to `M-:` `(elpaca-wait)`.

I'm aware of interactive `elpaca-try` but use-package lets me configure the package too.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for the suggestion. I have a local branch where I've been experimenting with this feature. I'll merge it after I test it more.

**Comment by p00f** [comment]
Thanks!

**Comment by cfclrk** [comment]
I'm switching over to elpaca this weekend (and it's awesome!). This really threw for a loop. After restarting Emacs about 50 times today, I finally found this issue :)

I think a README update would be enough, but if this can be automated that would of course even even better!

**Comment by progfolio** [comment]
Should work now on the latest master.
Testing is appreciated.
