### ISSUE TITLE
[Bug]: `*elpaca-log*` buffer can grow extremely large and cause Emacs to crash

### ISSUE THREAD

**Issue by ckruse** [progfolio/elpaca#79]
### Elpaca Version

```
Elpaca 987b1b6 HEAD -> master, origin/master, origin/HEAD
installer:      0.2
emacs-version:  GNU Emacs 29.0.60 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68))
 of 2023-03-09
git --version:  git version 2.39.2
```

### Operating System

macOS

### Bug Description

When calling `elpaca-update-all` the log buffer gets opened and a lot of activity is shown, including git commit messages. Some packages generate *very* large output, in this case the culprit is `erlang`, due to their large git repo.

This can cause Emacs to hang and, finally, crash.

**Comment by progfolio** [comment]
Thanks for the report.
Could you start Emacs from the command line, trigger the issue, and see if there are any messages printed to the command line when Emacs crashes? Did you happen to notice the number of log entries the hang occurred at? It should be displayed in the header-line of the log buffer: `Elpaca Manager (X matches)`.

**Comment by progfolio** [comment]
As a side note: I would chime in on this issue about breaking out the Erlang major mode into its own repository.
There's no reason you should need to download that huge repository just to use it, and I'm surprised a popular mirror hasn't sprung up.

https://github.com/erlang/otp/issues/5100

**Comment by ckruse** [comment]
Yeah, it is really a bit to much to have erlang-mode in this repo, I agree.

Regarding your questions: I tested with my private Linux notebook, and I can reproduce the issue there, too, although it doesn't crash.

Directly before Erlang there are 4032 entries, and everything is fine. After Erlang checkout there are 98460 entries and input really lags. After a while GNOME asks if it should kill the process because it doesn't respond (still 98460 entries). After more time the entries increase to 115048 entries. After about 10 minutes I try to exit Emacs (with C-x C-C) and after quite some time it asks if it really should exit because there is a git log still running:

![Bildschirmfoto vom 2023-03-09 19-57-54](https://user-images.githubusercontent.com/175095/224128470-b321cac1-9ca0-46e9-acae-64c3bd53ab2b.png)

I will try your dev branch next.

**Comment by ckruse** [comment]
Ok, with the fix branch Emacs keeps responsive and doesn't crash.

Oh, forgot it in the previous post: no output in the console.

**Comment by progfolio** [comment]
> entries increase to 115048 entries

More than I expected! 

There are a number of improvements I can make here:
I'll likely add a user option to set a limit for the number or rows to display, which can be overridden via a search tag. (Similar to elpaca-verbosity and the #verbosity search tag)
Though the issue seems to just be with displaying such a long log at this point, I should also add a way to flush and/or rotate the log after a certain length to reduce the chance of it becoming too large in memory for long-running Emacs sessions.
Another idea which may work is to extend tabulated-list-mode so that it can append rows to the table without doing a full reprint.

I'll explore all these options and keep you posted.
Thanks for testing.

**Comment by ckruse** [comment]
Thanks!

**Comment by progfolio** [comment]
> I'll likely add a user option to set a limit for the number or rows to display,

This is now present on the "feat/ui-row-limit" branch.
Still a work in progress, but it adds the `elpaca-ui-row-limit` user option.
When a UI view exceeds that limit, a button is added to the header-line and end of the table which, when clicked will load `elpaca-ui-row-limit` more rows. I've also bound the command to load more rows to "+" by default in elpaca-ui-mode buffers. I'll work on it more tomorrow, but feel free to give it a try and let me know what you think.

**Comment by ckruse** [comment]
Emacs keeps responsive and doesn't crash, even when using macOS. Great work, thank you!

But it is a bit confusing. It does scroll even when there are more than the default 1k lines. What do I see, the last 1k lines?

**Comment by progfolio** [comment]
> Emacs keeps responsive and doesn't crash, even when using macOS. Great work, thank you!

Glad to hear it prevents the crash.

> But it is a bit confusing. It does scroll even when there are more than the default 1k lines. What do I see, the last 1k lines?

What is shown will depend on the current search filter and tabulated-list-mode sort key.
It probably needs more work in the case of the filter used when `elpaca-update-all` is run.
That relies on the `#latest` tag, which may need to be adjusted.

**Comment by progfolio** [comment]
I've merged this feature into the master branch and fixed the table row ordering issue.
Thanks again for the report and feel free to me know if the feature still needs work.

**Comment by ckruse** [comment]
Thank you for your work!
