### ISSUE TITLE
basic example, using leaf with elpaca, to install and configure vertico

### ISSUE THREAD

**Issue by reuleaux** [progfolio/elpaca#8]
I am only just starting out with elpaca, so bear with me. - I am trying to get a very basic configuration running:
but I use _leaf_ (https://github.com/conao3/leaf.el), and _leaf-keywords_ (https://github.com/conao3/leaf-keywords.el),
instead of _use-package_ (and I would think that this should work just as well [?]). After all, leaf is modeled after use-package.

Elpaca works for me, in the sense that I can see it downloading packages: _leaf_, _leaf-keywords_, and _vertico_ -
which I want to configure then with _leaf_. This is my basic setup:

```elisp
;;; init-elpaca.el --- ELPACA INIT DEMO   -*- lexical-binding: t; -*-
;; Bootstrap Elpaca
(declare-function elpaca-generate-autoloads "elpaca")
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(when-let ((elpaca-repo (expand-file-name "repos/elpaca/" elpaca-directory))
           (elpaca-build (expand-file-name "builds/elpaca/" elpaca-directory))
           (elpaca-target (if (file-exists-p elpaca-build) elpaca-build elpaca-repo))
           (elpaca-url  "https://www.github.com/progfolio/elpaca.git")
           ((add-to-list 'load-path elpaca-target))
           ((not (file-exists-p elpaca-repo)))
           (buffer (get-buffer-create "*elpaca-bootstrap*")))
  (condition-case-unless-debug err
      (progn
        (unless (zerop (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo))
          (error "%s" (list (with-current-buffer buffer (buffer-string)))))
        (byte-recompile-directory elpaca-repo 0 'force)
        (require 'elpaca)
        (elpaca-generate-autoloads "elpaca" elpaca-repo)
        (kill-buffer buffer))
    ((error)
     (delete-directory elpaca-directory 'recursive)
     (with-current-buffer buffer
       (goto-char (point-max))
       (insert (format "\n%S" err))
       (display-buffer buffer)))))
(require 'elpaca-autoloads)
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca (elpaca :host github :repo "progfolio/elpaca"))

  
(elpaca leaf (require 'leaf))
(elpaca leaf-keywords (require 'leaf-keywords))

(elpaca vertico (require 'vertico))

  
(leaf vertico
  :init
  (vertico-mode)
  )
```

If I comment out this last bit for a second in the stanza above:
```elisp
;; (leaf vertico
;;  :init
;; (vertico-mode)
;; )
```
then I can see _elpaca_ fetching recipes from Melpa, GNU ELPA, NonGNU ELPA, and installing
leaf, leaf-keywords, vertico, and their dependencies (the Elpaca Log "Package Status Info" is green, after that).

And I would think, that I could use leaf then as above:
```elisp
(leaf vertico
  :init
   (vertico-mode)
  )
```
But apperently not:
```
Warning (initialization): An error occurred while loading ‘/home/rx/.emacs.d/init.el’:

Symbol's function definition is void: leaf

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
What I am doing wrong?

The situation is not much better for me, if I use use-package instead
```elisp
(elpaca use-package (require 'use-package))
(elpaca vertico (require 'vertico))

(use-package
  :init
  (vertico-mode)
  )
```
So I guess, my configuration (weak understanding) is cauing this issue,  rather than a use-package vs leaf thing.
Thanks,
  -A

**Comment by reuleaux** [comment]
To partly answer my own question: I am progressing at least with 

```elisp
(elpaca vertico (leaf ,(elpaca-first leaf))
	:init
	(vertico-mode)
	)
```

having had a look at the elpaca-use-package macro. - However: I would really like vertico to be
leaf-configured only, after _both_: leaf and _leaf-keywords_ are installed .

And trying to find a similar macro:  

```elisp
(defmacro elpaca-leaf (order &rest body)
  "Execute BODY in `leaf' declartion after ORDER is finished.            
If the :disabled keyword is present in body, the package is completely ignored. 
This happens regardless of the value associated with :disabled.                 
The expansion is a string indicating the package has been disabled."
  (declare (indent 1))
  (if (memq :disabled body)
      (format "%S :disabled by elpaca-leaf" order)
    `(elpaca ,order (leaf ,(elpaca--first order) ,@body))))
```
with usage:

```(elpaca-leaf
   :init
    (vertico-mode)
 )

```
does not work out of the box for me.

**Comment by reuleaux** [comment]
I am adding one more remark to my own issue: A useful technique for me in the
past for debugging my emacs init file was to compile it - so that I could see all kinds
possible issues with it on the command line (before actually using it then):

```
emacs --batch -f batch-byte-compile init.el
```

This works only, of course, if I wrap the initial bootstrapping / configuration steps 
in _eval-and-compile_, like so (originally practiced with _straight.el_, and here adapted for _elpaca_):
```elisp
(eval-and-compile

  (setq debug-on-error t)
  
  ;; init-elpaca.el --- ELPACA INIT DEMO   -*- lexical-binding: t; -*-
  ;; Bootstrap Elpaca
  (declare-function elpaca-generate-autoloads "elpaca")
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (when-let ((elpaca-repo (expand-file-name "repos/elpaca/" elpaca-directory))
           (elpaca-build (expand-file-name "builds/elpaca/" elpaca-directory))
           (elpaca-target (if (file-exists-p elpaca-build) elpaca-build elpaca-repo))
           (elpaca-url  "https://www.github.com/progfolio/elpaca.git")
           ((add-to-list 'load-path elpaca-target))
           ((not (file-exists-p elpaca-repo)))
           (buffer (get-buffer-create "*elpaca-bootstrap*")))
    (condition-case-unless-debug err
	(progn
          (unless (zerop (call-process "git" nil buffer t "clone" elpaca-url elpaca-repo))
          (error "%s" (list (with-current-buffer buffer (buffer-string)))))
          (byte-recompile-directory elpaca-repo 0 'force)
          (require 'elpaca)
          (elpaca-generate-autoloads "elpaca" elpaca-repo)
          (kill-buffer buffer))
      ((error)
       (delete-directory elpaca-directory 'recursive)
       (with-current-buffer buffer
	 (goto-char (point-max))
	 (insert (format "\n%S" err))
       (display-buffer buffer)))))
  (require 'elpaca-autoloads)
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca (elpaca :host github :repo "progfolio/elpaca"))

  )
  

(eval-and-compile
  ;; some very basic variables - YMMV
  (add-to-list 'load-path "~rx/el")
  (add-to-list 'load-path "~/cfg/gnus")
  (add-to-list 'custom-theme-load-path "~rx/el/themes")
  ;; (setq load-prefer-newer t)
  )

;; And maybe wrap even some more initial bootstrapping / config bits in (eval-and compile ...)

```
And - a few hours ago at least - this worked for me with _elpaca_ as well:
currently it is now working for me [?] - but this may well be an issue with
my internet connection,   Elpa/Melpa/... connectivity, or what not.
Or I have bootstrapped my emacs config just too often now [?].


Anyway these are must have's for me, before I can seriously consider switching to elpaca (to summarize): 

- find a way to seemlessly use elpaca with _leaf_ / _leaf-keywords_ (or _setpup.el_ - as mentioned in the other issue  https://github.com/progfolio/elpaca/issues/7)

- being able to debug my config by compiling it on the command line, before actually using it.

**Comment by progfolio** [comment]
I appreciate the report. I'm going to split this up into two separate issues and combine one of them with another, existing issue.
Discussion for leaf can take place in #7.
Byte compiling is a separate issue and I've opened #9 to discuss that.
