### ISSUE TITLE
[Feature]: explain why elpaca is great and how it compares to the other Emacs package managers

### ISSUE THREAD

**Issue by tzz** [progfolio/elpaca#82]
### Feature Description

I'm curious about elpaca but based on the README and the manual I couldn't figure out quickly how it's different from all the other Emacs package managers.

I checked the README, the manual, and open+closed issues.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
I've added some of the information above to the top section of the README. Let me know if you think it can be improved in any way. Thanks again for the report.
