### ISSUE TITLE
[Feature]: make `elpaca-update-all` user interface similiar to the `lazy.nvim` interface

### ISSUE THREAD

**Issue by ckruse** [progfolio/elpaca#83]
### Feature Description

Currently the `update-all` interface is a big list with loads of entries, and it is somewhat hard to guess what actually happened, and even to know that updating has finished. Currently I do C-x C-c and look if there is still a running process.

An interface like the update interface of [lazy.nvim](https://github.com/folke/lazy.nvim) would be much easier to understand.

![Bildschirm­foto 2023-03-14 um 09 06 54](https://user-images.githubusercontent.com/175095/224935875-33c60201-3209-40e5-9b1d-59fe67073e21.png)

Is it possible to get a view like this?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Thanks for bringing this to my attention.
A few improvements can be made:

> Currently the update-all interface is a big list with loads of entries...
> Is it possible to get a view like this?

It should be possible to write a search tag which offers a similar, stripped down update log. e.g.

```emacs-lisp
(defun +short-log (entries)
  (cl-loop with (current compact)
           for entry in (reverse entries)
           for cols = (cadr entry)
           for info = (aref cols 2)
           do (when (and (equal (aref cols 1) "update-log")
                         (not (string-match-p "\\(?:^\\(?:\\(?:Author\\|Merge\\):\\)\\)" info)))
                (cond
                 ((string-prefix-p "commit " info)
                  (let ((start (length "commit ")))
                    (setf (alist-get 'commit current) (substring info start (+ start 6)))))
                 ((string-prefix-p "Date: " info)
                  (let ((ws (split-string (string-trim info) " ")))
                    (setf ws (cdr ws) ;; pop "Date:"
                          (alist-get 'date current)
                          (format "(%s %s %s)" (nth 3 ws) (nth 4 ws) (nth 6 ws)))))
                 (current ;; on first message line
                  (let ((copy (copy-tree entry))
                        (info (thread-last
                                (string-trim info)
                                (replace-regexp-in-string "^\* " "")
                                (replace-regexp-in-string
                                 "\\([([]?#[[:digit:]]+[])]?\\)"
                                 (lambda (s) (propertize s 'face 'elpaca-busy)))
                                (replace-regexp-in-string
                                 "^.*: " (lambda (s) (propertize s 'face 'elpaca-finished))))))
                    (setf (aref (cadr copy) 2)
                          (string-join
                           (list (propertize (alist-get 'commit current)
                                             'face 'elpaca-busy)
                                 info
                                 (propertize (alist-get 'date current)
                                             'face '((:foreground "grey"))))
                           " "))
                    (push copy compact)
                    (setq current nil)))))
           finally return compact))
```

If you evaluate that function and then search for "#latest #(+short-log)" in the log buffer after updating or fetching it should filter the view to something like the following:

![elpaca-short-log-demo](https://user-images.githubusercontent.com/44036031/225080718-db425f1b-f76a-4725-b891-f3f354fc6f04.png)

Does that look better to you?

That brings me to the second improvement:
We need a way for users to set what filter is used by default for commands which log. I'll have to think about this, but my first hunch is to have a user option which is an alist mapping such commands to defaults filters.

Third, I should be able to add an overall progress indicator to the header-line for UI views. I had this feature in older versions of Elpaca and can add it back.

**Comment by ckruse** [comment]
Ah, much better! Really nice, thank you!

How does that work with the new log truncation feature, will it search only in the limited buffer or in the complete log?

**Comment by progfolio** [comment]
> Ah, much better! Really nice, thank you!

You're welcome. I'll work on it some more as well as the other features I mentioned.

> How does that work with the new log truncation feature, will it search only in the limited buffer or in the complete log?

Any search rows beyond `elpaca-ui-row-limit` will be hidden. For example, I set the row limit to one and I have 5 updates here:

![image](https://user-images.githubusercontent.com/44036031/225109903-429a1653-5baf-42c2-b13f-a1b1a272e4ae.png)

**Comment by ckruse** [comment]
> I'll work on it some more as well as the other features I mentioned.

Thank you for working on the other features :-)

> Any search rows beyond elpaca-ui-row-limit will be hidden. For example, I set the row limit to one and I have 5 updates here:

Yes, but for example when I use the default view of `elpaca-update-all` and there are, e.g., 3k more entries. Will the modified search also search in the truncated lines or only on the 5 visible lines?

Based on your answer I guess that it will search in the complete log.

**Comment by progfolio** [comment]
Yes, the complete logs of the events returned by the filter will be searched. The tags are processed in order, so in the case of "#latest #(+short-log)":

- #latest will return only the tail of the log since the last bulk operation.
- #(+short-log) will operate on those results and compact the update-log status entries. If the number of entries at that point is more than elpaca-ui-row-limit, those entries beyond the limit will be hidden.

Does that makes sense?

**Comment by bdarcus** [comment]
I'm also a big fan of the lazy.vim update UI. Some nice improvements here @progfolio!

In particular:

1. the fontification to highlight different pieces of info (do have a different face for breaking changes?)
2. being able to click on the commit and see it directly (!)

One thing that still confuses me is the "update-log" entries in the "status" column.

![image](https://user-images.githubusercontent.com/1134/226437771-ed324d2e-ac1f-437a-be81-259d6e1b898d.png)

**Comment by progfolio** [comment]
> One thing that still confuses me is the "update-log" entries in the "status" column.

That column shows the status of the order at the time of the log event. It's useful for debugging and filtering logs.
e.g. searching for `| byte-comp` would filter the log to show events which were logged when the order had a status of  "byte-compilation".

**Comment by bdarcus** [comment]
> That column shows the status of the order at the time of the log event.

But what does the value "update-log" itself mean? All of my entries have it, but not clear to me what to make of it.

**Comment by progfolio** [comment]
@ckruse 
> Is it possible to hide the package name on consecutive lines? This would it make much easier to grasp the change of the package.

Yes, it's definitely possible. However, bear in mind that the entries can be sorted by any column. This may always work out in the case of  the "#update-log" search filter, but not in other cases.

@bdarcus 
> But what does the value "update-log" itself mean? 

You can think of it as a way of categorizing log events to make them easier to search for later.

>  All of my entries have it, but not clear to me what to make of it.

They all have it when the search filter is "#update-log". If the search query is altered, they may not.

**Comment by progfolio** [comment]
I've merged a progress bar + the update-log changes to master.
Testing is appreciated.

Note that `elpaca-fetch-all` will use the `#update-log` search query.
`elpaca-update-all` will still show much more (byte compilation output, etc).

I've still yet to add a way to override the default queries for commands, but I will soon.

**Comment by progfolio** [comment]
Thanks for testing.

> The 47 represents packages installed successfully (not needing update, and whose updates didn't fail)?
> And those three other colored circles?
> Yellow waiting/paused, red failed, and the other in-progress?

Yes, you've go the right idea.
Each of those numbers is a count of order states across all queues.
From left to right: "finished", "blocked", "failed", "other".
They should have tool tips if you mouse over them which describe them, too.

> Also, am I imagining things or does this show some subtle vertical alignment issues? Or maybe the red one just displays smaller than the others?

The faces used (elpaca-finished, elpaca-blocked, elpaca-failed) only specify `(:weight bold :foreground "#XXXXXX")`.
They should display similarly. I do see what you mean in the screenshot, but I think that might just be an optical illusion. I imported it into GIMP and ran a guide along the base of them:

![image](https://user-images.githubusercontent.com/44036031/227659820-810670ff-0fea-4c53-a0e1-25aa5954ae4c.png)

I may embolden the "other" just to make it more consistent with the others.

**Comment by ckruse** [comment]
Much better, thanks a lot!

**Comment by progfolio** [comment]
> I may embolden the "other" just to make it more consistent with the others.

I've pushed a change which does this.
The tool tip text will actually show the orders for each category in the progress bar, too.


![order-status-echo](https://user-images.githubusercontent.com/44036031/227738771-6fb55ab3-7a70-4c76-b58e-f2f180c83d97.png)

This should be slightly more efficient, too, since the tool-tip string is only generated on demand.

**Comment by bdarcus** [comment]
Hmm ... I don't get any tooltips in the UI.

**Comment by progfolio** [comment]
> Hmm ... I don't get any tooltips in the UI.

M-x elpaca-version?

**Comment by bdarcus** [comment]
Right; sorry.

```
Elpaca 43d6bab HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-03-12
git --version:  git version 2.39.2
```

**Comment by progfolio** [comment]
Interesting.  Have you restarted Emacs since updating? Do you see tooltips when hovering over UI elements outside of Elpaca (e.g. the mode-line)?

**Comment by bdarcus** [comment]
Yes to both questions.

> I would also test in a clean environment by evaluating (elpaca-test).

Right; it works there, so I guess there's something in the config I need to look into!
