### ISSUE TITLE
[Bug]: Installer does not build autoloads if repo already exists, like in git submodule setup

### ISSUE THREAD

**Issue by darkfeline** [progfolio/elpaca#84]
### Elpaca Version

installer:      0.2

### Operating System

Arch Linux

### Bug Description

The provided installer/bootstrap does not work in a submodule-managed setup.

e.g., I git clone my emacs config along with elpaca submodule and then try to start Emacs.

The installer does not build autoloads if the repo already exists, and the freshly checked out repo is missing autoloads

**Comment by progfolio** [comment]
You'll have to be more specific.
What do you have checked into the submodule?

**Comment by progfolio** [comment]
I think I see what you mean.
I'm trying to keep the installer as short as possible, but I'll take a look to see if I can think of a way to make it work in cases where the autoloads are absent (This could happen if a user deletes them manually as well).

**Comment by progfolio** [comment]
I've updated installer on the "fix/autoloads" branch so that it should work with your submodule setup. Testing is appreciated.

**Comment by darkfeline** [comment]
Works for me.  FWIW I looked over the new installers and it also looks good.  Thanks for quick turnaround

**Comment by progfolio** [comment]
Merged to master branch.
Thanks again for the report and testing.
