### ISSUE TITLE
[Support]: emacsql-sqlite dependency issue

### ISSUE THREAD

**Issue by bdarcus** [progfolio/elpaca#85]
### Elpaca Version

Using version 0.3

### Operating System

Fedora Linux.

### Description

Follow-up from Discord.

I still don't know where the problem is, and so whether this is an elpaca bug, and apologies if this is not elpaca-related.

But I keep getting this error when trying to load `org-roam`:

```
Error (use-package): citar/:config: Cannot open load file: No such file or directory, emacsql-sqlite
```

Here's the config I'm using, and the key packages at play are:

- `citar` (in [init-biblio.el](https://gitlab.com/bdarcus/emacs-elp/-/blob/main/lisp/init-biblio.el))
- `citar-org-roam` (in [init-notes.el](https://gitlab.com/bdarcus/emacs-elp/-/blob/main/lisp/init-biblio.el))
- `org-roam`

I was trying to sort out a [load order problem](https://github.com/emacs-citar/citar-org-roam/issues/26) among them, and think in doing so, ran into this problem.

But since I'm not directly installing or configuring `emacsql`, am wondering if it's something or other with `elpaca`?

**Comment by progfolio** [comment]
Please include the output of `M-x elpaca-version` and the use-package declarations for the packages.

**Comment by bdarcus** [comment]
How do I capture that output?

**Comment by progfolio** [comment]
You should be able to copy it from the \*Messages* buffer after executing the command.

**Comment by progfolio** [comment]
I've cloned the full configuration you've linked into a temporary environment and everything installed cleanly.
Is there something else that needs to be done to trigger the error you're seeing?
It's also difficult for me to reproduce anything on my end because the set up assumes local files exist, which I do not have (e.g. ~/org/*.bib).

> Error (use-package): citar/:config: Cannot open load file: No such file or directory, emacsql-sqlite

Indicates that something is trying to load emacsql-sqlite during the `:config` stanza of the citar's use-package declaration.
I haven't seen anything to indicate this is a bug with Elpaca yet.
My advice would be to start simpler. Use a single file for the init and add each use-package declaration one at a time. That will help narrow down when the problem occurs. The elpaca-test macro can be useful for this as well. e.g.

```emacs-lisp
(elpaca-test
  :dir "elpaca.test"
  :init
  ;;bootstrap is already included, just add init forms...
  (elpaca elpaca-use-package (elpaca-use-package-mode) (setq elpaca-use-package-by-default t))
  (elpaca-wait)
  ;;etc
  )
  ```

**Comment by bdarcus** [comment]
Doh!

### Version

```
Elpaca 2bbd509 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-03-12
git --version:  git version 2.39.2
```

### Config

This generates the error, upon opening Emacs:

```elisp
(use-package org-roam
  :elpaca (org-roam :host github :repo "org-roam/org-roam")
  :init (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/org/roam")
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :target
      (file+head
       "%<%Y%m%d%H%M%S>-${slug}.org"
       "#+title: ${title}\n")
      :unnarrowed t)
     ("n" "literature note" plain
      "%?"
      :target
      (file+head
       "%(expand-file-name \"biblio\" org-roam-directory)/${citekey}.org"
       "#+title: ${citekey}.${author} :: ${title}.\n#+created: %U\n#+last_modified: %U\n\n")
      :unnarrowed t))))

(use-package citar-org-roam
  :after (citar org-roam)
  :config (citar-org-roam-mode)
  :custom
  (citar-org-roam-capture-template-key "n")
  (citar-org-roam-subdir "biblio"))

(use-package citar
  :custom
  (citar-bibliography bd/bibliography)
  (citar-notes-paths bd/notes)
  (citar-library-paths bd/library-files)
  (org-cite-global-bibliography bd/bibliography)
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'csl-activate)
  :hook
  (org-mode . citar-capf-setup)
  (markdown-mode . citar-capf-setup)
  (LaTeX-mode . citar-capf-setup))
```

**Comment by bdarcus** [comment]
> I've cloned the full configuration you've linked into a temporary environment and everything installed cleanly. Is there something else that needs to be done to trigger the error you're seeing? It's also difficult for me to reproduce anything on my end because the set up assumes local files exist, which I do not have (e.g. ~/org/*.bib).

I was trying to figure out how to simplify it in posting the above reply, but not having much luck. Sorry about that.

> > Error (use-package): citar/:config: Cannot open load file: No such file or directory, emacsql-sqlite
> 
> That error message indicates that something is trying to load emacsql-sqlite during the `:config` stanza of the citar's use-package declaration. 

In reviewing the details, I did modify it to the above, which now generates a different error, specific to `org-roam` and `emacsql-sqlite`, again upon opening Emacs:

```
⛔ Error (use-package): org-roam/:catch: Cannot open load file: No such file or directory, emacsql-sqlite
```

> I haven't seen anything to indicate this is a bug with Elpaca yet. My advice would be to start simpler. Use a single file for the init and add each use-package declaration one at a time. That will help narrow down when the problem occurs.

OK.

> The elpaca-test macro can be useful for this as well...

I've seen you mention the test macro elsewhere, I think, but I wasn't clear how to use it. But looking at the docstrings now, things are more clear!

Will give it a shot.

I have, FWIW, been using the new `--init-directory` option in Emacs 29 to test this.

**Comment by progfolio** [comment]
Try evaluating the following in your \*scratch* buffer:

```emacs-lisp
(elpaca-test
  :dir "elpaca.85"
  :early-init (setq inhibit-splash-screen t
                    native-comp-jit-compilation nil)
  (load-theme 'modus-vivendi t)
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package org-roam
    :elpaca (org-roam :host github :repo "org-roam/org-roam")
    :init (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory "~/org/roam")
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :target
        (file+head
         "%<%Y%m%d%H%M%S>-${slug}.org"
         "#+title: ${title}\n")
        :unnarrowed t)
       ("n" "literature note" plain
        "%?"
        :target
        (file+head
         "%(expand-file-name \"biblio\" org-roam-directory)/${citekey}.org"
         "#+title: ${citekey}.${author} :: ${title}.\n#+created: %U\n#+last_modified: %U\n\n")
        :unnarrowed t))))

  (use-package citar-org-roam
    :after (citar org-roam)
    :config (citar-org-roam-mode)
    :custom
    (citar-org-roam-capture-template-key "n")
    (citar-org-roam-subdir "biblio"))

  (use-package citar
    :custom
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'csl-activate)
    :hook
    (org-mode . citar-capf-setup)
    (markdown-mode . citar-capf-setup)
    (LaTeX-mode . citar-capf-setup)))
```

It will install everything in a temporary environment and launch a new Emacs session. On my end, everything installs cleanly and I get no errors. However, I'm on Emacs 30.

**Comment by bdarcus** [comment]
> On my end, everything installs cleanly and I get no errors. 

Same here. 

> However, I'm on Emacs 30.

Maybe I'll update my Emacs build.

Anyway, below is the final minimal version I needed, with the paths set, and vertico added.

No errors, and `citar-org-roam-mode` is correctly set. 

I just needed to run `org-roam-db-sync` for the note indicators to correctly show up `citar`.

![image](https://user-images.githubusercontent.com/1134/226126082-73a5f97c-a06a-4dae-acdd-dd127de0732a.png)

I'll close this, then, and see if I can rebuild back up a simple single-file version. 

Thanks much for the help!

```elisp
(elpaca-test
  :dir "elpaca.85"
  :early-init (setq inhibit-splash-screen t
                    native-comp-jit-compilation nil)
  (load-theme 'modus-vivendi t)
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package vertico
    :init
    (vertico-mode))

  (use-package org-roam
    :elpaca (org-roam :host github :repo "org-roam/org-roam")
    :init (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory "~/org/roam")
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :target
        (file+head
         "%<%Y%m%d%H%M%S>-${slug}.org"
         "#+title: ${title}\n")
        :unnarrowed t)
       ("n" "literature note" plain
        "%?"
        :target
        (file+head
         "%(expand-file-name \"biblio\" org-roam-directory)/${citekey}.org"
         "#+title: ${citekey}.${author} :: ${title}.\n#+created: %U\n#+last_modified: %U\n\n")
        :unnarrowed t))))

  (use-package citar-org-roam
    :after (citar org-roam)
    :config (citar-org-roam-mode)
    :custom
    (citar-org-roam-capture-template-key "n")
    (citar-org-roam-subdir "biblio"))

  (use-package citar
    :custom
    (citar-bibliography "~/org/bib/academic.bib")
    (citar-notes-paths '("~/org/roam/biblio"))
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'csl-activate)
    :hook
    (org-mode . citar-capf-setup)
    (markdown-mode . citar-capf-setup)
    (LaTeX-mode . citar-capf-setup)))
```

**Comment by bdarcus** [comment]
Update: I ended up deleting the local elpaca directory and reinstalling everything. That solved it, for whatever reason.
