### ISSUE TITLE
[Bug]: `elpaca-update-all` doesn't update

### ISSUE THREAD

**Issue by ckruse** [progfolio/elpaca#86]
### Elpaca Version

~~~
Elpaca ae6115e HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 29.0.60 (build 19, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-03-19
git --version:  git version 2.40.0
Mark set
~~~

### Operating System

Linux

### Description

When running `elpaca-update-all` nothing happens, the log is still empty. Even when I change the search to `#latest`, there are no new entries.

But when I update packages manually with `elpaca-update` updates get applied, and when I run a `elpaca-fetch-all` there are changes fetched.

Am I missing something?

**Comment by progfolio** [comment]
Possibly an unintended consequence of https://github.com/progfolio/elpaca/commit/2bbd50993b107ee3af8c22a2b77990a19b6512d8

I plan on rewriting both `elpaca-fetch-all` and `elpaca-rebuild-all` later tonight, which will obviate the need for that workaround. I'll let you know when that is done and hopefully it will resolve the issue.

**Comment by ckruse** [comment]
Cool! Thank you very much!

**Comment by progfolio** [comment]
Sorry for the delay.
I've reworked those commands (as well as some other issues). 
Testing is appreciated.

**Comment by p00f** [comment]
It works now, thanks

**Comment by progfolio** [comment]
Thank you for testing.

**Comment by ckruse** [comment]
Works again, thanks!
