### ISSUE TITLE
[Feature]: load-path support for use-package

### ISSUE THREAD

**Issue by actondev** [progfolio/elpaca#88]
### Feature Description

To load & customize my own local elisp packges/snippets I've been using `(use-package foo :load-path "elisp/foo")`.
This seems to not work. I'm also seeing in `elpaca-use-package-ignored-keywords` that the `load-path` is ignored.
So far I've been using `:elpaca nil` in any package I had `:load-path`. Is there a better way I'm not aware of?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
So long as the local packages are stored in a git repository, you should be able to use the local file path for `:repo`. e.g.

```emacs-lisp
(elpaca (local-lisp :repo "~/local-lisp/"))

;; Or, with elpaca-use-package-mode:

(use-package local-lisp :elpaca (:repo "~/repos/local-lisp/"))
```

Note, that method will clone the repo locally into `$ELPACA-DIR/$ELPACA-REPOS-DIR`. 

If the elisp is not managed in a git repository, you're better off using `:elpaca nil` and setting things up as you would normally with use-package.

Does that help?

**Comment by actondev** [comment]
Haven't yet tried any `:repo`, but as you said if this method `clones` the local repo, so I assume if I modify changes to the "original" local repo, I need to "update" the package for the changes to take effect.
I will definitely try it though for local packages that I host in git as well, something for which before I had to use `straight` or `el-get`. Being able to manage everything with one package manager is awesome!

Back to the topic, I'm seeing that the `elpaca/builds/<package>/*.el` files are symlinks to the `repo` dir. Would it be a viable solution to have `:load-path` make a symlink of the `:load-path` folder to `builds/`? Or are there other limitations?

In any case, I'm asking for this because if `:load-path` would work with elpaca, that would mean that no changes are needed at all for converting from use-package (apart from bootstrapping elpaca ofcourse), which is really great!

**Comment by progfolio** [comment]
> Haven't yet tried any :repo, but as you said if this method clones the local repo, so I assume if I modify changes to the "original" local repo, I need to "update" the package for the changes to take effect.

That's one way to do it.
Another option would be to work on the version stored under `$ELPACA-DIR/$ELPACA-REPOS/`, commit your changes, and push them upstream.

>  I'm seeing that the elpaca/builds/<package>/*.el files are symlinks to the repo dir. Would it be a viable solution to have :load-path make a symlink of the :load-path folder to builds/? Or are there other limitations?

It would complicate implementing #72.
Consider, too, that allowing Elpaca to manage the package give you the benefit of easily rebuilding the package after changes are made.

>  I'm asking for this because if :load-path would work with elpaca, that would mean that no changes are needed at all for converting from use-package

Assuming the configuration you're using is hosted here:

https://github.com/actondev/.emacs.d

It looks like use-package's `:load-path` keyword is used sparingly:

https://github.com/actondev/.emacs.d/search?q=%3Aload-path

Adding `:elpaca nil` in those cases shouldn't require too much work.
(In the case of the declarations in temp.org, I'm not sure `:load-path` is necessary considering the "elisp" dir is added to load-path in config.org.)

For now, I'd recommend sticking with that simple approach.
I've noted this for further consideration, though.

Thanks.

**Comment by actondev** [comment]
Thanks for taking the time and looking into it.
Indeed using `:elpaca nil` is just fine for now :)
