### ISSUE TITLE
[Feature]: Add a normalize/fix remotes command

### ISSUE THREAD

**Issue by darkfeline** [progfolio/elpaca#90]
### Feature Description

Requesting a feature similar to normalize from `straight.el`, specifically for fixing the remotes for packages' Git repos.  Specifically, a command that adds/modifies remotes for each package repo to match what is declared in the recipe.

My use case:

I use git submodules to both initially fetch packages and lock packages at specific commits for my Emacs config.  Unfortunately this means that the remotes for these repos aren't set up properly, particularly when using a forked elpaca recipe.

e.g., 

forked elpaca recipe: fork=my remote, origin=upstream
git submodule: origin=my remote

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Do you happen to have your config uploaded somewhere so I can look it over?

**Comment by darkfeline** [comment]
No, my config/dotfiles are private.  It is not very complicated though.  Basically, I have `.config/emacs/init.el` committed, and `.config/emacs/elpaca/repos/*` each committed as submodules.  You can probably replicate it by adding  `.config/emacs/elpaca/repos/*` as submodules in your own config.

**Comment by darkfeline** [comment]
FWIW I've implemented this personally using this

```elisp
(defun mir-elpaca-fix-remotes ()
  "Fix elpaca package repo remotes."
  (interactive)
  (dolist (e (elpaca--queued))
    (when-let ((e (cdr e))
               (default-directory (elpaca<-repo-dir e))
               (recipe (elpaca<-recipe e))
               (repo (plist-get recipe :repo))
               (URI (elpaca--repo-uri recipe))
               ;; Skip repos without extra remotes
               (remotes (plist-get recipe :remotes)))
      (call-process "git" nil "*mir-elpaca-fix-remotes*" t
                    "remote-add-force" elpaca-default-remote-name URI)
      (dolist (spec remotes)
        (when-let ((remote (car spec))
                   (props (cdr spec))
                   (inherited (elpaca-merge-plists recipe props))
                   (URI (elpaca--repo-uri inherited)))
          (call-process "git" nil "*mir-elpaca-fix-remotes*" t
                        "remote-add-force" remote URI))))))
```

```bash
# git-remote-add-force
#!/bin/sh
# Implements git remote add, but updates if same name remote exists.
set -eu
name=$1
url=$2
if git remote get-url "${name}" >/dev/null; then
    git remote set-url "${name}" "${url}"
    git fetch "${name}"
else
    git remote add "${name}" "${url}"
fi
```

Some more context on git submodules: the core feature of git submodules is that you can "pin" the commit to be checked out for child git repos in each commit in the parent repo.  So it functions much as you'd want lockfiles to for elpaca/straight assuming you keep your Emacs config in some sort of dotfiles git repo.

However, the ability to setup the child repo remotes such that git can find any referenced commits is a bit wonkier IMO.  Basically, you can specify a single remote which will be used as the `origin` when git sets up submodules.  It is assumed that the specified remote contains the superset of all child repo commits that it might need for any commits in the parent repo history.  For forked elpaca repos that would mean specifying the fork repo (which contains both upstream commits and fork-local commits) which would then become `origin`, whereas elpaca would have upstream be `origin` and the fork be `fork`.

**Comment by progfolio** [comment]
> FWIW I've implemented this personally using this
>
> ```elisp
> (defun mir-elpaca-fix-remotes ()
>   "Fix elpaca package repo remotes."
>   (interactive)
>   (dolist (e (elpaca--queued))
>     (when-let ((e (cdr e))
>                (default-directory (elpaca<-repo-dir e))
>                (recipe (elpaca<-recipe e))
>                (repo (plist-get recipe :repo))
>                (URI (elpaca--repo-uri recipe))
>                ;; Skip repos without extra remotes
>                (remotes (plist-get recipe :remotes)))
>       (call-process "git" nil "*mir-elpaca-fix-remotes*" t
>                     "remote-add-force" elpaca-default-remote-name URI)
>       (dolist (spec remotes)
>         (when-let ((remote (car spec))
>                    (props (cdr spec))
>                    (inherited (elpaca-merge-plists recipe props))
>                    (URI (elpaca--repo-uri inherited)))
>           (call-process "git" nil "*mir-elpaca-fix-remotes*" t
>                         "remote-add-force" remote URI))))))
> ```

Cool. This could be refactored to take advantage of the queue system and work asynchronously, via `elpaca--make-process`. If you're interested in that, take a look at how the functions in `elpaca-build-steps` are implemented.

> ```bash
> # git-remote-add-force
> #!/bin/sh
> # Implements git remote add, but updates if same name remote exists.
> set -eu
> name=$1
> url=$2
> if git remote get-url "${name}" >/dev/null; then
>     git remote set-url "${name}" "${url}"
>     git fetch "${name}"
> else
>     git remote add "${name}" "${url}"
> fi
> ```

An elisp equivalent (untested) should be:


``` emacs-lisp
(defun +elpaca-remote-add-force (name url)
  "Update remote with NAME if it exists. Otherwise add it with URL."
  (elpaca-with-process (elpaca-process-call "git" "remote" "get-url" name)
    (if (not success)
        (elpaca-process-call "git" "remote" "add" name url)
      (elpaca-process-call "git" "remote" "set-url" name url)
      (elpaca-process-call "git" "fetch" name))))
```

> Some more context on git submodules: the core feature of git submodules is that
> you can "pin" the commit to be checked out for child git repos in each commit in
> the parent repo. So it functions much as you'd want lockfiles to for
> elpaca/straight assuming you keep your Emacs config in some sort of dotfiles git
> repo.

> However, the ability to setup the child repo remotes such that git can find any
> referenced commits is a bit wonkier IMO. Basically, you can specify a single
> remote which will be used as the `origin` when git sets up submodules. It is
> assumed that the specified remote contains the superset of all child repo
> commits that it might need for any commits in the parent repo history. For
> forked elpaca repos that would mean specifying the fork repo (which contains
> both upstream commits and fork-local commits) which would then become `origin`,
> whereas elpaca would have upstream be `origin` and the fork be `fork`.

Submodules are a great fit on paper. I've experimented with them for Elpaca's backup system. However, they add a little more overhead when trying to work with the repository (as evidenced by this thread) which makes them less suitable for people who aren't as familiar with git. Personally, I'm not a fan of using them for this reason.
 
Feel free to add a page on the [wiki](https://github.com/progfolio/elpaca/wiki/_new) describing your submodule-driven setup if you like.

I'll consider this closed since you've found a solution and it's unlikely I'll use submodules as the general backup strategy for Elpaca.
