### ISSUE TITLE
[Bug]: No recipe: (json-end-of-file "'}' expected near end of file" "<string>"

### ISSUE THREAD

**Issue by dragove** [progfolio/elpaca#92]
### Elpaca Version

Elpaca 8a2d571 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-03
git --version:  git version 2.40.0

### Operating System

Arch Liux

### Description

I just copy the installer code from this repo, and start my emacs, my emacs freezes for several minutes and after some wating, this message showed up: 

| package |   status |   Info | Time |
|--|--|--|--|
| elpaca   |   failed | No recipe: (json-end-of-file "'}' expected near end of file" "<string>"2 245830 245448 |  264.67213 |

**Comment by progfolio** [comment]
Thanks for taking the time to fill out the report.
Unfortunately, I'm unable to reproduce the bug on my end with Emacs 28.2.
Please try the following:

1. delete the ~/.emacs.d/elpaca/ directory if present.
2. launch emacs from the command line with `emacs --debug-init`
3. If execution pauses as the debugger, copy the entire output of the stacktrace buffer here.

**Comment by dragove** [comment]
still error without any log. Could this be a network error?

![image](https://user-images.githubusercontent.com/24190403/229336704-38a911d3-4ec0-4ba3-945d-bceaa32ab9a2.png)

**Comment by dragove** [comment]
Sorry, I've found the reason. My network is not able to connect to elpa and cause the problem. I changed my proxy setting to connect elpa via proxy. This problem disappers.

**Comment by progfolio** [comment]
Not a problem. Glad you got it figured out.
