### ISSUE TITLE
[Support]: bbdb fails to install

### ISSUE THREAD

**Issue by benthamite** [progfolio/elpaca#95]
### Elpaca Version

Elpaca 8a2d571 HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68))
 of 2023-03-05
git --version:  git version 2.40.0

### Operating System

macOS 13.2.1 (22D68)

### Description

When [bbdb](https://elpa.gnu.org/packages/bbdb.html) is installed with `elpaca`, `M-x bbdb` returns `load-with-code-conversion: Cannot open load file: No such file or directory, bbdb-site`. However, the package installs fine with `straight` or with `package-install`.

Looking at my `builds` directory, I see that there is no `bbdb-site.el` file, but rather `bbdb-site.el.in`. I don't know what the `.in` extension is. When the package is instead installed via `package-install`, `bbdb-site.el` exists in the corresponding directory.

Relevant parts of my config:

``` emacs-lisp
(defvar elpaca-installer-version 0.3)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (kill-buffer buffer)
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(use-package bbdb
  :demand t)
```

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a report.
It looks like installing bbdb from source requires running Make.
The `.in` file extension is an input file which is likely used by a Make script to generate an output file.
You'll want to follow the instructions at:

https://elpa.gnu.org/packages/bbdb.html

Under the section which starts:

>>> To compile and install BBDB from Savannah with `make'
(see also the generic file INSTALL):

The steps can be run via the `:pre-build` recipe keyword.
e.g.
`:pre-build (("configure") ("make")) ;;etc`
You may also have to adjust the `:files` recipe keyword to link the desired files over.

**Comment by benthamite** [comment]
Thank you.
