### ISSUE TITLE
[Support]: ⛔ Warning (emacs): Duplicate item declaration: magit

### ISSUE THREAD

**Issue by aaronjensen** [progfolio/elpaca#97]
### Elpaca Version

```
Elpaca ec7b71b HEAD -> master, origin/master, origin/HEAD
installer:      0.3
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (Build 22E261))
 of 2023-04-09
git --version:  git version 2.39.2
```

### Operating System

macOS

### Description

I'm trying out switching from straight.el to elpaca. I seem to have most things working, but I have a couple of warnings:

```
⛔ Warning (emacs): Duplicate item declaration: magit
⛔ Warning (emacs): Duplicate item declaration: git-commit
```

I'm gathering that this has to do with me declaring a package that depends on magit prior to declaring magit itself. This is rather difficult for me to track down, so maybe I'm missing something. It's also a seemingly unfortunate difference between straight and elpaca because now my configuration is much more sensitive to ordering.

Is there an easier way for me to track this down? Should the item duplicate detection not warn if the recipe is identical? Or is there something else I'm missing? Thanks!

**Comment by progfolio** [comment]
Yes. When you force the queue to be synchronous, there's no way Elpaca can tell what comes after the call.
Minimizing the usage of elpaca-wait is recommended.

**Comment by progfolio** [comment]
I've reworded the warning to better reflect this case.

**Comment by aaronjensen** [comment]
Thanks, though I'm not sure that warning would have helped me anymore. I was able to guess what the problem was, but not really able to easily diagnose it without the dependency chain (which package that I put an order in for ended up needing magit?)

I believe what straight does in this situation is it only fails if the recipe differs from the previously specified recipe. Is that something that elpaca can do as well?

As an aside, wow. Elpaca is night and day faster than straight and moving to it wasn't very hard at all. It took me less than an hour and I've got almost 150 packages. Aside from some reordering and the issues I opened, it just worked. Nice work, and thank you.

**Comment by progfolio** [comment]
> Thanks, though I'm not sure that warning would have helped me anymore. I was able to guess what the problem was, but not really able to easily diagnose it without the dependency chain (which package that I put an order in for ended up needing magit?)

For this you can `M-x elpaca-info` `magit` which will show the packages dependencies and dependents.
There's also the `elpaca-dependencies` and `elpaca-dependents` commands. I'll think on how I can convey that better in the warning.

> I believe what straight does in this situation is it only fails if the recipe differs from the previously specified recipe. Is that something that elpaca can do as well?

I believe straight.el actually registers the new recipe, but does not use it. That's part of the reason why so many people run into the bug of "I asked for package X, but it was installed as a dependency before I asked for it" (especially with something like Org, which many packages depend on). Elpaca's queue system largely solves that problem, but it's not possible to synchronously block (via elpaca-wait) and also see the future from the elisp interpreter's perspective. 

Eventually, I'd like to write a macro which reduces the nesting necessary to install everything without elpaca-wait, but it's tricky and I'm not sure if it's worth it (even one level of indentation seems to be too much for may people when it comes to their init file). The warning should not crop up after-init-time, e.g. when re-evaluating a use-package declaration. Let me know if it does, and I can fix that.

> As an aside, wow. Elpaca is night and day faster than straight and moving to it wasn't very hard at all. It took me less than an hour and I've got almost 150 packages. Aside from some reordering and the issues I opened, it just worked. Nice work, and thank you.

Thank you for trying it out!
Don't hesitate to let me know if you have any other issues or ideas for improvement.
